### ISSUE TITLE
Unsupported scan results on Google Distroless images

### ISSUE THREAD

**Issue by eumel8** [quay/clair#1001]
# Description of Problem / Feature Request

When I push [Google Distroless Images](https://github.com/GoogleContainerTools/distroless) to my Quay registry, I've got Unsupported security scan results. I.e from [Debian Java Image](https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java?gcrImageListsize=30)

### Expected Outcome

Security findings based on CVE for Debian.

### Actual Outcome

Unsupported

### Environment

- Clair version/image: clair-jwt:v3.2.2
- Clair client name/version: clair-jwt:v3.2.2
- Host OS: Ubuntu 18.04
- Kernel (e.g. `uname -a`):  4.15.0-76-generic 
- Kubernetes version (use `kubectl version`):  1.16.8
- Helm version (use `helm version`): 3.1.2
- Network/Firewall setup: canal

Additional infos: in 
https://github.com/quay/clair/blob/8cdd815ccdab27a2ded0e68740b27444efca8d1e/ext/featurefmt/dpkg/dpkg.go#L41 is a file regex for "var/lib/dpkg/status". It seems Google holds the  package information in one file per package in "var/lib/dpkg/status.d"

Maybe it's easy for a Go programmer to add a loop to catch the package information from there :-) Workaround would be an extra build to provide the required status file with information from the status directory.

**Comment by ldelossa** [comment]
@eumel8 ClairV2 is currently in maintenance and we will be not be doing feature requests there. Instead can you please open a feature request here: https://github.com/quay/claircore/

That library will back ClairV4, the newest version of Clair which is currently in Alpha.
