### ISSUE TITLE
Feature Request - Support for Alpine 3.12

### ISSUE THREAD

**Issue by dsalamancaMS** [quay/clair#1013]
### Description of Problem / Feature Request

Alpine 3.12 images are showing as not supported when scanned.

### Expected Outcome
Support Alpine 3.12

### Actual Outcome
Not Supported

**Comment by yybgbname** [comment]
maybe missing metadata.  https://github.com/alpinelinux/alpine-secdb

**Comment by chessmango** [comment]
Repo is deprecated, source changed to https://secdb.alpinelinux.org/ - simple enough Nginx directory listing seemingly, same content

**Comment by yybgbname** [comment]
thanks

**Comment by tohch4** [comment]
> Repo is deprecated, source changed to https://secdb.alpinelinux.org/ - simple enough Nginx directory listing seemingly, same content

So if I understand [the calling code that uses correctly `secdbGitUrl`](https://github.com/quay/clair/blob/c39101e9b8206401d8b9cb631f3aee47a24ab889/ext/vulnsrc/alpine/alpine.go#L65), simply changing the URL will not work.

The new endpoint, secdb.alpinelinux.org, is a simple HTTPS server with nginx, but the code in clair expects a [git HTTP server backend and/or a dumb HTTP backend with a properly formed git repository and we have neither](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols), which means it will need to use a different transport mechanism, or we need the actual git repo. It seems like this was a temporary problem that led to things like quay/clair#556 before, but now it is a permanent.

I will try to look into this with my colleagues and perhaps draft a PR.
