### ISSUE TITLE
Does Clair support multi-client mode?

### ISSUE THREAD

**Issue by CloveXJ** [quay/clair#1014]
I want to scan images in 3 different k8s nodes. My plan is:

install clairctl or analyze-local-image in every node;
install clair and clairdb in center node;
connect every client to the clair in center node;
if i start imagescan job in 3 nodes at the same time, will the cvedb in center node be locked or conflict?

my clair version: V2.0.8

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
