### ISSUE TITLE
Failed to analyze using API v1: push image https://docker.artifactory.entarch.prd.aws.xyz.net/v2/alpha/nonprod/graphql:ceb2e10ae1bc to Clair failed: can't push layer to Clair: Post https://abc.npr.aws.xyz.net:443/v1/layers: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by iamnagu** [quay/clair#1023]
### Description of Problem / Feature Request

not to scan using clair/klar I get the below error , any help is greatly appreciated 

Failed to analyze using API v1: push image https://docker.artifactory.entarch.prd.aws.xyz.net/v2/alpha/nonprod/graphql:ceb2e10ae1bc to Clair failed: can't push layer to Clair: Post https://abc.npr.aws.xyz.net:443/v1/layers: x509: certificate signed by unknown authority

I have tried added the cert and run update-ca-certificates still i get the same issue
COPY cert/rootca.crt /usr/local/share/ca-certificates
RUN update-ca-certificates
----

I tried using insecure flag with no luck pod crashed with the flag, below is the error

flag provided but not defined: -insecure-tls Usage of /clair: -config string Load configuration from the specified file. (default "/etc/clair/config.yaml") -cpu-profile string Write a CPU profile to the specified file before exiting. -log-level string Define the logging level. (default "info")

### Expected Outcome

scanned result

### Actual Outcome

Failed to analyze using API v1: push image https://docker.artifactory.entarch.prd.aws.xyz.net/v2/alpha/nonprod/graphql:ceb2e10ae1bc to Clair failed: can't push layer to Clair: Post https://abc.npr.aws.xyz.net:443/v1/layers: x509: certificate signed by unknown authority
### Environment

non prod

- Clair version/image:  Release v2.1.4
- Clair client name/version: klar-2.4.0-osx-amd64
- Host OS: ios
- Kernel (e.g. `uname -a`):  Darwin Kernel Version 18.7.0
- Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:50:54Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- Helm version (use `helm version`):  Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
- Network/Firewall setup: 

Thanks

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
