### ISSUE TITLE
Clair V4 Client Tools

### ISSUE THREAD

**Issue by Fodoj** [quay/clair#1027]
I tried couple of existing client tools, like Klar and claircli, but they don't seem to work with Clair V4 and this API: https://github.com/quay/clair/blob/development-4.0/openapi.yaml. 

With this issue I just want to get a confirmation (or links to other client tools may be) that currently only client tool is most likely Quay. Is that so?

**Comment by ldelossa** [comment]
Hello.

We use Clairctl often to process manifests, view index reports, and view vuln reports. 

Are you experiencing an issue with Clairctl? Can you elaborate.

**Comment by Fodoj** [comment]
If you are talking about this tool https://github.com/jgsqware/clairctl - I didn’t try it. Do you use it with latest Clair V4 alpha release?

**Comment by ldelossa** [comment]
Nope. 

ClairV4 has its own native CLI tool. https://github.com/quay/clair/tree/development-4.0/cmd/clairctl

**Comment by Fodoj** [comment]
Ah nice, I did not know it exists. Are there pre-compiled binaries as well?

**Comment by ldelossa** [comment]
As of right now no, but ClairV4 is slated for beta within the up coming
weeks. We will soon start compiling the cli tool in our release pages.

**Comment by ldelossa** [comment]
@Fodoj closing this. if you'd like any support on our cli tool don't hesitate to contact us @ issues.redhat.com/ or https://groups.google.com/forum/#!forum/clair-dev

**Comment by Fodoj** [comment]
Whoever finds this issue - atm clairctl is already included in the latest clair v4 images
