### ISSUE TITLE
Clair UBI8 Scanning

### ISSUE THREAD

**Issue by KrisJohnstone** [quay/clair#1028]
### Description of Problem / Feature Request
We are utilising the quay operator, upon investigation clair seems to be missing vulnerabilities during scans and green lighting *all* ubi8 images.

Red Hat Security:
![redhat-security](https://user-images.githubusercontent.com/18162364/90463632-c6f70e80-e14e-11ea-9cdc-1fc1f400e677.PNG)

Clair Results:
![clair-results](https://user-images.githubusercontent.com/18162364/90463663-dbd3a200-e14e-11ea-94fe-13468b454de7.PNG)

Claiir db:
![clair-db](https://user-images.githubusercontent.com/18162364/90463686-e8f09100-e14e-11ea-98b0-f1a74134baa9.PNG)
![clair-namespace](https://user-images.githubusercontent.com/18162364/90463694-ebeb8180-e14e-11ea-8fd5-93c5d5215807.PNG)

### Expected Outcome

Vulnerabilities are found where known vulnerabilities exist.

### Actual Outcome

No CVEs are found.

### Environment

- Clair version/image: quay.io/projectquay/clair-jwt:qui-gon
- Quay Version: 3.3
- Quay Operator: 1.1.2
- Clair client name/version: 
- Host OS: CentOS
- Kubernetes version (use `kubectl version`):  OpenShift 4.4.10
- Network/Firewall setup: Public

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
