### ISSUE TITLE
Extract the vulnerable version info for a feature/pkg

### ISSUE THREAD

**Issue by xia0pin9** [quay/clair#1029]
I want to utilize the clair vulnerability database to check the packages installed on my linux machines. But it seems I can't find the corresponding vulnerable version information of my package/feature in clair database. I am running the latest version of (locally built) clair docker image with an empty clair database on Ubuntu.

I thought the `affected_version` column in `vulnerability_affected_feature` table is what I wanted, but the values in this column are either shown as `#MAXV#` or the same as the value in `fixedin`:

```
clair=# select * from vulnerability_affected_feature limit 10;
 id | vulnerability_id | feature_name  | feature_type |    affected_version    |        fixedin
----+------------------+---------------+--------------+------------------------+------------------------
  1 |                1 | flexbackup    |            1 | 1.2.1-3                | 1.2.1-3
  2 |                2 | linux         |            1 | 4.19.37-1              | 4.19.37-1
  3 |                3 | tinymux       |            1 | #MAXV#                 |
  4 |                4 | ffmpeg        |            1 | 7:2.4.1-1              | 7:2.4.1-1
  5 |                5 | mumble        |            1 | 1.2.4-0.2              | 1.2.4-0.2
  6 |                6 | smarty3       |            1 | 3.0~rc1-1              | 3.0~rc1-1
  7 |                7 | chromium      |            1 | #MAXV#                 |
  8 |                8 | linux         |            2 | 4.4.0-157.185          | 4.4.0-157.185
  9 |                8 | linux-aws     |            2 | 4.4.0-1090.101         | 4.4.0-1090.101
 10 |                8 | linux-aws-hwe |            2 | 4.15.0-1039.41~16.04.1 | 4.15.0-1039.41~16.04.1
(10 rows)
```

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
