### ISSUE TITLE
nvd data feed url version 1.0 is not working anymore and need to be changed to 1.1

### ISSUE THREAD

**Issue by Portshift-Admin** [quay/clair#1046]
### Description of Problem / Feature Request
I'm using clair version v2.1.4
nvd data feed url version 1.0 is not working anymore and need to be changed to 1.1
In the logs I see that clair is trying to reach the 1.0 version:
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:54.994342","data feed name":"2002","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2002.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.007395","data feed name":"2003","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2003.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.009511","data feed name":"2004","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2004.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.013436","data feed name":"2005","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2005.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.019141","data feed name":"2006","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2006.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.020896","data feed name":"2007","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2007.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.023139","data feed name":"2008","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2008.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.026024","data feed name":"2009","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2009.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.027873","data feed name":"2010","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2010.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.029656","data feed name":"2011","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2011.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.032440","data feed name":"2012","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2012.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.039304","data feed name":"2013","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2013.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.054302","data feed name":"2014","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2014.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.057099","data feed name":"2015","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2015.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.059093","data feed name":"2016","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2016.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.060806","data feed name":"2017","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2017.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.064588","data feed name":"2018","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2018.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.066658","data feed name":"2019","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2019.meta failed status code: 404"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-09-22 04:09:55.069566","data feed name":"2020","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2020.meta failed status code: 404"}

### Expected Outcome

Clair should call https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-{year}.meta

### Actual Outcome

error when updating the db

### Environment

- Clair version/image: v2.1.4
- Clair client name/version: v2.1.4
- Host OS: docker 
- Kernel 
- Kubernetes version 1.16
- Helm version (use `helm version`): N/A (used kubectl apply)
- Network/Firewall setup: None

**Comment by hdonnay** [comment]
We'll certainly help review any patches, but the current maintainers (@ldelossa and I) don't have spare time to go back and work on v2.

Version 4 doesn't ingest the NVD feed, so this isn't a problem on the current version.

**Comment by byteborg** [comment]
Integrated in https://github.com/quay/clair/pull/1056
How are you scheduling releases for 2.x?
