### ISSUE TITLE
Problem to submit manifest to indexer endpoint

### ISSUE THREAD

**Issue by SofyaTavrovskaya** [quay/clair#1057]
### Description of Problem / Feature Request

Hi!
I deployed testClairv4 and I am trying to use Clair API. I tried to submit a Manifest object to this endpoint POST indexer/api/v1/index_report. And I got the fail when try to get image layers from registry.hub.docker.com. 
What am I doing wrong? I didn't find any info how to add to request docker registry token

### Actual Outcome

{"manifest_hash":"sha256:bb0eaf4eee00c28cb8ffd54e571dd225f1dd2ed8d8751b2835c31e84188bf2de","state":"IndexError","packages":{},"distributions":{},"repository":{},"environments":{},"success":false,"err":"failed to fetch layers: encountered error while fetching a layer: fetcher: unexpected status code: 401 401 Unauthorized"}

### Environment

- Clair version/image: v4.0.0
- Clair client name/version: 
- Host OS: "Ubuntu, 20.04.1 LTS (Focal Fossa)"
- Kernel (e.g. `uname -a`): Linux 5.4.0-48-generic
- Kubernetes version (use `kubectl version`): 
- Network/Firewall setup:

**Comment by ldelossa** [comment]
@SofyaTavrovskaya can you please show the manifest you are submitting to Clair?

This error indicates the URLs you provided in the Manifest object are behind some type of authentication. You may need to provide header information with the provided Manifest.

**Comment by SofyaTavrovskaya** [comment]
@ldelossa 
I'm submitting to Clair this manifest:

```
{
  "hash": "sha256:6858809bf669cc5da7cb6af83d0fae838284d12e1be0182f92f6bd96559873e3",
  "layers": [
    {
      "hash": "sha256:df8698476c65c2ee7ca0e9dbc2b1c8b1c91bce555819a9aaab724ac64241ba67",
      "uri": "https://registry.hub.docker.com/v2/library/busybox/blobs/sha256:df8698476c65c2ee7ca0e9dbc2b1c8b1c91bce555819a9aaab724ac64241ba67"
    }
  ]
}
```

**Comment by hdonnay** [comment]
Yeah, that layer URL requires auth, which Clair doesn't know about natively. Any tool generating Clair manifests should follow redirects as far as possible and include any relevant headers.

The `clairctl` tool can generate a manifest for you, to compare against here's a quick terminal transcript to illustrate:

```
% cat >manifest.bad.json <<.
heredoc> {
  "hash": "sha256:6858809bf669cc5da7cb6af83d0fae838284d12e1be0182f92f6bd96559873e3",
  "layers": [
    {
      "hash": "sha256:df8698476c65c2ee7ca0e9dbc2b1c8b1c91bce555819a9aaab724ac64241ba67",
      "uri": "https://registry.hub.docker.com/v2/library/busybox/blobs/sha256:df8698476c65c2ee7ca0e9dbc2b1c8b1c91bce555819a9aaab724ac64241ba67"
    }
  ]
}
heredoc> .
% curl --data @manifest.bad.json http://localhost:6060/indexer/api/v1/index_report
{"manifest_hash":"sha256:6858809bf669cc5da7cb6af83d0fae838284d12e1be0182f92f6bd96559873e3","state":"IndexError","packages":{},"distributions":{},"repository":{},"environments":{},"success":false,"err":"failed to fetch layers: encountered error while fetching a layer: fetcher: unexpected status code: 401 401 Unauthorized"}

% clairctl manifest docker.io/library/busybox:latest | tee manifest.tool.json
{"hash":"sha256:2ca5e69e244d2da7368f7088ea3ad0653c3ce7aaccd0b8823d11b0d5de956002","layers":[{"hash":"sha256:df8698476c65c2ee7ca0e9dbc2b1c8b1c91bce555819a9aaab724ac64241ba67","uri":"https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/df/df8698476c65c2ee7ca0e9dbc2b1c8b1c91bce555819a9aaab724ac64241ba67/data?verify=1601417709-T%2Fafgsr9dU%2FyVZe2VDlgpLDgapU%3D","headers":{"Referer":["https://index.docker.io/v2/library/busybox/blobs/sha256:df8698476c65c2ee7ca0e9dbc2b1c8b1c91bce555819a9aaab724ac64241ba67"]}}]}
% curl --data @manifest.tool.json  http://localhost:6060/indexer/api/v1/index_report
{"manifest_hash":"sha256:2ca5e69e244d2da7368f7088ea3ad0653c3ce7aaccd0b8823d11b0d5de956002","state":"IndexFinished","packages":{},"distributions":{},"repository":{},"environments":{},"success":true,"err":""}
```
