### ISSUE TITLE
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/..data': Read-only file system

### ISSUE THREAD

**Issue by Jaybe-bdk** [quay/clair#1061]
### Description of Problem / Feature Request

The image build of version v2.1.5 with kaniko end up in a known error of upgrading alpine-baselayout.
Root cause is a problem of kaniko  ( https://github.com/GoogleContainerTools/kaniko/issues/1297 ), but this could not be fix immediately.

Possible workarround: pin the alpine version to 3.11

### Expected Outcome

The build will not fail.

### Actual Outcome

(1/6) Upgrading busybox (1.31.1-r16 -> 1.31.1-r19)
Executing busybox-1.31.1-r19.post-upgrade
(2/6) Upgrading alpine-baselayout (3.2.0-r6 -> 3.2.0-r7)
Executing alpine-baselayout-3.2.0-r7.pre-upgrade
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/..data': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/token': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/namespace': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/..2020_09_29_08_04_02.531215222/namespace': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/..2020_09_29_08_04_02.531215222/ca.crt': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/..2020_09_29_08_04_02.531215222/token': Read-only file system
ERROR: alpine-baselayout-3.2.0-r7: failed to rename var/.apk.f752bb51c942c7b3b4e0cf24875e21be9cdcd4595d8db384 to var/run.
Executing alpine-baselayout-3.2.0-r7.post-upgrade
(3/6) Upgrading ca-certificates-bundle (20191127-r2 -> 20191127-r4)
(4/6) Upgrading ssl_client (1.31.1-r16 -> 1.31.1-r19)
(5/6) Upgrading ca-certificates (20191127-r2 -> 20191127-r4)
(6/6) Upgrading musl-utils (1.1.24-r8 -> 1.1.24-r9)
Executing busybox-1.31.1-r19.trigger
Executing ca-certificates-20191127-r4.trigger
1 error; 44 MiB in 45 packages
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1

### Environment

- Clair version/image: v.2.1.5
- Clair client name/version: n/a
- Kaniko Version:  v0.24.0
- Host OS: AWS Kubernetes AMI for EKS
- Kernel (e.g. `uname -a`): Linux
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- Network/Firewall setup:

**Comment by ldelossa** [comment]
@JensBode please discuss this on our mailing list if you are looking for support. This is not a Clair related issue. 
https://groups.google.com/g/clair-dev
