### ISSUE TITLE
Web-UI for clair

### ISSUE THREAD

**Issue by PavloZabudskyi** [quay/clair#1062]
### Description of Problem / Feature Request

Is there any web interface for clair? I think there was some before. But now I don't see any trace of it.
What are options? Do we need to use some third-party solutions, like harbor? 

### Environment

- Clair version/image: 2.1.4
- Clair client name/version: N/A
- Host OS: N/A
- Kernel (e.g. `uname -a`): N/A
- Kubernetes version (use `kubectl version`): N/A
- Network/Firewall setup: N/A

**Comment by ldelossa** [comment]
@PavloZabudskyi 

There is no UI as far as I know. Quay is the main application for Clair and provides a UI for its reporting.

If you wanted to take a look at adding a UI to Clair V4 (current main branch) I'd welcome the idea. For now I will close this issue. Open another if you'd like to talk design or tackling a UI.

**Comment by hdonnay** [comment]
I don't know of any web-based UI specifically for Clair.

Conceptually, there's no reason there _can't_ be a Clair-specific UI, but the thinking is that you have to get a Manifest from somewhere, and where ever you get that probably has a better picture of the specific information about that artifact and can display Clair's results in a more context.
