### ISSUE TITLE
Does clair support scanning ubi  images ?

### ISSUE THREAD

**Issue by nadgowdas** [quay/clair#1082]
### Description of Problem / Feature Request

I am trying to use Clair to scan UBI/RHEL images. But, when I looked into the db tables `namespace` it only shows `centos:6,7,8`. Is there a reason other RHEL flavors are not supported ?

### Expected Outcome

clair to support curating advisories for rhel/ubi.

### Environment

- Clair version/image: 
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Network/Firewall setup:

**Comment by ldelossa** [comment]
Clair V4 fully supports this. I suggest an upgrade to the latest Clair version. This support will not be added to v2 or v3 unless contributed by the community.
