### ISSUE TITLE
Getting error while running clair: Connection reset by peer

### ISSUE THREAD

**Issue by pardeepbeniwal** [quay/clair#1087]
Hi,
I have run below command successfully:
$ mkdir $PWD/clair_config
$ curl -L https://raw.githubusercontent.com/coreos/clair/master/config.example.yaml -o $PWD/clair_config/config.yaml
$ docker run -d -e POSTGRES_PASSWORD="" -p 5432:5432 postgres:9.6
$ docker run -d -p 6060-6061:6060-6061 -v $PWD/clair_config:/config quay.io/coreos/clair-git:latest -config=/config/config.yaml

After that I am checking health with below urls:
curl  http://localhost:6060/health
curl  http://localhost:6061/health
curl  http://{MY_IP}:6060/health
curl  http://{MY_IP}:6061/health

I am getting this error: _**curl: (56) Recv failure: Connection reset by peer**_

Please help me

**Comment by smitphilip** [comment]
Looks like firewall maybe? Is your clair container actually starting up?
`sudo docker container ls`

**Comment by pardeepbeniwal** [comment]
> Looks like firewall maybe? Is your clair container actually starting up?
> `sudo docker container ls`

yes, all containers are up

**Comment by pardeepbeniwal** [comment]
> > Looks like firewall maybe? Is your clair container actually starting up?
> > `sudo docker container ls`
> 
> yes, all containers are up

Is there any way to install on ubuntu machine without docker ?

**Comment by hdonnay** [comment]
Some things to note:

1. I don't know how recent the `quay.io/coreos/clair-git:latest` container is, probably over a year old.

2. The old `master` branch (now `development-3.0`) is effectively unsupported.

If you want to use that specific version, I'd suggest building the container yourself. Someone on the mailing list might be able to help.
