### ISSUE TITLE
Could not get NVD data feed hash version 1.0

### ISSUE THREAD

**Issue by savujevi** [quay/clair#1116]
### Description of Problem / Feature Request

When we start clair in version 2.1.6 we get following errors:

{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-10-29 12:36:55.865980","data feed name":"2018","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2018.meta  failed status code: 404"}

It seems, that version 1.0 is not longer available. How can we switch to version 1.1 ?

Thank you for you help.

### Expected Outcome

NDV data is imported without problems.

### Actual Outcome

{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-10-29 12:36:55.865980","data feed name":"2018","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2018.meta  failed status code: 404"}

### Environment

- Clair version/image: 2.1.6
- Clair client name/version: klar lastest version.
- Host OS: rhel 7
- Kernel (e.g. `uname -a`): Linux clair-14-db7pm 3.10.0-1127.18.2.el7.x86_64 #1 SMP Mon Jul 20 22:32:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`): OpenShift 3.11
- Network/Firewall setup:

**Comment by ocrawford555** [comment]
👋 what is more odd to me is that I thought this issue was fixed in a recent release, yet it seems from our logs as well, that it is still trying to use the 1.0 feed:

https://github.com/quay/clair/blob/release-2.0/ext/vulnmdsrc/nvd/nvd.go#L42

2.1.5 release: https://github.com/quay/clair/pull/1056

**Comment by hdonnay** [comment]
Closed due to age, V2
