### ISSUE TITLE
Quay interface doesn't come up in test mode

### ISSUE THREAD

**Issue by meletis** [quay/clair#1120]
### Description of Problem / Feature Request

Hi,

We took the steps in https://quay.github.io/clair/howto/testing.html and used the "ready-v4.0.0-rc.20" branch so that we can build the containers.

Building the container was successful, but the Quay interface is down and we can't create an account, as per the instructions. We have attached the clair-quay logs for convenience.

[quay-logs.txt](https://github.com/quay/clair/files/5494849/quay-logs.txt)

### Expected Outcome

The Quay UI should render

### Actual Outcome

502 Bad Gateway
nginx/1.14.1

<img width="877" alt="Screenshot 2020-11-05 at 4 02 14 PM" src="https://user-images.githubusercontent.com/654163/98250597-4c38d500-1f80-11eb-8061-9f9aa766b547.png">

### Environment

- Clair version/image: v4.0.0-rc.20
- Clair client name/version: v4.0.0-rc.20
- Host OS: MacOS 10.15.7
- Kernel (e.g. `uname -a`): Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
- Kubernetes version (use `kubectl version`): N/A
- Network/Firewall setup: N/A

**Comment by ldelossa** [comment]
@meletis 

Quay takes a bit to come up. I noticed I received this 502 Bad Gateway until just about a minute passed. 

Is it possible that you did not wait enough time for Quay to come up? Please allow up to a minute for the local Quay to initialize.

**Comment by meletis** [comment]
Thank you, @ldelossa 
I actually waited for 3-4 hours and nothing changed. Is it possible that it has to do with MacOS? Did you also try with MacOS?

**Comment by ldelossa** [comment]
@meletis its possible. this initial test was on Fedora. I have a mac book tho, let me test on this.

**Comment by ldelossa** [comment]
@meletis also did you consider all notes in the troubleshooting section of that document? https://quay.github.io/clair/howto/testing.html#troubleshooting

**Comment by meletis** [comment]
@ldelossa , I did check the port conflicts and permissions, but I didn't check the resources section. Thank you for the tip, I will increase the limits and I will retry. I will also wait for your test results on your Mac. 

Thanks!

**Comment by ldelossa** [comment]
@meletis 

I just ran the local dev on my mac:

macOS Catalina 
Version 10.15.17

Docker specs:

CPU: 4
Memory: 12gb
Swap: 2gb
Disk Image Size: 208 gb

Quay started with no issues.

**Comment by meletis** [comment]
Oh, thank you for these specs, @ldelossa .they are totally different than mine. I will try again and will get back.

**Comment by meletis** [comment]
It worked. All it needed was a few more GB of memory! Thank you so much, @ldelossa!

**Comment by ldelossa** [comment]
glad it worked out.
