### ISSUE TITLE
Vulnerabilities present in Clair v2.1.5/6

### ISSUE THREAD

**Issue by dravos** [quay/clair#1146]
### Description of Problem / Feature Request

The version of the alpine linux base image that Clair v2.1.5 and v2.1.6 are built on top of have vulnerabilities of varying severities. In the Dockerfile, was able be resolve it by upgrading the affected packages with `RUN apk upgrade` added right after `FROM golang:1.13-alpine`. Since support for golang1.13 on dockerhub [won't address this](https://github.com/docker-library/golang/issues/349) (wouldn't hurt to check on your own behalf though), I can make a PR with this addition to the Dockerfile if desired.

### Expected Outcome

No vulnerabilities

### Actual Outcome

<img width="598" alt="Screen Shot 2020-12-15 at 12 21 23 PM" src="https://user-images.githubusercontent.com/29226256/102249294-364bf780-3ed0-11eb-97b2-7dbecc3406be.png">

### Environment

- Clair version/image: v2.1.5/v2.1.6
- Clair client name/version: 
- Host OS: Docker image based on Alpine Linux
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
Closing due to age, V2
