### ISSUE TITLE
[Question] Can we get the component path information the clair rscanning results

### ISSUE THREAD

**Issue by hbandi** [quay/clair#1149]
- Clair version/image: 2.0.8
- Clair client name/version: klar
- Host OS: centos

We want to find the Clair component path information from the Clair results.
Can you please help us with this?
Thanks

**Comment by ldelossa** [comment]
@hbandi Clair v2 is under community maintenance. This request would need to be fulfilled by a contributing community member. 

Please upgrade to Clair v4.0 in the mean time and see if this feature is necessary in our latest version.

**Comment by hdonnay** [comment]
Closing due to age, V2
