### ISSUE TITLE
Questions: are CVE sources fetched regularly

### ISSUE THREAD

**Issue by osallou** [quay/clair#115]
it is not clear in documentation if remote sources are fetched at regular interval.
At Clair startup I can see the fetch of remove sources (Debian, etc.), but are they updated at regular interval ? Or should I trigger (how?) Clair to update itself ?

At last, once a layer has been analysed by Clair, let's say at time X.
At time X+1, let's say new vulnerabilities  are available from remote source and Clair got them (updated its database).
If I query my layer again, will vulnerabilities returned for this layer contain the new vulnerabilities, or should I reupload my layer at regular interval to get it up-to-date against current database?

Thanks

**Comment by Quentin-M** [comment]
Hi,

Yes, Clair updates its internal vulnerability database at regular interval, and this interval is [configurable](https://github.com/coreos/clair/blob/master/config.example.yaml#L52).
Yes, if you query again your image, an up-to-date report will be returned to you.

Note that the update process also generates notifications, which names are [sent](https://github.com/coreos/clair/tree/master/notifier) depending on your [config](https://github.com/coreos/clair/blob/master/config.example.yaml#L56). This allows you to know about any vulnerability changes immediately and know which layer are now affected / aren't affected anymore.

**Comment by osallou** [comment]
Thanks, closing the issue
