### ISSUE TITLE
Please add cp config.yaml.sample config.yaml to https://quay.github.io/clair/howto/testing.html

### ISSUE THREAD

**Issue by cynthia-rempel** [quay/clair#1153]
### Description of Problem / Feature Request
please change https://quay.github.io/clair/howto/testing.html to read

git clone --single-branch --branch release-4.0 https://github.com/quay/clair.git
cd clair/
cp config.yaml.sample config.yaml
sudo make local-dev-up-with-quay

when I ran
git clone --single-branch --branch release-4.0 https://github.com/quay/clair.git
cd clair/
sudo make local-dev-up-with-quay

it failed
### Expected Outcome
All the pods launched would succeed

### Actual Outcome
Some pods failed

### Environment

- Clair version/image: 
- 4.0
- Clair client name/version: 
- Host OS: 
- Fedora
- Kernel (e.g. `uname -a`): 
- Linux localhost.localdomain 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`): 
- docker-compose version 1.27.4, build unknown
- Network/Firewall setup: 
home network connected to internet

**Comment by ldelossa** [comment]
@cynthia-rempel this is not correct.

The configuration file used in local dev is found in https://github.com/quay/clair/tree/main/local-dev/clair

You containers are failing for a different reason. Please take a look at: https://quay.github.io/clair/howto/testing.html#troubleshooting

Once you review that, if your error still persists please provide more details including the error messages and container logs.
