### ISSUE TITLE
will clairctl works with AWS ECR

### ISSUE THREAD

**Issue by hbandi** [quay/clair#1154]
Can we generate manifest from AWS ECR using clairctl 

Clair version/image: V4.0.0
Clair client name/version: clairctl
Host OS: centos

**Comment by ldelossa** [comment]
Hello @hbandi 

Clairctl uses a library which abstracts registry access. https://github.com/google/go-containerregistry

If this library is compatible with AWS ECR, it will work. What this boils down too is ECR must implement the OCI registry spec.

**Comment by hdonnay** [comment]
Yes, I'd consider it a bug if it doesn't work, modulo authentication issues; if I recall correctly, the registry spec punts on the specific method of authentication, so comprehensive support in our best-effort tool may not be possible.

Please open a bug if you find `clairctl mainfest ${image}` doesn't work as expected
