### ISSUE TITLE
contrib/analyze-local-image pollutes /tmp

### ISSUE THREAD

**Issue by abulimov** [quay/clair#117]
As [os.Exit() in go skips all deferred instructions](https://gobyexample.com/exit), the statement `defer os.RemoveAll(path)` on [line 116](https://github.com/coreos/clair/blob/master/contrib/analyze-local-images/main.go#L116) gets executed _only_ when our image has visible vulnerabilities.

So almost every time this tool is used the temporary directory `/tmp/analyze-local-image-*` remains.

**Comment by Quentin-M** [comment]
Good catch!
