### ISSUE TITLE
Make maximum number of notifier's connections to DB configurable.

### ISSUE THREAD

**Issue by jan-zmeskal** [quay/clair#1179]
### Feature Request

As of now (February 2021), the number of maximum DB connections maintainer by pool is [hard-coded for notifier](https://github.com/quay/clair/blob/eb519e0752d3cf7f5f8daeefd4ad9bd29cbfa8c2/notifier/service/service.go#L182). It would be very useful if this could be configured [the same way it can be done for matcher](https://github.com/quay/clair/blame/main/Documentation/reference/config.md#L176).

**Comment by jan-zmeskal** [comment]
Actually the same applies also for indexer.

**Comment by klr8** [comment]
We are also facing this issue as our PostgreSQL database, which is managed by a central team, puts severe constraints on the maximum number of connections.

**Comment by hdonnay** [comment]
This should be possible via the connection string as of e86c1fbfe45b7b6898ba09ca567e814e5022698e.

The first release to include this should be v4.4.0, and it's currently in the nightly builds.
