### ISSUE TITLE
link to setup claire in analyze-local-images page is not valid

### ISSUE THREAD

**Issue by westlifezs** [quay/clair#119]
Hello,
The link (https://github.com/coreos/clair/blob/master/docs/Run.md) in https://github.com/coreos/clair/tree/master/contrib/analyze-local-images is not a valid one.

The link behind the word "**doc**" is needed to setup Clair instance. Unfortunately it is no longer valid. I will need this link to setup Clair to test the local analyze tool. Could some please fix this?

Here is how the link is mentioned (after click "doc" I can only see 404 but not the valid page)

 You also need a working Clair instance, the bare minimal setup is to run Clair in a Docker instance without much configuration, To learn more about how to run Clair, take a look at the **doc**:

**Comment by Quentin-M** [comment]
Fixed by #123. Thanks for reporting.
