### ISSUE TITLE
Notifier panics at start

### ISSUE THREAD

**Issue by jan-zmeskal** [quay/clair#1198]
### Description of Problem / Feature Request
When deploying notifier to OCP, it panics at the start. Full log is attached. I'm not gonna go into great detail as this problem is already addressed in #1193. I just created this issue to point out that this can be observed also on the `main` branch and is not unique for Hank's `notifier-efficiency` branch.
[clair-notifier-1-59g25.log](https://github.com/quay/clair/files/6100519/clair-notifier-1-59g25.log)

### Environment
Encountered when running clair from `main` branch, commit 102ae88dd84c1f769b8c037226d92b301d887aab.

**Comment by chrisbsmith** [comment]
I'm seeing the same error when following [the instructions for local development](https://quay.github.io/clair/howto/testing.html#starting-a-cluster) using docker compose. The 

I've tried this on Amazon Linux2 and Ubuntu 20.04 AWS EC2s, both with the same result.  

# Environment
* Ubuntu: 20.04.2 LTS (Focal Fossa)
* go: go1.16 linux/amd64
* docker: 19.03.8
* docker-compose version 1.25.0

I figure it's related, but the scanning job never queues and a check of docker logs reveals these on the traefik container. I can open another issue if these are unrelated issues.

```
172.18.0.14 - - [08/Mar/2021:19:21:01 +0000] "GET /indexer/api/v1/index_state HTTP/1.1" 404 19 "-" "-" 1 "-" "-" 0ms
172.18.0.14 - - [08/Mar/2021:19:28:01 +0000] "GET /indexer/api/v1/index_state HTTP/1.1" 400 72 "-" "-" 15 "indexer@docker" "http://172.18.0.14:6000" 1ms
```

**Comment by hdonnay** [comment]
As noted, there's a fix in #1193

**Comment by chrisbsmith** [comment]
@hdonnay , I'm very new to Quay and Clair and am comparing vulnerability scanners to add to my environment.  I ran the same make commands from your PR branch and the notifier stayed up, but the security scan sits in a "Queued" state forever.  I'm still seeing these logs in traefik router.  

```
172.18.0.9 - - [08/Mar/2021:20:52:27 +0000] "GET /indexer/api/v1/index_state HTTP/1.1" 400 72 "-" "-" 3762 "indexer@docker" "http://172.18.0.9:6000" 0ms
```

Any help or direction on where to look here would be great.

**Comment by hdonnay** [comment]
This seems unrelated to this issue, so I'd recommend opening a discussion with all the details you can think of. Given that that endpoint doesn't return 400, my hunch is it's something in the router.

**Comment by jan-zmeskal** [comment]
@hdonnay With https://github.com/quay/clair/pull/1193 merged, I guess we can close this, right?

**Comment by hdonnay** [comment]
Yeah, forgot to link this before merging.
