### ISSUE TITLE
go get: Segmentation fault error encountered intermittently 

### ISSUE THREAD

**Issue by westlifezs** [quay/clair#121]
while running "go get -u github.com/coreos/clair/contrib/analyze-local-images",
I occationally hit errors saying "Segmentation fault". anyone know why this happened? I could not find anywhere I can further debug regarding this issue.

thanks,

**Comment by jzelinskie** [comment]
You get this error running `go get` or actually running the binary `analyze-local-images`?

**Comment by westlifezs** [comment]
I think the error comes from go get. I can get it succeed after trying several times. therefore this issue is not a big deal for me. However, issue #120 is a real issue for me. could you please take a look at that one whenever you get a chance?

**Comment by Quentin-M** [comment]
Hi,

Unfortunately, I don't think this issue is related to Clair. What's your go version?

**Comment by westlifezs** [comment]
Am I using the right go version?
go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

**Comment by westlifezs** [comment]
also could you let me know where to find the log of clair_clair. It seems like I am not able to start the instance (like I stated in #120 ). but I could not find its log anywhere. thx

**Comment by jzelinskie** [comment]
You are using the wrong compiler. You're using gccgo and not gc, the standard distribution of the Go compiler. gccgo tracks standard Go, but is frequently out of date and most projects don't go out of their way to support it.

**Comment by westlifezs** [comment]
thanks for clarification. I have this issue resolved by using the standard go. but I am still facing the clair_clair exit 1 without log issue. any suggestions? thx.

**Comment by jzelinskie** [comment]
We can continue that discussion in #120.
