### ISSUE TITLE
Vulnerability report can break API contract due to time.Time being null

### ISSUE THREAD

**Issue by crozzy** [quay/clair#1231]
### Description of Problem / Feature Request

Using the library https://github.com/ugorji/go/ to do the JSON response encoding means that all `time.Time` objects that evaluate to `IsZero() == true` will be marshaled as `"time": null`. 

This means that if, when grabbing `vuln`s from the DB, they have an `Issued` time of `0001-01-01 00:00:00+00` they will end up being send back from the API as something like:

```
	"vulnerabilities": {
		"931353": {
			"id": "931353",
			"updater": "pyupio",
			"name": "pyup.io-26132",
			"description": "setuptools before 1.3 has a security vulnerability in SSL match_hostname check as reported in Python 17997.",
			"issued": null,
			"links": "",
			"severity": "",
			"normalized_severity": "Unknown",
			"package": {
				"id": "",
				"name": "setuptools",
				"version": "\u003c1.3",
				"kind": "binary"
			},
```

This isn't a huge deal unless the consumer is validating the response as Quay does and throws this error:
```
gunicorn-web stdout | jsonschema.exceptions.ValidationError: None is not of type 'string'
gunicorn-web stdout | Failed validating 'type' in schema['properties']['vulnerabilities']['additionalProperties']['properties']['issued']:
gunicorn-web stdout |     {'description': 'The timestamp in which the vulnerability was issued\n',
gunicorn-web stdout |      'type': 'string'}
gunicorn-web stdout | On instance['vulnerabilities']['931353']['issued']:

```

### Expected Outcome

The JSON is always a string (or Quay is updated to accept null).

### Actual Outcome

The `issued` time can be null and Quay seems to expect a string.

### Environment

- Clair version/image: main
- Clair client name/version: main
- Host OS: Linux
- Kernel (e.g. `uname -a`): 4.15.0-34-generic
- Kubernetes version (use `kubectl version`): NA
- Network/Firewall setup: docker-compose

This might not be an issue, or could be an environment quirk, but it's something I ran into while running locally.

**Comment by ldelossa** [comment]
Good catch. 

@hdonnay you recently added this package into ClairCore. 
Can you file a ticket in http://issues.redhat.com for this so we can track as a blocker for Quay 3.6 as it will utilize Clair 4.1-alpha.1 

@thomasmckay This will be a blocker for 4.1-alpha in 3.5/3.6 

@hdonnay Quay errors out here because it's using our OpenAPI spec to validate the responses. This fix maybe as simple as updating OpenAPI spec to allow for null? 

Outside of a quick fix however, we should determine if we **want** this behavior

**Comment by hdonnay** [comment]
It's not in claircore, only clair.

I think having the string would benfit from being more uniform (and the previous behavior), but one argument for the null is that any clients would no longer need to recognize the bogus time string.

**Comment by ldelossa** [comment]
Yeah I can see null being useful here, but we get into the business of "interpreting" fields coming from the upstream vuln database instead of just passing them along as is, which I'm not sure we want to do.

I think I'm in favor of returning back to providing the string and not null, if possible.
