### ISSUE TITLE
RHEL criterion "is installed" content causes panic

### ISSUE THREAD

**Issue by mlhoyt** [quay/clair#1249]
## Description of Problem / Feature Request

Using quay/clair v2 as the base of https://github.com/arminc/clair-local-scan/ (specifically v2.1.6 defined [here](https://github.com/arminc/clair-local-scan/blob/master/.travis.yml#L9)), have discovered very recently that https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL8.xml appears to break the following code:

https://github.com/quay/clair/blob/dcf2adb5fef0ec61746812f7930c9eb6923400e4/ext/vulnsrc/rhel/rhel.go#L274-L279

Searching for the `criterion` in the RHEL8.xml file produces:
```
$ grep '<criterion' rhsa-RHEL8.xml | grep 'is installed' | sort -u
      <criterion comment="Red Hat CoreOS 4 is installed" test_ref="oval:com.redhat.rhsa:tst:20211193004"/>
      <criterion comment="Red Hat Enterprise Linux 8 is installed" test_ref="oval:com.redhat.rhba:tst:20191992003"/>
     <criterion comment="Red Hat Enterprise Linux 7 is installed" test_ref="oval:com.redhat.rhsa:tst:20191619011"/>
     <criterion comment="Red Hat Enterprise Linux 8 is installed" test_ref="oval:com.redhat.rhba:tst:20191992003"/>
```

The `"Red Hat CoreOS 4 is installed"` matches the " is installed" check but then obviously does not match `"Red Hat Enterprise Linux "` so the code to extract the `osVersion` via range ultimately panics because of an invalid range: `panic: runtime error: slice bounds out of range [25:24]`.

### Steps to reproduce

```
docker run --name clair-db -d -p 5432:5432 arminc/clair-db:latest
docker run --name clair-server -d --link clair-db:postgres -p 6060-6061 arminc/clair-local-scan:latest
```

### Expected Outcome

That the clair-server container does not panic and exit but completes loading vulnerabilities and waits for scanner (client) connections.

### Actual Outcome

```
...
panic: runtime error: slice bounds out of range [25:24]

goroutine 45 [running]:
github.com/quay/clair/v2/ext/vulnsrc/rhel.toFeatureVersions(0xc00153ca68, 0x2, 0xc0057c3178, 0x1, 0x1, 0xc00aef64d0, 0x1, 0x1, 0x2, 0xc0057c3160, ...)
	/go/clair/ext/vulnsrc/rhel/rhel.go:276 +0xbf8
github.com/quay/clair/v2/ext/vulnsrc/rhel.parseRHSA(0x7f0f8b8c01e8, 0xc00582c000, 0xc00582c000, 0x7f0f8b8c01e8, 0xc00582c000, 0x43, 0x0)
	/go/clair/ext/vulnsrc/rhel/rhel.go:166 +0x1c7
github.com/quay/clair/v2/ext/vulnsrc/rhel.(*updater).Update(0xd053d0, 0x9f24c0, 0xc0000b1340, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/clair/ext/vulnsrc/rhel/rhel.go:133 +0x553
github.com/quay/clair/v2.fetch.func1(0x9f24c0, 0xc0000b1340, 0xc00011c120, 0xc000278300, 0x92a284, 0x4, 0x9e3600, 0xd053d0)
	/go/clair/updater.go:243 +0xa5
created by github.com/quay/clair/v2.fetch
	/go/clair/updater.go:242 +0x1a9
```

### Environment

* Clair version/image: quay.io/coreos/clair:latest
    * Via: https://hub.docker.com/r/arminc/clair-local-scan tag=latest which was built approx 2021-04-18
* Host OS: same result on Ubuntu linux and MacOS (Darwin)

**Comment by hdonnay** [comment]
v2 is unsupported, patches welcome

**Comment by ocrawford555** [comment]
Also seeing this problem (running Clair v2.1.6), would be great if the patch attached to this issue could be looked into. Thanks!

**Comment by mlhoyt** [comment]
@hdonnay thank you for the help getting the patch merged.

If there is documentation on how to proceed from here I have not found it.
How do I get a new tag created on the `release-2.0` branch?
How do I get a new image built and published from that new tag to https://quay.io/repository/coreos/clair ?

Thank you for the additional help!

**Comment by mlhoyt** [comment]
I am not sure who to thank for the new `v2.1.7` tag and the corresponding https://quay.io/repository/coreos/clair image but they are very much appreciated.

**Comment by mlhoyt** [comment]
AFAIK, this issue can be closed.  I am not sure why the "Fixes ..." line in the PR body did not close this automatically.

**Comment by klongmitre** [comment]
@mlhoyt - I'm still seeing the error using `quay.io/coreos/clair:v2.1.7` you reference above.
```
{"Event":"updating vulnerabilities","Level":"info","Location":"updater.go:192","Time":"2021-05-03 14:37:29.534705"}
{"Event":"fetching vulnerability updates","Level":"info","Location":"updater.go:239","Time":"2021-05-03 14:37:29.535840"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"alpine.go:52","Time":"2021-05-03 14:37:29.535923","package":"Alpine"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"oracle.go:119","Time":"2021-05-03 14:37:29.536785","package":"Oracle Linux"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"debian.go:63","Time":"2021-05-03 14:37:29.536904","package":"Debian"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2021-05-03 14:37:29.537638","package":"RHEL"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"ubuntu.go:85","Time":"2021-05-03 14:37:29.540400","package":"Ubuntu"}
panic: runtime error: slice bounds out of range

goroutine 15 [running]:
github.com/coreos/clair/ext/vulnsrc/rhel.toFeatureVersions(0xc420503bb0, 0x2, 0xc42000e070, 0x1, 0x1, 0xc4205186f0, 0x1, 0x1, 0x160, 0x83dc80, ...)
	/go/src/github.com/coreos/clair/ext/vulnsrc/rhel/rhel.go:292 +0xaf4
github.com/coreos/clair/ext/vulnsrc/rhel.parseRHSA(0x7f20d7bbb168, 0xc4202465d0, 0xc4202465d0, 0x7f20d7bbb168, 0xc4202465d0, 0x88ae6e, 0x4)
	/go/src/github.com/coreos/clair/ext/vulnsrc/rhel/rhel.go:182 +0x1c7
github.com/coreos/clair/ext/vulnsrc/rhel.(*updater).Update(0xafdf80, 0x8f02c0, 0xc42009f100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/clair/ext/vulnsrc/rhel/rhel.go:145 +0x6f6
github.com/coreos/clair.fetch.func1(0x8f02c0, 0xc42009f100, 0xc4200245f0, 0xc420020660, 0x88b11e, 0x4, 0x8e86e0, 0xafdf80)
	/go/src/github.com/coreos/clair/updater.go:243 +0xa5
created by github.com/coreos/clair.fetch
	/go/src/github.com/coreos/clair/updater.go:242 +0x19d
```
