### ISSUE TITLE
Could not save image: Error response from daemon: digest not found

### ISSUE THREAD

**Issue by westlifezs** [quay/clair#125]
Hello,

I was trying to call a remote running clair to get its scan report. The command I used is the same as described in the README of "analyze-local-images":

analyze-local-images -endpoint "http://CLAIR_IP:6060" -my-address "URL_TO_DOWNLOAD_IMAGE" -minimum-severity High IMAGE_ID

However, I got an error like the following:

 I | Saving hh to local disk (this may take some time)
Could not save image: Error response from daemon: digest not found

I verified each of the parameter and I believe they are correct.  I actually pulled the image into the clair node manually and did "docker images" in order to get its image id. Am I doing this correctly? does the digest here refer to image id?

thanks

**Comment by westlifezs** [comment]
Another related question I have is about "my-address parameters" for the tool "analyze-local-images". In  readme says that "The my-address parameters defines the IP address of the HTTP server that Clair will use to download the images. " does it mean "my-address" is equivalent to the URL value of "docker pull"? I am still having the digest not found issue even after I use my-address the same value as the URL I used for docker pull, could you please explain a bit more regarding how can I use  "analyze-local-images" together with a remote running clair? thanks

**Comment by westlifezs** [comment]
also, when I run "docker images --digests" I found out that DIGESTs for all my images are shown as none. Here is one example:
REPOSITORY       TAG                DIGEST              IMAGE ID            CREATED             SIZE
postgres                 latest              <none>              dbc8c4900ce5        12 days ago         264.6 MB

does it look right? shall I create a digest for the image for "analyze-local-images" to recognize the image remotely? or image id is suffice? thanks

**Comment by westlifezs** [comment]
When I use the same command line like:
analyze-local-images -endpoint "CLAIR_IP:6060" -my-address "CLAIR_IP" IMAGE_ID
It works when I run the command within clair server (CLAIR_IP is its public ip). However the same command won't work if I run it under another host even though I can ping/telnet the clair server with 6060 from that host. It still shows "Could not save image: Error response from daemon: digest not found". Any ideas? thanks

**Comment by Quentin-M** [comment]
Hi,

```
Could not save image: Error response from daemon: digest not found
```

Can you try to `docker save` an image on your machine (i.e. `docker save -o IMAGE_ID.tar IMAGE_ID`) ? If you can't, then the issue is most likely related to your Docker install. What's your version by the way?

```
also, when I run "docker images --digests" I found out that DIGESTs for all my images are shown as none.
```

Me too. It doesn't matter.

```
Another related question I have is about "my-address parameters" for the tool "analyze-local-images". In readme says that "The my-address parameters defines the IP address of the HTTP server that Clair will use to download the images. " does it mean "my-address" is equivalent to the URL value of "docker pull"? I am still having the digest not found issue even after I use my-address the same value as the URL I used for docker pull, could you please explain a bit more regarding how can I use "analyze-local-images" together with a remote running clair? thanks
```

analyze-local-images is a contrib tool that aims at helping people to get started with Clair. The [code](https://github.com/coreos/clair/blob/master/contrib/analyze-local-images/main.go) is quite straightforward, you might want to take a look. It simply save all the Docker layers of a given image on disk using `docker save`. Then it retrieves the image history to understand the order of the layers in the image. Finally, for each layer, it queries the Clair's API to analyze them. If Clair runs locally, it can simply gives Clair the local path to the layer archives. However, if Clair runs remotely, the tool setups a simple HTTP server that will serve these archives to Clair. This HTTP server only accepts requests from the Clair host (parsed out of the `-endpoint` parameter) to add a very thin layer of security in a very simple manner (again, this is not designed to be used in prod). Now, the tool must gives Clair the addresses where to download the layer archives from, this address is created using the `my-address` parameter.

**Comment by westlifezs** [comment]
thanks very much for the info.
You are right the issue comes from "docker save". It seems like I am not allowed to save the image unless I can see the image through "docker images" in the local host. Am I right?

Our goal is to do security checks for all of our docker images within our registry. I thought I could use a remote clair service along a set of parameters (information about container registry URL, image tags, etc) to do the work. Should I used "analyze-local-images" tool along with a remote clair server to do this? Or there are other better ways to do so? It will be wonderful if there is a tiny example regarding how I can set things up under this use case.

Thank you very much!

**Comment by westlifezs** [comment]
my docker version is 
:docker --version
Docker version 1.10.3, build 20f81dd

**Comment by Quentin-M** [comment]
Yeah, docker save requires that the image is present locally. This is why the tool is called "analyze-local-images`. Again, this is just to help people discovering Clair.

If you want to integrate Clair to your container registry, you should use the [Clair API](https://github.com/coreos/clair/blob/master/api/v1/README.md) directly. This is the best way to use Clair. More specifically, you want to call [POST /v1/layers](https://github.com/coreos/clair/blob/master/api/v1/README.md#post-layers) for every layer that your registry has. Then you can use [GET /v1/layers/:name](https://github.com/coreos/clair/blob/master/api/v1/README.md#get-layersname) to get vulnerabilities for your images. You'll also be able to receive and process useful [notifications](https://github.com/coreos/clair/blob/master/notifier/README.md) from Clair.

**Comment by westlifezs** [comment]
this is very helpful. I am also new to docker therefore I was not able to figure out earlier that " POST(GET) /v1/layers" is the kernel part of clair. I am closing the issue now as I am now cleared. thanks
