### ISSUE TITLE
updaters failing with 403 forbidden errors

### ISSUE THREAD

**Issue by sindhuputta** [quay/clair#1251]
### Description of Problem / Feature Request

Recently I have setup Clair V4.0.4 version in our local kubernetes environment. As soon the postgress db is available the clair server has updated DB with all CVEs, I can see it in logs. But after a while updaters kick in and I am seeing a bunch of HTTP 503 forbidden errors in logs. When the updaters initially could populate the postgress DB why does the incremental updaters fail so? And I don't see the URLs being posted to logs for which we have 503 forbidden error.

Also I see below notifier error, I tried to remove "notifier" stanza also tried to assign empty values in config.yaml but ClairV4 mandates to populate notifier and I don't have any webhook or any other amqs in place because we are least interested at the moment. Is there a way to skip notifier setup?
{"level":"error","component":"notifier/service/Init","component":"notifier/service/keyManagerInit","component":"notifier/keymanager/Manager.loop","time":"2021-04-22T11:39:50Z","time":"2021-04-22T11:39:50Z","message":"received error when bumping public key expiration"}

### Expected Outcome

Updaters should have updated DB without issues.

### Actual Outcome
{"level":"error","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","error":"updating errors:\n\tRHEL8-advanced-virtualization-including-unpatched: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-jboss-cs-including-unpatched: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-satellite-6.5: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-cfme-5.9: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-amq-clients-2: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL8-rhvm-4-including-unpatched: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-openshift-4.3: ovalutil: fet

I have pasted only a snippet here but the actual error much more bigger than this. Please let me know if you need any details.

### Environment
- Clair version/image: https://quay.io/repository/projectquay/clair:4.0.4
- Clair client name/version: clairctl:4.0.4
- Host OS: Red Hat Enterprise Linux Server release 7.9
- Kernel (e.g. `uname -a`): Linux 5.4.17-2036.102.0.2.el7uek.x86_64
- Kubernetes version (use `kubectl version`): 1.18.10
- Network/Firewall setup:

**Comment by sindhuputta** [comment]
Really appreciate it if someone can take a look into it. All I need to know is why would I get forbidden errors. I have even set the proxy and could reach external sites so no issues from our end.

**Comment by sindhuputta** [comment]
I was going through closed issues here and I found this suggestion by one of the members "hdonnay", he seem to be part of Clair team and the message goes like this - "There should be logs before this point that have the URL used, but I would be doubtful that this is a proxy issue as the upstream server returns 403 for a rate limit."
The logs before this point or even before 100 lines at this point doesn't print any URLS.
Although I can see some successful updaters like belos,

`
{"level":"debug","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","component":"libvuln/updateDriver/RunUpdaters","component":"internal/updater/Executor","run_id":1369830508,"updater":"RHEL8-rhel-8-including-unpatched","component":"internal/vulnstore/postgres/updateVulnerabilities","ref":"9c1fe950-b5e4-44b9-8638-556c49144887","time":"2021-05-03T12:44:23Z","time":"2021-05-03T12:44:23Z","message":"update_operation created"}
{"level":"debug","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","component":"libvuln/updateDriver/RunUpdaters","component":"internal/updater/Executor","run_id":1369830508,"updater":"debian-buster-updater","component":"internal/vulnstore/postgres/updateVulnerabilities","ref":"ca4ff6bc-87bc-40e0-89ed-9960ff403867","skipped":649,"inserted":21508,"ops_removed":1,"time":"2021-05-03T12:44:28Z","time":"2021-05-03T12:44:28Z","message":"update_operation committed"}
{"level":"info","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","component":"libvuln/updateDriver/RunUpdaters","component":"internal/updater/Executor","run_id":1369830508,"updater":"debian-buster-updater","ref":"ca4ff6bc-87bc-40e0-89ed-9960ff403867","time":"2021-05-03T12:44:28Z","time":"2021-05-03T12:44:28Z","message":"successful update"}
{"level":"debug","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","component":"libvuln/updateDriver/RunUpdaters","component":"internal/updater/Executor","run_id":1369830508,"updater":"debian-buster-updater","time":"2021-05-03T12:44:28Z","time":"2021-05-03T12:44:28Z","message":"done"}
{"level":"debug","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","component":"libvuln/updateDriver/RunUpdaters","component":"internal/updater/Executor","run_id":1369830508,"updater":"debian-stretch-updater","component":"internal/vulnstore/postgres/updateVulnerabilities","ref":"fdc71347-3517-478d-939a-0563e6d32a7f","skipped":0,"inserted":23949,"ops_removed":1,"time":"2021-05-03T12:44:30Z","time":"2021-05-03T12:44:30Z","message":"update_operation committed"}
{"level":"info","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","component":"libvuln/updateDriver/RunUpdaters","component":"internal/updater/Executor","run_id":1369830508,"updater":"debian-stretch-updater","ref":"fdc71347-3517-478d-939a-0563e6d32a7f","time":"2021-05-03T12:44:30Z","time":"2021-05-03T12:44:30Z","message":"successful update"}
{"level":"debug","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","component":"libvuln/updateDriver/RunUpdaters","component":"internal/updater/Executor","run_id":1369830508,"updater":"debian-stretch-updater","time":"2021-05-03T12:44:30Z","time":"2021-05-03T12:44:30Z","message":"done"}
{"level":"debug","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","component":"libvuln/updateDriver/RunUpdaters","component":"internal/updater/Executor","run_id":1369830508,"updater":"RHEL8-rhel-8-including-unpatched","component":"internal/vulnstore/postgres/updateVulnerabilities","ref":"9c1fe950-b5e4-44b9-8638-556c49144887","skipped":0,"inserted":1552848,"ops_removed":1,"time":"2021-05-03T12:48:30Z","time":"2021-05-03T12:48:30Z","message":"update_operation committed"}
{"level":"info","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","component":"libvuln/updateDriver/RunUpdaters","component":"internal/updater/Executor","run_id":1369830508,"updater":"RHEL8-rhel-8-including-unpatched","ref":"9c1fe950-b5e4-44b9-8638-556c49144887","time":"2021-05-03T12:48:30Z","time":"2021-05-03T12:48:30Z","message":"successful update"}
{"level":"debug","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","component":"libvuln/updateDriver/RunUpdaters","component":"internal/updater/Executor","run_id":1369830508,"updater":"RHEL8-rhel-8-including-unpatched","time":"2021-05-03T12:48:30Z","time":"2021-05-03T12:48:30Z","message":"done"}
{"level":"debug","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","component":"libvuln/updateDriver/RunUpdaters","component":"internal/updater/Executor","run_id":1369830508,"time":"2021-05-03T12:48:30Z","time":"2021-05-03T12:48:30Z","message":"done"}
{"level":"error","component":"libvuln/New","component":"libvuln/Libvuln/loopUpdaters","error":"updating errors:\n\tRHEL8-openstack-15.0-including-unpatched: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-rhel-7.4-e4s: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL8-storage-ceph-4-including-unpatched: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL8-openshift-4.3: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL8-rhoar-nodejs-12: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL8-openshift-4.1: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL8-openstack-16: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-ansible-2.6: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-openshift-4.3: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-openshift-service-mesh-1.1: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-rhel-7.4-tus: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL6-satellite-tools-6.3: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-openstack-8-including-unpatched: ovalutil: fetcher got unexpected HTTP response: 403 (403 Forbidden)\n\tRHEL7-j
`

**Comment by sindhuputta** [comment]
Also it seems these are the list of updater URLs:
https://secdb.alpinelinux.org/
http://repo.us-west-2.amazonaws.com/2018.03/updates/x86_64/mirror.list
https://cdn.amazonlinux.com/2/core/latest/x86_64/mirror.list
https://www.debian.org/security/oval/
https://linux.oracle.com/security/oval/
https://packages.vmware.com/photon/photon_oval_definitions/
https://github.com/pyupio/safety-db/archive/
https://catalog.redhat.com/api/containers/
https://www.redhat.com/security/data/
https://support.novell.com/security/oval/
https://people.canonical.com/~ubuntu-security/oval/

So I tested each one of them inside my clair container environment with Curl and all of them worked, meaning I did not get any blocks from our proxy.

**Comment by hdonnay** [comment]
As you seem to have found in [1168](https://github.com/quay/clair/discussions/1168), the 403 errors are (almost certainly) a rate limit from the upstream Red Hat servers.

The URLs should be in the logs; grepping for the name of the updater (e.g. `RHEL7-openshift-4.3`) will help narrow down the log messages.

The 403 avalanche on a fresh start is a known issue, and will hopefully be fixed in v4.1. I realize this is quite annoying.

**Comment by sindhuputta** [comment]
Thanks Hank. We are ignoring them for now.

**Comment by hdonnay** [comment]
This should be OK with the v4.1.0 release. If you can find time, please check that it fixes the 403 returns.

**Comment by sindhuputta** [comment]
Thanks Hank. We will try and let you know how it goes.

**Comment by hdonnay** [comment]
Closing due to age. If there are still updater problems on startup, please open new issues.
