### ISSUE TITLE
Will there be a new 2.1.x release?

### ISSUE THREAD

**Issue by reasonerjt** [quay/clair#1253]
Dear maintainers,

Will you release a new patch for 2.1.x to incorporate the following fix?
https://github.com/quay/clair/commit/31e704b589553981c47cdaa0c519d4f909fa7db6

**Comment by hdonnay** [comment]
The latest v2 tag, [v2.1.7](https://github.com/quay/clair/tree/v2.1.7), contains this fix. I'll try to build and push a new container once I sort out access to  the old coreos namespace.
