### ISSUE TITLE
Debug mode for clairctl 4.04 version, no information in usage of this tool as well.

### ISSUE THREAD

**Issue by sindhuputta** [quay/clair#1258]
### Description of Problem / Feature Request
I am clairctl V4.0.4(linux-amd64). It used to work until couple of days back but all of a sudden I am getting 404 for report option. But it doesnot print any more details that I can use to debug. It just prints one line like below,
2021/05/01 00:30:13 unexpected return status: 404

I have see the clairctl usage and i don't find any option to enable debug mode. Even then I have used --log-level debug but clairctl just exits with message 2021/05/01 00:25:46 flag provided but not defined: -log-level

### Expected Outcome
Vulnerability report

### Actual Outcome
2021/05/01 00:30:13 unexpected return status: 404

### Environment

- Clair version/image: 4.0.4
- Clair client name/version: clairctl-4.04(linux-amd64)
- Host OS: Linux 7
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): N/A
- Network/Firewall setup:

**Comment by hdonnay** [comment]
Clairctl has a debug flag, `D`. The flags are different between the main
command and the subcommand, see also `clairctl help` and `clairctl help report`.

Also, in 4.0 the debug flag only applies to the `clairctl` internals.

**Comment by sindhuputta** [comment]
Hi Hank,
Like I mentioned I did not see anything about debug mode in the help message. Please see below help message by clarictl-4.0.4 version,

`skputta-mac:cmd skputta$ ./clairctl help report
NAME:
   clairctl report - request vulnerability reports for the named containers

USAGE:
   clairctl report [command options] container...

DESCRIPTION:
   Request and print a Clair vulnerability report for the named container(s).

OPTIONS:
   --host value           URL for the clairv4 v1 API. (default: "http://localhost:6060/") [$CLAIR_API]
   --out value, -o value  output format: text, json, xml (default: text)
   
skputta-mac:cmd skputta$ ./clairctl help 
NAME:
   clairctl - interact with a clair API

USAGE:
   clairctl [global options] command [command options] [arguments...]

VERSION:
   0.1.0

DESCRIPTION:
   A command-line tool for clair v4.

COMMANDS:
   manifest         print a clair manifest for the named container
   report           request vulnerability reports for the named containers
   export-updaters  run updaters and export results
   import-updaters  import updates
   help, h          Shows a list of commands or help for one command

GLOBAL OPTIONS:
   -D                           print debugging logs (default: false)
   --config value, -c value     clair configuration file (default: "config.yaml") [$CLAIR_CONF]
   --issuer value, --iss value  jwt "issuer" to use when making authenticated requests (default: "clairctl")
   --help, -h                   show help (default: false)
   --version, -v                print the version (default: false)
`

**Comment by sindhuputta** [comment]
I am looking for debug mode for report subcommand, since its not mentioned in the usage message, please let me know the flag and usage information. Thanks Hank.

**Comment by hdonnay** [comment]
Like I said, it's the `D` flag: `clairctl -D report ...`
