### ISSUE TITLE
Excluding certain paths during the Clair scan

### ISSUE THREAD

**Issue by chaitanyamoger** [quay/clair#1272]
### Description of Problem / Feature Request

While scanning images there are some paths in the image containing jars which create vulnerabilities which we want to ignore. We want to remove these by excluding these paths from the scans. How do I exclude a path in the image from being scanned for vulnerabilities?

### Expected Outcome

Ability to exclude paths from being scanned

### Actual Outcome

Whole container is being scanned for vulnerabilities

  ### Environment
  
  
  
  - Clair version/image: quay.io/coreos/clair:v2.1.6"
  - Clair client name/version: Klar V2.4.0
  - Host OS: Linux
  - Kernel (e.g. `uname -a`): 4.1.12-124.40.6.el7uek.x86_64
  - Kubernetes version (use `kubectl version`): 1.19
  - Network/Firewall setup: No

**Comment by hdonnay** [comment]
This is not possible, and the ability will most likely not be added. Any consumer of Clair's reports should discard or ignore vulnerabilities that they determine can be allowed. In our view, the client is more likely to be in a position to make interpretation and policy decisions like this.
