### ISSUE TITLE
could not pull ubuntu-cve-tracker repository The requested URL returned error: 503

### ISSUE THREAD

**Issue by SoaadMahmoud** [quay/clair#1275]
### Description of Problem / Feature Request

<could not pull ubuntu-cve-tracker repository The requested URL returned error: 503>

### Expected Outcome

<Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2021-04-21 16:15:40.668695","updater name":"ubuntu"}>

### Actual Outcome

<"Event":"could not pull ubuntu-cve-tracker repository","Level":"error","Location":"ubuntu.go:174","Time":"2021-05-27 12:14:15.262830","error":"exit status 128","output":"Cloning into '.'...\nerror: RPC failed; HTTP 503 curl 22 The requested URL returned error: 503\nfatal: expected flush after ref listing\n"}
 {"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2021-05-27 12:14:15.262888","error":"could not download requested resource","updater name":"ubuntu"}>

### Environment

<prod
-->

- Clair version/image: 2.1.7
- Clair client name/version: 
- Host OS: redhat 7
- Kernel (e.g. `uname -a`): 3.10.0-1062.el7.x86_64
- Kubernetes version (use `kubectl version`): not used
- Network/Firewall setup:

**Comment by hdonnay** [comment]
This is a server-side error, there's nothing Clair can do except perhaps retry at a better time.

**Comment by DoctahPopp871** [comment]
Hello, 
I just ran into the same error and opened a similar issue : https://github.com/quay/clair/issues/1302

Im wondering why the `git://git.launchpad.net/ubuntu-cve-tracker` is not being used, it seems to be more stable then the HTTP(s) endpoint.
