### ISSUE TITLE
swagger: request url is misconfigured

### ISSUE THREAD

**Issue by Dentrax** [quay/clair#1280]
### Description of Problem / Feature Request

I think request URL is misconfigured on the Swagger. Currently, it tries to send a `[POST]` request to: `localhost:8082indexer` 

I tried on this commit: 45538e0ccee4d4ee12247da11f295ff32dcbe4ff

### Expected Outcome

I guess, it should be: `http://localhost:8082/indexer/api/v1/index_report`

### Actual Outcome

![Screen Shot 2021-06-02 at 17 56 04](https://user-images.githubusercontent.com/16493751/120503256-cffa5900-c3cb-11eb-9881-6c8a15b03887.png)

**Comment by hdonnay** [comment]
I think this is fixed in the linked PR.
