### ISSUE TITLE
localhost:8080 page throws 502 Bad Gateway - timeout and high cpu problems

### ISSUE THREAD

**Issue by Dentrax** [quay/clair#1281]
### Description of Problem / Feature Request

I was following the how-to [documentation](https://quay.github.io/clair/howto/getting_started.html) step-by-step.

```
$ git clone git@github.com:quay/clair.git
$ cd clair
$ make local-dev-up-with-quay
```

If I wait ~5-10 mins, then CPU usage drop down to %10 and `localhost:8080` starts throwing `The connection was reset` error.

### Expected Outcome

It should work?

### Actual Outcome

502 Bad Gateway
High CPU Usage? (Is it normal?)

```
$ kubectl version

Unable to connect to the server: net/http: TLS handshake timeout
```

![Screen Shot 2021-06-02 at 18 42 25](https://user-images.githubusercontent.com/16493751/120510626-47cb8200-c3d2-11eb-8dcc-e2869720ded9.png)

![Screen Shot 2021-06-02 at 18 42 18](https://user-images.githubusercontent.com/16493751/120510608-439f6480-c3d2-11eb-9f60-6578aac2faae.png)

### Environment

- Clair version/image: 45538e0ccee4d4ee12247da11f295ff32dcbe4ff
- Clair client name/version: `does not installed`
- Host OS: `macOS 11`
- Kernel (e.g. `uname -a`): `Darwin XXX 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64`
- Kubernetes version (use `kubectl version`): `Client 1.19`
- Network/Firewall setup: `no firewall`

_How can I export a log file in order to make diagnosis easier?_
Any ideas? 🤔

**Comment by crozzy** [comment]
Hi!

Just tried this again and everything worked as expected, there is a delay between the `make` command starting the container and quay becoming available, but usually just a minute or two.

All the `make` command is doing is starting selected containers that are defined in the `docker-compose.yaml` file and thus you can view the container logs with the standard docker commands (e.g. `docker ps`, `docker logs clair-quay -f` etc.).
