### ISSUE TITLE
Undetected vulnerabilities in Clair vs Trivy

### ISSUE THREAD

**Issue by JamesAHowieson** [quay/clair#1291]
### Description of Problem / Feature Request

I was using ClairV2 against an Alpine image running python, originally no vulnerabilities were found, I thought this was strange as I knew for a fact that image had vulnerabilities. Assuming it was the outdated Clair version, I ran another scan using AWS ECR, which I'm assuming uses an up-to-date version of Clair. This time vulnerabilities were found, but only 20.

When I ran Trivy locally, it found 86 total vulnerabilities from the same image. I was even using the "--ignore-unfixed" parameter.

Just flagging this up in case you weren't aware of this. I found a closed issue about the Alpine source database here --> https://github.com/quay/clair/issues/754. In case they are in anyway related.

### Expected Outcome

Up-to-date version of Clair should be able to detect the same or similar amount of vulnerabilities as Trivy.

### Actual Outcome

Clair misses a lot of vulnerabilities that are present in the image that Trivy is picking up.

### Environment

- Clair version/image: V2, assuming V4 on AWS ECR
- Clair client name/version: N/A
- Host OS: N/A
- Kernel (e.g. `uname -a`): N/A
- Kubernetes version (use `kubectl version`): N/A
- Network/Firewall setup: N/A

**Comment by hdonnay** [comment]
Going to close this, as it's a v2 issue.

Feel free to reopen if you can add a v4 reproducer. In this case, that'd be a false positive/negative from the alpine security database and the manifest/registry tag that produces it.
