### ISSUE TITLE
aggregating layer vulnerability report into image level

### ISSUE THREAD

**Issue by westlifezs** [quay/clair#130]
It appears to me that vulnerabilities per layer within each image are grouped directly in "analyze-local-images": https://github.com/coreos/clair/blob/master/contrib/analyze-local-images/main.go#L194

However, what if a vulnerability detected at a lower layer has been patched at an higher level (e.g. higher layer is created through "apt-get update")? will the vulnerabilities detected at a lower layer still be presented as a result? Or it will be removed? I have not identified where this scenario is being handled. Any comments will be highly appreciated!   

Thanks,

**Comment by Quentin-M** [comment]
Hi,

[`GET /v1/layers/:name`](https://github.com/coreos/clair/tree/master/api/v1#get-layersname) correctly returns all the features and vulnerabilities that may affect the specified layer, taking into account every parent layers in the right order. Thus, every additions, deletions or updates in any layers of an image are properly accounted for. This is why `ParentName` must be specified in [`POST /v1/layers`](https://github.com/coreos/clair/tree/master/api/v1#post-layers).

This is why `analyze-local-images` only calls `GET /v1/layers/:name` on the last layer of the image.

Relevant:
- https://github.com/coreos/clair/blob/f0642bb/database/pgsql/layer.go#L27
- https://github.com/coreos/clair/blob/f0642bb/database/pgsql/layer.go#L116
- https://github.com/coreos/clair/blob/f0642bb/database/pgsql/queries.go#L86

**Comment by westlifezs** [comment]
thanks for your clarification. so if I need to obtain a vulnerability report for a target image, I only need to "GET /v1/layers/TARGET_IMAGE_ID" after I posted all of its ancestors in the right order, right?

**Comment by westlifezs** [comment]
confirmed based on my test. thanks
