### ISSUE TITLE
could not pull ubuntu CVE tracker repository using HTTPs URL

### ISSUE THREAD

**Issue by DoctahPopp871** [quay/clair#1302]
### Description of Problem / Feature Request

<could not pull ubuntu-cve-tracker repository The requested URL returned error: 503>

### Expected Outcome

<Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2021-04-21 16:15:40.668695","updater name":"ubuntu"}>

### Actual Outcome

< clair {"Event":"could not pull ubuntu-cve-tracker repository","Level":"error","Location":"ubuntu.go:174","Time":"2021-06-24 17:45:40.445250","error":"exit status 128","output":"Cloning into '.'...\nfatal: unable to access 'https://git.launchpad.net/ubuntu-cve-tracker/': The requested URL returned error: 503\n"}
 clair {"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2021-06-24 17:45:40.445324","error":"could not download requested resource","updater name":"ubuntu"}>

### Environment

<prod>

- Clair version/image: 2.1.7
- Clair client name/version: 
- Host OS: cos-linux
- Kernel (e.g. `uname -a`): `<5.4.89+ #1 SMP Sat Feb 13 19:45:14 PST 2021 x86_64 Intel(R) Xeon(R) CPU GenuineIntel GNU/Linux>`
- Kubernetes version (use `kubectl version`): not used
- Network/Firewall setup: 

This is related to issue : https://github.com/quay/clair/issues/1275

I have been able to replicate this connectivity issue locally by interacting with the HTTPs URL via git clone 
```
Cloning into 'ubuntu-cve-tracker'...
fatal: unable to access 'https://git.launchpad.net/ubuntu-cve-tracker/': The requested URL returned error: 503
```

However when using the git based url  `git://git.launchpad.net/ubuntu-cve-tracker` The git interaction succeeds. If the HTTPs URL is unstable server side, and the git url is stable, is there any reason why that is not being used ? 

Change could be made here to use the non HTTPs URL : https://github.com/quay/clair/blob/ba233c85f0fb1af56a1866cda819f69e2e04da20/ext/vulnsrc/ubuntu/ubuntu.go#L39

**Comment by hdonnay** [comment]
This was done in af7d890, so it's been that way ever since git started being used. It seems odd to switch to an insecure transport just to work around transient errors on the server side.

This being a v2 issue, it's not going to get worked on by any current maintainers.

**Comment by SofyaTavrovskaya** [comment]
@hdonnay, @DoctahPopp871  I'm not sure that it's a transient error. I see in Clair logs that this error is being occurred since the end of April, and I don't see any successful try until today

**Comment by SofyaTavrovskaya** [comment]
@hdonnay One more question: Is there any way to configure Сlair v2 to make retries if it receives 503 error during updating. Because it's not only our problem: https://bugs.launchpad.net/ubuntu-cve-tracker/+bug/1925337

**Comment by hdonnay** [comment]
Configure? I don't think so, but I'm not certain.
