### ISSUE TITLE
Error registering to listen for server side events.

### ISSUE THREAD

**Issue by sbenhai** [quay/clair#1305]
When I try to go through tutorials step by step I get this [error](https://drive.google.com/file/d/1NjS9wEnsSU_F9EwxlOi2IF-suPWygxRv/view?usp=sharing) at Step 4.

**Comment by hdonnay** [comment]
This looks like an issue with `quay`, and more appropriate for that project's issue tracker.

**Comment by BillDett** [comment]
Please feel free to raise a ticket for us at https://issues.redhat.com/projects/PROJQUAY.  Please add as much detail as possible (including your quay configuration if possible).
