### ISSUE TITLE
Not able to install Clair Scanner

### ISSUE THREAD

**Issue by bhuvi11** [quay/clair#1310]
We are currently trying to use clair for container image scanning. We have tried almost all the possible installation documents. None of them are working

Clair-scanning - Not working
Clairctl - not working
Using docker-compose up not working
Clair API - Not working

What exactly should be the IP ?  i have tried local IP, public IP, docker0 IP. Nothing is working

Can someone please help

**Comment by crozzy** [comment]
Hi @bhuvi11, it's a little hard to debug from the information provided, can you provide any logs from any of the methods you tried?

Note:
Clair-scanning: what do you mean specifically by this?
Clairctl: Needs to pointed at a working Clair instance, so not likely to be work if the instance isn't working
Using docker-compose up: please used the provided Makefile commands to run clair in docker as it chooses which services to start based on the command
Clair API: Not sure what you are referring to here.

Thanks

**Comment by hdonnay** [comment]
Closing due to lack of response.
