### ISSUE TITLE
Error in pushing the test ubuntu image

### ISSUE THREAD

**Issue by bparinas** [quay/clair#1311]
I'm using the latest local dev release

### Description of Problem / Feature Request

~/clair$ podman pull ubuntu:latest
Trying to pull docker.io/library/ubuntu:latest...
Getting image source signatures
Copying blob c549ccf8d472 skipped: already exists  
Copying config 9873176a8f done  
Writing manifest to image destination
Storing signatures
9873176a8ff5ac192ce4d7df8a403787558b9f3981a4c4d74afb3edceeda451c
~/clair$ podman login --tls-verify=false localhost:8080
Authenticating with existing credentials...
Existing credentials are valid. Already logged in to localhost:8080
~/clair$ podman tag ubuntu:latest localhost:8080/clairv4-org/testing:latest
~/clair$ podman push --tls-verify=false localhost:8080/clairv4-org/testing:latest
Getting image source signatures
Error: Error trying to reuse blob sha256:feef05f055c989eea0367f5d3a2cba79896dd6d8a8b72bea2c729548a4ca5aef at destination: Error checking whether a blob sha256:feef05f055c989eea0367f5d3a2cba79896dd6d8a8b72bea2c729548a4ca5aef exists in localhost:8080/clairv4-org/testing: unauthorized: authentication required

**Comment by hdonnay** [comment]
This looks like an issue with a container registry (I assume quay?), not with Clair. Their issue tracker would probably have some actionable ideas.
