### ISSUE TITLE
502 Bad Gateway Error - Clair v4.0.6

### ISSUE THREAD

**Issue by arvindbalaji** [quay/clair#1317]
### Description of Problem / Feature Request

Doing the following with https://github.com/quay/clair/releases/tag/v4.0.6.
- Running Clair locally with "make local-dev-up". 
- No changes to the config.yml file.
- All the containers start up as expected and on Traefik's UI on port 7000, it shows Clair running on 6060.

**Issue**
However, running the scan using clairctl returns a 502 Bad Gateway Error. The logs contain the following error message:
**clair-notifier | 9:14PM ERR client error retreiving latest update operations. backing off until next interval error="/matcher/api/v1/internal/update_operation/: unexpected status: 502 Bad Gateway" component=notifier/updatepoller/Poller.onTick**

### Actual Outcome

./clairctl-linux-amd64 -D report "alpine"
debug: 2021/07/19 14:13:57 alpine: fetching
debug: 2021/07/19 14:13:57 using text output
debug: 2021/07/19 14:13:58 alpine: manifest: sha256:1775bebec23e1f3ce486989bfc9ff3c4e951690df84aa9f926497d82f2ffca9d
debug: 2021/07/19 14:13:58 GET /indexer/api/v1/index_report/sha256:1775bebec23e1f3ce486989bfc9ff3c4e951690df84aa9f926497d82f2ffca9d: 404 Not Found
debug: 2021/07/19 14:13:58 need to post manifest sha256:1775bebec23e1f3ce486989bfc9ff3c4e951690df84aa9f926497d82f2ffca9d
debug: 2021/07/19 14:13:58 don't have needed manifest sha256:1775bebec23e1f3ce486989bfc9ff3c4e951690df84aa9f926497d82f2ffca9d
debug: 2021/07/19 14:13:58 alpine: found manifest sha256:1775bebec23e1f3ce486989bfc9ff3c4e951690df84aa9f926497d82f2ffca9d
debug: 2021/07/19 14:13:58 alpine: found 1 layers
debug: 2021/07/19 14:13:59 GET /indexer/api/v1/index_report/sha256:1775bebec23e1f3ce486989bfc9ff3c4e951690df84aa9f926497d82f2ffca9d: 404 Not Found
debug: 2021/07/19 14:13:59 need to post manifest sha256:1775bebec23e1f3ce486989bfc9ff3c4e951690df84aa9f926497d82f2ffca9d
debug: 2021/07/19 14:13:59 POST /indexer/api/v1/index_report: 201 Created
debug: 2021/07/19 14:13:59 setting validator "/indexer/api/v1/index_report/sha256:1775bebec23e1f3ce486989bfc9ff3c4e951690df84aa9f926497d82f2ffca9d" → "\"2fe35c45ab26679b8a6d1281a85109f4\""
debug: 2021/07/19 14:13:59 GET /matcher/api/v1/vulnerability_report/sha256:1775bebec23e1f3ce486989bfc9ff3c4e951690df84aa9f926497d82f2ffca9d: 502 Bad Gateway
alpine error unexpected return status: 502

### Environment

- Clair version/image: 4.0.6
- Clair client name/version: https://github.com/quay/clair/releases/download/v4.0.6/clairctl-linux-amd64 
- Host OS: Linux
- Kernel (e.g. `uname -a`): Linux ubuntu 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`): N/A
- Network/Firewall setup: N/A

**Comment by hdonnay** [comment]
With the release of 4.3, 4.0 is out of support.
