### ISSUE TITLE
Basic auth support?

### ISSUE THREAD

**Issue by mattlorimor** [quay/clair#135]
I've been working on adding basic auth support so that Clair can pull images directly from Docker Registry servers that require basic auth.

Would you want to see this as a pull request to Clair so that others can benefit from this feature. If you are not interested in supporting basic auth at all, I'll simply fork the code for our own internal use.

Let me know!

**Comment by jzelinskie** [comment]
When you POST to `/v1/layers` with `https://user:password@yourregistry.com/path/to/layer` does it not simply work? This would be ideally how we support this if we don't already.

**Comment by mattlorimor** [comment]
Dammit. Good question. Trying...

**Comment by mattlorimor** [comment]
Yep. Works fine. Disregard my silliness. It's been a long day. :)
