### ISSUE TITLE
Clair docker image v2.1.7 doesn't support scam-sha-256 encryption postgres

### ISSUE THREAD

**Issue by daliaezt** [quay/clair#1354]
Hi Team,

we have clair installed as docker container v2.1.7 and connecting to external postgres v12 using md5 encryption method.

we need to change md5 method to scram-sha-256 method for postgres.

After switching to scram-sha-256, clair container wasn't able to connect to postgres and showing below error msg 
 {"Event":"pgsql: could not open database: pq: unknown authentication response: 10","Level":"fatal","Location":"main.go:97"}

Does clair v2.1.7 support scram-sha-256 ?

**Comment by hdonnay** [comment]
It looks like the version of `github.com/lib/pq` used doesn't support it.

Patches welcome if someone has the time to make the change and test it. I'll close this in a few days if no one steps up.
