### ISSUE TITLE
Update 'quay.io/projectquay/golang' version to v1.17 in docker-compose.yaml to support Linux/ARM64 

### ISSUE THREAD

**Issue by odidev** [quay/clair#1355]
### Description of Problem / Feature Request

I am working with Clair on the Linux/ARM64 platform. 

**docker-compose.yaml** file creates containers with 'quay.io/projectquay/golang:1.16' docker image. Since version 1.17 is now available with Linux/ARM64 support, it will be helpful if the golang version is updated to 1.17 in the docker-compose.yaml file as well. 

Please share your opinion on this. If interested, I am happy to raise a PR. 

### Environment

- Clair version/image: main branch
- Clair client name/version: https://github.com/quay/clair/releases/download/v4.1.1/clairctl-linux-arm64
- Host OS: Linux (Ubuntu)
- Kernel : Linux/ARM64 (AARCH64)
- Kubernetes version : v1.21
- Network/Firewall setup: NA

**Comment by hdonnay** [comment]
yeah, this sounds great
