### ISSUE TITLE
Security Scan is queued

### ISSUE THREAD

**Issue by JagadeeshRam** [quay/clair#1358]
### Description of Problem / Feature Request

I have setup clair in local with quay . I followed the steps mentioned in documentation but after pushing the image it was showing security scan is queued for many hours
![image](https://user-images.githubusercontent.com/55401565/132469347-4ca903cb-3d7d-4218-8347-9287ead97dfd.png)

### Expected Outcome
The Expected outcome is
![image](https://user-images.githubusercontent.com/55401565/132469494-16ac87c3-0906-40dd-b580-0ad535f4de7b.png)

### Environment

- Clair version/image:  Clair  V2.2
- Clair client name/version:  Quay
- Host OS: CentOS 8

**Comment by Amar1729** [comment]
Did you bring up clair with the make target `local-dev-up-with-qauy`? If so, is the indexer service running? Check with `docker-compose ps`.

If the indexer service (`clair-indexer`) says `Exit 1` you may have to bring it up again, with `docker-compose up -d indexer-quay`.

**Comment by JagadeeshRam** [comment]
Clair -indexer was working perfectly it didn't show  any errors  and also gone through the errors ,no issues was found
![image](https://user-images.githubusercontent.com/55401565/132551365-50d4ccc8-fa37-4c94-ac18-cb4b7d4b60ac.png)

**Comment by hdonnay** [comment]
You'll need to provide information about your configuration, preferably without using quay. For example, configuration and logs when running a report via `clairctl`.

**Comment by JagadeeshRam** [comment]
When I run with clairctl i got the error

![WhatsApp Image 2021-09-09 at 4 52 12 PM](https://user-images.githubusercontent.com/55401565/132677402-ad65b31e-e791-4f75-b621-d1f1d07e8177.jpeg)

**Comment by hdonnay** [comment]
I suspect you're using an external command called `clairctl`, not the one from this project.

**Comment by JagadeeshRam** [comment]
Yes I was using differnt one sorry for that . After  I using Clairctl from this project it was not giving the report .Just printing "OK"
![image](https://user-images.githubusercontent.com/55401565/136251071-9ca37777-1563-4ece-bd0a-c87b7adcbc6c.png)

Is there any reason for it

**Comment by crozzy** [comment]
No vulnerabilities were found for that image, you can use `clairctl -D report --out json debian:latest` for a more verbose report in JSON:

```
NAME:
   clairctl report - request vulnerability reports for the named containers

USAGE:
   clairctl report [command options] container...

DESCRIPTION:
   Request and print a Clair vulnerability report for the named container(s).

OPTIONS:
   --host value           URL for the clairv4 v1 API. (default: "http://localhost:6060/") [$CLAIR_API]
   --out value, -o value  output format: text, json, xml (default: text)
   --help, -h             show help (default: false)
   

```
