### ISSUE TITLE
analyze-local-images tool reports the second latest layer report rather than the current image layer?

### ISSUE THREAD

**Issue by westlifezs** [quay/clair#136]
It seems like "analyze-local-images" evaluate all "Layers" one by one within "manifest.json" while assessing the target image, right? However, the topmost layer is not included in the "Layers" within "manifest.json". It is actually the value of "Config". It appears to me that the tool returns the most-recent-history layer assessment result rather than the assessment result for the target image (topmost layer), right? Here is the code I was looking at: https://github.com/coreos/clair/blob/master/contrib/analyze-local-images/main.go#L130. I guess if this is the case, then it probably needs to be fixed.

Correct me if I am wrong.

**Comment by liangchenye** [comment]
The 'Config' is not used and the topmost layer is included:
https://github.com/coreos/clair/blob/master/contrib/analyze-local-images/main.go#L310

**Comment by westlifezs** [comment]
makes sense. thx
