### ISSUE TITLE
Clair 4.2.0 not scanning RHEL RPMs

### ISSUE THREAD

**Issue by jasonbrianhall** [quay/clair#1361]
It doesn't seem like Clair 4.2.0 is scanning RPMs .  I scanned some of my images that were several months old and richxsl/rhel7 from docker.io and only received some pypi results and maven findings.    I can see that the the database has RHEL based vulnerabilities when I query the "vuln" table but they aren't showing up when I query http://matcher:port/matcher/api/v1/vulnerability_report/imageDigest
[richxsl_rhel7.json.gz](https://github.com/quay/clair/files/7146457/richxsl_rhel7.json.gz)

**Comment by hdonnay** [comment]
Do you have logs from the server for a run?

**Comment by jasonbrianhall** [comment]
See attached log.

**Comment by hdonnay** [comment]
If you attached something to the email, it didn't make it to the github issue.
If you're referencing the upload on the initial post, that's not a log; it looks like the response to an API call.

**Comment by jasonbrianhall** [comment]
[clair.tar.gz](https://github.com/quay/clair/files/7158007/clair.tar.gz)

Attached the logs (HTML and ANSI)

**Comment by hdonnay** [comment]
From the logs and server response, it looks like the image was indexed successfully.

From the server logs, it looks like the server was stopped in the middle of fetching vulnerabilities. Please try using the latest version and letting the server finish fetching vulnerabilities.

**Comment by jasonbrianhall** [comment]
Ran 4.2.2 all day and it is still doing the same thing.

**Comment by hdonnay** [comment]
Is this still happening on the latest release?

**Comment by hdonnay** [comment]
Closing due to age.
