### ISSUE TITLE
Please use OVAL export for Ubuntu vulnerabilities source

### ISSUE THREAD

**Issue by Tejuvmware** [quay/clair#1373]
### Description of Problem / Feature Request

This is with respect to the issue https://github.com/quay/clair/issues/804 . I'm one of the customer who is facing issues in pulling https://git.launchpad.net/ubuntu-cve-tracker (https://bugs.launchpad.net/ubuntu-cve-tracker/+bug/1943825)  due to multiple github calls and on reaching out to ubuntu-cve-tracker team I have been redirected to clair developers. 

I just wanted to check if we got fix for this in any of the versions of Clair ?  Using OVAL is going to solve my problem. May I know in which versions of clair image this has been implemented ?

Currently I'm using goharbor/clair-photon:v2.1.0 version in our k8s cluster which is going with multiple docker image restarts as it is failing to pull https://git.launchpad.net/ubuntu-cve-tracker.

**Comment by hdonnay** [comment]
V2 is not actively maintained. Changing the source has not been implemented in any Clair v2 version. Patches welcome.

**Comment by Tejuvmware** [comment]
Thank you for the response @hdonnay. What can be the solution for the bug then?

**Comment by hdonnay** [comment]
The solution would be for someone running the old version to write, test, and submit a patch.

**Comment by Tejuvmware** [comment]
Can we have someone from clair developer to release a patch for this bug ?

**Comment by hdonnay** [comment]
To the best of my knowledge, there are no active developers for v2.
