### ISSUE TITLE
Issues using analyze-local-images tool

### ISSUE THREAD

**Issue by Jerem28** [quay/clair#138]
When I'm trying to run the analyze-local-images tool with Clair deployed locally, I always encounter this problem : 

```
2016-04-11 16:58:38.125330 I | Saving a443d5a72a2e to local disk (this may take some time)
2016-04-11 16:58:47.805567 I | Retrieving image history
2016-04-11 16:58:47.822857 I | Setting up HTTP server (allowing: clairsvc-clair.kmt-dev1.orange-labs.fr)
2016-04-11 16:58:47.923039 I | Analyzing 14 layers...
2016-04-11 16:58:47.923052 I | Analyzing d8bd0657b25f17eef81a3d52b53da5bda4de0cf5cca3dcafec277634ae4b38fb
2016-04-11 16:58:48.059773 I | Could not analyze layer: Got response 400 with message {"Error":{"Message":"could not find layer"}}
```

Concerning the logs produced by my Clair instance running, I have this : 

`worker: layer d8bd0657b25f17eef81a3d52b53da5bda4de0cf5cca3dcafec277634ae4b38fb: failed to extract data from http://127.0.0.1:9279/d8bd0657b25f17eef81a3d52b53da5bda4de0cf5cca3dcafec277634ae4b38fb/layer.tar: could not find layer
`

I've also noticed that the layer.tar normally generated by a function in analyze-local-images never appears in my /tmp directory.

I've tried many differents configuration (also trying to use it but remotely, but it always give me the same response from the worker component).

**Comment by Quentin-M** [comment]
Hi,

It looks like that Clair runs on a remote host and that you've specified the `-endpoint` parameter correctly (`clairsvc-clair.kmt-dev1.orange-labs.fr`). However, it looks to me that Clair, on the remote host, tries to download the layer from `127.0.0.1` (ie. locally). This means that you probably have set `-my-address` to `127.0.0.1`. You must set this to the public IP address of the host that runs `analyze-local-images`: it runs a web server that allows Clair to download the layers.

**Comment by Jerem28** [comment]
My mistake, I mixed up some of my logs and accidently paste the wrong ones, it seems to work locally now, but I have to work on finding a way to expose HTTP Server through a public IP with our company environment. Thanks for your help :)
