### ISSUE TITLE
Clair can not start the scanning because the manifest has been queued for hours

### ISSUE THREAD

**Issue by ZeroGold52** [quay/clair#1393]
I added a distribution in Claircore but failed to scan Ubuntu images when following the steps to test ClairV4 locally. As described in the [documentation](https://quay.github.io/clair/howto/testing.html#viewing-results), Clair will automatically start the scanning and display security scanner results on the Tags page after pushing an image to Quay.

However, I found the manifest for the tag of my uploaded image had been queued for several hours. By now, it hasn't return any result yet. Does someone know how to skip the queueing process and start the security scanner?

![481f19b4f06f09dd95578f1ef2e9c1d](https://user-images.githubusercontent.com/20592498/137054762-f89067b1-1e0e-47cc-aaf8-2e9f8d6b9872.png)

### Environment

- Clair version/image: clair-4.1.5 && claircore-0.4.7
- Host OS: Ubuntu 20.04
- Kubernetes version: v1.20.5

**Comment by hdonnay** [comment]
You can use the `clairctl` command to request reports. The logs will also have output about what the various services are doing.

**Comment by hdonnay** [comment]
Closing due to length of time without a response.
