### ISSUE TITLE
docs should explain how to garbage-collect old images

### ISSUE THREAD

**Issue by majewsky** [quay/clair#1399]
My Clair DB is slowly filling up with index reports for old deleted images. I would like to clean those up, but I cannot find anything in the docs regarding how to do that in a safe way. `grep -Ri delete` only finds the DELETE endpoint for notifications, but there is no DELETE endpoint for manifests or index reports. `grep -Ri garbage` only finds the garbage collection for update operations, but there is no garbage collection for anything else. Am I missing something? What is the best practice here?

### Environment

N/A

**Comment by hdonnay** [comment]
Yes, this is an oversight in the current API. I've got some PRs cooking to fix this, I'll link them once I submit them.

**Comment by hdonnay** [comment]
I forgot to update this issue: the API was added and documented in 93a835ec75959252d0d7eaac4d16a7ffca468a67, about a year ago 🫠
