### ISSUE TITLE
Exporting updaters doesn't work

### ISSUE THREAD

**Issue by flavienbwk** [quay/clair#1401]
### Description of Problem / Feature Request

After running the following command, an error happens :

```bash
clairctl export-updaters updates.gz
```

Error :

```txt
...
2021-10-25T13:55:26+02:00 INF successful update component=libvuln/updates/Manager.driveUpdater ref=ffbe13d0-3e04-40c6-bbd5-f4065c974936 updater=clair.cvss
2021-10-25T13:55:26+02:00 INF finished update component=libvuln/updates/Manager.driveUpdater updater=clair.cvss
2021-10-25T13:56:06+02:00 ERR  error="updating errors:\nubuntu-bionic-updater: vulnerability database parse failed: ubuntu: unable to decode OVAL document: unable to decode string as datestamp: \"unknown\"\nubuntu-xenial-updater: vulnerability database parse failed: ubuntu: unable to decode OVAL document: unable to decode string as datestamp: \"unknown\"\nubuntu-focal-updater: vulnerability database parse failed: ubuntu: unable to decode OVAL document: unable to decode string as datestamp: \"unknown\"\nubuntu-trusty-updater: vulnerability database parse failed: ubuntu: unable to decode OVAL document: unable to decode string as datestamp: \"unknown\"\n"
```

This generates a broken `updates.gz` of ~8.9Gb

### Expected Outcome

No error or at least a non-broken ~archive~ JSON `updates.gz`

### Environment

- https://github.com/flavienbwk/clair-docker
- Clair version/image: 4.3.0
- Clair client name/version:  0.2.0
- Host OS: Ubuntu 
- Kernel (e.g. `uname -a`):  5.4.0-89-generic 18.04.1-Ubuntu
- Kubernetes version (use `kubectl version`): None (Docker 20.10.7)
- Network/Firewall setup: None

Thank you !

**Comment by kairen** [comment]
Same issue here.

**Comment by SofyaTavrovskaya** [comment]
Yep, the same!
```
ERR errors encountered during updater run error="updating errors:\nubuntu-bionic-updater: vulnerability database parse failed: ubuntu: unable to decode OVAL document: unable to decode string as datestamp: \"unknown\"\nubuntu-trusty-updater: vulnerability database parse failed: ubuntu: unable to decode OVAL document: unable to decode string as datestamp: \"unknown\"\nubuntu-xenial-updater: vulnerability database parse failed: ubuntu: unable to decode OVAL document: unable to decode string as datestamp: \"unknown\"\nubuntu-focal-updater: vulnerability database parse failed: ubuntu: unable to decode OVAL document: unable to decode string as datestamp: \"unknown\"\n" component=libvuln/updates/Manager.Start
```

**Comment by flavienbwk** [comment]
@hdonnay can we do something ?

**Comment by hdonnay** [comment]
I've talked to the ubuntu security team to fix their data.

What do you mean by the output being "broken"?

**Comment by flavienbwk** [comment]
Thank you. It means the generated .gz file is corrupted/can't be opened.

**Comment by hdonnay** [comment]
Ah, I think our docs fell out of sync at some point: the resulting file isn't gzipped. It should be a lot of JSON.

**Comment by flavienbwk** [comment]
Oh OK thanks.

However import doesn't work too.

**Comment by kairen** [comment]
@flavienbwk The export-updaters' output is a JSON format file, but `import-updaters` will open a gzip file and parse data, so you need to compress manually the output file before import.

The below screenshot is the result for testing [clair-docker](https://github.com/flavienbwk/clair-docker):

![image](https://user-images.githubusercontent.com/4667563/140290666-6ebfeb24-0f35-41cf-8e5b-42e807541335.png)

**Comment by flavienbwk** [comment]
Thank you very much @kairen ! It worked as well on my side.  
I've updated the documentation of [clair-docker](https://github.com/flavienbwk/clair-docker).

This issue answers to my problems and is to be closed from my point of vue.
