### ISSUE TITLE
Clair-quay doesn't work when deployed with make local-dev-up-with-quay

### ISSUE THREAD

**Issue by avgkoster** [quay/clair#1403]
Hello everyone, when deploying clair, at first everything is fine, but then the clair-quay service does not rise
docker-compose logs quay produces the following
clair-quay            | | SecurityScanner        | dial tcp 172.19.0.2:8089: connect: connection refused | 🔴     |
clair-quay            | +------------------------+-------------------------------------------------------+--------+
clair-quay            | | SigningEngine          | -                                                     | 🟢     |
clair-quay            | +------------------------+-------------------------------------------------------+--------+
clair-quay            | | TeamSyncing            | -                                                     | 🟢     |
clair-quay            | +------------------------+-------------------------------------------------------+--------+
clair-quay            | | TimeMachine            | -                                                     | 🟢     |
clair-quay            | +------------------------+-------------------------------------------------------+--------+
clair-quay            | | UserVisibleSettings    | -                                                     | 🟢     |
clair-quay            | +------------------------+-------------------------------------------------------+--------+
clair-quay            | Running init script '/quay-registry/conf/init/nginx_conf_create.sh'
clair-quay            | Running init script '/quay-registry/conf/init/runmigration.sh'
clair-quay            | Traceback (most recent call last):
clair-quay            |   File "/quay-registry/conf/init/data_migration.py", line 3, in <module>
clair-quay            |     from app import app
clair-quay            |   File "/quay-registry/app.py", line 34, in <module>
clair-quay            |     from data.billing import Billing
clair-quay            |   File "/quay-registry/data/billing.py", line 1
clair-quay            |     from __future__ import annotations
clair-quay            |     ^
clair-quay            | SyntaxError: future feature annotations is not defined

version of go lang 1.17

**Comment by bgercken** [comment]
Same issue here. Tested with master, release-4.3 and release-4.2. CentOS 7 latest. Posting details to the clair-dev mail list.

**Comment by hdonnay** [comment]
This looks like a python error, which would be quay's bailiwick. Please raise an issue there with the version that has this happen.
