### ISSUE TITLE
Clairctl not showing reports 

### ISSUE THREAD

**Issue by JagadeeshRam** [quay/clair#1411]
### Description of Problem / Feature Request
 
I was not able to get the vulnerability report showing " image_name ok " but sometimes it was getting the report. 
![image](https://user-images.githubusercontent.com/55401565/139521194-4d82b9c4-f0b1-4768-9f7c-6416f526c7af.png)
  

### Expected Outcome
![image](https://user-images.githubusercontent.com/55401565/139521224-18324011-3576-4ae8-8f9b-af53183ae901.png)

### Environment

-Clair version/image: Clair V2.2
Clair client name/version: Quay

**Comment by hdonnay** [comment]
There's no such version as v2.2, and also v2 is unsupported.

It looks like you're actually using v4. Post `clair` logs and `clairctl` json and debugging output if you'd like help with this.

**Comment by JagadeeshRam** [comment]
Sorry It was V4 only, I was attaching clairctl  json output
![image](https://user-images.githubusercontent.com/55401565/142140264-c6702090-85f9-41a2-8403-d76d966f560f.png)

**Comment by JagadeeshRam** [comment]
Quay clair log output file attached

[quay-clair_log.txt](https://github.com/quay/clair/files/7552016/quay-clair_log.txt)
