### ISSUE TITLE
Got Bad Gateway error while scanning via clair v2.1.7

### ISSUE THREAD

**Issue by SoaadMahmoud** [quay/clair#1429]
### Description of Problem / Feature Request
got Bad Gateway error while scanning via clair 

### Expected Outcome

Nov 11 14:45:35 172.24.0.1 clair-adapter-standalone[26715]: {"expire":3600,"level":"debug","msg":"Updating scan job","redis_key":"harbor.scanner.clair:store:scan-job:dd8f3b5f-4ad4-4b88-913b-9c6eaf2207d0","scan_job_id":"dd8f3b5f-4ad4-4b88-913b-9c6eaf2207d0","scan_job_status":"Finished","time":"2021-11-11T13:45:35Z"}

### Actual Outcome

Nov 11 14:45:35 172.24.0.1 clair-adapter-standalone[26715]: {"error":"preparing layers: Get \"https://registry-url/v2/projectname/amazon/aws-alb-ingress-controller/manifests/sha256:d64b09cad7a3b42eb348e9711b37880379da5d53a30b875a8e4dcb5f8350f89b\": Bad Gateway","level":"error","msg":"Scan worker failed","time":"2021-11-11T13:45:35Z"}

### Environment
prod

-->

- Clair version/image: 2.1.7
- Clair client name/version: 
- Host OS: redhat 7.9
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Network/Firewall setup: 
- Harbor version : 2.3.2

**Comment by crozzy** [comment]
Hey! Unfortunately we no longer support Clair v2, but from the looks of it the generated URL is just a generic placeholder.
