### ISSUE TITLE
clairctl 401 error

### ISSUE THREAD

**Issue by JagadeeshRam** [quay/clair#1446]
### Description of Problem / Feature Request
I was getting 401 error for this latest issues please tell how to avoid it

### Expected Outcome
Vulnerability report

### Actual Outcome
![image](https://user-images.githubusercontent.com/55401565/143233337-be46680b-ffcd-465f-87df-6229e9d5b4a3.png)

### Environment

- Clair version/image:4.3.5

**Comment by crozzy** [comment]
The latest version of `local-dev` by default has PSK authentication https://github.com/quay/clair/blob/main/local-dev/clair/config.yaml#L13. I suspect that you are coming across this. You can pass the config to `clairctl` and it should use the same PSK to authenticate calls:
```
   --config value, -c value     clair configuration file (default: "config.yaml") [$CLAIR_CONF]
```

**Comment by JagadeeshRam** [comment]
I pushed the config file, but it did not resolve the issues

**Comment by JagadeeshRam** [comment]
Thank You It was worked
