### ISSUE TITLE
Replace worker engine version with list of capabilities

### ISSUE THREAD

**Issue by Quentin-M** [quay/clair#146]
Currently, the worker engine version is stored as a [constant](https://github.com/coreos/clair/blob/8fd0aa1/worker/worker.go#L29), that isn't optimal as people can register and upgrade their custom components. The capabilities could potentially be versioned.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
