### ISSUE TITLE
Address client UX

### ISSUE THREAD

**Issue by Quentin-M** [quay/clair#148]
When developing Clair, we focused on making Clair integrable by developers and container registries. It appears that the community uses Clair as it is a lot, analyzing images that could be either local or hosted by some registries. This issue is about integrating a solid command-line tool, for instance (and removing the whole `contrib/analyze-local-images` tool).

**Comment by jzelinskie** [comment]
I'm closing this. I think we want to leave this out of the scope of the core project and recommend clairctl for local usage and building integration with the API for more advanced use cases.
