### ISSUE TITLE
Number of connects / disconnects of clair during 24h to postgresql

### ISSUE THREAD

**Issue by ohauer** [quay/clair#1485]
### Description of Problem / Feature Request
after installing quay.io/coreos/clair:v4.3.5 and connected to postgresql we saw in our monitoring a high increase of connects/disconnects rate from clair to postgres.

add the following lines to file postgresql.conf

```sh
log_connections = on
log_disconnections = on
log_duration = on
log_line_prefix = '%m [%p] %u %d %h '
```
we count 410.586.268 connects/disconnects during 24h from clair in idle state (no scans done during this time)

### Expected Outcome
A magnitude lower connections during 24h in idle state

### Actual Outcome
Nothing special in clair logs 

### Environment
Calir4 installed as docker container on VM and as container in K8s

- Clair version/image:  quay.io/coreos/clair:v4.3.5
- Clair client name/version:  NA
- Host OS:  Ubuntu 20.04.3 LTS
- Kernel: 5.4.0-96-generic
- Kubernetes version: v1.20.14
- Network/Firewall setup:  NA

We will do an update to 4.3.6 to see if we get lower numbers

**Comment by hdonnay** [comment]
How often are updaters run? How many Clair instances? How many concurrent connections are made per instance?

**Comment by hdonnay** [comment]
Will close shortly if there's nothing more to report.
