### ISSUE TITLE
how can run the project

### ISSUE THREAD

**Issue by xwb1993** [quay/clair#1499]
I haved download the clair-release-4.3,but when run clair\cmd\clair\main.go,shows 
must provide a -conf flag or set "CLAIR_CONF" in the environment.
How can I solve it？ Thanks!

**Comment by hdonnay** [comment]
You must provide a -conf flag or set "CLAIR_CONF" in the environment, the value of either being the path to clair's config file.

**Comment by xwb1993** [comment]
> You must provide a -conf flag or set "CLAIR_CONF" in the environment, the value of either being the path to clair's config file.

![github](https://user-images.githubusercontent.com/18282502/155637632-592975dd-a094-4d93-a508-b38ef8cb5b7b.png)
 
Thank you for your reply！ But i'm not sure which one is clair's config file  inneed,like this?

**Comment by hdonnay** [comment]
Yes, that's the format that's needed. You'll have to customize it to your environment, as described [here](https://quay.github.io/clair/howto/getting_started.html). You can also find short explanations for the configuration keys [here](https://quay.github.io/clair/reference/config.html).

**Comment by xwb1993** [comment]
> Yes, that's the format that's needed. You'll have to customize it to your environment, as described [here](https://quay.github.io/clair/howto/getting_started.html). You can also find short explanations for the configuration keys [here](https://quay.github.io/clair/reference/config.html).

Thank you very much!
![Uploading 1.png…]()
