### ISSUE TITLE
Unsupported by Quay Security Scanner

### ISSUE THREAD

**Issue by annaparienti** [quay/clair#1507]
### Description of Problem / Feature Request

We scan our images via Quay Clair Security Scanner, since we bump the operator base image (see [this ](https://github.com/IBM/ibm-block-csi-operator/pull/243) change) we started getting an error message under Tags and SECURITY SCAN.
Could you assist with that?

### Expected Outcome

```
Passed
```

### Actual Outcome

```
The manifest for this tag has an operating system or package manager unsupported by Quay Security Scanner
```

### Environment

- Clair version/image: https://recovery.quay.io/
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
If you're having problems with quay.io, please contact quay.io support.
