### ISSUE TITLE
Only get vulnerabilities from a particular namespace

### ISSUE THREAD

**Issue by rmartinez3** [quay/clair#152]
I only need to be looking at RHEL based vulnerabilites. I'm seeing now how i can change either the datastore or the updaters to only handle RHEL based vulnerabilities. What interfaces can i change to get this option.

**Comment by jzelinskie** [comment]
Recompiling clair without the imports of the components you don't want will do the trick.

https://github.com/coreos/clair/blob/4246c5244bbcffb9d278617a80bbe184bb8e935d/cmd/clair/main.go#L28-L45

**Comment by rmartinez3** [comment]
thanks for the quick response!
