### ISSUE TITLE
Temp file location/filling up?

### ISSUE THREAD

**Issue by sbehrens** [quay/clair#153]
Hello,

I've noticed when running the 'analyze-local-images' tool a few times that I start running out of disk space (until I reboot the system, restarting the Docker machine or removing the images doesn't help).  Where are the temp files located and are they being removed after the analyzer completes?

**Comment by rmartinez3** [comment]
The temp files should be located in your /tmp folder. it was for mine. it  should be a folder called analyze-lcoal-images or something like that. I had to remove it since it was filling my computer up

**Comment by sbehrens** [comment]
Thanks, I just confirmed it's not cleaning up temp files correctly.  

``` bash
sbehrens@lgml-sbehrens3 /var/folders/j7/c6s0xn0x3nj86j5jjhn89fbm4xhv43/T$ ls -l | grep analyze                                                                                                                                              1 ↵
drwx------   7 sbehrens  sbehrens   238 Apr 22 09:42 analyze-local-image-077522631
drwx------   8 sbehrens  sbehrens   272 Apr 22 09:44 analyze-local-image-145196438
drwx------   9 sbehrens  sbehrens   306 Apr 22 09:42 analyze-local-image-191599799
drwx------  41 sbehrens  sbehrens  1394 Apr 22 09:41 analyze-local-image-257114695
drwx------  43 sbehrens  sbehrens  1462 Apr 22 09:18 analyze-local-image-328548829
drwx------  62 sbehrens  sbehrens  2108 Apr 22 08:46 analyze-local-image-395502097
drwx------  13 sbehrens  sbehrens   442 Apr 22 09:48 analyze-local-image-421464594
drwx------  19 sbehrens  sbehrens   646 Apr 22 08:51 analyze-local-image-492539904
drwx------  35 sbehrens  sbehrens  1190 Apr 22 09:08 analyze-local-image-535277259
drwx------  26 sbehrens  sbehrens   884 Apr 22 09:04 analyze-local-image-551364093
drwx------  40 sbehrens  sbehrens  1360 Apr 22 09:25 analyze-local-image-706063211
drwx------   2 sbehrens  sbehrens    68 Apr 22 09:52 analyze-local-image-777429368
drwx------  44 sbehrens  sbehrens  1496 Apr 22 09:33 analyze-local-image-814373925
drwx------   7 sbehrens  sbehrens   238 Apr 22 09:42 analyze-local-image-983906511
```

**Comment by Quentin-M** [comment]
Hi,

Thanks for the report.

Which version of the `analyze-local-images` tool are you using? This issue should have been fixed by 1040dbbff9ea395700d1232b4906b73e0de32a8f. I will investigate that if you are running the latest version.

**Comment by sbehrens** [comment]
Fixed in the later build, thanks.

**Comment by Quentin-M** [comment]
Awesome! I was actually looking at it and I just noticed that in some cases (i.e. SIGINT), it does not clean properly. Linking #158.

To answer the initial question, this contrib tool uses the `TMPDIR` environment variable (or `/tmp` if there's none) and then creates a folder named `analyze-local-images-XXX` where XXX is a random generated number.
