### ISSUE TITLE
official 4.4.1 image has vanished from Quay

### ISSUE THREAD

**Issue by majewsky** [quay/clair#1554]
The 4.4.1 image is not available from the official Quay repository anymore:

```
$ curl -i https://quay.io/v2/projectquay/clair/manifests/4.4.1
HTTP/2 404
date: Tue, 19 Apr 2022 11:15:10 GMT
content-type: application/json
content-length: 131
server: nginx/1.14.1

{"errors":[{"code":"TAG_EXPIRED","detail":{},"message":"Tag 4.4.1 was deleted or has expired. To pull, revive via time machine"}]}
```

Was an expiry date set accidentally, or is this an intentional yank?

### Environment

- Clair version/image: 4.4.1
- Clair client name/version: N/A
- Host OS:  N/A
- Kernel (e.g. `uname -a`):  N/A
- Kubernetes version (use `kubectl version`):  N/A
- Network/Firewall setup:  N/A

**Comment by hdonnay** [comment]
This was by mistake. The release script must have flagged it to expire -- I'll investigate.
