### ISSUE TITLE
The Compose file './docker-compose.yaml' is invalid

### ISSUE THREAD

**Issue by esbeneickhardt** [quay/clair#1564]
### Description of Problem / Feature Request
When following the guide in your [documentation ](https://quay.github.io/clair/howto/testing.html) to spin up a working local development environment, I get an error when calling **docker-compose up -d**.

### Expected Outcome

A working local development environment

### Actual Outcome

ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services.activemq: 'profiles'
Unsupported config option for services.grafana: 'profiles'
Unsupported config option for services.jaeger: 'profiles'
Unsupported config option for services.notifier: 'profiles'
Unsupported config option for services.pgadmin: 'profiles'
Unsupported config option for services.prometheus: 'profiles'
Unsupported config option for services.quay: 'profiles'
Unsupported config option for services.quay-notifier: 'profiles'
Unsupported config option for services.redis: 'profiles'
Unsupported config option for services.skopeo: 'profiles'
Unsupported config option for services.webhook-target: 'profiles'
services.indexer.depends_on contains an invalid type, it should be an array
services.matcher.depends_on contains an invalid type, it should be an array
services.notifier.depends_on contains an invalid type, it should be an array
services.quay-notifier.depends_on contains an invalid type, it should be an array
services.webhook-target.depends_on contains an invalid type, it should be an array

### Environment

- Clair version/image: 4.4
- Clair client name/version: NA
- Host OS: Windows/WSL2
- Kernel (e.g. `uname -a`): Linux PF2E14HA 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`): NA
- Network/Firewall setup: NA

**Comment by hdonnay** [comment]
It looks like your `docker-compose` is out-of-date. Profile support was added in v1.28

**Comment by esbeneickhardt** [comment]
Thanks for the suggestion, it seems apt-get only fetches docker-compose v1.25 on Ubuntu20.04.

I updated docker-compose using the following commands:
```
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

Now it works :)

**Comment by hdonnay** [comment]
Opened #1566 to update the documentation.
