### ISSUE TITLE
Endless restarting of clair-indexer and clair-matcher

### ISSUE THREAD

**Issue by esbeneickhardt** [quay/clair#1565]
### Description of Problem / Feature Request

When going through the **Getting Started With ClairV4** guide in [The book](https://quay.github.io/clair/howto/testing.html), and attempting to **Starting a Cluster** the two containers **clair-indexer** and **clair-matcher** go into a loop of endless restarts. Traefik is available at **localhost:8080**, but nothing else is.

### Expected Outcome

Clair services at **localhost:6060**

### Actual Outcome

**clair-indexer** and **clair-matcher** restart endlessly

### Environment

- Clair version/image: 4.4
- Clair client name/version: NA
- Host OS: Ubuntu20.04 via WSL2
- Kernel (e.g. `uname -a`): Linux PF2E14HA 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`): NA
- Network/Firewall setup: NA

**Comment by hdonnay** [comment]
You'll need to provide information on what's happening -- log output would be a good start.

**Comment by brenguy** [comment]
you can fix this by installing the latest go on your linux os. Then you can run `go mod vendor` in the root of the project. I believe that is how I fixed the issue.
