### ISSUE TITLE
Add wait/backoff for postgres 

### ISSUE THREAD

**Issue by amouat** [quay/clair#159]
It would be great if Clair waited for Postgres to become available rather than crashing out. IMO, this should be done in the Go code itself. See https://medium.com/@kelseyhightower/12-fractured-apps-1080c73d481c#.b9pu0hu5u for more details.

In the meantime, I hacked together: https://github.com/amouat/clair-with-wait in case anyone finds it useful.

**Comment by Quentin-M** [comment]
Hi,

Sounds fair!
I'll make sure this is implemented.

Thanks for your input.

**Comment by jzelinskie** [comment]
@amouat If you want to open a PR, I think we'd be fine with upstreaming this

**Comment by amouat** [comment]
Yayyy! Thanks! :)
