### ISSUE TITLE
clair-postgres pg_ctl: could not start server

### ISSUE THREAD

**Issue by dkoci** [quay/clair#1590]
Hi.
I have some issue with clair-postgres pod. I am running quay in OKD 4.9. Everything was ok until yesterday. Clair-postgres pod stucked in terminating state. I am unable to start new pod.

Log output:
`waiting for server to start....2022-06-22 08:25:53.935 UTC [26] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-06-22 08:25:53.942 UTC [26] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-06-22 08:25:54.013 UTC [26] LOG:  redirecting log output to logging collector process
2022-06-22 08:25:54.013 UTC [26] HINT:  Future log output will appear in directory "log".
......... stopped waiting
pg_ctl: could not start server
Examine the log output.
`

Please help

**Comment by hdonnay** [comment]
What do the logs in the `log` directory say?

**Comment by dkoci** [comment]
> 
[postgresql-Wed.log](https://github.com/quay/clair/files/8968057/postgresql-Wed.log)

Please see the attached log file.

**Comment by hdonnay** [comment]
It looks like the database got corrupted. You should recreate the database.

**Comment by dkoci** [comment]
> It looks like the database got corrupted. You should recreate the database.

Will be ok to disable clair, delete clair-postgres PVC and then enable clair again?

**Comment by hdonnay** [comment]
Yes, as long as migrations are enabled in clair's config.
