### ISSUE TITLE
Support picking up vulnerability databases from local sources (files)

### ISSUE THREAD

**Issue by rqc** [quay/clair#163]
Hello,

First of all, thanks for the wonderful work on Clair. We are using it to provide security scanning as part of a microservice-oriented system. In our development / test workflow, we run the Clair and Postgres containers to provide integration with our system. We are currently having issues since the downloads for  the database sources take a long time. I understand that this might be improved from a network performance standpoint as you point out [here](https://github.com/coreos/clair/issues/92). However, it would be nice also, to be able to point to the sources locally, from the host file system where Clair is running, and then the updater can reconcile any updates when it eventually downloads the source files. 

So, my question is, can this be done right now? If so, is it configurable, for instance, through the `config.yml` file or through env vars? If not, is there an interest in adding some functionality like this to Clair?

Thanks!

**Comment by liangchenye** [comment]
It can not be done right now. How about commit the Postgres container with updated vulnerability data and reuse that?

**Comment by rqc** [comment]
Thanks @liangchenye for the workaround. That might work for some of our scenarios, but sometimes, we run a CI pipeline for staging / dev purposes and we like re-creating an entire environment from scratch, including the Postgres container.

Would it be something useful to you to have this functionality? I might give it a try to make a contribution if there is interest. 

Thanks :smile:

**Comment by jgsqware** [comment]
You can also mount a docker volume for your postgres container and reuse
that volume later on in your ci pipeline

Le jeu. 5 mai 2016 22:38, Ricardo Quintana notifications@github.com a
écrit :

**Comment by philips** [comment]
@jgsqware I think we need to consider packaging up and shipping a pre-built index for clair. Having every user scrap everything themselves is OK but it can be rather time consuming, particularly if [we add file hash](https://github.com/coreos/clair/issues/172) features.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
