### ISSUE TITLE
clair server (v4.4.4) don't with "docker-compose up -d or make local-dev"

### ISSUE THREAD

**Issue by joaco-sy** [quay/clair#1640]
### Description of Problem / Feature Request

Hi, I hope you're having a grate day.

After I clone the repository, I tried docker compose up and make without any results.
the traefic is running but quay and clair doesn't. they gave me an 404 error when I tried to connect to the 6060 and 8443 ports
go version go1.19.2 linux/amd64
I did the go mod tidy and vendor and also rebuild the containers           

### Environment

- Clair version/image: latest
- Clair client name/version: NA
- Host OS:  Linux
- Kernel (e.g. `uname -a`):  Linux kali 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`): 
- Network/Firewall setup: NA

**Comment by hdonnay** [comment]
Please post log output from running `docker-compose up` on the `main` branch.

**Comment by hdonnay** [comment]
Closing for lack of response.

**Comment by danekantner** [comment]
I am having the same issue -- I only get 404s when loading the 6060 port

**Comment by hdonnay** [comment]
Are you getting a 404 from an API endpoint when using the `main` branch?
