### ISSUE TITLE
fetchers: fetch and record package hashes

### ISSUE THREAD

**Issue by philips** [quay/clair#172]
In some cases a user may remove package metadata. We should be able to handle this use case. This will require two things.

1) Download package metadata for each of the indexes and correlating that to the version. There might be databases that have this already?

```
$ ar vx etcd_2.3.3+dfsg-1_amd64.deb
x - debian-binary
x - control.tar.gz
x - data.tar.xz
$ tar -xvf control.tar.gz
x ./
x ./conffiles
x ./control
x ./md5sums
x ./postinst
x ./postrm
x ./prerm
$ cat md5sums | head -n 4
e043bc98b005e96a0ee29b05f69110a6  lib/systemd/system/etcd.service
2017914e911695eb74cbe393cfd8b0e6  usr/bin/etcd
40e862effe50391ab3f78eb0c9c6833c  usr/bin/etcdctl
```

2) Host this database somewhere on our coreos.net mirror infrastructure so everyone could use it without downloading and extracting the packages themselves.

Another cool thing that could come out of this: We could detect if the metadata says version X but the user has a different hash on disk

**Comment by steve-jansen** [comment]
+1, this is especially helpful for minimal Docker images

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
