### ISSUE TITLE
Running Clair locally is DOA

### ISSUE THREAD

**Issue by beckler** [quay/clair#1734]
### Description of Problem / Feature Request

Following the directions laid out here: https://quay.github.io/clair/howto/testing.html

We've been unable to get the Quay or Clair to run successfully locally.
There are no errors during the entire build process, and trafik also doesn't report any issues.
We're unsure how to approach moving forward with using this toolset any further.

`make local-dev`/`docker-compose up -d` output:
![Screen Shot 2023-05-05 at 11 10 54 AM](https://user-images.githubusercontent.com/3254069/236497818-0f4acc3b-1371-466c-baf2-a78a8be4e58f.jpg)

Traefik Dashboard:
<img width="1454" alt="Screen Shot 2023-05-05 at 11 10 02 AM" src="https://user-images.githubusercontent.com/3254069/236498092-e17d44c6-8d99-4546-8f99-88e19ac8294f.png">

### Expected Outcome

Any actual usable application

### Actual Outcome

Clair reports 404:
<img width="391" alt="Screen Shot 2023-05-05 at 11 06 42 AM" src="https://user-images.githubusercontent.com/3254069/236497879-cd386479-95ba-4496-9dbc-773b78352360.png">

Quay reports `Service Unavailable`:
<img width="497" alt="Screen Shot 2023-05-05 at 11 06 47 AM" src="https://user-images.githubusercontent.com/3254069/236497923-3c26a907-b1a9-48af-b02a-5b4b5f630cb8.png">

### Environment

- Clair version/image: main branch
- Clair client name/version: main branch
- Host OS: macOS 12.6
- Kernel (e.g. `uname -a`): `Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64`
- Kubernetes version (use `kubectl version`): ```Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:47:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17-gke.5400", GitCommit:"6862a2a3696fe4a22d5e429d689d5874ef4200d4", GitTreeState:"clean", BuildDate:"2023-02-22T09:27:53Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}```
- Network/Firewall setup: local machine - nothing special

**Comment by crozzy** [comment]
Clair does not have a UI so and there is no root handler implemented: [here](https://quay.github.io/clair/reference/api.html) are the API docs. You can run Clair with Quay (`local-dev-quay`), although if you are looking to have a local quay I'd suggest starting with the [Quay repo](https://github.com/quay/quay).

**Comment by beckler** [comment]
Ah okay! I wasn't really sure what to expect running it locally, but that's good to know!
