### ISSUE TITLE
clair-matcher  warning unable to parse python vulnerability range

### ISSUE THREAD

**Issue by vaibhav-bhadade** [quay/clair#1735]
Description of Problem / Feature Request
We are using clair local development environment to scan docker images for our project .  Scan report are genrated for image scan but While scanning it has been observed that clair-matcher is raised waring as below. 

clair-matcher   | 4:29AM DBG query component=internal/matcher/Controller.Match matcher=python request_id=98dc9bf5e681b320 vulnerabilities=2
clair-matcher   | 4:29AM WRN unable to parse python vulnerability range advisory="RHSA-2011:0554: python security, bug fix, and enhancement update (Moderate)" component=internal/matcher/Controller.Match matcher=python range= request_id=98dc9bf5e681b320

This warning is common for most of the images so want to know what the root cause of the above issue can be. 

Expected Outcome
No warnings should be displayed. and all vulnerabilities which are missing due to warning should be as part of report 

Actual Outcome
images scan report not include vulnerabilities  as expected. 

Environment
Clair version/image: 4.6.1
Clair client name/version: clairctl 
Host OS: Red Hat Enterprise Linux release 8.7
Kernel (e.g. uname -a): 4.18.0-425.19.2.el8_7.x86_64
Kubernetes version (use kubectl version):  - 
Network/Firewall setup:  -

**Comment by afsanjar** [comment]
The failed CVE is https://access.redhat.com/errata/RHSA-2011:0554; I don't see ppc64le as an impacted product, which may be why the warning is generated.

**Comment by hdonnay** [comment]
Is there an error?

**Comment by vaibhav-bhadade** [comment]
@hdonnay , Its an warning from matcher component and corresponding vulnerability is not populated in results.

**Comment by hdonnay** [comment]
Closing for age and lack of information.
