### ISSUE TITLE
Verifying the Clair Installation

### ISSUE THREAD

**Issue by rammanoj** [quay/clair#1820]
I have been trying to install clair all day today. I couldn't even figure out what's happening wrong or how to verify if my installation went well. I followed the instructions given [here](https://quay.github.io/clair/howto/testing.html#starting-a-cluster). I have four containers running locally:
![image](https://github.com/quay/clair/assets/21082378/60f79bc1-8d6a-48d4-9dd1-9e35644dea54)
I visited http:localhost:8080/, and traefik is showing everything in green. So, I ran an image scan with Klar, but it failed. To verify if my clair is installed correctly. I visited http://localhost:6060/indexer and even the matcher's URL as well. It prompted me:
![image](https://github.com/quay/clair/assets/21082378/5d3b07a9-57bb-445d-86ec-1750f56fd803)

I also visited http://0.0.0.0:51221/ to check if the quay came up. But it replied "Service Unavailable". 

Is the clair actually running ? How do I verify if it's working? I could not find any help in the documentation regarding this issue.

Any help would be appreciated.

@crozzy / @hdonnay

**Comment by hdonnay** [comment]
I don't know what `klar` is. What does running a report with `clairctl report` say? What do the logs say?

Your screenshot shows a `401`, that indicates you have it configured with authentication.

**Comment by rammanoj** [comment]
@hdonnay Thanks for the reply. I guess you are true. Here is the screenshot of running clairctl:
![image](https://github.com/quay/clair/assets/21082378/3d5e0473-36bb-4cbe-bbe3-fd1a43204618)

However, I have just cloned and ran docker compose. Is authentication enabled by default ?

**Comment by hdonnay** [comment]
Yes, see [`local-dev/clair/config.yaml`](https://github.com/quay/clair/blob/main/local-dev/clair/config.yaml). You'll need to use that configuration. The help from the `clairctl` commands should explain how.
