### ISSUE TITLE
Clair Vulnerability Databases/Sources

### ISSUE THREAD

**Issue by kderck** [quay/clair#1852]
Hi Quay/Clair. Where could I find the the Vulnerability Databases that Clair uses. I've had a look through the documentation and I'm unable to find it. (Or just looking in the wrong place!)

**Comment by crozzy** [comment]
This is documentation of HTTP resources Claircore uses, some are exclusively for context information and don't have vulnerability information, but it should be a good start https://quay.github.io/claircore/concepts/updater_defaults.html

**Comment by crozzy** [comment]
Closing, feel free to reopen if needed
