### ISSUE TITLE
Incorrect old CVES are being report with COPY and python virtualenv

### ISSUE THREAD

**Issue by sumkincpp** [quay/clair#1928]
When a `COPY` command is used for python virtualenv, some old non-present vulnerabilities are being reported as CVE-s.

This seems like a bug starting with some new version of Quay - in some of the previous version I had not seen this behaviour.

### Description of Problem / Feature Request

![image](https://github.com/quay/clair/assets/738925/b663c0bb-3219-4305-b75d-0315def95923)

### Expected Outcome

No errors are reported
 
### Actual Outcome

CVEs are reported for some real old versions, even though the latest conform version is installed

![image](https://github.com/quay/clair/assets/738925/a40fe87a-0bf6-4af7-aa6a-ef5f8810cd52)

![image](https://github.com/quay/clair/assets/738925/8dfeec75-edf0-4537-bf56-df8233f548d9)

### Environment

Quay v3.8.11

**Comment by hdonnay** [comment]
We would need the Clair version, relevant logs, and the `clairctl report -o json` output. A link to the relevant container would also be helpful.
