### ISSUE TITLE
Kernel* packages should be ignored by FeatureDetectors

### ISSUE THREAD

**Issue by Quentin-M** [quay/clair#200]
Unless evidence to the contrary, code provided by kernel\* packages is never executed by containers.

**Comment by jzelinskie** [comment]
I'm not sure if this is the ideal behavior.

If you're shipping a container with a vulnerable kernel, you should still be informed of this. Hiding specific packages should probably be implemented by whatever frontend (hyperclair, Quay, etc...) to the clair API people are using.

**Comment by jzelinskie** [comment]
The official statement is that we're not going to hide this information from the API and tools should filter this if it is not relevant to the API consumers.
