### ISSUE TITLE
4.7.4 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [quay/clair#2055]
👋 it looks like 4.7.4 release was not completed, ie the github release did not get created as 4.7.3, raise this issue for some awareness. Thanks! 🙏 

relates to https://github.com/Homebrew/homebrew-core/pull/170499

**Comment by crozzy** [comment]
Thanks, we're working on it

**Comment by crozzy** [comment]
We had an issue with `actions/upload-artifact` 3->4 where the default behaviour changed when uploading multiple files to the same artifact (https://github.com/actions/upload-artifact/?tab=readme-ov-file#improvements). v4.7.4 should be good now.

**Comment by chenrui333** [comment]
sounds perfect, thanks!
