### ISSUE TITLE
How to check private registry using clairctl

### ISSUE THREAD

**Issue by l1monenko** [quay/clair#2060]
### Description of Problem / Feature Request
I want to test a locally built docker image, I tried to use quya to do this, with the public repository it worked, but when I use the private repository I failed because I couldn't find where to use the credentials from the private repository.
![Screenshot 2024-05-08 003552](https://github.com/quay/clair/assets/146029723/9d428825-1feb-4ba2-bd00-82cdabbfdd54)

### Environment
- Clair version/image: 4.7.4

**Comment by hdonnay** [comment]
`Clairctl` consults the normal docker and podman authentication files.
