### ISSUE TITLE
How to configure support for multiple private image registries? Or settings to skip certificate verification

### ISSUE THREAD

**Issue by MK-BK** [quay/clair#2077]
How to configure support for multiple private image registries? Or settings to skip certificate verification

**Comment by hdonnay** [comment]
Configure the client that's making registry API calls with the credentials for the registries. For `clairctl`, the paths documented for the `docker` and `podman` CLIs should be honored.

There is no way to skip certificate verification; you should configure the environment for clair and/or the clients to trust the needed certificate. This can be done by adding the certificate to the system trust store (see [`update-ca-trust(8)`](https://www.mankier.com/8/update-ca-trust)) or the [relevant environment variables](https://pkg.go.dev/crypto/x509#SystemCertPool).
