### ISSUE TITLE
Clair Support for Arch Linux

### ISSUE THREAD

**Issue by esatterwhite** [quay/clair#209]
Would love to see support for Arch Linux. It is increasing in popularity / prevalence.

**Comment by jzelinskie** [comment]
linking to #60

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
