### ISSUE TITLE
pgsql: pq: relation "goose_db_version" already exists

### ISSUE THREAD

**Issue by steve-jansen** [quay/clair#211]
We can deploy Clair successfully a first time, but, subsequent container restarts raise a DB migration error with Goose.

```
sudo /usr/bin/docker -H unix:///var/run/docker.sock run -it --name=clair --rm -p 6060-6063:6060-6063 -v /etc/clair:/etc/clair quay.io/coreos/clair:v1.2.2 -config=/etc/clair/config.yaml
2016-06-27 02:36:18.102369 I | pgsql: running database migrations
2016-06-27 02:36:18.137254 E | pgsql: pq: relation "goose_db_version" already exists
2016-06-27 02:36:18.137279 C | main: database: could not open database
```

This seems to be related to [goose issue #1](https://bitbucket.org/liamstask/goose/issues/1/postgres-error-relation-goose_db_version) about the proper way to create metadata tables.

We are using a AWS RDS Postgres instance for the DB.

Any ideas on how to fix this?

**Comment by Quentin-M** [comment]
Hi,

My apologies the delayed answer, I am not sure why I never noticed that issue before.

_goose_ ensures that the table doesn't exist before trying to create it [[1](https://github.com/coreos/clair/blob/28fbfc72e7a77f15fffc3848ecbb44943dd15a70/vendor/bitbucket.org/liamstask/goose/lib/goose/migrate.go#L199)]. However, by looking at how it is done, we notice that _goose_ executes a `SELECT` query on `goose_db_version` and consider any error as the table missing [[2](https://github.com/coreos/clair/blob/28fbfc72e7a77f15fffc3848ecbb44943dd15a70/vendor/bitbucket.org/liamstask/goose/lib/goose/dialect.go#L53)]. Besides the `Ping` call which makes sure that the connection to the database is alive, this query is the very first to be executed on the database when Clair starts. It would be very useful to know the exact error that this query encounters, either by making goose print it, or by reading the database logs (verbose mode).

Also, could you please share the PostgreSQL version you run on RDS and the connection string configured in Clair? We actually also run a bunch of Clair instances on AWS RDS.
