### ISSUE TITLE
Python vulnerability scanning

### ISSUE THREAD

**Issue by jakedt** [quay/clair#214]
Find a vulnerability source for python, potentially using https://requires.io, which in turn uses mitre: https://cve.mitre.org/

**Comment by liangchenye** [comment]
I just found https://github.com/requires/monitoring/blob/master/requirements.txt which maybe useful.
But it seems incomplete, there are more python related CVE issues in cve.mitre.org than that mentioned in 'requirements.txt'

**Comment by MackJM** [comment]
Is anyone working on getting python into the namespaces? Or is this more just a looking into if it's possible? Either way, seems interesting.

I found this https://github.com/pyupio/safety-db/blob/master/data/insecure_full.json while looking into this. One thing I found is that it's only updated monthly.

**Comment by jzelinskie** [comment]
I don't think anybody has started any work on this yet. The changes that happened for v3 just made it possible to effectively support application-related features. Now seems like a good time to look into it again.

**Comment by cnorthwood** [comment]
I've started work on this in https://github.com/coreos/clair/pull/748, however finding an appropriate source for vulnerabilities is proving difficult. SafetyDB has a non-commercial license which I'm unsure of the scope of (a naive reading suggests that it only covers Clair being used in non-commercial settings, but I suspect it's also intended to stop commercial projects being scanned).

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
