### ISSUE TITLE
OpenAPI schema out of date

### ISSUE THREAD

**Issue by zregvart** [quay/clair#2161]
### Description of Problem / Feature Request

I've noticed that the [current published OpenAPI document](https://github.com/quay/clair/blob/0a3a4611964014c0c9846d8c79acdd062af9c17d/openapi.yaml) is out of date. The `SourcePackage`'s property [`source`](https://github.com/quay/clair/blob/0a3a4611964014c0c9846d8c79acdd062af9c17d/openapi.yaml#L803-L804) is declared as `string`, whereas in the claircore it is [`Package`](https://github.com/quay/claircore/blob/59b3a5af2562bea91983dc6679fab758d64d25cf/package.go#L17) via recursive declaration of `Package`.

When I try to validate the Clair `clair` formatted report produced by clair-action with the JSON Schema generated using https://github.com/grantila/typeconv/, e.g. `npx typeconv -f oapi -t jsc openapi.yaml`, I get a schema violation like:

```
packages.02FzDBS76jWKACvjeaEWyg==.source.source: Invalid type. Expected: string, given: object
```

### Expected Outcome

The OpenAPI schema should reflect the report generated from Clair.

### Actual Outcome

See the description above

### Environment

Using clair-action 0.0.10.

**Comment by crozzy** [comment]
I think the correct way to go is something like [this](https://github.com/quay/clair/pull/2175) where the Package refers to itself, this was an issue for a long time in the swagger UI but appears to have be fixed: https://github.com/swagger-api/swagger-ui/issues/3325

**Comment by crozzy** [comment]
This is merged into main, @zregvart feel free to reopen if issues remain
