### ISSUE TITLE
Disable fetcher(s)?

### ISSUE THREAD

**Issue by Djelibeybi** [quay/clair#221]
Is there a way to disable one/more fetchers when Clair runs? 

I'd like to disable the Debian/Ubuntu fetchers as they take a very long time to run and I'm not intending on scanning any images based on Debian or Ubuntu.

**Comment by jzelinskie** [comment]
You cannot at runtime, but you can at compile time. If you strip the imports from main.go (i.e. remove [this line](https://github.com/coreos/clair/blob/master/cmd/clair/main.go#L31))

**Comment by Djelibeybi** [comment]
True. I guess I was hoping for something I wouldn't have to keep reverting to make sure I don't check it into my git repo by mistake. :)

Can I turn this into a config enhancement request?

**Comment by jzelinskie** [comment]
Addressed in #432.
