### ISSUE TITLE
Clair and Amazon ECR

### ISSUE THREAD

**Issue by aurcioli-handy** [quay/clair#224]
I've been looking into how to integrate Clair with the use of Amazon's container registry. I haven't had much luck so far as it seems Clair requires a URL to a specific layer which I'm not able to get from ECR. Is there any support or documentation for this?

**Comment by Quentin-M** [comment]
Hi,

Maybe you would be interested in https://github.com/zalando/clair-sqs ?

**Comment by aurcioli-handy** [comment]
Ah, thankyou!
