### ISSUE TITLE
Clair container fails to start

### ISSUE THREAD

**Issue by noahwhite** [quay/clair#225]
I'm attempting to start Clair v1.2.3 on CoreOS 1068.8.0 Stable and it dies on start. The logs show:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x482735]

goroutine 1 [running]:
panic(0xafc3a0, 0xc820012080)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/clair/config.Load(0x7ffda6258e9c, 0x13, 0xc82016d500, 0x0, 0x0)
    /go/src/github.com/coreos/clair/config/config.go:119 +0x3f5
main.main()
    /go/src/github.com/coreos/clair/cmd/clair/main.go:58 +0x1d4
```

My docker run command looks like:

`/usr/bin/docker run --name quay-clair -d -p 6060-6061:6060-6061 -v /home/core/clair_config:/config quay.io/coreos/clair:v1.2.3 -config=/config/config.yaml`

Seems that its failing on the config, however, my config looks good. Is there a validator (like the CoreOS cloud-config validator) I could use to debug this? Thnx.

**Comment by jgsqware** [comment]
hello,
could you provide your config.yaml?

**Comment by noahwhite** [comment]
I had pulled it down with curl per the instructions. I ended up copying and pasting the one from the v1.2.2 branch and that worked. Thnx
