### ISSUE TITLE
Clair scanner project structure (question)

### ISSUE THREAD

**Issue by elicode1** [quay/clair#226]
Was wondering why Clair is not structured the "Go way":

```
bin/                                                                    # command executable
   clair
pkg/                                                                  # package objects                        

src/
   api/
        context/
        v1/
        api.go
        router.go
    ....
    clair/
        clair.go                                                    # main go file                                   
    github.com/                                                # 3rd party packages
    ...
Dockerfile
config.example.yaml
...
```

This is the main convention for using golang as far as the official doc claim:
[https://golang.org/doc/code.html](url)

So am I missing something? and if not are you open to pullresquests for refactoring the project to look more like the official doc advise?

Thanks
Eli

**Comment by jzelinskie** [comment]
Clair is structured properly. If you follow the [instructions in the README](https://github.com/coreos/clair#source), it should install it properly into your GOPATH. If you don't want to use `go get` you will have to `git clone` the source code into the properly place in your GOPATH like so:

```
cd $GOPATH
git clone git@github.com:coreos/clair.git src/github.com/coreos/clair
```

**Comment by Quentin-M** [comment]
You simply mix up workspace and repository.

**Comment by elicode1** [comment]
Ok got it, so the only thing is missing for me in the README is package management. 
Whats the right way to add packages?
`go get` will not install to `vendor/` so how would you advise to do it? 

Thanks

**Comment by jzelinskie** [comment]
`go get` does download the `vendor` directory. If you attempt to build Clair, it will use the packages in vendor.
