### ISSUE TITLE
Could not save images even I get to see Docker Images

### ISSUE THREAD

**Issue by cuteydarling** [quay/clair#227]
Hello,

Sorry that I'm very new to Docker as well as CoreOS.

I'm currently facing this problem where i cant scan images locally where Clair is being deploy in local.

Below is my error popup.
![image](https://cloud.githubusercontent.com/assets/17915580/17577150/6a8d4e82-5f72-11e6-9ea3-2dca3a8de962.png)

Any idea why is this happening? Appreciate if anyone could help me out on this.

Thank You!

**Comment by supereagle** [comment]
The analyze tool will run docker save command to pull image, so you should provide the full image name.

**Comment by jzelinskie** [comment]
Sorry, but this tool is unsupported now. You should try using clairctl for local scanning.
