### ISSUE TITLE
Failure to scan layers over 200MB

### ISSUE THREAD

**Issue by jzelinskie** [quay/clair#237]
Due to [this line](https://github.com/coreos/clair/blob/28fbfc72e7a77f15fffc3848ecbb44943dd15a70/worker/worker.go#L34), we cannot scan layers larger than 200MB. This value should probably be configurable and not hard-coded.

**Comment by Quentin-M** [comment]
To be accurate, it prevents analysis of layers that contain files that match the extraction pattern AND are over 200MB.
