### ISSUE TITLE
Broken url link: coreos clair document page 404

### ISSUE THREAD

**Issue by zyfdegh** [quay/clair#244]
README.md 
# Documentation

The latest stable documentation can be found [on the CoreOS website](https://coreos.com/clair/docs/latest/). Documentation for the current branch can be found inside the Documentation directory at the root of the project's source code.

**returns 404**

**Comment by alekssaul** [comment]
Thanks, I believe the correct address is; https://tectonic.com/quay-enterprise/docs/latest/clair.html

**Comment by jzelinskie** [comment]
This link will be fixed the next time that CoreOS.com synchronizes its documentation with the Clair repository. Until then, use the link posted by @alekssaul

**Comment by jzelinskie** [comment]
This is no longer broken.
