### ISSUE TITLE
Wrong version number determined on quay.io for an installed package

### ISSUE THREAD

**Issue by drobakowski** [quay/clair#245]
On quay.io we are seeing a wrong version number determined for the installed package `gnupg` in our image `quay.io/synlay/docker-erlang:19.0`. On `quay.io` the version `1.4.20-1ubuntu3` is shown, while the image has the version `1.4.20-1ubuntu3.1` installed. Version `1.4.20-1ubuntu3` does have a vulnerability which is fixed with `1.4.20-1ubuntu3.1`.

I've verified the installed version through:

```
docker run -it --rm quay.io/synlay/docker-erlang:19.0 dpkg-query --show gnupg
> gnupg 1.4.20-1ubuntu3.1
```

[Link to the security scan](https://quay.io/repository/synlay/docker-erlang/image/bd52c5e824235e12f45dd095620993de1246eefa6f0537b963118447f2dbdceb?tab=vulnerabilities)

**Comment by jzelinskie** [comment]
closing due to age. please remake this issue if it's still relevant. thanks
