### ISSUE TITLE
How to enable debug log in clair?

### ISSUE THREAD

**Issue by ScorpioCPH** [quay/clair#249]
I want to enable debug log in clair (which is `log.Debugf`), but there is no config in `config.yaml` for this feature, thanks.

**Comment by Quentin-M** [comment]
Hi,

You can use the following command-line parameter: `--log-level=debug`

**Comment by ScorpioCPH** [comment]
@Quentin-M, thanks for answering my question, but where to add this parameter, in docker-compose.yaml? I use `docker-compose` to deploy clair.

**Comment by Quentin-M** [comment]
Right there: https://github.com/coreos/clair/blob/93f7f10/docker-compose.yml#L21

**Comment by ScorpioCPH** [comment]
@Quentin-M, good, thank you so much!
