### ISSUE TITLE
Any way to run clair against a directory

### ISSUE THREAD

**Issue by tailhook** [quay/clair#250]
Is there any way to run clair against an already unpacked container in directory? (it looks like even command-line tools like klar and hyperclair use docker API, right?

It may be useful with containers alternative to docker and rkt. For example: systemd-nspawn, lxc,  and bare virtual machines.

At a glance, it looks like it's easy to do because clair unpacks containers anyway and check the folder for vulnerabilities. So only a command-line is needed.

Am I missing something? Will such PR be accepted if it needs to be implemented?

**Comment by jgsqware** [comment]
hyperclair use in fact docker api but for lac image, it extract it as a
tarball into a folder that will be pulled later on by Clair, so we could
adapt the get directly the tarball from your layers

**Comment by tailhook** [comment]
@jgsqware that sounds promising. Is there a command-line flag for that? Or should I open an issue in hyperclair?

**Comment by jgsqware** [comment]
hyperclair will be integrated in clqir project so we can keep this issue.
need to think how to implement it.

**Comment by jzelinskie** [comment]
closing due to age. please remake this issue if it's still relevant. thanks
