### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by el-liberator** [quay/clair#259]
How works notifications ? 
I define an endpoint in the configuration file like this :
endpoint: http://name.domain.com/event
but no json file is sent to this url

**Comment by Quentin-M** [comment]
Hi,

Each time the Clair's updaters run, new vulnerabilities or updates to known vulnerabilities may arise. When it is the case, notifications IDs are sent to the specified URL in JSON format with the POST verb. You'll then be able to retrieve this notification and browse its pages using the API. Once received, the notification has to be deleted explicitly to acknowledge that you properly dealt with it. Note that it is a common misconception that notifications are sent when a layer/image has been analyzed and contains vulnerabilities.

I hope my answer helps you.

**Comment by el-liberator** [comment]
Ok , merci pour la clarification. / Thank you for clarification.
