### ISSUE TITLE
Make pgsql tests database agnostic and actual unit tests

### ISSUE THREAD

**Issue by Quentin-M** [quay/clair#264]
In the early stages of the project, most of the database tests were implementation agnostic and were running on each registered implementation. But it got removed after an internal discussion for a silly reason that I can't seem to remember. We should extract the tests from the pgsql package, make them database agnostic and move them to the database package, just like before.

Also, instead of using scenario based tests, we should definitely make them unit tests and use fixtures more often.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
