### ISSUE TITLE
Build a lightweight Clair image

### ISSUE THREAD

**Issue by Quentin-M** [quay/clair#269]
Since https://github.com/coreos/clair/pull/261 has been merged, we should now be able to create a lightweight image, that doesn't ship Go and that is not based on a huge base layer but would only have the Clair binary and the few necessary dependencies (bzr, rpm, xz-utils).

**Comment by vbmade2000** [comment]
@Quentin-M There is one Dockerfile. Can this issue be closed ?

**Comment by Quentin-M** [comment]
The current image still uses Alpine, ideally we'd build the image from scratch and place the binaries there (multistep build). But that's fine for now.
