### ISSUE TITLE
clair fetch image layer from openstack swift or ceph s3

### ISSUE THREAD

**Issue by coztest** [quay/clair#28]
Hi, 
    In my private registry, the images stored in openstack swift which need http auth header to download or get a file, so when I use "POST /v1/layers" API, I can't insert a layer from swift to clair directly. I modify "worker/worker.go func getLayerData()" to add a auth header before "r, err := http.Get(path)" but is not a graceful solution, is there a better one :).

**Comment by josephschorr** [comment]
One idea would be to enable direct linking to objects in Swift (http://docs.openstack.org/kilo/config-reference/content/object-storage-tempurl.html) and then send those URLs to Clair

**Comment by Quentin-M** [comment]
^ Same solution used for AWS S3.
