### ISSUE TITLE
Issues running clair with latest Postgres

### ISSUE THREAD

**Issue by jmhooper** [quay/clair#284]
I ran into an issue getting clair to fire up today after letting it sit for a while.

I'm running clair with docker-compose. I use exactly the `docker-compose.yml` and `config.yaml` files linked from the README with the database source updated per the docker-compose setup instructions.

Today I pulled the latest `clair` and `postgres` images and tried to start it up. I ran into the following issue:

```
$ docker-compose up
Starting clair_postgres
Starting clair_clair
Attaching to clair_postgres, clair_clair
postgres_1  | LOG:  database system was shut down at 2016-10-26 15:24:56 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
clair_1     | 2016-12-09 15:13:09.641159 I | pgsql: running database migrations
clair_1     | 2016-12-09 15:15:40.257339 E | pgsql: dial tcp 92.242.140.2:5432: getsockopt: connection refused
clair_1     | 2016-12-09 15:15:40.257512 C | main: database: could not open database
clair_clair exited with code 1
```

I blew up the saved postgres and clair containers and updated the config files to look like the latest examples, but kept seeing the problem above.

I managed to fix the issue by changing the postgres image I use in my docker-compose.yml. Before that I was using the latest `postgres` image which looks like it was at v9.6.

```yaml
version: '2'
services:
  postgres:
    container_name: clair_postgres
    image: postgres:9.4
# ...
```

It looks like it's working for me now, though I'm still waiting on it to download vulnerabilities. Since I basically backtracked all the way through the setup guide in the README on master and was still running into the issues, I'd imagine someone with a fresh setup would see the same. Just wanted to let you know that was going on.

**Comment by Quentin-M** [comment]
Hi,

Thanks for the report. It appears that Clair couldn't connect to PostgreSQL because it wasn't listening just yet. I believe that this recent change https://github.com/coreos/clair/commit/39854ac64d457223ad85b4b13eb118dcbb245199 would be enough to work around your issue.

**Comment by jmhooper** [comment]
Interesting. I also tried this and still saw the issue:

```shell
docker-compose start postgres
# wait for it to start and hop over to another shell
docker-compose start clair
```

And also I don't understand how bumping down to 9.4 solved my problem if that was the case?

**Comment by jmhooper** [comment]
I'll try adding that to my config and hopping back up to the latest postgres and will report back.

**Comment by jmhooper** [comment]
Okay, that did appear to work. Thanks for the help!

I guess we can close this now. I am still curious about why it worked with 9.4 though?

**Comment by Quentin-M** [comment]
You're welcome! I believe that is a simple coincidence as PostgreSQL and Clair are racing at startup.
