### ISSUE TITLE
How to deal with version ranges

### ISSUE THREAD

**Issue by alexandernst** [quay/clair#293]
If I'm understanding Clair's design as of it is now, if a package has a vulnerability in version 1.3 then Clair marks all version from 0.0 to <1.3 as vulnerable to this bug. 

There are some cases (OpenSSL, for example), in which a vulnerability affects only a range of versions, on maybe several ranges, e.g:

CVE foo-bar affects

    1.0.1 to 1.0.4b
    and
    1.1.4 to 1.1.9j
    and
    1.2.8 to 1.2.9a

How does Clair deal with that?

**Comment by jzelinskie** [comment]
I'm prepping a PR now that attempts to address this issue. I'm thinking that version parsers will be made another registrable functionality and `FeatureVersions` in the database will contain another column that indicates which version was used.

**Comment by jzelinskie** [comment]
related: https://github.com/coreos/clair/issues/222

**Comment by jzelinskie** [comment]
Clair now supports comparing version numbers across a variety of version formats (versionfmt).
I'm going to close this and eventually we should open an issue for supporting complex version comparisons like the example above.
