### ISSUE TITLE
How do I ignore unstable debian CVEs?

### ISSUE THREAD

**Issue by chrisfelix82** [quay/clair#297]
I get a lot of high severity errors in standard off the shelf images like jenkins.  Digging deeper, I see that the patches are in unstable debian releases (e.g. sid).  Obviously I cannot apt-get upgrade to those in my images.  How can I ignore reporting on those? Thanks.

**Comment by Quentin-M** [comment]
Hi,

It entirely depends of the integration you're using of Clair. At the end of the day, Clair just provides security information via API in JSON format. You can simply filter out everything that you want to see.

**Comment by chrisfelix82** [comment]
I'm using klar https://github.com/optiopay/klar

**Comment by jzelinskie** [comment]
This sounds like an issue better suited for the klar repository.
Please reopen if this isn't true. Thanks.
