### ISSUE TITLE
Clair unable to analyse images

### ISSUE THREAD

**Issue by jmellor** [quay/clair#304]
Clair is unable to analyse some images.
Here are the steps and logs for one of my more obvious examples.  This error happens whether the docker image is local or remote

Workaround attempt: make the image local:
$ docker pull registry.internal/analytics/event-writer
Using default tag: latest
latest: Pulling from analytics/event-writer
aed15891ba52: Pull complete
773ae8583d14: Pull complete
d1d48771f782: Pull complete
cd3d6cd6c0cf: Pull complete
8ff6f8a9120c: Pull complete
12999f8eade7: Pull complete
fdae63a2d580: Pull complete
bc75dd47f137: Pull complete
a1a6b7483ba6: Pull complete
Digest: sha256:f7ef92c9935d0d6930bd35129216dd888ca54d5c1481608647d4ae0f584aa0da
Status: Downloaded newer image for registry.internal/analytics/event-writer:latest

Analyse the image:
$ bin/analyze-local-images registry.internal/analytics/event-writer
2017-01-09 11:38:05.683800 I | Saving registry.internal/analytics/event-writer to local disk (this may take some time)
2017-01-09 11:38:20.847943 I | Retrieving image history
2017-01-09 11:38:20.896243 I | Analyzing 9 layers...
2017-01-09 11:38:20.896279 I | Analyzing a940c634b64a460f47e4c5d6f51e49c28280eb9e0e3da24df76b00c8c60ba756
2017-01-09 11:38:20.934571 I | Could not analyze layer: Post http://127.0.0.1:6060/v1/layers: dial tcp 127.0.0.1:6060: getsockopt: connection refused
$ echo $?
1

I can see no means of debugging this, so I'm stuck.  The machine has plenty of disk, 10GB of RAM and 4 processors.  It is running an up-to-date copy of Ubuntu 16.04, the latest available version of analyze-local-images, the latest available version of Docker (1.12.5) and the latest available docker versions of quay.io/coreos/clair and postgres.

Help!

**Comment by justinclayton** [comment]
From the error, it looks like clair isn't running on localhost:6060. I would check to make sure you can hit the API before continuing.

**Comment by supereagle** [comment]
Please check whether Clair is running locally (on the same machine with the analyzed images). If not, need to specify the Clair server with parameter `-endpoint "http://<CLAIR-IP-ADDRESS>:6060"`. You can refer to the [doc](https://github.com/coreos/clair/tree/master/contrib/analyze-local-images#usage)

**Comment by jmellor** [comment]
That seems to be the problem - clair was not running for some reason, and its the last thing that I would normally think of.  Not anymore.  Thanks!
