### ISSUE TITLE
How to scan own baseimage as CentOS

### ISSUE THREAD

**Issue by lune-sta** [quay/clair#306]
Hello,
I am using the baseimage of CentOS I built by myself.
When scanning with Cleir, the following error appears.

```
...
2017-01-17 07:15:09.634493 W | worker: layer aad9589efa62a4ebcf2bf605b9817e0840a67315db952c110dd6c68daaaa****: Layer's namespace is unknown but non-namespaced features have been detected
2017-01-17 07:15:09.635276 I | api: 127.0.0.1:48928 "POST /v1/layers" 422 (708.40533ms)
2017-01-17 07:15:09.636067 I | Could not analyze layer: Got response 422 with message
{
    "Error": {
        "Message": "worker: OS and/or package manager are not supported"
    }
}
```

I read the following issue and thought that I could scan after changing a part of the source.
But I do not know well what to change.
https://github.com/coreos/clair/issues/78

The main points are as follows.
- My baseimage name is 'my-centos6'.
- I want to scan any tag as centos6.

 I'd like to know if there is a good method. Thank you.

**Comment by jzelinskie** [comment]
What are the contents of your base image's `/etc/centos-release` file? This is likely the file that Clair is trying to use to determine what OS is inside the container. If the contents don't match the regular expression we use to determine CentOS version, then you can end up with the error you posted.

**Comment by lune-sta** [comment]
Thanks @jzelinskie, `/etc/centos-release` file had the following contents.

```
# cat /etc/centos-release
CentOS release 6.8 (Final)
```

**Comment by lune-sta** [comment]
Is there a mechanism to detect OS other than `/etc/centos-release`?
I'd like to know how to detect OS.

**Comment by Quentin-M** [comment]
@lune-sta Everything is in https://github.com/coreos/clair/tree/master/worker/detectors/namespace

**Comment by lune-sta** [comment]
Thanks @Quentin-M, Unfortunately I could not understand the cause, but I scanned it by modifying redhatrelease.go. Thank you very much. I will close this issue.
