### ISSUE TITLE
Replace contrib/k8s with an upstream helm chart

### ISSUE THREAD

**Issue by jzelinskie** [quay/clair#310]

**Comment by Kr1Kr1** [comment]
Hi, 
It seems that the helm chart defined in /contrib/helm/clair does not setup the database. 
Do you plan to add it or not?

Karin

**Comment by jzelinskie** [comment]
Hey there,

The previous Kubernetes manifests did not come with any database and left it to the user to specify their own preexisting database's URI.

Given some free time, I wouldn't mind adding this feature or accepting a PR for it. Granted, I don't know how production-ready relying the PostgreSQL database is, and don't necessarily want people losing data by accident.

**Comment by Kr1Kr1** [comment]
Hi, 

I'd like to deploy Clair on GCE and I am currently working on it, using the postgresql stable helm chart which supports persistent volume claim. I'll make a PR once done if it can help :)

**Comment by jzelinskie** [comment]
That sounds awesome! Thanks!

**Comment by sathieu** [comment]
Hi, Any news on porting the Helm chart to https://github.com/kubernetes/charts? (See also https://github.com/kubernetes/charts/issues/1750)

**Comment by jzelinskie** [comment]
I'm going to be at Helm Summit next week, so I'll chat with some people about it there.
I'm not sure how strongly people feel about using the official Helm repositories instead of cloning the repository.

**Comment by sathieu** [comment]
I would prefer using the official repo, then using another repo, then git-cloning.

**Comment by ghost** [comment]
Does the current chart support the v2 version if I provide that tag on the image for Clair? Or is it made to work with >=v3 only?

**Comment by jzelinskie** [comment]
The current chart supports Clair v3 only. It isn't hard to modify to use with v2, though. Just change the image tag and the template for the configmap (it's also an open issue that this configmap needs to be made a secret regardless).

**Comment by ghost** [comment]
@jzelinskie cool, thanks! Yeah, I was wondering if just changing the tag was gonna be enough, mainly because I thought the new config file format was incompatible with the v2 version.
About the configmap, I already changed it downstream but it'd be better to use the Clair chart exactly as it is upstream. I'll open a PR soon.

**Comment by jzelinskie** [comment]
I'm going to close this issue.
I think it's easier to keep our Helm charts versioned with Clair as long as it's all in the same repository.
If you want Clair in the official Charts repository, you should create an issue there.
