### ISSUE TITLE
Clair does not find any vulns in RHEL.

### ISSUE THREAD

**Issue by treezio** [quay/clair#311]
We are considering deploying quay registry if we can find out any solution for this.

I've been tracking some issues but I get lost between all those Issues, commits and PR (I'm newbie in GitHub).

I got Clair deployed on Docker using the current master version since it includes Alpine Support and when I launch the analyze-local-images binary I just get a message reporting a successful execution. This is impossible since I checked the image using docker-openScap and it reports several CVEs.

**Comment by jzelinskie** [comment]
Are finding vulnerabilities when you push the image to Quay.io? It's quite possible open-scap uses different resources to determining it's vulnerabilities. We're depending on the upstream distributions to maintain their vulnerability databases. In the case of Alpine Linux, we use http://git.alpinelinux.org/cgit/alpine-secdb/

**Comment by Quentin-M** [comment]
You also have to wait for Clair to finish its initial update (see other issues).

**Comment by treezio** [comment]
Thanks for your quick replies guys.

We dont have any quay.io repository currently working, we are looking forward to integrate it in case we can solve the RHEL images problem though.

also I knew about the first vulnerabilities db update.

Also when updating I'm having some issues:
2017-01-30 04:13:10.652758 E | updater/fetchers/metadata_fetchers: could not decode NVD data feed '2008': EOF
2017-01-30 04:13:10.652809 E | updater: an error occured when loading metadata fetcher 'NVD': updater/fetchers: could not parse.

I face the same message everyday but different years data feed, I guess this is related to some proxy/middleware problem. 

In  the first run I got:
2017-01-27 13:41:48.105930 E | updater/fetchers/metadata_fetchers: could not decode NVD data feed '2015': read tcp 172.17.0.2:38409->180.205.18.15:80: read: connection reset by peer

Then I get the:
an error occured when loading metadata fetcher 'NVD': updater/fetchers: could not parse.

anyway, I'm still not able to analyze RHEL Images, is Clair supporting RHEL based images?

**Comment by Quentin-M** [comment]
Definitely a networking issue. Not much we can do on our side.

CentOS is supported. Never tested RHEL itself, would have to verify how the namespace and package parsers behave and potentially adjust.

**Comment by jzelinskie** [comment]
closing due to age. please remake this issue if it's still relevant. thanks

**Comment by ilackarms** [comment]
can anyone confirm if Clair works on RHEL images?

**Comment by treezio** [comment]
Didn't work for me.

**Comment by jzelinskie** [comment]
Would you mind opening a new issue? RHEL definitely is working for numerous Clair installations and the logs in this issue are related to NVD metadata and not RHEL.
