### ISSUE TITLE
Include Last Update in API Responses

### ISSUE THREAD

**Issue by acdha** [quay/clair#315]
I was just getting started with clair and was suspicious when I noticed that `analyze-local-images` passed some images which I knew were stale. After looking at #176, #311, etc. it seems like this could be solved in the simplest case by having `analyze-local-images` check that `/v1/namespaces` doesn't return a null namespaces list and that each listed namespace also isn't null, but it'd really be nice if there was simply a way to get the last update time so a tool could refuse to run if the update list was more than n hours out of date.

**Comment by jzelinskie** [comment]
The v3 API now includes this.
