### ISSUE TITLE
binary check rather than only check particular files

### ISSUE THREAD

**Issue by huahuiyang** [quay/clair#320]
clair only check some particular files, for ubuntu, clair checks ‘etc/apt/sources.list and var/lib/dpkg/status’ to compare with the CVE database to figure out some security issues.
just curious is it good enough?
my point is shall we do binary check to make it solid? What if people only hack the file(var/lib/dpkg/status) to go through security check?

please correct me if I misunderstand the scanning strategy under the hood.

**Comment by jzelinskie** [comment]
Hi there!

By binary check, do you mean hashing the files and referencing a database of file hashes?
There isn't an architectural reason why this couldn't be supported, although I suspect it will cause a few minor changes. We aren't familiar with any accurate, public-licensed CVE<>hash databases that could be integrated, so it hasn't been much of a priority.

In practice, we've found that informing users how to fix things is more valuable than simply presenting them with as much data as possible. I'd be hesitant to add support for something like this upstream unless we could still provide actionable items to users based off of the data.

**Comment by jzelinskie** [comment]
This is stale and probably a duplicate of #172.
