### ISSUE TITLE
Handling false positives because of "not really" affected packages.

### ISSUE THREAD

**Issue by yfoelling** [quay/clair#321]
Hey,

is there a way of handling false positives of vulnerabilities that affect packages like "kernel-headers" , "*-license" etc.?

for example "RHSA-2016:2574", i installed golang into an Centos image, by this you need to install the "kernel-headers" package. You cant just upgrade this, because the Host Kernel is not on this Version yet.
If you scan the Image with clair it looks like you are vulnerable by a high severity vulnerability.

Is this the wanted behavior, a bug, or so i need to filter those Packages?

**Comment by jzelinskie** [comment]
The consensus from the Clair maintainers is that this functionality is best built into the UI presenting the data from Clair and that we shouldn't implement it inside Clair. A UI can have user accounts and preferences for managing ignored vulnerabilities which are features beyond the scope of Clair itself.

Kernel headers may be an exception to the rule if we can prove that no container runtime actually uses them.
