### ISSUE TITLE
Understanding Clair output

### ISSUE THREAD

**Issue by transcedentalia** [quay/clair#344]
Hello!

I tried running the Clair locally on Mac as you described on the documentation page using docker-compose  and I got the following output:

```
> docker-compose -f $HOME/docker-compose.yml up
Starting clair_postgres
Starting clair_clair
Attaching to clair_postgres, clair_clair
clair_postgres | LOG:  database system was shut down at 2017-03-07 00:41:53 UTC
clair_postgres | LOG:  MultiXact member wraparound protections are now enabled
clair_postgres | LOG:  autovacuum launcher started
clair_postgres | LOG:  database system is ready to accept connections
clair_clair | 2017-03-07 11:03:49.085771 I | pgsql: running database migrations
clair_clair | goose: no migrations to run. current version: 20151222113213
clair_clair | 2017-03-07 11:03:49.174333 I | pgsql: database migration ran successfully
clair_clair | 2017-03-07 11:03:49.174716 I | api: starting main API on port 6060.
clair_clair | 2017-03-07 11:03:49.174867 I | api: starting health API on port 6061.
clair_clair | 2017-03-07 11:03:49.176078 I | updater: updater service started. lock identifier: 44a7ebf0-93c9-46af-853a-63eb79100957
clair_clair | 2017-03-07 11:03:49.185079 I | notifier: notifier service is disabled
clair_clair | 2017-03-07 11:03:49.236305 I | updater: updating vulnerabilities
clair_clair | 2017-03-07 11:03:49.236371 I | updater: fetching vulnerability updates
clair_clair | 2017-03-07 11:03:49.236646 I | updater/fetchers/debian: fetching Debian vulnerabilities
clair_clair | 2017-03-07 11:03:49.236826 I | updater/fetchers/rhel: fetching Red Hat vulnerabilities
clair_clair | 2017-03-07 11:03:49.237773 I | updater/fetchers/ubuntu: fetching Ubuntu vulnerabilities
clair_clair | 2017-03-07 11:05:33.672809 E | updater/fetchers/debian: could not unmarshal Debian's JSON: read tcp 172.18.0.3:42770->128.31.0.67:443: read: connection reset by peer
clair_clair | 2017-03-07 11:05:33.672902 E | updater: an error occured when fetching update 'debian': updater/fetchers: could not parse.
clair_clair | 2017-03-07 11:19:34.062972 I | updater: adding metadata to vulnerabilities
clair_clair | 2017-03-07 11:47:23.176523 I | updater: update finished
clair_clair | 2017-03-07 11:47:23.199393 I | updater: updating vulnerabilities
clair_clair | 2017-03-07 11:47:23.199453 I | updater: fetching vulnerability updates
clair_clair | 2017-03-07 11:47:23.199508 I | updater/fetchers/ubuntu: fetching Ubuntu vulnerabilities
clair_clair | 2017-03-07 11:47:23.199591 I | updater/fetchers/debian: fetching Debian vulnerabilities
clair_clair | 2017-03-07 11:47:23.200133 I | updater/fetchers/rhel: fetching Red Hat vulnerabilities
clair_clair | 2017-03-07 11:48:29.261018 I | updater: adding metadata to vulnerabilities
clair_clair | 2017-03-07 12:25:11.917585 I | updater: update finished
clair_clair | 2017-03-07 14:25:11.021761 I | updater: updating vulnerabilities
clair_clair | 2017-03-07 14:25:11.021886 I | updater: fetching vulnerability updates
clair_clair | 2017-03-07 14:25:11.021941 I | updater/fetchers/ubuntu: fetching Ubuntu vulnerabilities
clair_clair | 2017-03-07 14:25:11.023025 I | updater/fetchers/debian: fetching Debian vulnerabilities
clair_clair | 2017-03-07 14:25:11.024014 I | updater/fetchers/rhel: fetching Red Hat vulnerabilities
clair_clair | 2017-03-07 14:25:33.649479 I | updater: adding metadata to vulnerabilities
clair_clair | 2017-03-07 15:02:23.932154 I | updater: update finished
```

Note that I started it at 11:03 and by 15:02, when I stopped it because I had to go, I couldn't see any specific/useful output. I also checked the database and it wasn't anything new there (database, tables, etc.). Does this mean that it even did not populate the database with the vulnerabilities?

Could you please shed some light on this? I cannot understand the output or maybe I'm missing something. Any advise is much appreciated.

**Comment by jzelinskie** [comment]
Hey there,

On first run, Clair will attempt to migrate the database and run the first update for the vulnerability database. After the output `update finished`, you should have contents in all tables except for `layer`, `layer_diff_featureversion`, and `lock`. You must use the Clair API in order to POST images that will have their features indexed in order to leverage the application's full potential. 

Your logs look like you definitely should have contents in your database. How were you checking?

**Comment by transcedentalia** [comment]
Hi Jimmy!

I checked the database using pgAdmin 4 and I can see no tables:
![image](https://cloud.githubusercontent.com/assets/1708003/23905258/53c6235a-08c2-11e7-8f93-73438dfc90f0.png)

Also it took it ~1h to populate the database theoretically (until I saw the "updater: update finished" message). How often is this operation performed?

Thanks

**Comment by jzelinskie** [comment]
Are you sure you're connecting to the Postgres that's being started by compose? All the log messages from from Clair seem to indicate that it's created the database schema and filled the tables with vulnerabilities.

>Also it took it ~1h to populate the database theoretically (until I saw the "updater: update finished" message). How often is this operation performed?

The [updater interval in the config file](https://github.com/coreos/clair/blob/e10352864da16a7484fa445c2bba07998123e153/config.example.yaml#L54) defines how often updates run. After the first one, updates are incremental and do not take as long.


Unrelated: I just noticed that the docker compose file uses an old release of Clair. I think I'm going to change it to point to HEAD.

**Comment by transcedentalia** [comment]
Using the psql this time I can see the following databases:

>
postgres=# \list
                             List of databases
   Name    |  Owner   | Encoding | Collate | Ctype |   Access privileges
-----------+----------+----------+---------+-------+-----------------------
 postgres  | postgres | UTF8     | C       | C     |
 template0 | postgres | UTF8     | C       | C     | =c/postgres          +
           |          |          |         |       | postgres=CTc/postgres
 template1 | postgres | UTF8     | C       | C     | =c/postgres          +
           |          |          |         |       | postgres=CTc/postgres
(3 rows)
> 

postgres (user postgres) is the one I specified in config.yaml and it doesn't have any tables after running Clair:

> 
postgres=# \connect postgres
You are now connected to database "postgres" as user "postgres".
postgres=# \dt
No relations found.
postgres=#
> 

In config.yaml I have:
> 
database:
    # PostgreSQL Connection string
    # http://www.postgresql.org/docs/9.4/static/libpq-connect.html
    source: postgresql://postgres:<password_here>@postgres:5432?sslmode=disable
>

**Comment by transcedentalia** [comment]
Hi Jimmy!

Do you have any thoughts on this?

Thanks

**Comment by jzelinskie** [comment]
Sorry about the delayed response. Did you ever figure this out? The clair binary definitely succeeded in creating the schema and updating. When you start a new instance of Clair and point it to the database, does it restart this process or find the previous schema and data?

**Comment by jzelinskie** [comment]
I'm closing this due to being stale.

**Comment by AshishVerma7690** [comment]
@transcedentalia Have you ever able to see the database entries?
