### ISSUE TITLE
Clair DataBase Replication

### ISSUE THREAD

**Issue by shiva022** [quay/clair#345]
Hello Team, 

I need your suggestion regarding clair's Database replication. Actually, I want to replicate the clair database from one environment to another environment as I don't have Internet access in other environment & I want to scan the image out there. Could you please let me know if I can replicate clair database from one environment to another environment so that my I can schedule update in one environment for clair database & same would get replicate in other environment.  Also let me know how the clair database will update with latest vulnerability definitions (In online Environment).

**Comment by jzelinskie** [comment]
At the moment there is no story for operating Clair in an environment without the internet.

Even if you copied the tables over from another database instance connected to the internet, it wouldn't create entries linking vulnerabilities to FeatureVersions. Solving this problem requires working with a few different offline Clair users and discussing the proper design.

If it's at all possible, you could create firewall rules for Clair that only allow access to the documented data sources.

**Comment by shiva022** [comment]
Thank you for the response. What If I take the pg_dump from the running instance of the clair and restore the dump in another (offline) running clair instance. And I can schedule weekly to take the dump from one instance (online) to another instance (offline). A quick response on the same is really appreciated. Thank you in advance.

**Comment by jzelinskie** [comment]
Copying the data from another database instance skips over a process where Clair creates intermediary links between vulnerabilities and what's affected by them.

If both databases had the same image data, you could copy the database. However, this likely defeats the purpose of running an offline Clair. I assume the reason you want it offline is related to security concerns around the image metadata it stores.

**Comment by jzelinskie** [comment]
closing due to age. if this issue is going to be remade it should focus on the discussion for online usage of clair
