### ISSUE TITLE
Clair config does not support environment variables for DB url and credentials

### ISSUE THREAD

**Issue by jaekunchoi** [quay/clair#346]
This is important as we want container config to be environment agnostic.
Especially when working with Kubernetes, we need a way to encrypt them with secrets then pass them as environment variables.

Config should not be aware of environment and not hard coded.

**Comment by ErikThoreson** [comment]
you should be able to use these for postgres

https://www.postgresql.org/docs/9.4/static/libpq-envars.html

**Comment by dgonzalez** [comment]
This is important. Without being able to inject the PostgreSQL password into clair it is really hard to make it secure.

**Comment by jlk** [comment]
I just tried setting the following environment variables in a docker-compose.yml:
```
environment:
  PGHOST: clair_postgres
  PGUSER: postgres
  PGPASSWORD: testing
  PGSSLMODE: disable
```
When I fire up the composition, Clair exits with the following:

```
clair_1      | {"Event":"pgsql: no database connection string specified","Level":"fatal","Location":"main.go:96","Time":"2017-07-04 20:17:04.614629"}
clair_1 exited with code 1
```

Looking through database/pgsql/pgsql.go, it looks like the Clair pgsql driver just looks in the yaml before making calls to libPQ.

edit - test above was with Clair 2.0.1.

**Comment by dgonzalez** [comment]
I found a workaround: Use dockerize to render the configuration on the entrypoint as in this repository: https://github.com/tobilg/clair-dcos

**Comment by ArcticSnowman** [comment]
Clair should really construct the PostgreSQL connection string from variables not expect user to supply a working one.

**Comment by jzelinskie** [comment]
Clair uses a YAML file for configuration. This file should be treated as a secret. There are too many configuration options to support everything as an environment variable and would likely just make things more confusing.

**Comment by pascalwacker** [comment]
@jzelinskie how about loading default values from the config file, but being able to override them with env variables? IMHO that should be the default of how software, especially deployed in a docker environment should operate.
