### ISSUE TITLE
consider changing default port

### ISSUE THREAD

**Issue by kevinburke** [quay/clair#353]
Port 6060 is also recommended for use by `godoc`: https://godoc.org/golang.org/x/tools/cmd/godoc

This means if you are also running a local godoc server, you are going to have a conflict.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
