### ISSUE TITLE
How to determine if the vulnerability db actually loaded?

### ISSUE THREAD

**Issue by tobilg** [quay/clair#355]
I can't see an indication that the vulnerabilities have loaded successfully. In contrary, if I try to check some images from Docker Hub with `klar`, which actually have known issues, I always see a 

> Found 0 vulnerabilities

result. Clair is starting successfully, and the stderr doesn't show any errors.

**Comment by tobilg** [comment]
After nearly an hour I saw the 

> updater: update finished

message. Is there a way to expose this via the notifier?

**Comment by jzelinskie** [comment]
There isn't, but we can consolidate discussion into #315 which recommends that we add the last update to every API response.
