### ISSUE TITLE
Add missing parse case to featurefmt

### ISSUE THREAD

**Issue by jzelinskie** [quay/clair#356]
Many of the parsers have code like the following pseudo-code:

```py
packages_file = """
package_name: one
package_version: 1.0

package_name: two
package_version
"""

for line in packages_file:
  if line == package_name:
    pkg.name = parse_package_name_from_line(line)
  elif line == package_version:
    pkg.version = parse_package_version_from_line(line)

  if pkg.name != "" and pkg.version != "":
    packages_map[uniquename(pkg)] = pkg
    pkg = new_blank_pkg_object()
  # The following is the missing case we need to add:
  if line == blank_line:
    pkg = new_blank_pkg_object()
```

We need to add missing case that determines if the parser has hit the new line delimiter between two separate packages and then resets our current package object.

I haven't had this bug cause any problems parsing so far, but a malformed file could definitely cause issues.

**Comment by Quentin-M** [comment]
I agree. Assumption was made that the package managers would not produce an invalid file, so little validation has been written. Changing this would be straight-forward and provide some peace of mind.

The `kind/enhancement` label is kinda pointless tho. Or I start writting PRs that just make the project worse, then I can label them `kind/regression`.
