### ISSUE TITLE
Syntax error while running pgsql database migrations on initial startup

### ISSUE THREAD

**Issue by chr2002ca** [quay/clair#358]
Just ran the following commands(on 4/11/17) to install Clair from source as instructed by your README on a RHEL6 box that has a fresh install of Postgres 8.4 and I'm seeing the following error message:

$ go get github.com/coreos/clair
$ go install github.com/coreos/clair/cmd/clair
$ cd /apps/go/bin
$ vi config.yaml
$ ./clair -config=config.yaml
2017-04-11 14:34:31.728178 I | pgsql: running database migrations
2017-04-11 14:34:31.730438 C | main: pgsql: an error occured while running migrations: pq: syntax error at or near "NOT"

I didn't see any notes about supported version of Postgres, so I'm not sure if 8.4 is the right version.  

Any assistance you can provide is greatly appreciated.

**Comment by jzelinskie** [comment]
Clair is tested on Postgres 9.4, 9.5, and 9.6.
We recommend using 9.6. I'll update the documentation. Thanks!

**Comment by chr2002ca** [comment]
Yep, using Postgres 9.6 fixed the issue.  Thank you!
