### ISSUE TITLE
How to get clair working in Kubernetes

### ISSUE THREAD

**Issue by Jdoe213** [quay/clair#364]
Hello,

I followed the instructions to get clair going in Kubernetes. I am actually using minikube. The pods, services, replication controllers are green and the logs appear to be ok. However, I am unable to launch the clairsvc service. It opens up a url and gives me an error "The webpage cannot be found". I assume I am most likely doing something wrong.

With that being said, after I run the following steps

git clone https://github.com/coreos/clair
cd clair/contrib/k8s
kubectl create secret generic clairsecret --from-file=./config.yaml
kubectl create -f clair-kubernetes.yaml

How do I see the ui or data? Apologies in advance, I am relatively new to this.

thank you,

Joe

FOLLOW UP:

After further digging, it looks like I need to make restful calls to clair. I am using git bash currently. What is the best way of going about doing this on a windows machine?

**Comment by shikhi7** [comment]
Any updates?

**Comment by rosstimson** [comment]
Take a look at projects like [Klar](https://github.com/optiopay/klar) or [clairctl](https://github.com/jgsqware/clairctl) in order to start actually scanning some images.

**Comment by leeadh** [comment]
Hi did anyone resolve this beacuse when I did a kubectl get pods, nothing is returned.,

**Comment by jzelinskie** [comment]
The Helm chart in the distribution directory is the recommended way to run Clair on Kubernetes.

**Comment by leeadh** [comment]
Hi jzelinskie I did that also but it didn't work. I helm installed and then I exposed as nodeport for the admin portal. 

How do u access the dashboard by default using hell chart cause my pods didn't create any load balancer ip

**Comment by anuradhai4i** [comment]
@leeadh Are you looking at the correct namespace? what do you get with kubectl get pods --all-namespaces
