### ISSUE TITLE
Map container image names to layers?

### ISSUE THREAD

**Issue by caipre** [quay/clair#365]
Hey -- just getting started with clair, and it looks like the database doesn't track which images contain which layers. This means we have to use an external tool (eg, `docker inspect`) to first query what layers make up an image before we can query clair about vulnerabilities.

Is this the recommended workflow?

Could a table be added to the Postgres schema so that a query like the following is possible?

```sql
select count(*)
from
  image
  inner join image_layer on
    image_layer.image_name = image.name
  inner join layer on
    image_layer.layer_name = layer.name
where
  image.name = 'foo'
  and image.tag = '1.0.0'
```

(My SQL is rusty, but you get the idea)

A corresponding endpoint could be added to the HTTP API.

@mavenraven @davidxia

**Comment by jzelinskie** [comment]
Hi there,

Clair doesn't keep track of what images contain what layers (though it does keep track of parent layers) -- this is meant to be managed by the client of the API. Since the client provides the unique name of the layers, this can be used to store the information of what image this layer came from. For instance, the Quay registry uses the image ID concatenated with a unique storage uuid to manage this complexity.

**Comment by mavenraven** [comment]
Hi @jzelinskie, thanks for your response! If we built an API on top of Clair that allows for users to query for vulnerabilities based on image name, is that something you'd be interested in having in Clair proper?

**Comment by damelo** [comment]
Hi there , i'm using Registry API in order to identify which layers are contained in a given image provided by users and which vulnerabilities are found.

**Comment by jzelinskie** [comment]
@mavenraven A particular layer's SHA can be reused in different images with different histories. For example, the empty layer is used in many images and would appear to have vulnerabilities unless you name the layer something like `thisparticularimagehistory-sha256:abcdef`. At the moment, the separation of concern is that a registry (or other API client) should maintain this name to layer history mapping.

**Comment by caipre** [comment]
@jzelinskie Indeed, even the same image might have layers repeated. I've settled on the following to avoid collisions:

```go
qualified := fmt.Sprintf("%s:%s@%s+%s",
   image.name, image.tag, layer.digest, layer.parent)
hashdigest := fmt.Sprintf("%x", sha256.Sum256([]byte(qualified)))
```

This is using https://github.com/jgsqware/clairctl . Once I have things working I'll submit a PR there.

**Comment by jzelinskie** [comment]
Sounds good! I'll close out this issue unless there's anything more.
