### ISSUE TITLE
Could not analyze layer: Got response 400 with message {"Error":{"Message":"could not find layer"}}

### ISSUE THREAD

**Issue by overip** [quay/clair#384]
Hello, I have an issue which I think is related to some bug.

I installed CoreOS Clair on Kubernetes 1.5.4 with the following commands
`wget https://raw.githubusercontent.com/coreos/clair/master/contrib/k8s/config.yaml`
`wget https://raw.githubusercontent.com/coreos/clair/master/contrib/k8s/clair-kubernetes.yaml`
`mkdir config`
`cp config.yaml config/config.yaml`
`kubectl create secret generic clairsecret --from-file=./config.yaml`
`kubectl create -f clair-kubernetes.yaml`

I made sure that the postgres and clair pods were up and running, after that I installed analyze-local-images with the following commands
`apt-get update`
`apt install golang-go`
`mkdir go`
`export GOPATH=$HOME/go`
`export PATH=$PATH:$GOROOT/bin:$GOPATH/bin`
`go get -u github.com/coreos/clair/contrib/analyze-local-images`

Now I am trying to scan local images and I get the error
Could not analyze layer: Got response 400 with message {"Error":{"Message":"could not find layer"}}
I tried to scan images **from the master** (the clair and postgres pods are running on a minion) with
`analyze-local-images -endpoint "http://<IP_OF_POD_ON_WHICH_CLAIR_RUNS>:6060" -my-address "<KUBERNETES_MASTER_IP>" <Docker Image ID>`

I also tried to log into Clair container, installing analyze-local-images tool in there and tried to scan the local images without success. Could please anybody tell me if I am doing something wrong, or as I suspect it is a bug?
Thank you

**Comment by Quentin-M** [comment]
Hi,

See https://github.com/coreos/clair/pull/387. Besides, as stated in other issues and as you discovered by yourself, this tool is only meant to be used for local images, against a relatively local Clair instance - for discovery purposes.

**Comment by jzelinskie** [comment]
Hi.
I recommend using the clairctl tool instead of the unsupported analyze-local-images tool.
Thanks.
