### ISSUE TITLE
go get -u github.com/coreos/clair/contrib/analyze-local-images

### ISSUE THREAD

**Issue by liuyihe111** [quay/clair#399]
while running "go get -u github.com/coreos/clair/contrib/analyze-local-images", 
it returns errors as follow：
package github.com/coreos/clair/contrib/analyze-local-images: cannot find package "github.com/coreos/clair/contrib/analyze-local-images" in any of:
	/usr/local/go/src/github.com/coreos/clair/contrib/analyze-local-images (from $GOROOT)
	/root/go/src/github.com/coreos/clair/contrib/analyze-local-images (from $GOPATH)
 anyone know why this happened? and what I should do to solve it？

**Comment by jgsqware** [comment]
Analyze-local-image is not in the repository anymore. To achieve the same
things, such as analyze-local-image, you can use
github.com/jgsqware/clairctl

**Comment by liuyihe111** [comment]
@jgsqware Thank you very much！I have tried to  use github.com/jgsqware/clairctl. 
But when I do the follows :curl https://glide.sh/get | sh, it return errors.
My OS is CentOS7, should I need to install other software?

**Comment by jzelinskie** [comment]
Closing this as this discussion should continue on the clairctl repository.

There's also [a repository for the analyze-local-images tool](https://github.com/coreos/analyze-local-images), but we no longer offer any support for it or maintain it.
