### ISSUE TITLE
New Fetcher for NPM CVE Snyk Database

### ISSUE THREAD

**Issue by philips** [quay/clair#40]
look at https://github.com/Snyk/vulndb

**Comment by liangchenye** [comment]
Working on this.

Using git command to download the vulnerability data in Synk/vulndb/data/npm

**Comment by Quentin-M** [comment]
Is there any better (automated) database than that?
It looks that they based their work on https://nodesecurity.io, https://retirejs.github.io/retire.js/ and https://blog.osvdb.org/ (which is now shutdown)

**Comment by liangchenye** [comment]
Oh, yes. nodesecurity.io keeps updating. Synk is slower than it.
We can get all the advisories from https://api.nodesecurity.io/advisories.

**Comment by Quentin-M** [comment]
@liangchenye That souds better to me! It's mentioned on https://nodejs.org/en/security/.

**Comment by jzelinskie** [comment]
IIRC there were licensing issues with Snyk. I'm going to close this because if we implement nodejs support it's unlikely to be done with this data source.
