### ISSUE TITLE
busybox vulnerability database

### ISSUE THREAD

**Issue by jzelinskie** [quay/clair#402]
I haven't looked too much in detail, but it appears BusyBox also keeps track of its vulnerabilities: https://www.cvedetails.com/vendor/4282/Busybox.html

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
