### ISSUE TITLE
Fixes adds epoch number to the package version

### ISSUE THREAD

**Issue by domcar** [quay/clair#412]
Hello,

Since Clair Version 2.0.0

when I retrieve the fixes for some packages the API adds the epoch to the Version although it is not present in official repository. Example:
`GET` `http://0.0.0.0:6060/v1/namespaces/centos:7/vulnerabilities/RHSA-2017:0254/fixes`
gives me

```{
  "Features": [
    {
      "Name": "spice-server",
      "NamespaceName": "centos:7",
      "VersionFormat": "rpm",
      "Version": "0:0.12.4-20.el7_3"
    }
  ]
}
```

But the Epoch `0:` is not part of the package version when for example I make a `yum list available` on the VM.
Also here: https://access.redhat.com/errata/RHSA-2017:0254 or https://vulners.com/redhat/RHSA-2017:0254 the epoch is not present

**Comment by jzelinskie** [comment]
To my understanding, a lack of epoch in the version is equivalent to 0, so we're being more explicit in this case since other versions have non-zero epochs. If this is not true or there's another strong argument to remove the 0 epoch, I'm open to changing this code.

**Comment by domcar** [comment]
Yes it is true that `a lack of epoch in the version is equivalent to 0` but this makes it just pedantic and more difficult to compare with package version coming from the official repository.
I just think it makes more sense to use the exact same version as in official repos.

**Comment by jzelinskie** [comment]
I don't think we're going to change because it makes comparing versions more reasonable programmatically. Now that Clair maintainers work at Red Hat maybe we can work something out with the data sources.
