### ISSUE TITLE
problem fetching ubuntu vulnerabitilies

### ISSUE THREAD

**Issue by zetaab** [quay/clair#414]
{"Event":"could not pull Ubuntu repository","Level":"error","Location":"ubuntu.go:189","Time":"2017-06-12 10:47:27.871577","error":"exit status 3","output":"bzr: ERROR: Not a branch: \"/tmp/ubuntu-cve-tracker739409183/.bzr/branch/\": location is a repository.\n"}
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:220","Time":"2017-06-12 10:47:27.872240","error":"could not download requested resource","updater name":"ubuntu"}
{"Event":"could not branch Ubuntu repository","Level":"error","Location":"ubuntu.go:177","Time":"2017-06-12 10:56:31.001650","error":"signal: killed","output":""}
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:220","Time":"2017-06-12 10:56:31.071582","error":"could not download requested resource","updater name":"ubuntu"}

using docker image quay.io/coreos/clair:v2.0.0

**Comment by jzelinskie** [comment]
Fixed in #568. Please open a new issue if you're still experiencing this bug on a non-bzr Clair.
