### ISSUE TITLE
Potentially skipped RHEL CVEs

### ISSUE THREAD

**Issue by domcar** [quay/clair#419]
Hello,
i'm running two instances of Clair and strangely on one the RHSA-2017:1484 is missing while on the other is present. Is there a way to trigger manually the DB update?
Or is there any log where I could see if something is going wrong?
The two setups are identical.
Please tell me if you need any information the figure out the problem

**Comment by domcar** [comment]
Update: I removed and recreated the DB and now the missing CVE is available. Now I wonder if also other CVE are missing, I discovered this one only by coincidence

**Comment by jzelinskie** [comment]
The RHEL updater collects all the CVEs newer (by title) than the last time it updated.
There's a possibility that the maintainers of the database inserted older entries after Clair had updated. I'm speculating here, of course.

For now, I suggest you configure the update interval to be something infrequent (once or twice a day) to try to avoid something like this. I might shoot an email to the maintainers to find out their update strategy.

**Comment by jzelinskie** [comment]
Closing in favor of #419
