### ISSUE TITLE
Can Clair provide a API to query the last successed  vulernability update time?

### ISSUE THREAD

**Issue by yixingjia** [quay/clair#422]
It will be nice that Clair can provide a API to return the timestamp of last successful update vulnerability database.

When we will integration Clair with docker system there is no way to know if the vulnerability database is up to date or not. (Yes Clair will update database in back end, but without check the log, we can't tell the status)

so if we have this kind of API we can use it to integration with other systems.

**Comment by jzelinskie** [comment]
We're working on a new schema and gRPC API for v3.
We're going to aim to include this value in the API responses containing vulnerabilities.

Thanks for the feedback!

**Comment by yixingjia** [comment]
mean while can we also consider the update time for each namespaces?  as different namespace have different update time.

**Comment by reasonerjt** [comment]
@jzelinskie , this may not be a "usability" issue, Clair needs a better way to figure out if the vulnerability data is stale, without the checking the logs.

**Comment by jzelinskie** [comment]
This is now in the responses of the Clair v3 API.
