### ISSUE TITLE
Rescan after notification for vulnerability update?

### ISSUE THREAD

**Issue by reasonerjt** [quay/clair#425]
Hi, I'm integrating Clair into my registry, and here is a question.

I'm creating a notification endpoint to receive the notification from Clair.  The plan was to rescan images when the vulnerability DB is updated.

However, I've noticed the response of GET notification has an attribute "OrderedLayersIntroducingVulnerability", my question is,  does it mean when I use the "GET Layer" API to query vulnerabilities of a image that is previously scanned, the response will reflect the latest update in vulnerability without needing to rescan?

I appreciate your answers!

**Comment by jzelinskie** [comment]
>The plan was to rescan images when the vulnerability DB is updated.

Clair does not need to rescan images when the vulnerability databases are updated. From the README:
>3. Clients use the Clair API to query the database; correlating data is done in real time, rather than a cached result that needs re-scanning.

Notifications are intended show the difference between the previous set of Layers that introduced a Vulnerability with the new set of Layers that introduce the Vulnerability.

**Comment by reasonerjt** [comment]
Ah, thanks @jzelinskie 
I really should have read the doc more carefully.

**Comment by reasonerjt** [comment]
Thanks @jzelinskie, my question's answered, but please allow me to keep this open for a few more days, just in case I have further questions on this topic.

**Comment by reasonerjt** [comment]
No further questions for this particular issue, closing.
