### ISSUE TITLE
Potentially wrong detection if a feature lister checks multiple files.

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#430]
Assuming
1. Feature lister "Alpha" is detecting features in files "/etc/a" and "/etc/b".
2. In Layer "A", "Alpha" listed features "1" in "/etc/a" and "2" in "/etc/b".
3. In Layer "B", "Alpha" listed feature "3" in "/etc/a".
4. "A" is the parent of "B".

The computed diff will be:
"A" added "1" and "2"
"B" added "3", removed "1" and "2"

But in fact, there are two possibilities: 
1. in layer "B", "/etc/b" is removed and therefore feature "2" is removed
2. in layer "B", "/etc/b" is not changed and therefore feature "2" is not removed

Same problem could happen to namespace detectors.

**Comment by KeyboardNerd** [comment]
Related #635

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
