### ISSUE TITLE
The status of "first update".

### ISSUE THREAD

**Issue by reasonerjt** [quay/clair#431]
Hi,

It seems that I can get the information of subsequent updates via the notification.
But there's no way to get the status of the "first update"?  There are some data in "keyvalue" table, but it's not exposed via the API?

In my integration, I wish to inform user about the unreadiness of the vuln DB.  Do you have any suggestions on getting the status of the first update?

**Comment by reasonerjt** [comment]
Hi, I see there maybe an issue asking about it in #355 

How about adding an API to simple return the value in keyvalue table?

**Comment by jzelinskie** [comment]
I think this should be covered by the ClairStatus protobuf message in the v3 API. If not, we can re-open.
