### ISSUE TITLE
level=fatal msg="failed to load configuration" error="open /etc/clair/config.yaml: no such file or directory"

### ISSUE THREAD

**Issue by idtestingking** [quay/clair#435]
[root@localhost ~]# docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
quay.io/coreos/clair-git   latest              ee6cf4643b22        6 days ago          422MB
postgres                   9.6                 f8d91fbcfa35        3 weeks ago         269MB
postgres                   latest              f8d91fbcfa35        3 weeks ago         269MB

[root@localhost ~]# docker run -d -p 6060-6061:6060-6061 -v $PWD/clair_config:/config quay.io/coreos/clair-git:latest -config=/config/config.yaml
3614df0854f67f01567df9f2891878067ee4adc6a4cc7442050f0594c8fb020c

my config yaml file 
clair:
  database:
    # Database driver
    type: pgsql
    options:
      # PostgreSQL Connection string
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
     source: postgresql://postgres:pguser@postgres:5432?sslmode=disable

      # Number of elements kept in the cache
      # Values unlikely to change (e.g. namespaces) are cached in order to save prevent needless roundtrips to the database.
      cachesize: 16384

  api:
    # API server port
    port: 6060
    grpcPort: 6070
    # Health server port
    # This is an unencrypted endpoint useful for load balancers to check to healthiness of the clair server.
    healthport: 6061

    # Deadline before an API request will respond with a 503
    timeout: 900s

    # 32-bit URL-safe base64 key used to encrypt pagination tokens
    # If one is not provided, it will be generated.
    # Multiple clair instances in the same cluster need the same value.
    paginationkey:
"config.yaml" 80L, 2790C                                                                                                                             1,1           Top

[root@localhost clair_config]# docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                          PORTS               NAMES
02f962383d35        quay.io/coreos/clair-git:latest   "/clair -config /c..."   17 minutes ago      Restarting (1) 32 seconds ago                       clair_clair
3d61b13c96d7        postgres:latest                   "docker-entrypoint..."   17 minutes ago      Up 17 minutes                   5432/tcp            clair_postgres
252a858f51fe        postgres                          "docker-entrypoint..."   About an hour ago   Up About an hour                5432/tcp            some-postgres
[

my docker always getting restarted please help me solve this problem

**Comment by NigelWan** [comment]
check file name *config.yaml* in your $PWD/clair_config

**Comment by XuHaoIgeneral** [comment]
@NigelWan  I have the save problem. but i have the 'config.yaml' in my host......   /home/clair_config/config.yaml 

``` sudo docker run --net=host --name=clair_server -it -p 6060-6061:6060-6061 -v $PWD/clair_config:/config quay.io/coreos/clair-git:latest -config=/home/clair_config/config.yaml ```

```
{"Event":"failed to load configuration","Level":"fatal","Location":"main.go:187","Time":"2019-04-26 00:55:18.941976","error":"open /home/clair_config: no such file or directory"}
```

**Comment by jrbecart** [comment]
@XuHaoIgeneral 
Instead of using `$PWD/clair_config` use the full path name (if on windows C:\path\...\clair_config)
PS: I am using CMDER
