### ISSUE TITLE
Put request to update a feature that is a fix for a vulnerability returning "insertVulnerability needs at least the Name and the Namespace" when it is provided

### ISSUE THREAD

**Issue by JohnBoccio** [quay/clair#438]
I am trying to perform a put request on a given feature to update it with the following json:
```json
{
	"Feature": {
		"Name": "updated-fix",
		"NamespaceName": "ubuntu:16.04",
		"version": "3.11-98"
	}
}
```
the URL to the request is: `192.168.99.100:30060/v1/namespaces/ubuntu%3A16.04/vulnerabilities/random-vulnerability/fixes/updated-fix`

get requests on both ubuntu:16.04 and on random-vulnerability (a vulnerability that I posted) are responding correctly.  However, when I try to perform the put request on the feature that is a fix for a vulnerability as shown above I receive the following error:
```json
{
	"Error": {
		"Message": "insertVulnerability needs at least the Name and the Namespace"
	}
}
```
Being at the name and the namespace are both provided, I am unsure of what the issue could be on my end and may be a bug in clair.

This also seems to occur in the delete request for a feature. I am sending a request for a deletion to the following URL and this is the response I get:
192.168.99.100:30060/v1/namespaces/ubuntu%3A16.04/vulnerabilities/Test/fixes/feature
```javascript
{
	"Error": {
		"Message": "insertVulnerability needs at least the Name and the Namespace"
	}
}
```

**Comment by jzelinskie** [comment]
Updating a feature is no longer supported behavior in the the v3 API.
