### ISSUE TITLE
incorrect PostgreSQL connection string in k8s/config.yaml

### ISSUE THREAD

**Issue by kcl11** [quay/clair#443]
believe it should be postgres**ql**://postgres:password@postgres:5432/postgres?sslmode=disable

without the "ql" you'll get the _main: pgsql: no database connection string specified_ error.

**Comment by hugoShaka** [comment]
I can reproduce the issue, but your workaround did not work for me.

kubectl : 1.7.2
minikube : 0.21.0

**Comment by alexppg** [comment]
I can use this string: source: `host=postgres port=5432 user=postgres password=password sslmode=disable dbname=postgres`.

**Comment by jzelinskie** [comment]
I think this is likely to the postgres URI not being quoted and it confusing the YAML parser:
`uri: "postgresql://postgres:password@postgres:5432/postgres?sslmode=disable"` might fix it.
I generally recommend using the key value pair format as @alexppg recommends.

**Comment by hugoShaka** [comment]
I will try tomorrow, thank you @alexppg @jzelinskie
