### ISSUE TITLE
Post http://localhost:6060/v1/layers: [...] connection reset by peer

### ISSUE THREAD

**Issue by slawekgh** [quay/clair#451]
my environment: 
```
root@L530:~/clair/clairctl_1.2.8# ./clairctl-linux-amd64 health
Clair: ✔

root@L530:~/clair/clairctl_1.2.8# ./clairctl-linux-amd64 version
Clairctl version 1.2.8
```
I logged into my private registry
```
 root@L530:~/clair/clairctl_1.2.8# docker login  172.18.0.4:5000
Username (test): 
Password: 
Login Succeeded
```
I can pull images

```
root@L530:~/clair/clairctl_1.2.8# ./clairctl-linux-amd64 pull 172.18.0.4:5000/alpine 
Image: 172.18.0.4:5000/alpine:latest
 1 layers found
  ➜ sha256:439fe6ccfef0dc3bdab43af4a8578cdaa12942009521523b015145165d82d467
 ```

but during push I get connection reset by peer
```
root@L530:~/clair/clairctl_1.2.8# ./clairctl-linux-amd64 push 172.18.0.4:5000/alpine  --log-level Debug 
2017-08-23 22:02:55.627628 D | config: No config file used
2017-08-23 22:02:55.627898 D | dockerdist: Downloading manifest for 172.18.0.4:5000/alpine
2017-08-23 22:02:55.628080 D | dockerdist: Retrieving repository client
2017-08-23 22:02:55.871967 D | dockerdist: endpoint.TLSConfig.InsecureSkipVerify: true
2017-08-23 22:02:55.966567 D | dockerdist: manifest type: *schema2.DeserializedManifest
2017-08-23 22:02:55.966590 D | dockerdist: retrieved schema2 manifest, no verification
2017-08-23 22:02:55.966616 I | config: retrieving interface for local IP
2017-08-23 22:02:55.966637 D | config: no interface provided, looking for docker0
2017-08-23 22:02:55.966881 I | clair: Pushing Layer 1/1 [sha256:439fe]
2017-08-23 22:02:55.998711 D | clair: Saving sha256:439fe6ccfef0dc3bdab43af4a8578cdaa12942009521523b015145165d82d467[https://172.18.0.4:5000/v2]
2017-08-23 22:02:56.026968 D | clair: auth.insecureSkipVerify: true
2017-08-23 22:02:56.026997 D | clair: request.URL.String(): https://172.18.0.4:5000/v2/alpine/blobs/sha256:439fe6ccfef0dc3bdab43af4a8578cdaa12942009521523b015145165d82d467
2017-08-23 22:02:56.050758 I | clair: adding layer 1/1 [sha256:439fe]: pushing layer to clair: Post http://localhost:6060/v1/layers: read tcp 127.0.0.1:52372->127.0.0.1:6060: read: connection reset by peer
client quit unexpectedly
2017-08-23 22:02:56.050795 C | cmd: pushing image "172.18.0.4:5000/alpine:latest": pushing layer to clair: Post http://localhost:6060/v1/layers: read tcp 127.0.0.1:52372->127.0.0.1:6060: read: connection reset by peer
```

**Comment by slawekgh** [comment]
clair + postgres from docker-compose
registry via docker run 
my containers:
```
root@L530:~/clair/clairctl_1.2.8# docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                              NAMES
14fb7b93d84a        registry:2                        "/entrypoint.sh /etc/"   47 minutes ago      Up 19 minutes       0.0.0.0:5000->5000/tcp             registry
0aaeec7f3217        quay.io/coreos/clair-git:latest   "/clair -config /conf"   5 hours ago         Up 5 hours          0.0.0.0:6060-6061->6060-6061/tcp   clair_clair
0edf8df8659e        postgres:latest                   "docker-entrypoint.sh"   5 hours ago         Up 5 hours          5432/tcp                           clair_postgres
```
all of them works in one network:
```
oot@L530:~/clair/clairctl_1.2.8# docker inspect registry | grep IPAdd | grep 172
                    "IPAddress": "172.18.0.4",
root@L530:~/clair/clairctl_1.2.8# docker inspect clair_clair | grep IPAdd | grep 172
                    "IPAddress": "172.18.0.3",
root@L530:~/clair/clairctl_1.2.8# docker inspect clair_postgres | grep IPAdd | grep 172
                    "IPAddress": "172.18.0.2",
```

**Comment by furuholm** [comment]
I could be wrong by my guess is that this is caused by, what it seems, the v1 API being dropped in preparation for Clair 3.0. See this commit: a378cb070cb9ec56f363ec08adb8e023bfb3994e

**Comment by jzelinskie** [comment]
@furuholm This is correct. To my knowledge there is not a version of clairctl that works with the Clair v3 API. Please use a stable release of v2.x.

**Comment by maxinfernito** [comment]
I don't really think it's a problem with clairctl. 
I've tried to spin up Clair on fresh Ubuntu and Centos today and failed both times. I've tried with docker images, with docker compose following the readme and no luck. Health endpoint returns 200OK, but :6060 always returns "Recv Failure: Connection Reset by Peer" and I can't see a single thing wrong in clair docker's logs. 
I've tried deploying it for over 30 times today with different config tweaks and still nothing, altho one time  for a few seconds it was replying with 'empty server response' but then again got back to connection reset by peer. 

Can you guys check if the latest clair indeed works fine for you? I may be either dumb or something got broken recently.

API doesn't matter, plain curl localhost:6060 already replies with connection reset

**Comment by maxinfernito** [comment]
@jzelinskie  @furuholm  thoughts?

**Comment by furuholm** [comment]
@thedawidbalut Have you tried to use a stable release of v2.x? Until clairctl has been updated to support the new API (which I don't know if it has or not) you won't be able to use clairctl with the latest version of Clair.

**Comment by maxinfernito** [comment]
@furuholm I'm not talking about clairctl. I'm talking about plain Clair which doesn't work for me after deploy. I take clair, deploy it as explained in readme and the API always replies with connection reset by peer when I try to contact it with curl hitting any API.

**Comment by furuholm** [comment]
@thedawidbalut Ok. In that case I don't think I will be able to help you out. I have not used the new API. I'm waiting for it to be finished before diving into it. 

FTIW I did try to spin up a docker container with the latest version and I get "empty reply from server" rather than "Connection Reset by Peer".

**Comment by maxinfernito** [comment]
@furuholm do you know where can I fetch the latest/old working API from? I'd like to use clair now for some projects and I can't find an old API that used to work.

Yeah, as mentioned earlier - you'll get 'empty reply from server' for a few seconds-minutes and then it flips to 'connection reset by peer' =/

Thanks for responding.

**Comment by furuholm** [comment]
@thedawidbalut Just saw this PR #469. Might be what is needed. 

Otherwise you can get the latest stable version here quay.io/coreos/clair:v2.0.1

**Comment by maxinfernito** [comment]
Thank you for the link to the stable version @furuholm

**Comment by jzelinskie** [comment]
@thedawidbalut is this safe to close?

**Comment by maxinfernito** [comment]
@jzelinskie yeah, it seems like there is nothing else to be done here. Using old version for now, and will switch to the new API once ready. Atho I'm just curious how come there are no tests that would verify the existing latest API. Unless it's fault on my side, many people may fall into the same situation when they try to setup everything up by following readme but will hit the wall anyways because the latest version didn't work =/
