### ISSUE TITLE
panic: runtime error: index out of range [recovered]  panic: runtime error: index out of range

### ISSUE THREAD

**Issue by qf31** [quay/clair#452]
hi,
i wanted to pen test some images to generate report using clairctl.
i encounter the following  errors after typing the following command:
sudo clairctl report --local splunk --log-level debug : 

[clair_404.txt](https://github.com/coreos/clair/files/1248140/clair_404.txt)

Can you help pin point why is this happening and how should i solve it ? Any advise is much appreciated.
thanks

**Comment by jzelinskie** [comment]
This is an issue with clairctl and not clair. Please open an issue on that repository.
