### ISSUE TITLE
Roadmap for Clair API v3?

### ISSUE THREAD

**Issue by furuholm** [quay/clair#461]
It would be nice to get some kind of overview of what the goals and plans are for Clair API v3 now that v1 has been dropped (discussed here: https://github.com/coreos/clair/issues/451#issuecomment-324930360). Also, is there a migration story for the tooling that relies on the v1 API?

**Comment by jzelinskie** [comment]
v3 essentially lays the foundation for solving all the problems that required breaking changes with v1/v2.

If you look at the ROADMAP.md, many of these are notably design goals of v3.

Off the top of my head these include:

* multiple namespaces per layer (this work is done)
* support for operating clair w/o internet (needs discussion, but is now possible)
* enabling/disabling feature detectors and vulnerability updaters (this work is done)
* gRPC API + HTTP gateway (this work is done)
* decoupling from Postgres (this work is done)

Downstream tooling will definitely need to add explicit support, but the v3 API is significantly smaller and actually takes care of a decent amount of logic that had to be implemented in those clients (e.g. linking layers to their parents).

**Comment by furuholm** [comment]
Thanks for the update! I've seen the roadmap but wasn't sure how v3 related to it.

**Comment by changdukkim** [comment]
Hello, Could you explain about "decoupling from Postgres (this work is done)"? Is this work means that clair supports another database?

**Comment by jzelinskie** [comment]
>Hello, Could you explain about "decoupling from Postgres (this work is done)"? Is this work means that clair supports another database?

This work was just making sure that we didn't leak any Postgres implementation details outside of its package. Previously the data models didn't fully abstract away the database and some things from Postgres were leaking into application code.
