### ISSUE TITLE
[Question] Process of notifications

### ISSUE THREAD

**Issue by alexppg** [quay/clair#462]
There's an option in the config file to set an endpoint to send notifications, but there's almost no explanation of how it works. Clair does analyze the previously fed images or you have to manage all the analysis? 

PD: Thanks for your work, really awesome.

**Comment by jzelinskie** [comment]
Have you read the doc on notifications [here](https://github.com/coreos/clair/blob/master/Documentation/notifications.md)?

**Comment by alexppg** [comment]
Sure, but I think it's not clear enough or I'm not able to understand it. 

It tracks vulnerabilities that affect images that are previously download or before send notifications the images are scanned again?

**Comment by jzelinskie** [comment]
Notifications are generated when new/updated vulnerabilities are inserted into the Clair database. A webhook is sent containing an identifier for that change to the database. Using that identifier, a person or program with access to Clair's API can look at the difference between the new and old vulnerabilities. This might be a change in metadata (e.g. severity) or a change in the images it affects.

Does this clear things up? If so, I'll make sure to add it to the documentation.

**Comment by alexppg** [comment]
Cool, thank you.
