### ISSUE TITLE
Can't even read an error message: invalid character 'N' looking for beginning of value

### ISSUE THREAD

**Issue by prismhr-smartin** [quay/clair#464]
I just setup a new Clair system using the standard compose method and the Postgres password. I then attempted to scan the Postgres image as a test. However this scan did not work and provided an error I had not seen before. I did another setup of Clair and got the same exact error message. I did restart Clair after Postgres as well. I have not seen this error before but now I cannot get a setup without it.

[root@871424-1gddk003 clair_config]# CLAIR_ADDR=http://10.101.0.228:6060 CLAIR_OUTPUT=High CLAIR_THRESHOLD=10 DOCKER_USER=smartinprism DOCKER_PASSWORD=***** /usr/local/go/bin/klar postgres:9.6
Analysing 24 layers
Push layer 11 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Push layer 10 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Push layer 9 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Push layer 8 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Push layer 7 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Push layer 6 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Push layer 5 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Push layer 4 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Push layer 3 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Push layer 2 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Push layer 1 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Push layer 0 failed: Can't even read an error message: invalid character 'N' looking for beginning of value
Analyse image https://registry-1.docker.io/v2/library/postgres:9.6 failed: Analyze error 404: Not Found

Found 0 vulnerabilities

**Comment by prismhr-smartin** [comment]
Here are the log entries when looking at docker logs when making the call.

{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:48.513713","elapsed time (ms)":0.025154,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:48.587000","elapsed time (ms)":0.027652,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:48.686469","elapsed time (ms)":0.019722,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:48.785982","elapsed time (ms)":0.024811999999999997,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:48.866592","elapsed time (ms)":0.020243,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:48.968435","elapsed time (ms)":0.024803,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:49.048329","elapsed time (ms)":0.016877,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:49.126294","elapsed time (ms)":0.0186,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:49.207174","elapsed time (ms)":0.033083,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:49.292904","elapsed time (ms)":0.039531,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:49.378757","elapsed time (ms)":0.017044,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:49.466403","elapsed time (ms)":0.028780999999999998,"method":"POST","remote addr":"172.19.0.1:38076","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-06 20:30:49.547396","elapsed time (ms)":0.020981,"method":"GET","remote addr":"172.19.0.1:38076","request uri":"/v1/layers/sha256:607901f3158080dab0777d26525cb63be590938beec4688e6b0f0eda753f78e0?vulnerabilities","status":"404"}

**Comment by jzelinskie** [comment]
What version of Clair are you using?
It looks like you're using something from git and not a stable release.

FWIW, Klar has a few known issues and doesn't support the v3 API. I can't really recommend or support it.

**Comment by prismhr-smartin** [comment]
I am using quay.io/coreos/clair-git:latest for my docker image. I only see latest and master for tags. I followed the Local Docker Compose method documented here - https://github.com/coreos/clair/blob/master/Documentation/running-clair.md

The default compose file contains the entry for quay.io/coreos/clair-git:latest. Should I switch to master for a stable release? I see no tagged release versions either in that repo.

**Comment by prismhr-smartin** [comment]
FYI I removed all current containers, pull'd fresh images as the build changed last night. I still get the same error. Here are the complete docker logs. I do see it having a ""grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}" issue but I do not know if that is to be expected or what the issue could be. I will also try using another client besides klar. Thank you so much for your help!


{"Event":"pagination key is empty, generating...","Level":"warning","Location":"config.go:110","Time":"2017-09-07 14:15:44.619865"}
{"Detectors":"redhat-release,alpine-release,apt-sources,lsb-release,os-release","Event":"Clair registered components","Level":"info","Listers":"apk,dpkg,rpm","Location":"main.go:101","Time":"2017-09-07 14:15:44.621897","Updaters":"alpine,debian,oracle,rhel,ubuntu"}
{"Event":"pgsql: could not open database: dial tcp 172.19.0.2:5432: getsockopt: connection refused","Level":"fatal","Location":"main.go:137","Time":"2017-09-07 14:15:44.625581"}
{"Event":"pagination key is empty, generating...","Level":"warning","Location":"config.go:110","Time":"2017-09-07 14:15:46.461885"}
{"Detectors":"alpine-release,apt-sources,lsb-release,os-release,redhat-release","Event":"Clair registered components","Level":"info","Listers":"apk,dpkg,rpm","Location":"main.go:101","Time":"2017-09-07 14:15:46.462240","Updaters":"rhel,ubuntu,alpine,debian,oracle"}
{"Event":"pgsql: could not open database: dial tcp 172.19.0.2:5432: getsockopt: connection refused","Level":"fatal","Location":"main.go:137","Time":"2017-09-07 14:15:46.463897"}
{"Event":"pagination key is empty, generating...","Level":"warning","Location":"config.go:110","Time":"2017-09-07 14:15:49.223636"}
{"Detectors":"redhat-release,alpine-release,apt-sources,lsb-release,os-release","Event":"Clair registered components","Level":"info","Listers":"rpm,apk,dpkg","Location":"main.go:101","Time":"2017-09-07 14:15:49.223926","Updaters":"alpine,debian,oracle,rhel,ubuntu"}
{"Event":"pgsql: could not open database: dial tcp 172.19.0.2:5432: getsockopt: connection refused","Level":"fatal","Location":"main.go:137","Time":"2017-09-07 14:15:49.225351"}
{"Event":"pagination key is empty, generating...","Level":"warning","Location":"config.go:110","Time":"2017-09-07 14:15:51.128078"}
{"Detectors":"alpine-release,apt-sources,lsb-release,os-release,redhat-release","Event":"Clair registered components","Level":"info","Listers":"apk,dpkg,rpm","Location":"main.go:101","Time":"2017-09-07 14:15:51.128322","Updaters":"ubuntu,alpine,debian,oracle,rhel"}
{"Event":"running database migrations","Level":"info","Location":"pgsql.go:270","Time":"2017-09-07 14:15:51.134439"}
{"Event":"database migration ran successfully","Level":"info","Location":"pgsql.go:277","Time":"2017-09-07 14:15:53.563016"}
{"Event":"starting health API","Level":"info","Location":"api.go:62","Time":"2017-09-07 14:15:53.563545","addr":"0.0.0.0:6061"}
{"Event":"updater service started","Level":"info","Location":"updater.go:91","Time":"2017-09-07 14:15:53.563592","lock identifier":"42b2ddd8-a65d-4a50-a1fa-084c1c030376"}
{"Event":"starting grpc server","Level":"info","Location":"server.go:155","Time":"2017-09-07 14:15:53.563954","addr":"[::]:6060"}
{"Event":"grpc server is configured without client certificate authentication","Level":"warning","Location":"server.go:199","Time":"2017-09-07 14:15:53.564531"}
2017/09/07 14:15:53 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
{"Event":"notifier service is disabled","Level":"info","Location":"notifier.go:76","Time":"2017-09-07 14:15:53.574393"}
{"Event":"updating vulnerabilities","Level":"info","Location":"updater.go:191","Time":"2017-09-07 14:15:53.604262"}
{"Event":"fetching vulnerability updates","Level":"info","Location":"updater.go:271","Time":"2017-09-07 14:15:53.604368"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2017-09-07 14:15:53.604438","package":"RHEL"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"ubuntu.go:88","Time":"2017-09-07 14:15:53.604448","package":"Ubuntu"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"oracle.go:119","Time":"2017-09-07 14:15:53.604555","package":"Oracle Linux"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"debian.go:63","Time":"2017-09-07 14:15:53.615461","package":"Debian"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"alpine.go:52","Time":"2017-09-07 14:15:53.615156","package":"Alpine"}
2017/09/07 14:15:54 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/09/07 14:15:56 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/09/07 14:15:58 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/09/07 14:16:03 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
{"Event":"finished fetching","Level":"info","Location":"updater.go:290","Time":"2017-09-07 14:16:09.508985","updater name":"debian"}
2017/09/07 14:16:10 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
{"Event":"finished fetching","Level":"info","Location":"updater.go:290","Time":"2017-09-07 14:16:15.527676","updater name":"alpine"}
2017/09/07 14:16:18 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/09/07 14:16:37 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/09/07 14:16:59 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/09/07 14:17:47 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:27.089366","elapsed time (ms)":0.023271999999999998,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:27.261474","elapsed time (ms)":0.02537,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:27.437000","elapsed time (ms)":0.026368,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:27.612414","elapsed time (ms)":0.08709499999999999,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:27.786114","elapsed time (ms)":0.034259,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:27.869454","elapsed time (ms)":0.025869,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:28.017435","elapsed time (ms)":0.102876,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:28.222601","elapsed time (ms)":0.020874999999999998,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:28.315835","elapsed time (ms)":0.025967999999999998,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:28.485151","elapsed time (ms)":0.039352,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:28.568015","elapsed time (ms)":0.205953,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:28.820394","elapsed time (ms)":0.076208,"method":"POST","remote addr":"172.19.0.1:43444","request uri":"/v1/layers","status":"404"}
{"Event":"Handled HTTP request","Level":"info","Location":"server.go:105","Time":"2017-09-07 14:18:28.901923","elapsed time (ms)":0.020375,"method":"GET","remote addr":"172.19.0.1:43444","request uri":"/v1/layers/sha256:607901f3158080dab0777d26525cb63be590938beec4688e6b0f0eda753f78e0?vulnerabilities","status":"404"}
2017/09/07 14:18:50 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}

**Comment by jzelinskie** [comment]
You have to use the v2.0.1 tag. git is an unreleased version of Clair that supports many breaking changes, including a new gRPC API, so every request Klar is sending is failing.

**Comment by prismhr-smartin** [comment]
I do not see any tag other than latest or master on quay.io/coreos/clair-git. I do not see any other location for a docker repo mentioned either. I get that repo location from the docker-compose file. Could you help me fine where a v2.0.1 tag is available for Clair as I do not see it at quay.io/coreos/clair-git?

**Comment by jzelinskie** [comment]
quay.io/coreos/clair has stable releases
quay.io/coreos/clair-git is for individual git commits and refs

**Comment by prismhr-smartin** [comment]
I think you meant the following

"quay.io/coreos/clair has stable releases
quay.io/coreos/clair-git is for individual git commits and refs"

Thank you I did not even know quay.io/coreos/clair existed. I can now see version tags and those I have already tested and work as expected.

It might help others if you include this quay.io/coreos/clair repository on your main guide - https://github.com/coreos/clair/blob/master/Documentation/running-clair.md and\or in your default docker-compose file.

**Comment by mpechner** [comment]
still a thing
Logs:
clair_clair | {"Event":"pagination key is empty, generating...","Level":"warning","Location":"config.go:110","Time":"2017-10-26 00:39:20.210297"}
clair_clair | {"Detectors":"alpine-release,apt-sources,lsb-release,os-release,redhat-release","Event":"Clair registered components","Level":"info","Listers":"apk,dpkg,rpm","Location":"main.go:101","Time":"2017-10-26 00:39:20.210675","Updaters":"debian,oracle,rhel,ubuntu,alpine"}
clair_clair | {"Event":"pgsql: could not open database: pq: the database system is starting up","Level":"fatal","Location":"main.go:137","Time":"2017-10-26 00:39:20.213020"}
clair_clair | {"Event":"pagination key is empty, generating...","Level":"warning","Location":"config.go:110","Time":"2017-10-26 00:39:21.516307"}
clair_clair | {"Detectors":"apt-sources,lsb-release,os-release,redhat-release,alpine-release","Event":"Clair registered components","Level":"info","Listers":"apk,dpkg,rpm","Location":"main.go:101","Time":"2017-10-26 00:39:21.516535","Updaters":"alpine,debian,oracle,rhel,ubuntu"}
clair_clair | {"Event":"running database migrations","Level":"info","Location":"pgsql.go:270","Time":"2017-10-26 00:39:21.521390"}
clair_clair | {"Event":"database migration ran successfully","Level":"info","Location":"pgsql.go:277","Time":"2017-10-26 00:39:21.523292"}
clair_clair | {"Event":"starting health API","Level":"info","Location":"api.go:62","Time":"2017-10-26 00:39:21.523493","addr":"0.0.0.0:6061"}
clair_clair | {"Event":"notifier service is disabled","Level":"info","Location":"notifier.go:76","Time":"2017-10-26 00:39:21.523528"}
clair_clair | {"Event":"updater service started","Level":"info","Location":"updater.go:91","Time":"2017-10-26 00:39:21.523543","lock identifier":"960930b6-fc95-44cd-a9b8-6304f0626d27"}
clair_clair | {"Event":"starting grpc server","Level":"info","Location":"server.go:155","Time":"2017-10-26 00:39:21.523777","addr":"[::]:6060"}
clair_clair | 2017/10/26 00:39:21 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
clair_clair | {"Event":"grpc server is configured without client certificate authentication","Level":"warning","Location":"server.go:199","Time":"2017-10-26 00:39:21.525289"}
clair_clair | 2017/10/26 00:39:22 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
clair_clair | 2017/10/26 00:39:24 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
clair_clair | 2017/10/26 00:39:27 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
clair_clair | 2017/10/26 00:39:30 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
clair_clair | 2017/10/26 00:39:35 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}

michaels-mbp:~ mpechner$ cat  docker-compose.yml 
version: '2'
services:
  postgres:
    container_name: clair_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  clair:
    container_name: clair_clair
    image: quay.io/coreos/clair:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - ./clair_config:/config
    command: [-config, /config/config.yaml]

**Comment by prismhr-smartin** [comment]
Switch your image to quay.io/coreos/clair:v2.0.0 and it should work, the latest I have seen sometimes has issues.

**Comment by wcgcoder** [comment]
> It might help others if you include this quay.io/coreos/clair repository on your main guide - https://github.com/coreos/clair/blob/master/Documentation/running-clair.md and\or in your default docker-compose file.

@prismhr-smartin is correct. The documentation available on the front page of the project suggests you use the `clair-git` image rather that `clair`; it should be updated!
