### ISSUE TITLE
Error starting userland proxy: Bind for 0.0.0.0:6060 failed: port is already allocated.

### ISSUE THREAD

**Issue by cliffbdf** [quay/clair#466]
I ran the code snippet verbatim at https://github.com/coreos/clair/tree/release-2.0#docker and obtained this error:

`docker: Error response from daemon: driver failed programming external connectivity on endpoint happy_carson (5121861ef9327b10855fd7e0ba67730e059a2649c2d2279b3dd438f1805328df): Error starting userland proxy: Bind for 0.0.0.0:6060 failed: port is already allocated.`

I am running docker on a Mac, with the latest version of docker. I have pulled the :latest tag for clair release 2.0. I have made sure that port 6060 is not in use on my machine - I even rebooted, and then did a `lsof -i | grep 6060` to make sure. Per the code snippet, postgres runs fine, but clair gives the above error.

**Expected Outcome**:

Clair should start without an error.

**Actual Outcome**:

Clair starts, but gives the error message.

**Environment**:
- Clair version/image: quay.io/coreos/clair:latest
- Host OS: OSX 10.11.6
- Kernel (e.g. `uname -a`): Linux moby 4.9.41-moby #1 SMP Wed Sep 6 00:05:16 UTC 2017 x86_64 Linux (embedded in Docker Community Edition 17.06.2-ce-mac27 (19124))
- Kubernetes version (use `kubectl version`): NA
- Helm version (use `helm version`): NA
- Network/Firewall setup: None - running locally on Mac

**Comment by arminc** [comment]
Have you had a look at this issue: https://github.com/docker/compose/issues/3277
There are reports on issues with Docker on Mac and VM's holding ports etc...

You cab try to run the Docker container on another port like '9888-9889:6060-6061'

**Comment by admirbrankovic** [comment]
I've had a similar issue, where brew was running a service that took up that port, and I got it solved by [stopping the brew service](https://robots.thoughtbot.com/starting-and-stopping-background-services-with-homebrew). Hope it helps someone!
