### ISSUE TITLE
Update How-to documentation

### ISSUE THREAD

**Issue by Joeyn414** [quay/clair#471]
I'm happy to see you've updated clair but can you please update the documentation to reflect the API changes? Some examples of running commands to interact with the clair server through the API and expected outcomes would be great. Also it appears as though there is a web app portion to the project but it is not clear as to how we would access it. I think your project could have a significant impact on the devops community but the documentation really needs to be updated so newbs like me can actually use it.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
