### ISSUE TITLE
Target date for V3?

### ISSUE THREAD

**Issue by reasonerjt** [quay/clair#472]
Hi, we've been using Clair v2, and generally happy with it.

Glad to see a lot of exciting improvements are taking place in v3, in #461 

Currently, we're considering to add driver to /ext to support another linux distro.  It would be helpful if you could let us know the estimated date for the release of v3, so we can decide whether to build the driver on top of v3 directly.

Thanks!

**Comment by jzelinskie** [comment]
I know this is super old, but we're trying to get a form of v3 shipped for end of November.

I'm going to close this in favor of #626
