### ISSUE TITLE
Clair API returns 404 for every call

### ISSUE THREAD

**Issue by toddysm** [quay/clair#474]
**Description of Problem**:
Started Clair as per your documentation and it appears to be running. I see the following entries in the logs:
`clair_1     | {"Event":"starting grpc server","Level":"info","Location":"server.go:155","Time":"2017-10-11 17:53:35.438686","addr":"[::]:6060"}
clair_1     | {"Event":"starting health API","Level":"info","Location":"api.go:62","Time":"2017-10-11 17:53:35.439587","addr":"0.0.0.0:6061"}
`
which assumes that the API is up and running however every call to http://localhost:6060/<anything> returns 404 Not Found. Here are the calls tried:

GET http://localhost:6060/v1/versions
GET http://localhost:6060/v1/namespaces
POST http://localhost:6060/v1/layers

**Expected Outcome**:
I expected to at least get some response on the versions call. Also, not sure how the health API is working and how to use it. 

**Actual Outcome**:

**Environment**:
- Clair version/image:
- Host OS:
- Kernel (e.g. `uname -a`):
- Kubernetes version (use `kubectl version`):
- Helm version (use `helm version`):
- Network/Firewall setup:

**Comment by jzelinskie** [comment]
You're running the latest version of Clair that is unreleased and has a different gRPC-based API than what is currently documented for stable.

You should try using a stable release `quay.io/coreos/clair:v2.0.1` or checking out the `release-v2.0` branch before building a binary.

**Comment by toddysm** [comment]
There is no v2.0.1 in Quay's repository. Here is the error I am getting:

`Pulling clair (quay.io/coreos/clair-git:v2.0.1)...`
`Pulling repository quay.io/coreos/clair-git`
`ERROR: Tag v2.0.1 not found in repository quay.io/coreos/clair-git`

Here is how the repository looks like:

![image](https://user-images.githubusercontent.com/1007103/32116201-85bfef78-bafe-11e7-9c63-0447d16e09c1.png)

It seems you guys deleted all other versions and left the `latest` only.

**Comment by toddysm** [comment]
Never mind - I should use the stable repository :)

Still, the question about the GET http://localhost:6060/v1/versions API remains - is this a valid call? I am still getting 404

**Comment by jzelinskie** [comment]
There is no versions resource in the v1 API. You can find the API docs on the [CoreOS website](https://coreos.com/clair/docs/latest/api_v1.html) or the [Documentation directory on the proper branch](https://github.com/coreos/clair/blob/release-2.0/Documentation/api_v1.md).

**Comment by johnseekins** [comment]
I'm experiencing the same problem as @toddysm ...

So...according to https://github.com/coreos/clair/blob/release-2.0/Documentation/api_v1.md#namespaces, this is a valid call:
```
$ curl http://localhost:6060/v1/namespaces
Not Found
```
So why do I get a 404 back?
Alternatively, is there any documentation around the gRPC API that was mentioned by @jzelinskie ?

**Comment by jzelinskie** [comment]
You're most likely using the wrong version of Clair. HEAD does not support the v1 API.

If you're interested in the v3 API that uses JSON/gRPC you can check its API out on [SwaggerHub](https://app.swaggerhub.com/apis/coreos/clair/3.0) or read the [OpenAPI Spec directly](https://github.com/coreos/clair/blob/master/api/v3/clairpb/clair.swagger.json).
