### ISSUE TITLE
404 page not found error

### ISSUE THREAD

**Issue by s-rohil** [quay/clair#476]
**Description of Problem**:
After installing clair with the commands given under docker-compose, I am trying to access localhost:6061/api but I get a 404 page not message in the browser.
I have also edited the source config in my .yml file to the value given in the comment

**Expected Outcome**:
I do not know what the expected outcome would look like and would want to see some documented steps. Hopefully, with all my questions, I would be able to document some steps for further use.

**Actual Outcome**:
Actual outcome is 404 error

![screen shot 2017-10-13 at 10 38 35 am](https://user-images.githubusercontent.com/25045737/31551502-c4a9f0f0-b002-11e7-850a-b0168899e83e.png)

**Environment**:
- Clair version/image: 
- Host OS: mac
- Kernel (e.g. `uname -a`): 16.7.0 Darwin Kernel Version 16.7.0
- Kubernetes version (use `kubectl version`):
- Helm version (use `helm version`):
- Network/Firewall setup:

**Comment by toddysm** [comment]
I have the same issue (see https://github.com/coreos/clair/issues/474) and I am not clear how to fix it. Let me know if you figure it out.

**Comment by drdivano** [comment]
Same issue here

**Comment by jzelinskie** [comment]
6061 is the health port. It has only one route for the root that returns whether the service is healthy or not. This is useful if you run Clair in something like an Amazon ASG or Kubernetes and need to know when to take an unhealthy node out of service.

6060 is the API server port. It has all of the API routes. You can find routes in our documentation. I recommend [trying to get namespaces](https://coreos.com/clair/docs/latest/api_v1.html#get-namespaces) as that is the most simple API call you can make.

Let me know if this helps,
Jimmy
