### ISSUE TITLE
Add support to ACI format

### ISSUE THREAD

**Issue by liangchenye** [quay/clair#48]
Hi, 
Is there any plan to support ACI format?
https://github.com/coreos/rkt/blob/master/Documentation/app-container.md#ACI
(If we have such mechanize to support ACI, we could support OCI bundle easily in the future.)

**Comment by jzelinskie** [comment]
@liangchenye We are interested in this behavior. Let's leave the issue open until we've merged code that supports scanning ACI.

**Comment by liangchenye** [comment]
checked in, close.
