### ISSUE TITLE
Scan docker image doesn't work

### ISSUE THREAD

**Issue by JeremyLr** [quay/clair#480]
**Description of Problem**:
I have currently deployed Harbor on Kubernetes. Harbor is working well, I can push/pull docker images, add users, manage the roles etc. 
I deployed the PostgreSQL 9.4+ database instance required and then I have used the Helm deployment to integrate Clair in the solution, according this documentation: https://github.com/coreos/clair/blob/master/Documentation/running-clair.md and I didn't modify anything in the source code.

There was an authentication issue with the registry because I was not enable to access to the registry:
http://registry-harbor-registry.dev2.forge.paas.gemalto.com/v2/_catalog

**Here is the result with Postman**:
```
{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "message": "authentication required",
            "detail": [
                {
                    "Type": "registry",
                    "Class": "",
                    "Name": "catalog",
                    "Action": "*"
                }
            ]
        }
    ]
}
```

So I removed the authentication in the config of the registry and then it is better:
```
{
    "repositories": [
        "library/alpine",
        "library/python-rabbitmq"
    ]
}
```

Although the logs from the pod where Clair is running display:
```
...
{"Event":"found and locked a notification","Level":"info","Location":"notifier.go:145","Time":"2017-10-24 12:18:26.389902","notification name":"6008d5cf-e820-4b6e-85c3-4c2d081ffaea"}
{"Event":"successfully sent notification","Level":"info","Location":"notifier.go:186","Time":"2017-10-24 12:18:26.391192","notification name":"6008d5cf-e820-4b6e-85c3-4c2d081ffaea"}
{"Event":"found and locked a notification","Level":"info","Location":"notifier.go:145","Time":"2017-10-24 12:18:26.509204","notification name":"48aa7acd-1d0b-4bfe-9de3-55c4839b4f0a"}
{"Event":"successfully sent notification","Level":"info","Location":"notifier.go:186","Time":"2017-10-24 12:18:26.510640","notification name":"48aa7acd-1d0b-4bfe-9de3-55c4839b4f0a"}
...
```

The **Actual Outcome** when I launch the scan from the Harbor UI, I get this log error from the "View Log" link in the vulnerability column:
```
[INFO] Entered scan initializer
[INFO] Image: library/alpine:3.6, digest: sha256:0930dd4cc97ed5771ebe9be9caf3e8dc5341e0b5e32e8fb143394d7dfdfa100e
[INFO] Entered scan layer handler, current: 0, layer name: edb9b5d463b4019f7112f75764a4dc89c8a0990a75572867088c021f0be4e35e, layer path: http://registry.harbor-registry:5000/v2/library/alpine/blobs/sha256:6d987f6f42797d81a318c40d442369ba3dc124883a0964d40b0c8f4f7561d913
[ERROR] [handlers.go:110]: Unexpected error: Unexpected status code: 404, text: Not Found
```
About the "Unexpected status code: 404" I investigate in the others logs and the results from the jobservice pod display:
```
[DEBUG] [statemachine.go:45]: Job: {JobID: 114, JobType: Scan}, transiting from State: initialize, to State: scanlayer.
[ERROR] [client.go:83]: Unexpected error: Unexpected status code: 404, text: Not Found
```
I guess it's related with the previous one, so if it's the case, the issue come from the ScanLayer which cannot calls Clair's API to scan layer. What do you think about it? I don't know how solve this issue... Do you have any idea? Some tracks of investigation?
Thanks in advance!

**Expected Outcome**:
The results of scanning, then the list of the vulnerabilities.

**Environment**:
- Clair version/image: coreos/clair-git
- Host OS: RHEL v7.2
- Kernel (e.g. `uname -a`): Linux 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 9 10:09:10 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes version: v1.6.1
- Helm version (use `helm version`): Client: v2.6.0 / Server: v2.6.1

**Comment by jzelinskie** [comment]
You've deploy the latest build of clair-git, which is an unstable version with a different API. Please use a stable release from `quay.io/coreos/clair`

**Comment by JeremyLr** [comment]
Indeed. Now it is working well :+1: 
Thanks a lot ! :-)
