### ISSUE TITLE
x509: certificate signed by unknown authority (skip-tls-check)

### ISSUE THREAD

**Issue by odg0318** [quay/clair#483]
**Description of Problem**: "x509: certificate signed by unknown authority" error occured during updaing data.

**Expected Outcome**: Successfully completed to update

**Actual Outcome**:

```
ov  6 05:50:57 172.18.0.1 clair[1946]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2017-11-06 05:50:57.856328","data feed name":"2002","error":"Get https://static.nvd
.nist.gov/feeds/xml/cve/nvdcve-2.0-2002.meta: x509: certificate signed by unknown authority"}
Nov  6 05:50:59 172.18.0.1 clair[1946]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2017-11-06 05:50:59.144452","data feed name":"2003","error":"Get https://static.nvd
.nist.gov/feeds/xml/cve/nvdcve-2.0-2003.meta: x509: certificate signed by unknown authority"}
Nov  6 05:51:00 172.18.0.1 clair[1946]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2017-11-06 05:51:00.302059","data feed name":"2004","error":"Get https://static.nvd
.nist.gov/feeds/xml/cve/nvdcve-2.0-2004.meta: x509: certificate signed by unknown authority"}
Nov  6 05:51:01 172.18.0.1 clair[1946]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2017-11-06 05:51:01.585477","data feed name":"2005","error":"Get https://static.nvd
.nist.gov/feeds/xml/cve/nvdcve-2.0-2005.meta: x509: certificate signed by unknown authority"}
Nov  6 05:51:02 172.18.0.1 clair[1946]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2017-11-06 05:51:02.751369","data feed name":"2006","error":"Get https://static.nvd
.nist.gov/feeds/xml/cve/nvdcve-2.0-2006.meta: x509: certificate signed by unknown authority"}
Nov  6 05:51:04 172.18.0.1 clair[1946]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2017-11-06 05:51:04.041081","data feed name":"2007","error":"Get https://static.nvd
.nist.gov/feeds/xml/cve/nvdcve-2.0-2007.meta: x509: certificate signed by unknown authority"}
Nov  6 05:51:05 172.18.0.1 clair[1946]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2017-11-06 05:51:05.285193","data feed name":"2008","error":"Get https://static.nvd
.nist.gov/feeds/xml/cve/nvdcve-2.0-2008.meta: x509: certificate signed by unknown authority"}
Nov  6 05:51:06 172.18.0.1 clair[1946]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2017-11-06 05:51:06.574842","data feed name":"2009","error":"Get https://static.nvd
.nist.gov/feeds/xml/cve/nvdcve-2.0-2009.meta: x509: certificate signed by unknown authority"}
```

**Environment**:
- Clair version/image: 2.0.1
- Clair client name/version: N/A
- Host OS: Mac
- Kernel (e.g. `uname -a`): Darwin 16.7.0
- Kubernetes version (use `kubectl version`): N/A 
- Helm version (use `helm version`): N/A
- Network/Firewall setup: N/A

I think that insecure connection could be required when updating vulnerability data such as `-insecure-tls`.

**Comment by jzelinskie** [comment]
It's very possible that NVD's certificate has changed and the CAs in the container need updating. I'm going to try and reproduce this when I have time.

**Comment by odg0318** [comment]
Is there no way to skip tls check now?

**Comment by weige008** [comment]
I meet the same question, how should i do?  thank you!

root@SZX1000349957:~# docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 postgres
222d0c1a03ff694554b218a69788335cd650618288d2e259be896b3179273805
root@SZX1000349957:~# 
root@SZX1000349957:~# docker run --link some-postgres:postgres -p 6060-6061:6060-6061 -v $HOME/clair_config:/config quay.io/coreos/clair -config=/config/config.yaml
{"Event":"running database migrations","Level":"info","Location":"pgsql.go:216","Time":"2017-11-15 01:51:54.939910"}
{"Event":"database migration ran successfully","Level":"info","Location":"pgsql.go:223","Time":"2017-11-15 01:51:55.228432"}
{"Event":"notifier service is disabled","Level":"info","Location":"notifier.go:77","Time":"2017-11-15 01:51:55.228866"}
{"Event":"starting main API","Level":"info","Location":"api.go:52","Time":"2017-11-15 01:51:55.228927","port":6060}
{"Event":"starting health API","Level":"info","Location":"api.go:85","Time":"2017-11-15 01:51:55.229133","port":6061}
{"Event":"updater service started","Level":"info","Location":"updater.go:80","Time":"2017-11-15 01:51:55.229232","lock identifier":"746323f0-1eda-481f-8a48-46c07468c9f6"}
{"Event":"updating vulnerabilities","Level":"info","Location":"updater.go:167","Time":"2017-11-15 01:51:55.232830"}
{"Event":"fetching vulnerability updates","Level":"info","Location":"updater.go:213","Time":"2017-11-15 01:51:55.232872"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"alpine.go:52","Time":"2017-11-15 01:51:55.232963","package":"Alpine"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"oracle.go:119","Time":"2017-11-15 01:51:55.233814","package":"Oracle Linux"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"debian.go:63","Time":"2017-11-15 01:51:55.234026","package":"Debian"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2017-11-15 01:51:55.240006","package":"RHEL"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"ubuntu.go:88","Time":"2017-11-15 01:51:55.240624","package":"Ubuntu"}
{"Event":"could not download Debian's update","Level":"error","Location":"debian.go:68","Time":"2017-11-15 01:52:01.425112","error":"Get https://security-tracker.debian.org/tracker/data/json: x509: certificate signed by unknown authority"}
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:220","Time":"2017-11-15 01:52:01.425205","error":"could not download requested resource","updater name":"debian"}

**Comment by jzelinskie** [comment]
NVD data has moved entirely. Please open a new issue if this persists on v2.0.6+ or v3+.
