### ISSUE TITLE
clair environment couldn't connect internet

### ISSUE THREAD

**Issue by like-inspur** [quay/clair#489]
I create an environment that couldn't connect internet, so I can't analyze image vulnerability. How can I create a local CVE environment? Thank you !

**Comment by hewen1125** [comment]
"In regular intervals, Clair ingests vulnerability metadata from a configured set of sources and stores it in the database."   You must connect internet to do this step. If your database has stored the data, you can close Clair`s updater and use it local. 

But the sources are constantly changing and you still need to update.

**Comment by KeyboardNerd** [comment]
Hi, if I understand you correctly, you want to use Clair without the internet. 

"support for operating clair w/o internet" is mentioned in [ROADMAP.md](https://github.com/coreos/clair/blob/e9eb761db6d4093a2cbb907c14a0a99ae4c5982c/ROADMAP.md) This feature is under development as a target for Clair V3. #461

**Comment by jzelinskie** [comment]
Duplicate of #401
