### ISSUE TITLE
Feature request: Allow to read configuration from STDIN

### ISSUE THREAD

**Issue by ye** [quay/clair#490]
**Description of Problem**:

Right now `clair` only supports default configuration (hardcoded in the source) or custom configuration loaded from a file (see https://github.com/coreos/clair/blob/0151dba/cmd/clair/config.go#L84)

**Expected Outcome**:
Custom configuration should also be able to be passed into clair via STDIN via Unix pipe or Unix output redirection. I.E.

`clair -config=stdin < /path/to/config.yaml` or 
`kubectl get secrets clair -o yaml | xargs clair -config=stdin`

**Actual Outcome**:

`clair -config=/path/to/config.yaml`

**Environment**: `Alphine Linux`
- Clair version/image: `quay.io/coreos/clair:v2.0.1`
- Clair client name/version: N/A
- Host OS: `macOS`
- Kernel (e.g. `uname -a`): N/A
- Kubernetes version (use `kubectl version`): client 1.8.3; server 1.6.4
- Helm version (use `helm version`): client 2.7.2; server 2.7.2
- Network/Firewall setup: Normal

**Comment by jzelinskie** [comment]
Are you aware of `<()` in bash? It creates an anonymous FIFO for any command within the parenthesis and allows you to pass it as an argument.

Example:
```sh
$ clair -config=<(cat /path/to/config.yaml)
{"Event":"pagination key is empty, generating...","Level":"warning","Location":"config.go:110","Time":"2018-09-26 17:13:51.574182"}
...
```
