### ISSUE TITLE
Clair show so much negligible vulnerability

### ISSUE THREAD

**Issue by wrfly** [quay/clair#491]
**Description of Problem**:
I'm using `portus` with `clair` image scanning support. But calir shows so much vulnerability of the images, most of the vulnerability is negligible.

```
$ reg vulns --clair http://localhost:6060 admin/nginx
...
CVE messages
...
Unknown: 2
Negligible: 29
Low: 7
Medium: 12
High: 4
```

**Expected Outcome**:

Can you add some config to avoid the negligible or low level vulnerability? Sometimes they are pretty annoying...

Thank you.

**Actual Outcome**:

emmm...

**Environment**:
- Clair version/image: quay.io/coreos/clair:latest
- Host OS: Ubuntu

**Comment by jzelinskie** [comment]
This is a feature that should be implemented in the client you're using to communicate with Clair: in this case, `reg`.
