### ISSUE TITLE
Show vulnerability date

### ISSUE THREAD

**Issue by danielviorreta** [quay/clair#497]
**Description of Problem**:
Hi,
I would like to retrieve the date of a vulnerability from Clair API. 
I know that I can retrieve the vulnerability name and the link, but it would be nice if I have a new field with the date the vulnerability was found instead of taking some additional manual steps.

Thanks in advance!

**Comment by jzelinskie** [comment]
We aren't guaranteed to actually have this information available from all databases.

A possible solution could be failing over to when the vulnerability was added into the Clair database. It seems like this would be very confusing after the first update of the database and all the vulnerabilities seem brand new.

**Comment by Allda** [comment]
Can we at least store the date for vulnerabilities from databases which provide the data? The default value would be NULL.
I am willing to implement this if you agree, but I would rather have confirmation before I will start to work on it.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
