### ISSUE TITLE
Vague documentation for helm installation

### ISSUE THREAD

**Issue by nukepuppy** [quay/clair#500]
**Description of Problem**:
Quickly able to deploy clair via  helm to a kubernetes cluster.  However instructions about the postgres dependency are kind of vague..   putting in the obvious information to the helm values.yml / custom.yml doesn't seem to yield expected results..

there is a postgresURI commented out by default (if this is followed how does one set a connection string?) values.yml also includes postgres|User|Database| - is this redundant considering there is a postgresURI??

are we supposed to use both?  if postgresURI is commented out afterall.. how do we provide the server to 'connect to'?

Configmap is created and seems to contain the expected value.. a PG connection string etc... however the container for clair is in a crash loop

**Expected Outcome**:
Setting postgresURI should just work.

**Actual Outcome**:
```
{"Event":"failed to connect to database","Level":"error","Location":"main.go:144","Time":"2017-12-19 17:37:26.943113","error":"pgsql: no database connection string specified"}
```

**Comment by nukepuppy** [comment]
for record my only workaround was to comment out the URI in values.yml and then manually edit the template for the configmap to enter my connection string.. .(hohum)

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
