### ISSUE TITLE
Unexpected results from Clair

### ISSUE THREAD

**Issue by ajgreenb** [quay/clair#502]
_Apologies for opening this as an issue. I tried asking in the IRC channel, but seems like no one was around. This is the only other listed option under **Contact**. Feel free to close this after addressing it._

I ran `ubuntu:16.04` through Clair, which turned up the following vulnerability profile:

```
Negligible: 15
Low: 14
Medium: 6
```

Then I built a Docker image that starts from `ubuntu:16.04`, updates the package-cache, and installs and runs `unattended-upgrades`. The `Dockerfile` looks like this:

```Dockerfile
FROM ubuntu:16.04
RUN [ "apt-get", "update" ]
RUN [ "apt-get", "install", "-y", "unattended-upgrades" ]
RUN [ "unattended-upgrades" ]
```

I ran the resulting image through Clair which turned out this vulnerability profile:

```
Negligible: 15
Low: 16
Medium: 14
```

Further testing of the vulnerabilities output revealed that the upgraded Docker image's vulnerability set is a strict superset of the plain `ubuntu:16.04` image's vulnerability set. Since [`unattended-upgrades`](https://wiki.debian.org/UnattendedUpgrades) installs the security patches for Debian, I would have expected running it to _decrease_ the number of vulnerabilities, rather than increasing it.

I might just be misunderstanding how Clair works. Does anyone have an explanation for this behavior? Thanks in advance.

**Comment by jzelinskie** [comment]
While your intuition is generally correct, it is not always necessarily true.

Sometimes to fix more critical issues, you're forced to update software to versions that could have more less-severe issues. I cannot say for certain whether or not this is the case for Ubuntu, but it should be noted that the databases that Clair gets its vulnerability information from are all maintained by humans and humans are capable of errors and being lazy. For example, they likely care more about keeping things more accurate for newer versions than older versions.

In an ideal world, the number of vulnerabilities would only ever go down, but I don't think that this is always the case, even for important projects like Ubuntu. Clair is also a best effort attempt for making this data available programatically. Maybe in the future, we'll have better collaboration around static  detection of vulnerabilities and the margin for error will decrease.

**Comment by ajgreenb** [comment]
That makes sense to me! I guess it just surprised me that _none_ of the original vulnerabilities were fixed by the security upgrade (only new ones added.) But, like you say, Clair is at the mercy of the data sources it uses which could be faulty. Thanks for answering.
