### ISSUE TITLE
Can it be off-line scanning CVE？

### ISSUE THREAD

**Issue by anhuiyuhu** [quay/clair#504]
Did clair support off-line scanning?

Thanks!

**Comment by anhuiyuhu** [comment]
0.0

**Comment by jzelinskie** [comment]
Clair v2 does not support offline scanning.
Clair v3's data model is designed such that it can support it in the future, but it has not been discussed in detail or implemented yet.

**Comment by anhuiyuhu** [comment]
@jzelinskie  thanks
