### ISSUE TITLE
don not have a api: list all vulnerabilities of a software .

### ISSUE THREAD

**Issue by xiaonancc77** [quay/clair#510]
don not have a api: list all vulnerabilities of a software .

I want to know softwares which in my image. and all high level vulnerabilities in the software.

![image](https://user-images.githubusercontent.com/18757382/35077224-f694d686-fc36-11e7-8562-21e601cfc248.png)

**Description of Problem**:

**Expected Outcome**:

**Actual Outcome**:

**Environment**:
- Clair version/image: 
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
Please use or contribute to third party tools described in [integrations.md](https://github.com/coreos/clair/blob/master/Documentation/integrations.md) to achieve this functionality.

**Comment by jzelinskie** [comment]
For a standalone client for Clair, right now I recommend [reg](https://github.com/genuinetools/reg) which supports Clair v2 AND v3 or [clairctl](https://github.com/jgsqware/clairctl) for v2.
