### ISSUE TITLE
Address hack in redhatReleaseRegexp

### ISSUE THREAD

**Issue by cdrage** [quay/clair#511]
Hey @vbatts I saw your comment here:

https://github.com/coreos/clair/blob/master/ext/featurens/redhatrelease/redhatrelease.go#L65

That links: https://github.com/coreos/clair/pull/193

I'm assuming we don't need that hack anymore (now that the PR is closed)?

**Comment by vbatts** [comment]
oh interesting. It'd before worth testing.
