### ISSUE TITLE
add requirement of a db to 'Running Clair' documentation

### ISSUE THREAD

**Issue by eversC** [quay/clair#512]
the need for a database for clair to use is pretty obvious (and an easy task to complete), but doesn't seem to be detailed anywhere in the 'Running Clair' documentation. 

There's mention of `A PostgreSQL 9.4+ database instance is required for all instructions.` in https://github.com/coreos/clair/blob/master/Documentation/running-clair.md, though no details specifically about creating a db.

I was expecting Clair to create the db itself, and looks like there is functionality to do that, via the `ManageDatabaseLifecycle` config bool (see https://github.com/coreos/clair/blob/master/database/pgsql/pgsql.go)-- though this defaults to false, and I can't see any docco for that either?

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
