### ISSUE TITLE
Wrong feature versionFormat(apk expected but dpkg found)

### ISSUE THREAD

**Issue by hewen1125** [quay/clair#514]
**Description of Problem**:
Wrong feature versionFormat(apk expected but dpkg found). 

**Expected Outcome**:

> {
                "name": "alpine-keys",
                "namespaceName": "alpine:v3.7",
                "version": "2.1-r1",
                "versionFormat": "**apk**",
                "vulnerabilities": []
            },

**Actual Outcome**:

>{
                "name": "alpine-keys",
                "namespaceName": "alpine:v3.7",
                "version": "2.1-r1",
                "versionFormat": "**dpkg**",
                "vulnerabilities": []
            },

**Environment**:
Use the latest code (master branch)

**Comment by KeyboardNerd** [comment]
By current design, VersionFormat does not imply specific package manager. In this case, dpkg and apk shares the same version format.

**Comment by jzelinskie** [comment]
Alpine's version strings are not well defined. 
We found that the dpkg version string spec actually works for every apk verison string, so we just reused it.
