### ISSUE TITLE
could not get NVD data feed hash

### ISSUE THREAD

**Issue by abzmungul** [quay/clair#515]
**Description of Problem**:
I get the following error in the logs

"Get http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2002.meta: read tcp 172.17.0.8:47180->129.6.13.177:80: read: connection timed out"

The Clair docker container is running on ECS, the ECS host has network connectivity outbound

**Expected Outcome**:

**Actual Outcome**:

**Environment**:
- Clair version/image: Latest
- Clair client name/version: 
- Host OS: Centos 7
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by deshui123** [comment]
I also met related issue, maybe you can try update NVD date manually.
All NVD data can be found in https://nvd.nist.gov/vuln/data-feeds.
Download related data and put them into the related path of clair.
For me, it works and not found ralated issue any more.

**Comment by abzmungul** [comment]
How would i go about updating this manually? would you mind giving me an example please?

**Comment by ninjaMog** [comment]
I think the download issue is caused by NVD disabling the http endpoint.  I'm just testing running the container with an updated https endpoint.

**Comment by ninjaMog** [comment]
Once I updated the NVD endpoints to https, the vulnerability update completed without NVD errors.

**Comment by ninjaMog** [comment]
I've now retested with http endpoints, and they're now working again.  Usual NVD reliability >_<

**Comment by jzelinskie** [comment]
Fixed in #565
