### ISSUE TITLE
Why Clair fail to scan quay.io/repository/coreos/prometheus-operator? is it because busybox?

### ISSUE THREAD

**Issue by flaviod** [quay/clair#516]
**Description of Problem**:

I would like to understand why Clair can't support this example of container: 
https://quay.io/repository/coreos/prometheus-operator?tab=tags
https://github.com/coreos/prometheus-operator/blob/master/Dockerfile

Is it because it is using busybox? And why busybox is not supported? 

https://quay.io/repository/prometheus/busybox?tag=latest&tab=tags

**Environment**:
- Clair version/image: 
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
I ran Clair release-2.0 to test the image and found that there's no feature ( installed package ) or namespace ( operating system version ) found in the images. I can't speak for why it's shown as unsupported on Quay's end but on Clair's end it's very clear. 

**Why Clair can't support this example of container**
The way Clair works is based on retrieving the operating system information and installed package information from **files in the container image**. You can look at which files are required in the function `RequiredFilenames() []string` defined in go source files in `ext/featurefmt` and `ext/featurens`. Those docker images you mentioned simply don't have the files that Clair requires to extract the necessary information.
