### ISSUE TITLE
Helm generates an issue in the Clair Configmap : "worksource" instead of "source"

### ISSUE THREAD

**Issue by JeremyLr** [quay/clair#519]
**Description of Problem**:

Hi, I would just to alert you about an issue with the generation of the configmap of Clair using Helm.
During the generation it seems a missing carriage return just after the last word of a comment involving the wrong key "worksource" instead of "work".
I think this issue probably come from the template.

**Actual Outcome**:

clair:
  database:
    # Database driver
    type: pgsql
    options:
      # PostgreSQL Connection string
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
      # This should be done using secrets or Vault, but for now this will also
      **worksource**: "postgres://postgres:password@x.x.x.x:5432/postgres?sslmode=disable"

      [ ... ]

**Expected Outcome**:

clair:
  database:
    # Database driver
    type: pgsql
    options:
      # PostgreSQL Connection string
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
      # This should be done using secrets or Vault, but for now this will also **work**
      **source**: "postgres://postgres:password@x.x.x.x:5432/postgres?sslmode=disable"

      [ ... ]

**Environment**:
- Clair version/image: **quay.io/repository/coreos/clair**
- Clair client name/version: **v2.0.1**
- Helm version (use `helm version`):  **client : v2.6.0 / server : v2.6.1**

**Comment by jzelinskie** [comment]
This was fixed in #518.
Thanks for the report!
