### ISSUE TITLE
could not branch Ubuntu repository

### ISSUE THREAD

**Issue by Vad1mo** [quay/clair#520]
I get this error in the logs with the latest clair (2.0.1) also the CPU Load is at its limit since hours.

```
{"Event":"could not branch Ubuntu repository","Level":"error","Location":"ubuntu.go:177","Time":"2018-02-08 22:53:30.777655","error":"signal: killed","output":""}
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:220","Time":"2018-02-08 22:53:30.784815","error":"could not download requested resource","updater name":"ubuntu"}

{"Event":"could not pull Ubuntu repository","Level":"error","Location":"ubuntu.go:189","Time":"2018-02-08 22:49:33.410341","error":"exit status 3","output":"bzr: ERROR: Not a branch: \"/tmp/ubuntu-cve-tracker041293065/.bzr/branch/\": location is a repository.\n"}
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:220","Time":"2018-02-08 22:49:33.410734","error":"could not download requested resource","updater name":"ubuntu"}
```

**Comment by KeyboardNerd** [comment]
I think this issue is related to [this line](https://github.com/coreos/clair/blob/fb32dcfa58077dadd8bfbf338c4aa342d5e9ef85/ext/vulnsrc/ubuntu/ubuntu.go#L190). When the bzr command exit abnormally, the repo might be in corrupted state, which causes all sorts of problems. I think cleaning up the folder is a good idea.

**Comment by tomer-1** [comment]
i've managed to solve this error by increasing the max memory and max CPU for the pod
it seems like the original chart doesn't take into consideration the cloning task memory and CPU needs

**Comment by jzelinskie** [comment]
This no longer effects Clair v2 or v3 as Ubuntu has moved to using git.
