### ISSUE TITLE
How long does clair takes to scan an image in the Registry?

### ISSUE THREAD

**Issue by arjunm183** [quay/clair#523]
**Description of Problem**: Scanning of clair images taken longer time. Would like to know how long does clair takes to scan an image once its pushed

**Expected Outcome**: As soon as the image is pushed to the registry the images should scan immediately.

**Actual Outcome**: As soon as the image is pushed to the registry the images takes long time to scan.

**Environment**:
- Clair version/image:  clair-jwt:v2.0.0
- Clair client name/version: 
- Host OS: SLES 12 SP1
- Kernel (e.g. `uname -a`):  3.12.67-60.64.18
- Kubernetes version (use `kubectl version`):  no
- Helm version (use `helm version`): no
- Network/Firewall setup: no firewall

**Comment by Quentin-M** [comment]
Hi,

This does not sound like an issue related to Clair specifically.
Clair will scan the image as soon as it is requested to do so via its API.
Thus, it ultimately depends on the tool that hook registry pushes to the Clair instances.

**Comment by jzelinskie** [comment]
I'm going to close out this issue. If someone wants to recreate an issue to discuss the design for distributed tracing for Clair, that'd be great.
