### ISSUE TITLE
could not branch Ubuntu repository

### ISSUE THREAD

**Issue by avomi** [quay/clair#524]
clair logs 

Feb 19 11:25:46 172.18.0.1 clair[509]: {"Event":"could not branch Ubuntu repository","Level":"error","Location":"ubuntu.go:177","Time":"2018-02-19 11:25:46.924706","error":"exit status 3","output":"bzr: ERROR: Invalid http response for http://bazaar.launchpad.net/~ubuntu-security/ubuntu-cve-tracker/master/.bzr/repository/packs/269638fd93f179ceafe5d289f42db0c1.pack: Missing the Content-Range header in a 206 range response\n"}
Feb 19 11:25:46 172.18.0.1 clair[509]: {"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:220","Time":"2018-02-19 11:25:46.924851","error":"could not download requested resource","updater name":"ubuntu"}

a manual download using bzr Fails either 
with 
bzr branch lp:ubuntu-cve-tracker
or with 
bzr branch https://launchpad.net/ubuntu-cve-tracker

with the same error in the final step 
Invalid http response for http://bazaar.launchpad.net/~ubuntu-security/ubuntu-cve-tracker/master/.bzr/repository/packs/16c916fc513b214fbddf8bfb4c8f1e61.pack: Missing the Content-Range header in a 206 range Response
If I use curl the file is downloaded correctly.

.

**Environment**:
- vmware/Harbor with clair: 
- Clair client name/version: clair2.0.1
- Host OS:  photonos v1.0
- Network/Firewall setup: docker Container behind nginx and corporate firewall

**Comment by KeyboardNerd** [comment]
It seems like an issue with bzr.
btw, did you curl with `range` header?

**Comment by avomi** [comment]
No. I used curl without the range header.

**Comment by tomer-1** [comment]
the failure is due to kubernetes kiling the bazaar process with OOM
you will need to increase the memory and CPU limits in the deployment for the pod to at lease 1500Mi and 200m respectively.
see the following PR : https://github.com/coreos/clair/pull/537

**Comment by ninjaMog** [comment]
I'm hitting the same issue, manual bzr branch commands fail using the bzr branch referenced by clair.

Visiting the site https://code.launchpad.net/ubuntu-cve-tracker
It now lists the main code as a git respository not a bzr repo.

The bzr branch links have different addresses: https://code.launchpad.net/ubuntu-cve-tracker/+branches

Does /ext/vulnsrc/ubuntu/ubuntu.go need to be updated to reference lp:~ubuntu-security/ubuntu-cve-tracker/master 
instead?

**Comment by jault3** [comment]
Getting #562 merged would be very helpful! Clair sits in a 1 minute loop updating vulnerability data from all sources because of that error.

**Comment by jzelinskie** [comment]
Fixed in #568. Please open a new issue if you're still experiencing this bug on a non-bzr Clair.
