### ISSUE TITLE
Clair connection issues in Ubuntu16

### ISSUE THREAD

**Issue by SyCode7** [quay/clair#526]
I have has issue with clair, the logs are below:
`2018/02/20 17:04:21 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
` 

I have looked around and tried several recommended fixes  without any success !!
My configuration is as follows:

`Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.858GiB
Name: slingshot
ID: CA7X:MACI:7LHI:CZ62:IDNO:FD4X:AJ7D:MDQJ:ZJYP:MHF4:WYTA:A3OU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 56
 Goroutines: 69
 System Time: 2018-02-20T18:08:12.902672024+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
`

**Comment by jzelinskie** [comment]
What version of Clair are you using? This looks like it's from master and not a stable release. If you'd like to use Clair with any existing clients, you'll probably want to use a stable release.

The failure looks like Clair is failing to bind to port 6060. Can you describe the steps you used to arrive at this error?
