### ISSUE TITLE
How Clair can identify package "version" in an image layer?

### ISSUE THREAD

**Issue by jeffweilee** [quay/clair#527]
Hi, The document says Clair uses ***static program analysis*** and ***doesn't run any containers to analyze image vulnerability﻿***. My question is: 
1. How Clair can identify package "version" without running the image container? 
2. If the image does not run as a container, how Clair find the package list under such as /var/lib/rpm/packages in an image?

Thanks.

**Comment by KeyboardNerd** [comment]
Container image is just a tarball of a file system. In Docker container image, the current file system can be computed by combining layers, which contain add/delete/change information to a file system.

If you decompress and look into the layers inside container images, for example in Docker Image, you can find the installed package information files e.g. `/var/lib/rpm/packages`, which contain the package versions.

**Comment by jeffweilee** [comment]
I find ```/var```, ```/etc```, ```/usr``` under ```/var/lib/docker/overlay2/l/{layerHashCode}/```.
And I also find installed package information under e.g. ```/var/lib/docker/overlay2/l/{layerHashCode}/var/lib/rpm```.

Thanks a lot!

**Comment by jeffweilee** [comment]
Although Clair decompresses image layers, but does Clair inspects the entire filesystem of a layer to scan the OS-level packages or Clair only inspect the default OS package repository, e.g. /var/lib/rpm/packages, which is actually not a thorough scan?
In other words, is Clair able to detect the vulnerability if I install an OS-level package binary manually instead from .rpm, .pkg, .dpkg under a customized path?

**Comment by KeyboardNerd** [comment]
No, it doesn't. Clair finds OS-level package managers that it can detect by inspecting files at specific locations. Pre-release version on master branch can find multiple package managers for a container.
