### ISSUE TITLE
Running Docker-Compose example results in connection error when booting clair image.

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#533]
**Description of Problem**:
Using docker-compose example on macOS results in connection error, when booting the container image.

I think this problem is related to #526. I'm trying to find the reason. 

**Repro Steps** :
Exactly the steps described in the [docker compose example](https://github.com/coreos/clair/blob/master/Documentation/running-clair.md#docker-compose)

**Expected Outcome**:

**Actual Outcome**:
`2018/03/23 06:16:22 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}`

**Environment**:
- Clair version/image: latest
- Clair client name/version: 
- Host OS: macOS
- Kernel (e.g. `uname -a`): Darwin Citrus.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
Other people are having the same problem as well: https://stackoverflow.com/questions/48694588/clair-startup-error-grpc-addrconn-resettransport-failed-to-create-client-transp

**Comment by KeyboardNerd** [comment]
I think the problem is related to IPV6 not enabled on container networking. Using docker run in the example works because networking is set to host networking, which in my case supports IPV6. We should find out a way to bind 0.0.0.0 only with IPV4 as a fallback.

**Comment by tipruzs** [comment]
same issue here. i tried to find a workaround using sysctl args during container launch, but this does not work. any hints available?

**Comment by alwaysbright** [comment]
Run into the same issue. Any workaround?

**Comment by jzelinskie** [comment]
This was fixed in #542. Create a new issue if this is not the case.
