### ISSUE TITLE
namespace unknown for features that exist

### ISSUE THREAD

**Issue by strantalis** [quay/clair#543]
**Description of Problem**:
I am noticing a lot of 422 responses in my clair logs that don't seem to add up and seem to be associated with clair not detecting the namespace. The images do get scanned but the 422 responses always seem to process slow and it just doesn't seem like there should be so many. 

For example the yum package.

Docker image does contain a valid /etc/redhat-release file. 
```
bash-4.2# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```
Logs below.(I added some custom logs trying to dig into this but haven't found anything)
```
{"Custom feature ":"yum","Event":"Custom","Level":"debug","Location":"worker.go:194","Time":"2018-04-20 05:31:33.627216"}
  | {"Event":"Namespace unknown","Level":"warning","Location":"worker.go:215","Time":"2018-04-20 05:31:33.627274","feature name":"yum","feature version":"3.4.3-158.el7","layer":"1d83828b-7dd7-46f8-a503-ee78ae22c2f3.e38bcb80-4ddf-45b3-9df9-6040786a219e9"}
  | {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2018-04-20 05:31:33.627628","elapsed time":24513986793,"method":"POST","remote addr":"[::1]:56270","request uri":"/v1/layers","status":"422"}
```
Results in postgres
```
clair=> select * from namespace;
 id |      name       | version_format
----+-----------------+----------------
  1 | centos:7        | rpm
  2 | debian:8        | dpkg
  3 | alpine:v3.5     | dpkg
  4 | debian:9        | dpkg
  5 | ubuntu:16.04    | dpkg
  6 | alpine:v3.4     | dpkg
  7 | alpine:v3.6     | dpkg
  8 | debian:unstable | dpkg
  9 | debian:10       | dpkg
 10 | debian:7        | dpkg
 11 | alpine:v3.3     | dpkg
 12 | alpine:v3.7     | dpkg
 13 | oracle:6        | rpm
 14 | oracle:5        | rpm
 15 | oracle:7        | rpm
 16 | ubuntu:14.04    | dpkg
 17 | ubuntu:12.04    | dpkg
 18 | ubuntu:13.04    | dpkg
 19 | ubuntu:15.04    | dpkg
 20 | ubuntu:16.10    | dpkg
 21 | ubuntu:15.10    | dpkg
 22 | ubuntu:12.10    | dpkg
 23 | ubuntu:17.10    | dpkg
 24 | ubuntu:17.04    | dpkg
 25 | ubuntu:14.10    | dpkg
 26 | centos:5        | rpm
 27 | centos:6        | rpm
 28 | alpine:v3.1     | dpkg
```
```
clair=> SELECT * FROM feature where name='yum';
  id   | namespace_id | name
-------+--------------+------
    83 |            1 | yum
  5875 |           10 | yum
  9075 |            2 | yum
  9960 |            4 | yum
 10349 |            9 | yum
 12292 |            8 | yum
 19504 |           23 | yum
 19344 |            5 | yum
 20995 |           16 | yum
 27157 |           27 | yum
 28120 |           15 | yum
(11 rows)
```
```
clair=> SELECT * FROM featureversion where feature_id=83;
  id  | feature_id |        version
------+------------+------------------------
 8932 |         83 | 3.4.3-158.el7
 7446 |         83 | 3.4.3-125.el7.centos
 5769 |         83 | 3.4.3-154.el7.centos.1
 2203 |         83 | 3.4.3-154.el7.centos
 2137 |         83 | 3.4.3-150.el7.centos
 1344 |         83 | 3.4.3-154.el7
   83 |         83 | 3.4.3-150.el7
(7 rows)
```
**Expected Outcome**:
I would expect clair to potentially return a 201 instead of a 422 for features that exist and are associated with a namespace. 

**Actual Outcome**:
Seems like the namespace isn't being detected properly or the feature isn't being associated with the namespace properly. I have also only noticed this for rhel/centos based images. 

**Environment**:
- Clair version/image: v2.0.2
- Kubernetes version (use `kubectl version`):  v1.7.6
- Helm version (use `helm version`): N/A
- Network/Firewall setup: N/A

**Comment by kanchwala-yusuf** [comment]
Hi,
I am facing a similar issue.

I have downloaded the individual layers of an image from the image manigest file and submitting it layer-by-layer to clair specifying the local filesystem paths. The Layer Name submitted to clair is "imagedigest + layerdigest".

And seeing the above mentioned ERROR for a few layaers on doing a post request to clair.


POST request to clair for one of the layers:
{"Layer": {"Name": "ca8a8cba89fe0cc58147bd2368fa93d5f1ea837817247613cd80fe017aadfbb565a7293804ac541b4e9fb51a61f31aba124f3f97a40712be982f7a3cdaa84426","Path": "/tmp/ca8a8cba89fe0cc58147bd2368fa93d5f1ea837817247613cd80fe017aadfbb565a7293804ac541b4e9fb51a61f31aba124f3f97a40712be982f7a3cdaa84426","Format": "Docker"}}

Response from clair:
{"Error":{"Message":"worker: OS and/or package manager are not supported"}}


In clair logs:
{"Event":"Namespace unknown","Level":"warning","Location":"worker.go:211","Time":"2018-05-10 08:08:19.719140","feature name":"xz-utils","feature version":"5.2.2-1.2","layer":"ca8a8cba89fe0cc58147bd2368fa93d5f1ea837817247613cd80fe017aadfbb565a7293804ac541b4e9fb51a61f31aba124f3f97a40712be982f7a3cdaa84426"}
{"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2018-05-10 08:08:19.719548","elapsed time":3042279502,"method":"POST","remote addr":"172.19.0.4:50110","request uri":"/v1/layers","status":"422"}

**Comment by jzelinskie** [comment]
Do either of you have an image that you can share that reproduces this issue?

**Comment by kanchwala-yusuf** [comment]
I was able to resolve this issue by specifying the parent layer in the Clair POST request.

**Comment by strantalis** [comment]
I don't have an image that I can share at this time. But some are built off of the following. 

[openjdk18-openshift](https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift)
[rhel7-atomic](https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/rhel7-atomic)

After very little digging the only place I could narrow it down to is [here](https://github.com/coreos/clair/blob/release-2.0/worker.go#L165). 

Could something be getting pulled from the database incorrectly because it seems like the feature versions do map to a namespace but for some reason that namespace isn't being mapped back correctly hence why it is hitting the following log statement. 

```log.WithFields(log.Fields{"feature name": feature.Feature.Name, "feature version": feature.Version, logLayerName: name}).Warning("Namespace unknown")```

**Comment by jzelinskie** [comment]
Potentially related to #511.

**Comment by superstator** [comment]
I am seeing this too, with some pretty common images from Docker Hub. If I just ignore the 422's and keep submitting layers it seems like it eventually works, though the number of features found seems suspiciously low. Have confirmed it with `nginx:1.15.2` and `redis:4.0.7-alpine` just to give two examples. I'm running `v2.0.8`.

**Comment by fxdgear** [comment]
I'm seeing this behavior on every version from 2.0.8-2.1.3

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
