### ISSUE TITLE
[CLOSED] Clair found 0 vuln even for vuln image

### ISSUE THREAD

**Issue by nicocolt** [quay/clair#544]
Hello all,

**Description of Problem**:
I try to analyze some known vulnerable image. Clair told me that there is no vuln is the image. Tried with more than one vuln image but always 0 vuln. I have check into the postgres database, and I see the vuln name that I want to look for.

**Expected Outcome**:
Clair should told me that image is vulnerable.

**Actual Outcome**:
Analysis [sha256:c5cf1] found 0 vulnerabilities

**Environment**:
- Clair version/image: quay.io/coreos/clair:latest
- Clair client name/version: jgsqware/clairctl:latest
- Host OS: Ubuntu 16.04 stretch/sid
- Kernel (e.g. `uname -a`): 4.4.0-119-generic x86_64
- Kubernetes version (use `kubectl version`): N/A
- Helm version (use `helm version`): N/A
- Network/Firewall setup: Direct connection to Internet

Thanks for your help
Nicolas

**Comment by nicocolt** [comment]
Clair took a lot of time to synchronize its database the first time. it works now.

Best.
Nicolas

**Comment by ishanVshah** [comment]
how much time it will take ? because i am facing same issue.
