### ISSUE TITLE
Add 'update reminding' feature

### ISSUE THREAD

**Issue by liangchenye** [quay/clair#55]
quay.io + Clair is really cool, but one thing is missing from a user's point of view: yes, my image is vulnerable, but is there an easy way to solve this?

To an OS user, we can always use 'apt-get update or zypper update' to keep our system as secure as possible. But to a container user, the scenario is different, most time we need another more secure image to replace the old one that was built months ago. So it would be user friendly if 'Clair' could neither tell the user:
   'rebuild your image with the same Dockfile (with 'apt-get update' inside), CVE A, CVE B would be solved. 
or 'update your image with another base image(from 14.04 to 15.04),  CVE A, CVE B, CVE C would be solved.
With the integration of quay.io, it is easy to get a more secure image.

I'm not sure if we can have this feature in the Clair roadmap.

**Comment by liangchenye** [comment]
We can keep track of the up to date repos of the supported distributions (for example: http://archive.ubuntu.com/ubuntu/dists/wily-updates) and make the 'update reminding' suggestion.

**Comment by Quentin-M** [comment]
Right.

So Clair is actually already aware if there is a package version that fixes a vulnerability (at least for the current operating system, see https://github.com/coreos/clair/blob/11475beb2caf7a5e70241c0516c82ed96a094453/docs/API.md#success-response-10). However, for now, it does not give any insight on how should we fix vulnerabilities. That is something that some people in the team want to see.

The new major version I am working on is intended to be much faster, more generic and more precise. It will hopefully help us to achieve that if we want to. One thing to note is that Clair is going to tell the vulnerabilities that each package adds to the image - and say if there is a version that fixes it. Yet I don't know about suggesting Dockerfile modifications.

I'll tell you more once I get further in the development on the new version. There're still a lot to do. If you want to be involved, don't hesitate to ping me (ie. on IRC).
