### ISSUE TITLE
Can't pull alpine-secdb repository

### ISSUE THREAD

**Issue by sylus** [quay/clair#556]
**Description of Problem**: Hi there!

I am using GitLab Auto Devops which makes use of Clair. However clair won't start due to:

```sh
{"Event":"could not pull alpine-secdb repository","Level":"error","Location":"alpine.go:186","Time":"2018-05-11 15:27:12.280273","error":"exit status 128","output":"Cloning into '.'...\nfatal: unable to access 'https://git.alpinelinux.org/cgit/alpine-secdb/': Failed to connect to git.alpinelinux.org port 443: Operation timed out\n"}
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:235","Time":"2018-05-11 15:27:12.280411","error":"could not download requested resource","updater name":"alpine"}
```

**Expected Outcome**: Clair boots up without error

**Actual Outcome**: Clair doesn't boot up properly

**Environment**:
- Clair version/image:  v2.0.1
- Clair client name/version:  v2.0.1
- Host OS: Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux 4.13.0-1016-azure #19-Ubuntu 
- Kubernetes version (use `kubectl version`): 1.9.5
- Helm version (use `helm version`): 2.8.2
- Network/Firewall setup: n/a

**Comment by sylus** [comment]
Nevermind is working now again!

**Comment by jeffweilee** [comment]
Hi @sylus , how the problem being solved? I encounter the same problem via **proxy**. It seems that **git** command does not access http_proxy environment variable during the process ...
I tried git config --global http.proxy, it works on terminal command: ```git clone https://https://git.alpinelinux.org/cgit/alpine-secdb```, but still not work on Clair ```alpine.go```:  

> Could not pull alpine-secdv repository. Failed to connect to git.alpinelinux.org port 443: Connection timed out``` via proxy.

Is there any solution of proxy setting for alpine CVE update (git clone) via proxy?
