### ISSUE TITLE
foreign key constraint violation uploading layers

### ISSUE THREAD

**Issue by djl197** [quay/clair#557]
**Description of Problem**:
I am attempting to scan a Centos based image,  We use a FROM centos:7.3 base image and then install custom RPMS on top of this.

I have attempted to use clair-scanner and klar to scan the images and in both cases I end up with errors.
The reported error from klar is
```
{"Error":{"Message":"database: an error occured when querying the backend"}}
Failed to analyze using API v1: push image https://gitlab.domain:4567/v2/container_name:clairfun-30 to Clair failed: push error 500: {"Error":{"Message":"database: an error occured when querying the backend"}}
Failed to analyze using API v3: push image https://gitlab.domain:4567/v2/container_name:clairfun-30 to Clair failed: rpc error: code = Unavailable desc = transport is closing
Failed to analyze, exiting
```
The clair instance reports the following
`{"Description":"insertLayer","Event":"Handled Database Error","Level":"error","Location":"pgsql.go:284","Time":"2018-05-15 20:20:24.598105","error":"pq: insert or update on table \"layer\" violates foreign key constraint \"layer_parent_id_fkey\""}`

Using clair-scanner I have observed the same issue and reported here:
https://github.com/arminc/clair-scanner/issues/45

Any idea what I can do to debug this further?

**Environment**:
I am doing this using Jenkins Pipeline running in Kubernetes.
It is a single Pod with a Jenkins-Slave container (including latest release of clair-scanner, klar, clairctl)
A second container running Docker In Docker
3rd Container running Clair V2.0.1 pointing to a DB
A single external DB is hosted and populated.

- Clair version/image: v2.0.1
- Clair client name/version: clair-scanner / clairctl / klar
- Host OS: N/A
- Kernel (e.g. `uname -a`): N/A 
- Kubernetes version (use `kubectl version`): 1.9

**Comment by jzelinskie** [comment]
Can you provide some details on the Postgres environment?
This is likely something I'll have to try and reproduce.
