### ISSUE TITLE
Dead link for API on Swaggerhub

### ISSUE THREAD

**Issue by LorensK** [quay/clair#564]
https://github.com/coreos/clair/blob/e907e4d263a743f7d4923c177e5db37f656a53b4/README.md#L34

Hi, README says to explore the API at https://app.swaggerhub.com/apis/coreos/clair/3.0 but that link is dead. Swaggerhub seems to know about Clair, knows a single 3.0 version of the API, but throws an "error processing the request" in a red box that I cannot copy-paste, and ends up saying "Sorry, we can't find coreos / clair / 3.0"

**Comment by jzelinskie** [comment]
Weird, it works for me?

<img width="1392" alt="screen shot 2018-07-05 at 9 30 01 pm" src="https://user-images.githubusercontent.com/343539/42355343-9c615d7c-809a-11e8-8a8e-7c4e0ac02dab.png">
