### ISSUE TITLE
Can't pull alpine-secdb git https repository via proxy: connection timed out

### ISSUE THREAD

**Issue by jeffweilee** [quay/clair#573]
**Description of Problem**:
Encounter problem fetching alpine CVE git repository via proxy.
 

> Could not pull alpine-secdv repository. Failed to connect to git.alpinelinux.org port 443: Connection timed out

I set environment parameter for proxy in docker-compose.yml. **The proxy setting works on Clair's oracle/rhel/debain CVE data update, but, unfortunately, the proxy does not work on alpine CVE repository update**. 

According to ```/ext/vulnsrc/alpine/alpine.go```, ```git clone https://https://git.alpinelinux.org/cgit/alpine-secdb``` is executed to fetch alpine CVE repository. **I wonder if the GIT command in ```alpine.go``` access proxy setting.**

What's weird is that, I tried to execute ```git config --global http.proxy [proxy_url]``` on host and container. In result, ```git clone https://https://git.alpinelinux.org/cgit/alpine-secdb``` works in terminal command line, but still not work for ```alpine.go`` where the error is still shown by Clair. 

Is there any solution of proxy setting for alpine CVE update (git clone) via proxy?

**Expected Outcome**:
Fetch alpine CVE w/o error

**Actual Outcome**:
Fetch alpine CVE w/ error: Failed to connect to git.alpinelinux.org port 443: Connection timed out

**Environment**:
- Clair version/image: v2.0.1
- Clair client name/version: v2.0.1
- Host OS: Centos7
- Kernel (e.g. `uname -a`): Linux 3.10.0-514.el7.x86_64 2016 x86_64 GNU/Linux
- Network/Firewall setup: http web proxy

**Comment by chaoticsmol** [comment]
I've had some success dealing with this by configuring Docker itself to use my proxy.

First, create an HTTP proxy configuration file.
```
hpc="/etc/systemd/system/docker.service.d/http-proxy.conf"
touch $hpc
echo "[Service]" >> $hpc
echo 'Environment="HTTP_PROXY=$HTTP_PROXY" "HTTPS_PROXY=$HTTP_PROXY" "http_proxy=$HTTP_PROXY" "https_proxy=$HTTP_PROXY" >> $hpc
```
(Where `$HTTP_PROXY` is your proxy URL).

Then restart Docker and Clair.

```
cd $CLAIR
docker-compose stop
systemctl stop docker
systemctl daemon-reload
systemctl start docker
docker-compose up
```
(Where `$CLAIR` is the directory you have clair's `docker-compose.yml` file)

Apologies if the above isn't quite accurate; I'm writing this from memory. Hope it helps.

**Comment by DooDleWilk** [comment]
This problem occurs only with Alpine, as the CVEs list is provided by git repo, where the others use different mechanisms.
git does not handle proxies by default, and must be configured accordingly using:
```git config --global http.proxy http://<username>:<password>@<proxy-server-url>:<port>```
