### ISSUE TITLE
Does Clair only work packages which are managed by common package managers?

### ISSUE THREAD

**Issue by coolljt0725** [quay/clair#58]
As we all know, `Clair` take the advantage of the common package manager to detect vulnerabilities, for now it support `rpm` and `dpkg`. Does it mean if user install an application in an image not by the common package manager, the `Clair` can't detect it?

**Comment by Quentin-M** [comment]
See #10.

The new database implementation and generalization of Clair I am working on (#54), as discussed off the records with liangchenye will make it way easier to manage. We will be able to do it in just an hour from that.

**Comment by Quentin-M** [comment]
Updating this question. As Clair v1.0+ is built as a framework, anyone can implement and integrate custom detectors and vulnerability databases that they may need. There is no dependency on packages, our defaults just happen to use them.
