### ISSUE TITLE
No Vulnerabilities loaded into database

### ISSUE THREAD

**Issue by ginsburgnm** [quay/clair#583]
**Description of Problem**:
The Updater is periodically running, (I see "updated finished" in the logs roughly every 2 hours) however there are no values populated into the vulnerability table. I was able to (through clair) push information into the ancestry, and layer tables (and probably a couple others), so I know that clair is able to insert data into the database just fine. I also pinged googled from inside the container that clair is running in, so outbound connections also seem fine.

For clarity's sake, I am running this in a local docker image. 
I guess the answer might lie there, where exactly do these vulnerabilities load in from?

**Expected Outcome**:
Vulnerabilities loaded into the vulnerability table after the updater runs

**Actual Outcome**:
Vulnerability table still empty.

**Environment**:
- Clair version/image: quay.io/coreos/clair-git:latest (created 2 days ago)
- Clair client name/version: 
- Host OS: Ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`): N/A
- Helm version (use `helm version`): N/A
- Network/Firewall setup:

**Comment by MackJM** [comment]
Do you have a database running locally? What I've done in the past to make sure that vulnerabilities are being populated, is docker exec on the db, then either dump the db or just look at it. 

This is how I dump the db:
`docker exec $(docker ps -q -f label=app:clairdb) pg_dump -U postgres --format=c --file=/tmp/postgres.sqlc vulnerabilitydb`

**Comment by ginsburgnm** [comment]
Operator error, The container was just formatting the output of my select statement in an unreasonable manner (pages, like I just held "d" for like a minute before I saw anything, of whitespace between the header and the first record). Closing the issue.
