### ISSUE TITLE
qcow2 image format

### ISSUE THREAD

**Issue by Patazerty** [quay/clair#584]
**Description of Problem**:

Clair is very useful with container environments, but it would be even better if it could be used at the infrastructure level (primarily Openstack). 

**Expected Outcome**:

Instead of pulling container images from a registry and scan every layer, clair could download qcow images from openstack / glance and scan every partition. A simple client can connect to openstack and retrieve the necessary authorization header + url of the image and send it to clair. I've successfully implemented an [experimental support](https://github.com/Patazerty/clair/blob/qcow-imagefmt/ext/imagefmt/qcow/qcow.go) for qcow images using the fuse-base qcowmount tool from [libqcow](https://github.com/libyal/libqcow) + fdisk to find and mount the different partitions to scan. This is not ideal as it requires the container running clair to be privileged to mount loop devices, the loop kernel module to be loaded on the host and there is a limit of loop devices (256 I believe).

**Actual Outcome**:

No support for qcow images 

**Environment**:
N/A

**Comment by jzelinskie** [comment]
Is the only way to deal work with qcow to mount a fuse filesystem?
I consider this a dealbreaker if we have to run the container as privileged to support this behavior.

**Comment by Patazerty** [comment]
There's libguestfs (launch a vm just to mount the qcow image), qemu-nbd  (exposes the qcow image as a network block device, requires the nbd kernel module and still needs mount privileges), and qcowmount that uses FUSE to expose a block device that still needs to be mounted somewhere. Maybe with unprivileged mounts / user namespaces this could work in a non-privileged container, but it's not possible (yet). 

Edit: I just found out about [lkl](https://github.com/lkl/linux), and tested the `lklfuse` tool that can mount kernel-implemented partitions with fuse, it works great. I'll implement `lklfuse` instead of a privileged `mount` in clair to see if unprivileged mounts can be acheived.

**Comment by jzelinskie** [comment]
Ideally we don't have to mount anything, rather, we could just parse the image using something like [zchee's qcow2 library](https://github.com/zchee/go-qcow2). It appears that their library doesn't implement reading though, so a good path forward might be to investigate how much of a gap is there for making that library useful before resorting to mounting the image (in userspace or not).

**Comment by Patazerty** [comment]
I agree it would be ideal to not use fuse, it would however require to extract/copy the entire partition contents which _could_ cause slow scans and a bigger io usage, but this solution would be more easy to use / plug and play. If I can replace qcowmount with something that does not need fuse (zchee's lib maybe ?), cpfromfs ot fs2tar utils from lkl would allow access to partitions contents without the need to mount anything.

In the meantime I successfully implemented lklfuse instead of a system mount for qcow scans and tested it in a unprivileged user-namespaced docker container: it works just fine.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!

**Comment by hdonnay** [comment]
Please open a new issue if you'd like us to consider a feature.

The biggest issue I see off the bat is needing some way to read qcow2 images in a unprivileged container, ideally in-process.

**Comment by fabiand** [comment]
There are tools to read qcow2 in user-space.
One issue is: qcow2 is a block device, and there is an fs within.

Now, there are a range of tools that tackle the different parts
https://libguestfs.org/nbdfuse.1.html
https://www.libguestfs.org/guestmount.1.html
or guestfish itself.

@hdonnay what do you need from the image? a file-system tree, access to files, rpm db, …?

**Comment by hdonnay** [comment]
We'd need some way to present an [`fs.FS`](https://pkg.go.dev/io/fs#FS) in code.
