### ISSUE TITLE
Vulnerabilities for Node Upstream dependencies

### ISSUE THREAD

**Issue by krishnapaparaju** [quay/clair#590]
**Description of Problem**:

Clair needs integration with a vulnerability database to display vulnerabilities for Node  upstream dependencies. CVE IDs are mapped from NVD to specific Node dependencies, this work is tracked [here](https://github.com/fabric8-analytics/cvejob).

**Expected Outcome**:

Integrate with OpenShift.IO AI platform as another 'Vulnerability Metadata source' to track upstream vulnerability metadata for Node dependencies.

1) Get a OpenShift.IO API token under 'profile' section  (Require registration at [OpenShift.IO](openshift.io))
2) Find any vulnerabilities for a Node application dependency
      _curl -k -H "Authorization: Bearer $token" 
      https://recommender.api.openshift.io/api/v1/component-analyses/npm/dependency-name/version_
      (For NPM dependency serve-static:1.7.1, check out [API response](https://gist.github.com/krishnapaparaju/63acd092642d97110a9bdaaca6ea9134) showing associated vulnerabilities)

**Actual Outcome**:
Currently scanning does not cover vulnerabilities for Node upstream dependencies.

**Environment**:
NA

**Comment by jzelinskie** [comment]
So far, Clair has only supported vulnerability sources from official sources for the given namespace. For example, Node should probably use the same API as `npm audit`. I'm also hesitant to add any vulnerability sources gated behind API keys.

I think this is a reasonable thing to implement, but I'm not sure it makes sense to upstream.
