### ISSUE TITLE
Alpine GIT issues

### ISSUE THREAD

**Issue by sweharris** [quay/clair#593]
CLAIR 2.0.4

    {"Event":"could not pull alpine-secdb repository","Level":"error","Location":"alpine.go:186","Time":"2018-08-22 20:15:16.252686","error":"exit status 128","output":"Cloning into '.'...\nfatal: unable to update url base from redirection:\nasked for: https://git.alpinelinux.org/cgit/alpine-secdb/info/refs?service=git-upload-pack\n   redirect: https://github.com/alpinelinux/alpine-secdb\n"}

    {"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:235","Time":"2018-08-22 20:15:16.252762","error":"could not download requested resource","updater name":"alpine"}

And git-http processes hang around in zombies.

It looks like the Alpine git repo has moved to github so URLs will need updating

**Comment by KeyboardNerd** [comment]
hmm actually do we @jzelinskie want to move those vuln data source URLs into a configuration file? It'll then be easier to deal with this kind of stuff.

**Comment by clandmeter** [comment]
I have redirected the repository to GitHub as something was hammering our cgit instance (we didn't know what) using all its horsepower. From my logs it was doing average 35 req/sec from different locations. I am not sure if you have so many users using this scanner or there is something wrong with this program.

If you can periodically clone the URL to your own infrastructure and point to this new location that would be good for us. Or even better, join this information into a single json file and let the scanner use that instead.

**Comment by ncopa** [comment]
you can also use https://github.com/alpinelinux/alpine-secdb

**Comment by jmbradshaw79** [comment]
@ncopa and @clandmeter I agree that an alternate endpoint should be used, as this is a taxing load on Alpine Linux infrastructure. Until this change has been pushed, could you make a small adjustment to the 301 configuration to not redirect everything to the root https://github.com/alpinelinux/alpine-secdb/ but instead include the paths and the query string? This should keep the load off your git servers while the endpoint changes propagate but not break current running applications. Something like, `rewrite ^/cgit/alpine-secdb/(.*?)/?$ https://github.com/alpinelinux/alpine-secdb/$1 permanent;` will enable most git clients to clone as before.

**Comment by shoeper** [comment]
@KeyboardNerd moving the vuln data sources to a config file is a very good thing, as it makes fixing such issues very easy.

**Comment by MackJM** [comment]
I should have PR for that shortly... If all goes well. Just testing it now.

**Comment by MackJM** [comment]
Here's my PR https://github.com/coreos/clair/pull/597

**Comment by tbhu** [comment]
it is too difficult

**Comment by ChrisCavegn** [comment]
Should this issue be fixed in quay.io/coreos/clair:latest?

I just upgraded to this Docker Image and got exactly the same error message.

**Comment by usr42** [comment]
There is no new release yet, so, it is also not fixed in latest.
When is a new release planed?

**Comment by jzelinskie** [comment]
The v2.0.5 release should have fixed this.
