### ISSUE TITLE
Clair does not support multiple architectures

### ISSUE THREAD

**Issue by jzelinskie** [quay/clair#608]
**Problem:**
Right now Clair works under the assumption that all of the images are x86. As of Docker-v2-2/OCI, this assumption isn't correct about all images.

**Steps forward:**
* Vulnerability Sources (vulnsrc) and Vulnerability Metadata Sources (vulnmdsrc) need to be audited and fixed to parse architectures as well.
* There likely needs to be new columns added to the database to include architecture information. This will obviously also change a few queries.
* The API for posting an Ancestry will need to be updated to include architecture information.

This issue is semi-related to #545

**Comment by KeyboardNerd** [comment]
will the package metadata file contain this info?

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
