### ISSUE TITLE
Failure of updater in first update will generate excessive requests to all remote vulnsrc URLs

### ISSUE THREAD

**Issue by reasonerjt** [quay/clair#616]
**Environment**:
- Clair version/image:  v2.0.x

**Description of Problem**:
In Clair v2, if any of the updaters fail in **_firsts update_**, after 1 minute of sleep all updaters will run again, this may generate excessive requests if one of the updater fails due to remote problem or misconfiguration, and may look like a DoS attack.  See https://github.com/coreos/clair/issues/596#issuecomment-417150931 and https://github.com/coreos/clair/issues/593#issuecomment-415320283 

An easy way to mitigate this is to extend the sleep duration upon failure.
I have a PR submitted against `v2` branch #615

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
