### ISSUE TITLE
Proxy configuration for update sites but not for docker registry?

### ISSUE THREAD

**Issue by ChrisCavegn** [quay/clair#618]
**Description of Problem**:

I try to run clair in a 'secure' company network behind a proxy & firewall.
To access the different update sites, clair needs to go through a http/https proxy.
We run our own docker registry inside our company network - it isn't required/currently not possible to go through the proxy

**Expected Outcome**:

I need to be able to configure a proxy for the connections to the update sites but not for the docker registry.

**Actual Outcome**:

If I configure a proxy, clair is able to connect to the update sites but not to our docker registry.
If I don't configure a proxy, clair is able to connect to our docker registry but not to the update sites.

**Environment**:
- Clair version/image: 2.0.5
- Clair client name/version: klar 2.1.0
- Host OS: RHEL 7.5
- Kernel (e.g. `uname -a`): 3.10.0
- Kubernetes version (use `kubectl version`): 1.11.2
- Helm version (use `helm version`): not installed by helm
- Network/Firewall setup: see provided description - more information required?

**Comment by MackJM** [comment]
I haven't tested this, but I have you tried setting `NO_PROXY` in the dockerfile?

**Comment by ChrisCavegn** [comment]
Ahhh, sometimes it's that simple
(We defined NO_PROXY as ENV Variable in the deployment.yaml and not in the Dockerfile, but thats the same thing)

Thank you, i'll close the issue.
