### ISSUE TITLE
NVD meta errors

### ISSUE THREAD

**Issue by ekristen** [quay/clair#622]
**Description of Problem**:

Possibly not downloading and installing NVD data? 

```invalid .meta file format```

**Environment**:
- Clair version/image: 2.0.5

**Comment by jzelinskie** [comment]
This is a known issue that's already fixed, but we have yet to cut a release. Expect it in the next day or so.

Sorry about the inconvenience.

**Comment by jzelinskie** [comment]
I just cut v2.0.6.
