### ISSUE TITLE
clair not installed

### ISSUE THREAD

**Issue by leeadh** [quay/clair#623]
guys, 

Failed to analyze using API v1: push image https://registry-1.docker.io/v2/library/postgres:9.5.1 to Clair failed: can't push layer to Clair: Post http://nodeip:6060/v1/layers: dial tcp 129.213.45.45:6060: connectex: No connection could be made because the target machine actively refused it.

I tried to deploy to my k8 cluster and when i do a kuebctl get pods, nothing returns. Can anyone help please?

**Comment by KeyboardNerd** [comment]
there are so many possibilities, please elaborate on all the steps you followed to start Clair in a k8s cluster and follow the issue guideline.
