### ISSUE TITLE
Optimize RHEL OVAL updates with PULP_MANIFEST

### ISSUE THREAD

**Issue by jzelinskie** [quay/clair#625]
### Feature Request
RHEL OVAL updates have a file, PULP_MANIFEST, that tracks changes. This could be used to optimize RHEL updates.

### Environment
N/A

**Comment by jzelinskie** [comment]
cc @sochotnicky

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
