### ISSUE TITLE
Postgres disk usage?

### ISSUE THREAD

**Issue by leonboot** [quay/clair#628]
### Description of Problem
Postgres runs out of disk in no time. What's the average volume of database transactions that Clair performs? Does it store the vulnerability database in Postgres? How many records are added for each scan of an image? Postgres uses Write Ahead Logs, which, to the best of my knowledge, contain all transactions ever performed on the database. So these logs will gradually consume space over time which can never be reclaimed. When running Harbor with Clair on Kubernetes using Harbor's official Helm chart, a 1GB persistent volume is being assigned to the database service by default. We ran out of disk space here with Harbor containing around a total of 250 image tags for 5 different images. Half of the disk space was consumed by the WAL files.

If the volume of database transactions is not that high, increasing the volume size should do the trick. But if the volume of transactions performed by Clair causes these log files to grow by, let's say, 5GB per week, you'd end up with a 260GB yearly increase of filesystem usage for WAL files alone.

So, what can be expected in terms of disk usage over time? Is Postgres the right tool for the job if Clair performs a lot of transactions? I'm not sure having a full transaction history for a vulnerability database is useful. Or is there another way to reduce this overhead?

### Environment

- Clair version/image: not sure, built by the Harbor Helm chart
- Clair client name/version: not sure, built by the Harbor Helm chart
- Host OS: CoreOS
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 1.9.3
- Helm version (use `helm version`): 2.9.1
- Network/Firewall setup:

**Comment by reasonerjt** [comment]
@leonboot 
Could you open an issue in https://github.com/goharbor/harbor-helm

**Comment by leonboot** [comment]
@reasonerjt sure, but I was wondering whether actually suggesting a larger volume for Postgres in the Helm chart would make sense. If Clair creates a high volume of Postgres transactions, the Write Ahead Logs of Postgres will grow at such a rate that even assigning 500GB might only get you so far.

**Comment by gyoho** [comment]
Just curious where does Clair save the docker layer for scan by POST request?

**Comment by KeyboardNerd** [comment]
in memory

**Comment by jzelinskie** [comment]
The Helm chart we maintain [starts with 10Gi persistence](https://github.com/coreos/clair/blob/504f0f3af302daa4c071a775d00f1634d57464d1/contrib/helm/clair/values.yaml#L76), but that's only for small installations. 1Gi seems far too low for anything for Harbor usage other than demos. I recommend playing things by ear, but you should only ever need a few hundred gigabytes for even the largest installations.
