### ISSUE TITLE
All images are safe !!

### ISSUE THREAD

**Issue by PasqualePuzio** [quay/clair#63]
Hi,

I'm testing Clair on a local machine. In particular, I'm trying to find vulnerabilities in my own images using the "analyze-local-images" script.
However, I can't find a vulnerable image that is recognized by this script. I also downloaded some images that are to vulnerable to OpenSSL heart bleed but according to Clair they are safe.

Am I missing something? Am I doing something wrong?

Could you please point out a few images in which Clair will find vulnerabilities?

Thanks

**Comment by Quentin-M** [comment]
Hi,

#5 and #57 may be relevant.

**Comment by PasqualePuzio** [comment]
Thank you very much for the quick reply.

I tested the script with aerospike 3.7.0.2 but I'm still getting the same result: Bravo, your image looks SAFE !

Should I launch the updater before running the script? Or does Clair already contain some default definitions?

Thanks

**Comment by Quentin-M** [comment]
The updater must runs first. The logs will tell you when the update is finished.

**Comment by lfshr** [comment]
@Quentin-M should clair not fail all requests if the uploader has not successfully run?
