### ISSUE TITLE
Implement rfc/deb822 parser

### ISSUE THREAD

**Issue by jzelinskie** [quay/clair#637]
### Description of Problem / Feature Request

We have a pretty error-prone implementation for parsing Ubuntu CVEs and dpkg databases. We should clean it up and build a proper parsing library for this format.

[RFC](https://www.w3.org/Protocols/rfc822/)
[Python implementation](https://github.com/romlok/python-debian/blob/master/lib/debian/deb822.py) 

### Environment

N/A

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
