### ISSUE TITLE
Presentation links are broken

### ISSUE THREAD

**Issue by CsatariGergely** [quay/clair#642]
### Description of Problem / Feature Request

The links to the presentations in https://github.com/coreos/clair/blob/master/Documentation/presentations.md are broken.

### Expected Outcome

The links to the presentations in https://github.com/coreos/clair/blob/master/Documentation/presentations.md are not broken.

### Actual Outcome

The links to the presentations in https://github.com/coreos/clair/blob/master/Documentation/presentations.md are broken.

### Environment

N/A

**Comment by jzelinskie** [comment]
duplicate of #560
