### ISSUE TITLE
updates the vulnerability database manually by API

### ISSUE THREAD

**Issue by cd1989** [quay/clair#649]
### Description of Problem / Feature Request

Want an API to updates the vulnerability database manually?

### Environment

- Clair version/image: 
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
Please look at release-2.0 branch

**Comment by cd1989** [comment]
@KeyboardNerd Sorry, I still didn't find API for updating vulnerability database.

**Comment by KeyboardNerd** [comment]
https://github.com/coreos/clair/blob/release-2.0/Documentation/api_v1.md#put-namespacesnsnamevulnerabilitiesvulnname

If you look little bit closer to documentation folder.

**Comment by cd1989** [comment]
There may be misunderstanding between us, I'm looking for API to update the whole vulnerability database.

The same work done by:

```
// Start updater
st.Begin()
go clair.RunUpdater(config.Updater, db, st)
```

**Comment by KeyboardNerd** [comment]
If you mean to call an API to trigger all updaters to run, there's no existing plan to do that.
