### ISSUE TITLE
swagger /ancestry/{ancestry_name} with_vulnerabilities 

### ISSUE THREAD

**Issue by yukiman76** [quay/clair#651]
Using the API V3 trying to get the vulnerabilities from a given scanned image 
it looks like the with_vulnerabilities parameter  is not respected 

ref swagger spec
https://app.swaggerhub.com/apis/coreos/clair/3.0#/AncestryService/GetAncestry

Expecting a list of vulnerabilities  for a given image, only getting list of 
- Clair version/image:  Latest (using Helm)
- Clair client name/version:  yebinama/paclair
- Host OS: docker ubuntu
- Kernel (e.g. `uname -a`): 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`):  GitVersion:"v1.11.2"
- Helm version (use `helm version`): 
- Network/Firewall setup:  N/A (test open)

**Comment by KeyboardNerd** [comment]
We don't respect that any more to simplify the API.
The swagger file on swagger hub is not updated. @jzelinskie
The V3 API is still unstable.

**Comment by yukiman76** [comment]
how do i get a list of vulnerabilities currently with V3

**Comment by KeyboardNerd** [comment]
By API definition, it should directly give the vulnerabilities. 

BTW, the master branch is now in half broken state, If you want to try out the API V3, you need commit on or short before:
8d5a0131c48d0812d1dd53b1af8e24ae4e51c4ba

**Comment by yukiman76** [comment]
ok, will stick with V2 for now then

**Comment by yukiman76** [comment]
Thanks for the help
