### ISSUE TITLE
docker version problem

### ISSUE THREAD

**Issue by bestkillua** [quay/clair#652]
### Description of Problem / Feature Request

I am using docker 1.10.3,clair 2.0.1,when i scan image,it will occurs error : {"Event":"failed to extract data from path"},but when i upgrade to 17.03.2,it works,why?

### Environment

- Clair version/image: 2.0.1
- Clair client name/version: 
- Host OS: ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.111-1.el7.elrepo.x86_64
- Kubernetes version (use `kubectl version`): 1.9.2
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
What's the logged error? And how did you use the docker client? 
This error indicates either the layer blob is failed to be downloaded or the layer blob format is not supported.

**Comment by bestkillua** [comment]
@KeyboardNerd thanks a lot,it was the reason of old docker version.
