### ISSUE TITLE
Make helm chart available in a Helm Repo

### ISSUE THREAD

**Issue by faraazkhan** [quay/clair#654]
### Description of Problem / Feature Request

Currently the clair chart is only available in a sub directory in this repo, this makes installing the chart more work that it really should be. It would be really nice to either contribute the chart to https://github.com/helm/charts or just push the chart with each release to a quay.io chart repository. 
### Expected Outcome

The official helm chart is available via a proper helm repository
### Actual Outcome

The chart is unavailable via any standard helm repo
### Environment

- Clair version/image: 
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by jzelinskie** [comment]
I think this is a reasonable request, but I'd prefer to only do this after we've cut a stable release of v3.

**Comment by jklare** [comment]
I think it would still be very helpful to push the helm chart in this repo to the official helm charts repo. Any new on this side? Maybe it would be a good idea to push the current version to the "testing" folder for helm charts to get some feedback from the community and more hands on it. After this testing phase, it should be possible to align the v3 release and the move to "stable" helm charts.

**Comment by jemag** [comment]
An official Helm chart of Clair would definitely makes things easier to get started with clair and promote its adoption. 

I know multiple individuals who simply went the way of Anchorage over Clair, for the sole fact that they had an official helm chart in the helm/charts repo.

@jzelinskie Given that this issue has been open for 1 year and that v3 might not be coming for a while, I think it would be beneficial to have the helm chart with the current version.

**Comment by jeff-knurek** [comment]
After related discussions during the Helm Summit about hosting charts  https://helmsummit2019.sched.com/event/S8tT/get-your-helm-charts-out-there-reinhard-nagele-codecentric-ag
I think it's actually better if the chart is hosted by CoreOS and listed in https://hub.helm.sh

----
I'd be happy to help contribute with this approach, but it would need some decisions from CoreOS on how to proceed with hosting the chart.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
