### ISSUE TITLE
Postgresql got updated and helm's chart for clair is not running with that new version

### ISSUE THREAD

**Issue by agboiza** [quay/clair#655]
### Description of Problem / Feature Request
Hi,

we are using clair with postgresql, but because postgresql has a new version, we are not able to start clair.
We noticed the error when we saw that the configmap generated for the postgresql previously, was called "clair-postgresql" and now it is called "clair-postgresql-init-scripts.

### Expected Outcome

We expected getting clair running with postgresql.

### Actual Outcome

Clair is not running.

### Environment

- Kubernetes version (use `kubectl version`): 1.9
- Helm version (use `helm version`): 2.11.0

**Comment by NiklasKnoll** [comment]
I am facing the same Issue! I tried to install Clair in my Cluster.
After the startup of the Database i get the following errors:
`` ERROR:  column "parent_id" does not exist
STATEMENT:  CREATE INDEX ON Layer (parent_id); ``

My Clair Pods shows these logs:
``{"Event":"running` database migrations","Level":"info","Location":"pgsql.go:216","Time":"2019-02-07 11:54:51.740184"}
{"Event":"pgsql: an error occured while running migrations: migration 2 failed: pq: column \"parent_id\" does not exist","Level":"fatal","Location":"main.go:96","Time":"2019-02-07 11:54:51.748945"} ``

I am using the helm chart from the master branch. I changed the clair image from clair-git:latest to clair:latest

**Comment by poojatr** [comment]
@NiklasKnoll hey which postgres version are you using?

**Comment by pradeepn-altran** [comment]
I tried installing Clair via Helm release.  I just used the default configuration that came with the Helm Release package. Not sure if I have to do anything. The configuration indicated postgresql user/password to be clair/clair. 
Thanks in advance for any pointers. Has anyone had experience deploying the Helm Package of Clair from
banzaicloud-stable - clair ?

Version 
```
CHART VERSION
0.1.1
DETAILS & LINKS
Type Helm Chart
Published March 25, 2019
```
The postgresql container shows error such as : 
```
DETAIL: Role "clair" does not exist. Connection matched pg_hba.conf line 1
FATAL: password authentication failed for user "clair" kubernetes.pod:
```

**Comment by sixsax** [comment]
@pradeepn-altran 

Claim helm chart "clair-0.1.1" comes with postgres installation but neither the "clair" user nor "clair" database will be created. So you have to login into postgres pod in order to create the "clair" user and "clair" database. Keep in mind, in the clair configmap the postgres connection string has user "clair" with password "clair".

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
