### ISSUE TITLE
[Question] - Ubuntu Cosmic Support - Target release timeline.

### ISSUE THREAD

**Issue by subash-canapathy** [quay/clair#660]
### Description of Problem / Feature Request

We are using clair for static scans of containers and we are seeing that it does a no-op/false-positive for Ubuntu 18.10 images as its not yet a supported namespace.
I am creating this ticket as a question to ask about the planned timeline of the next release (as the fix to support cosmic is already merged in)

### Expected Outcome

Target date for next release to avail the support for Ubuntu cosmic based images.

### Actual Outcome

Not sure when release will be cut

### Environment

- Clair version/image: 2.0.6
- Clair client name/version: 2.0.6 (v2 api) 
- Host OS: Amazon ECS / Ubuntu Cosmic base layer from dockerhub
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): NA
- Helm version (use `helm version`): NA
- Network/Firewall setup: NA

**Comment by subash-canapathy** [comment]
Commit link for cosmic image support 
https://github.com/coreos/clair/pull/650

**Comment by jzelinskie** [comment]
I cut a stable release today (v2.0.7) that contains a fix for this.
