### ISSUE TITLE
Amazon Linux

### ISSUE THREAD

**Issue by subash-canapathy** [quay/clair#662]
### Description of Problem / Feature Request

Clair returns no CVEs for amazonlinux:latest image whereas the image has several packages that has open CVEs. The layer output json detects the namespace and packages but possibly not looking up any CVE db to pull CVEs associated.

https://alas.aws.amazon.com/ - Amazon linux security center
AL:AmazonLinux CVE feed: https://alas.aws.amazon.com/alas.rss
AL2:AmazonLinux2 CVE feed: https://alas.aws.amazon.com/AL2/alas.rss

### Expected Outcome

Clair layer output for amazonlinux:latest has CVE info for packages

eg:

```json
{
    "Name": "file-libs",
    "NamespaceName": "amzn:2",
    "VersionFormat": "rpm",
    "Version": "5.11-33.amzn2.0.2",
    "Vulnerabilities": [
        {
            "Name": "ALAS-2017-900",
            "NamespaceName": "amzn:2",
            "Description": "An issue in file allowed an attacker to overwrite a fixed 20-byte stack buffer with a specially crafted .notes section in an ELF binary.",
            "Link": "https://alas.aws.amazon.com/ALAS-2017-900.html",
            "Severity": "High",
            "Metadata": {
                "NVD": {
                    "CVSSv3": {
                        "Score": 7.5,
                        "Vectors": "AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H"
                    }
                }
            }
        }
    ],
    "AddedBy": "sha256:20ccd029c3cdf66ab978c749b834432d7ffe74e40c6fb142e6bbcdaf420264fa_98f39d7a-ca98-4825-a465-e5c90fbb0e93"
}
```

### Actual Outcome

Clair layer output does not contain any CVE info 

eg:

```json
{
  "Name": "file-libs",
  "NamespaceName": "amzn:2",
  "VersionFormat": "rpm",
  "Version": "5.11-33.amzn2.0.2",
  "AddedBy": "sha256:20ccd029c3cdf66ab978c749b834432d7ffe74e40c6fb142e6bbcdaf420264fa_98f39d7a-ca98-4825-a465-e5c90fbb0e93"
}
```

### Environment

- Clair version/image: 2.0.6
- Clair client name/version: running Clair through CLI (exec /clair -config=/config/config.yaml)
- Host OS: AmazonLinux
- Kernel (e.g. `uname -a`): NA
- Kubernetes version (use `kubectl version`): NA
- Helm version (use `helm version`): NA
- Network/Firewall setup: NA

**Comment by tomdee** [comment]
I'm interested in this too, mainly just the part about pulling in the list of package vulnerabilities. Would anyone be interested in collaborating? I'd be looking for help with the OS detection part and testing?

**Comment by subash-canapathy** [comment]
i think the OS detection is happening correctly already. if you look at the layer output JSON the namespace and packages are there already. Only CVE lookup is missing.
The data for the CVEs by package name is on the RSS feed links

**Comment by jzelinskie** [comment]
We are detecting the namespace for Amazon Linux already. I didn't know that this vulnerability database existed. It looks like a good fit!

**Comment by jzelinskie** [comment]
We are detecting the namespace for Amazon Linux already. I didn't know that this vulnerability database existed. It looks like a good fit!

**Comment by tomdee** [comment]
The rss feed is missing package versions though, so I don't think it can be used.

**Comment by ericysim** [comment]
Hi, I didn't see this issue/conversation before, but here's a pull request: https://github.com/coreos/clair/pull/671

**Comment by subash-canapathy** [comment]
Can any write-access enabled reviewers bless the above pull request please. 
https://github.com/coreos/clair/pull/671

**Comment by subash-canapathy** [comment]
@jzelinskie @tomdee  - https://github.com/coreos/clair/pull/671 needs review

**Comment by nunofernandes** [comment]
I'm also in need of this.. Using amazon linux container images and would like to scan them.

Thanks,

**Comment by jtoberon** [comment]
https://github.com/coreos/clair/pull/671 was merged. Can this issue be closed?

**Comment by jzelinskie** [comment]
Yup! Thanks for the ping.
