### ISSUE TITLE
Issue in posting layers

### ISSUE THREAD

**Issue by AshishVerma7690** [quay/clair#663]
I am trying to post layers using api but everytime I am  getting error **{"Error":{"Message":"could not find layer"}}**
 It is working when using analyze-local-image
### Expected Outcome
Layer should be created

POST API : 
**curl -X POST -d '{ "Layer": {"Name": "1a5493c75df198fa201a4cda88bbc1c8de7cbaf09ccf49c62ee615239d0bcedc", "Path": "file:///{PATH}/1a5493c75df198fa201a4cda88bbc1c8de7cbaf09ccf49c62ee615239d0bcedc/layer.tar","Format": "Docker"}}' http://localhost:6060/v1/layers
The path is   /root/my_dir/ which contains : 
manifest.json
1a5493c75df198fa201a4cda88bbc1c8de7cbaf09ccf49c62ee615239d0bcedc/
3df5b4237cf08921d4aad69601c3f0ad34c7f583d3775a4c945e5098b908c313
3e6d62a6fe93da696c3048990dc0d57f893f0a26add30a733a0975d93f032f36
5a011cc51ed3ee38454e0249ecfffa78143bab5c20114c4a14f7e3022a97adf2

and every layer contains : json  layer.tar  VERSION

Do we need to change the path ?

**
### Actual Outcome
{"Error":{"Message":"could not find layer"}}

- Clair version/image:  Latest
- Host OS: Ubuntu

**Comment by KeyboardNerd** [comment]
Is this really Latest? latest API doesn't support `layers` any more.
If it's `release-2.0`, this error can happen when the path can't be opened by os.Open function.

**Comment by AshishVerma7690** [comment]
Now I am on clair-V2.0.0 . While posting the layer I a m still getting error  {"Error":{"Message":"could not find layer"}}

Clair_log  :  `clair_clair | {"Event":"failed to extract data from path","Level":"error","Location":"worker.go:122","Time":"2018-11-29 04:54:35.073116","error":"could not find layer","layer":"9b7c4fbac83843a7affe3edba55ef96b71ca8c0d3c282e40910e3638f97151f7","path":"file:////root/go/src/github.com/Ashish/9b7c4fbac83843a7affe3edba55ef96b71ca8c0d3c282e40910e3638f97151f7/layer.tar"}
`
 when I am trying to open the file on browser using `file:////root/go/src/github.com/Ashish/9b7c4fbac83843a7affe3edba55ef96b71ca8c0d3c282e40910e3638f97151f7/layer.tar`
 It directly  gives option to save/extract the layer.tar.

**Comment by AshishVerma7690** [comment]
Trying with Clair latest  While posting the layer I a m still getting error{"error":"ancestry is failed to be processed: [0] could not find layer from given path","code":13}

clair log : `clair_clair | {"Event":"failed to extract data from path","Level":"error","Location":"worker.go:415","Time":"2018-11-30 05:21:21.362256","error":"could not find layer from given path","layer":"SHA256","path":"file:///root/Ashish/1a5493c75df198fa201a4cda88bbc1c8de7cbaf09ccf49c62ee615239d0bcedc/layer.tar"}`
