### ISSUE TITLE
Video and Slide links in presentations are dead

### ISSUE THREAD

**Issue by SuperSandro2000** [quay/clair#665]
All the video and slide links in [Documentation/presentations.md](https://github.com/coreos/clair/blob/master/Documentation/presentations.md) are dead.
Would it be possible to use a new url shorter like bit.ly or just paste the raw links in?

**Comment by naibaf0** [comment]
https://github.com/coreos/clair/issues/560

**Comment by SuperSandro2000** [comment]
Private google drive and this look like two separate issues.
![](https://i.imgur.com/NZLhO2O.png)
