### ISSUE TITLE
Clair not pulling NVD Feeds

### ISSUE THREAD

**Issue by LewisPlangrid** [quay/clair#666]
### Description of Problem / Feature Request

I believe my Clair engine is not pulling any NVD Data feeds. When looking at the docker logs, I see:

"fetching vulnerability update for [ubuntu, oracle, RHEL, Debian, Alphine]"

I tried this on builds v2.0.7 and v.2.0.6

### Expected Outcome

To have a log entry or some verification that clair engine has successfully pulled nvd feeds. 

### Actual Outcome

No verification whatsoever, and I believe complete lack of pulling feeds. (So far my scans indicate far fewer vulnerabilities than expected and shown with other tools)

### Environment

- Clair version/image: v.2.0.6-7
Running on Amazon EC2 Instance with plenty of memory and storage provisioned. No other errors. Using klar for frontend if you would like to know.

**Comment by jzelinskie** [comment]
Can you run an update with the --debug flag on and post the logs here? That should show us if NVD is maybe filtering your requests.
