### ISSUE TITLE
Provide guide to generate pagination key

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#669]
### Description of Problem / Feature Request
The configuration file needs some kind of documentation to describe the tooling around generating the pagination key to make it easier to use multiple Clair instances.

### Environment

- Clair version/image: MASTER
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
