### ISSUE TITLE
A decoupled interface for /ext/

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#673]
### Description of Problem / Feature Request
Every time we change the core Clair logic, which could change the Clair database model/implementation/interface, all of those plugins may need to be changed.
We should fix this by introducing a layer of indirection so that people can still work on their plugins without conflicting with the core logic.
And yes, the issue template is too long, people won't read it.
### Environment
- Clair version/image: MASTER
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
