### ISSUE TITLE
Export failed to be parsed metadata

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#674]
### Description of Problem / Feature Request

Occasionally, there are a few packages that can not be parsed correctly. 
e.g. 
```javascript
{"Event":"could not determine vulnerability severity from: none.","Level":"warning","Location":"rhel.go:393","Time":"2018-12-11 15:43:53.158692"}
{"Event":"could not parse package version. skipping","Level":"warning","Location":"ubuntu.go:312","Time":"2018-12-11 15:44:04.312798","error":"invalid version","version":"0.27-1+deb7u1build0.12.04.1, 0.28-1+deb8u1"}
```
These events are interesting strings that should be added to tests, and handled correctly. We should have a tooling to export these interesting strings based on either log or let Clair generate a separate report, so that it can be monitored.

### Environment
- Clair version/image: MASTER
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by joelee2012** [comment]
i meet this issue as well, but not Occasionally, does someone know how to fix it ?

**Comment by KeyboardNerd** [comment]
It requires updating the corresponding parser. Please look at the "location" field in the log entry.
Feel free to submit a fix :)

**Comment by Hokwang** [comment]
Hi,

I am suffering same issue now.

{"Event":"could not parse package version. skipping","Level":"warning","Location":"ubuntu.go:316","Time":"2019-06-17 06:28:44.769872","error":"invalid version","version":"0.27-1+deb7u1build0.12.04.1, 0.28-1+deb8u1"}

please check this. I have only ubuntu error, others are fine.

**Comment by Hokwang** [comment]
one more log,

{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2019-06-17 06:47:16.715644","note":"Ubuntu disco is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}

**Comment by cblomart** [comment]
Got the same as @Hokwang 

{"Event":"could not parse package version. skipping","Level":"warning","Location":"ubuntu.go:316","Time":"2019-09-18 09:47:18.710778","error":"invalid version","version":"0.27-1+deb7u1build0.12.04.1, 0.28-1+deb8u1"}

**Comment by namloc2001** [comment]
Hi, I've performed some investigatory work and written it up on an issue I raised for the same error. Might be of use? #966

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
