### ISSUE TITLE
is there a way to create login id and password for clair deployed in kubernetes?

### ISSUE THREAD

**Issue by ravitejb** [quay/clair#677]
### Expected Outcome

Clair should be accessed from the kubernetes service by providing its login ID and password when using

### Actual Outcome

clair service is easily accessible without any authentication.

### Environment

- Clair version/image: v2.0.4
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 1.10.9-gke.5 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by jzelinskie** [comment]
One day we might get around to added authentication directly into Clair, but for now we recommend using a proxy.
