### ISSUE TITLE
Calculate CVEs by layer and its parent may not be correct

### ISSUE THREAD

**Issue by liangchenye** [quay/clair#68]
It seems that layers will be better shared among different images according to Docker 1.10. 
https://github.com/docker/docker/releases/tag/v1.10.0-rc1
https://github.com/docker/docker/pull/17924

So there will be images like these:
     ImageA :  [layer-baseA, layer-a, layer-b]
     ImageB :  [layer-baseB, layer-a, layer-c, layer-d]
If it happens, layer-a may have two different parents. In this case, we cannot get the correct CVEs of ImageA and ImageB because current Clair does not know the whole layer chain.

Logically layers with different parents should already exist because DockerV2 use a manifest to manage layers of an image (unlike V1). But since imageID is generated randomly, this does not happen.  
In my test here: (https://github.com/liangchenye/image-mining/tree/master/parent-layer),  no conflicted parents are found after scanning 1000+images.

**Comment by Quentin-M** [comment]
Hi,

Yes, thank you for pointing it out. We already thought about that issue.

One way to leverage this is to craft an unique ID for each layer that is added to Clair, that would not be the Docker ID. One could think about concatenating the ancestors IDs with the layer ID and hash that string (e.g. hash(layer-a + layer-b + layer-c) as the ID for layer-c). Of course, it really depends on your existing infrastructure, other solutions might exist. Quay already does something pretty similar.

**Comment by jzelinskie** [comment]
We should probably document this somewhere besides this issue.

**Comment by liangchenye** [comment]
I'm fine to close this.
But not sure where to document it.
Roadmap?

**Comment by jzelinskie** [comment]
I've made an issue for creating our roadmap. Thanks for the reminder!
