### ISSUE TITLE
README: some docs links do not work

### ISSUE THREAD

**Issue by kmoe** [quay/clair#690]
README.md provides a link to the API docs:
https://app.swaggerhub.com/apis/coreos/clair/3.0

However, this link leads to a page displaying "Sorry, we can't find coreos / clair / 3.0" and no API docs.

It also provides a link to the documentation on the CoreOS website:
https://coreos.com/clair/docs/latest/

This page contains a banner saying "These docs are deprecated while they are being migrated to Red Hat. For the most up to date docs, please see the corresponding GitHub repository.", so the user is directed back to the GitHub repo.

### Environment

N/A

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
