### ISSUE TITLE
Register keys used in keyvalue table to avoid collisions

### ISSUE THREAD

**Issue by jzelinskie** [quay/clair#698]
Access to the database's keyvalue API should be gated by a library that enforces no keys collide and potentially naming conventions for the different use cases.

### Environment

N/A

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
