### ISSUE TITLE
[SOLVED] failed to load configuration on docker-compose up

### ISSUE THREAD

**Issue by CaosFR** [quay/clair#703]
### Description of Problem / Feature Request

Hi,

When I try to install Clair with docker-compose guidline but after all is done clair dont look like run correctly. 
If I run docker-compose up without deamon I got this error : 

docker-compose up
Starting clair_postgres ... done
clair_clair is up-to-date
Attaching to clair_postgres, clair_clair
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:30:14.946953","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:30:15.747215","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:30:17.104118","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:30:18.459353","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:30:19.605702","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:30:21.582408","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:30:25.127498","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:30:31.933963","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:30:45.142796","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:31:11.163885","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:32:02.741953","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:39:21.394930","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:39:21.997409","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:39:22.525595","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:39:23.258225","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:39:24.418696","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:39:26.357028","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:39:29.894359","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:39:36.659419","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:39:49.849858","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location"                                                                                                                                                             :"main.go:190","Time":"2019-01-31 14:40:15.919065","error":"yaml: line 24: found                                                                                                                                                              character that cannot start any token"}
clair_postgres | 2019-01-31 14:40:54.384 UTC [1] LOG:  listening on IPv4 address                                                                                                                                                              "0.0.0.0", port 5432
clair_postgres | 2019-01-31 14:40:54.384 UTC [1] LOG:  listening on IPv6 address                                                                                                                                                              "::", port 5432
clair_postgres | 2019-01-31 14:40:54.407 UTC [1] LOG:  listening on Unix socket                                                                                                                                                              "/var/run/postgresql/.s.PGSQL.5432"
clair_postgres | 2019-01-31 14:40:54.456 UTC [20] LOG:  database system was inte                                                                                                                                                             rrupted; last known up at 2019-01-31 14:30:18 UTC
clair_postgres | 2019-01-31 14:40:54.483 UTC [20] LOG:  database system was not                                                                                                                                                              properly shut down; automatic recovery in progress
clair_postgres | 2019-01-31 14:40:54.498 UTC [20] LOG:  redo starts at 0/1651D10
clair_postgres | 2019-01-31 14:40:54.499 UTC [20] LOG:  invalid record length at                                                                                                                                                              0/1651D48: wanted 24, got 0
clair_postgres | 2019-01-31 14:40:54.500 UTC [20] LOG:  redo done at 0/1651D10
clair_postgres | 2019-01-31 14:40:54.593 UTC [1] LOG:  database system is ready                                                                                                                                                              to accept connections
clair_clair exited with code 1
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:30:14.946953","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:30:15.747215","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:30:17.104118","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:30:18.459353","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:30:19.605702","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:30:21.582408","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:30:25.127498","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:30:31.933963","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:30:45.142796","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:31:11.163885","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:32:02.741953","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:39:21.394930","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:39:21.997409","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:39:22.525595","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:39:23.258225","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:39:24.418696","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:39:26.357028","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:39:29.894359","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:39:36.659419","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:39:49.849858","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:40:15.919065","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:41:07.915504","error":"yaml: line 24: found character that cannot start any token"}
clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:42:08.353516","error":"yaml: line 24: found character that cannot start any token"}
...

### Expected Outcome

Dont know, done maybe ?

### Actual Outcome

clair_clair | {"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-01-31 14:42:08.353516","error":"yaml: line 24: found character that cannot start any token"}

### Environment

- Clair version/image: latest
- Clair client name/version:  clair-git
- Host OS: Debian 
- Kernel (e.g. `uname -a`): 8.x
- Kubernetes version (use `kubectl version`): dont have 
- Helm version (use `helm version`): dont know what is it
- Network/Firewall setup: local network

TY for support

**Comment by mikkeschiren** [comment]
What is the content of your config.yaml ? And have you tested out clair instead of clair-git ?

**Comment by CaosFR** [comment]
Hi @mikkeschiren  and thanks for try to help me.

Yes , I had try to "docker-compose up" on "clair" repository and I got the same issue.

See in attached file my "config.yaml".
[config.zip](https://github.com/coreos/clair/files/2831232/config.zip)



TY

**Comment by mikkeschiren** [comment]
I think this line:
```
source: postgresql://postgres:password@postgres:5432?sslmode=disable
```
Should be something like:
```
source: host=postgres port=5432 password=password user=postgres sslmode=disable statement_timeout=60000
```

**Comment by CaosFR** [comment]
Sorry but `source: postgresql://postgres:password@postgres:5432?sslmode=disable` is for my connection with my postgres container.
If I change to `host=postgres port=5432 password=password user=postgres sslmode=disable statement_timeout=60000` clair try to connect to postgres outside Docker and I get a new error "could not connect database".

I suposse..

**Comment by sfo-md** [comment]
Hi,

this is my first comment on github. Yay.

I think you should add your database-name after the port like:
`postgresql://postgres:password@postgres:5432/$DB-NAME?sslmode=disable`

this works on my site.

**Comment by CaosFR** [comment]
Hi @sfo-md 

Ty for your help, it's work now :+1:  . First comment, first help, first win :)

**Comment by KeyboardNerd** [comment]
Please close when it's solved.

Thanks.
