### ISSUE TITLE
Unable to get clair up and running  : ""error":"open /config/config.yaml: permission denied"

### ISSUE THREAD

**Issue by poojatr** [quay/clair#707]
### Description of Problem / Feature Request

Not able to get clair up and running, i am following the docker method to install clair, its exiting with the error message **"error":"open /config/config.yaml: permission denied"** when i execute the run command 

docker run --net=host -d -p 6060-6061:6060-6061 -v $PWD/clair_config:/config quay.io/coreos/clair-git:latest -config=/config/config.yaml

I even tried sudo run, which also says: permission denied.
### Expected Outcome
when docker ps is done
clair is up and running

### Actual Outcome

Clair exited few minuted ago,
while the docker logs of clair contaienr says
{"Event":"failed to load configuration","Level":"fatal","Location":"main.go:190","Time":"2019-02-09 17:08:21.176708","error":"open /config/config.yaml: permission denied"}
 
### Environment

- Clair version/image: quay.io/coreos/clair-git:atest
- Clair client name/version: 
- Host OS: centos -7 /windows (am trying on both the systems, results are same)
- Kernel (e.g. `uname -a`): Linux localhost.localdomain 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`): not installed
- Helm version (use `helm version`): helm is not installed
- Network/Firewall setup: i dont know how to check

Should go,rpm and xz be installed prior?

I will really appreciate the help, am a beginner trying out with clair and dockers , so sorry for the silly doubts..

**Comment by KeyboardNerd** [comment]
Please go into the running docker container and see if the /config/config.yaml exists and try open it with, for example, vi.

go is not necessarily installed in the container image.
rpm, xz should be already installed in the image.

**Comment by achakote** [comment]
I have the same issue.  @KeyboardNerd container is not starting since it does not start the find /config/config.yaml

**Comment by Qwertie-** [comment]
I am getting the same issue after following the docker compose guide. I don't think I can access the container because its always in a state of restarting.

**Comment by Qwertie-** [comment]
Worked it out. This is an SELinux issue

![Screenshot from 2019-03-26 14-00-55](https://user-images.githubusercontent.com/6601505/54969834-b54c1e80-4fcf-11e9-888a-888420b7cc0e.png)


One of the answers here should fix the issue https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker
