### ISSUE TITLE
Add feature relation to database

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#711]
### Description of Problem / Feature Request

Now the API shows
Feature name = A, type = source package, version = 1.0, vulnerabilities = [C, D, E]
Feature name = B, type = binary package, version = 2.0, vulnerabilities = []

We don't know if A and B are related or not.
If those are related, the user should know that and decide what to do with the vulnerabilities.

We need to implement the database to record this information. It requires an update to all the implementation of feature detectors, and an update to database schema.

### Environment

- Clair version/image: master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
