### ISSUE TITLE
Failed to lock because search lock query failed

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#715]
### Description of Problem / Feature Request

```
{"Description":"searchLock","Event":"database: handled database error","Level":"error","Location":"pgsql.go:329","Time":"2019-02-25 15:56:00.808690","error":"pq: current transaction is aborted, commands ignored until end of transaction block"}
```

We can't do this: https://github.com/coreos/clair/blob/master/database/pgsql/lock.go#L71
because when a transaction errored and aborted, it requires a new transaction. Please put this logic outside.

My Lock Table:
12,"updater","6636b47a-3a9e-45ca-a142-bb6b52a60e60","2019-02-25 20:59:46.547449"
### Environment

- Clair version/image: master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
already fixed

**Comment by jzelinskie** [comment]
linking for auditing #723
