### ISSUE TITLE
travis should fail when a copyright header is missing in the go/proto/bash files.

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#716]
### Description of Problem / Feature Request

travis should fail when a copyright header is missing in the go/proto/bash files.

### Environment

- Clair version/image: master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by jzelinskie** [comment]
Fixed in #725
