### ISSUE TITLE
Get rid of Ancestry name

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#718]
### Description of Problem / Feature Request

It doesn't make sense to have ancestry names since we're doing the work based on the layers.

User should always use the list of layer names for querying the vulnerability scan result.

change: 

Change the gRPC API to accept the layer names when getting the Ancestry Results.

Internally we still compute the Ancestry name using the hash of layer names to keep track of things in the database. 
### Environment

- Clair version/image: master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
