### ISSUE TITLE
Differentiate package installer database removal, uninstalling all packages, and package changes

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#719]
### Description of Problem / Feature Request
currently the Ancestry builder logic has the following special handling:

If the feature detector gives 0 features, we assume that the package installer database is not changed, and thus the file doesn't exist in the layer blob, and thus no package is changed.

However, what if the package installer database is changed, but just that the feature detector cannot extract anything from it? 

Or what if the package installer database is removed, and thus the file exists in the database with "-" prefix ( e.g. for dpkg database, when file change: "var/lib/dpkg/status" exists, when file deleted: "var/lib/dpkg/-status" exists )

 

We could handle this case basically by changing the featurefmt to return if the required file exists in the layer blob or not.

### Environment

- Clair version/image: master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
kinda hard: 
1. when a featurefmt detects stuff, it should give the status if a file is removed/changed/not changed. And when adding leaf ancestry layer, layer should hold that information, and ancestry builder uses that information.

2. so, layer should hold the detector status information in db, which means query changes, and a bunch of model changes.

gotta take a few days to finish this.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
