### ISSUE TITLE
Add a "get started" section in readme

### ISSUE THREAD

**Issue by pierreozoux** [quay/clair#72]
I'd like to test my containers on my local machine.
How could I use your project to do so?

I saw your amazing video, and I really would like to test my containers.

Thanks!

**Comment by Quentin-M** [comment]
Hi,

Thanks for your interest. That's definitely something that we should add.

For now, some documentation may be found at : 
- https://github.com/coreos/clair/blob/master/docs/Run.md
- https://github.com/coreos/clair/blob/master/docs/API.md

To analyze your local container images easily, you may use this contrib tool: https://github.com/coreos/clair/tree/master/contrib/analyze-local-images

**Comment by pierreozoux** [comment]
Hey :)

Thanks it was an amazing help!
I got up and running in minutes!
https://microblog.pierre-o.fr/2016/test-the-security-of-your-images-in-coreos-with-clair

(I let you close the issue)

**Comment by Quentin-M** [comment]
Great! Thanks for the article!

I'll close the issue as soon as we'll have written a "getting started" doc.
