### ISSUE TITLE
Split namespace name and version

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#731]
### Description of Problem / Feature Request
We're now using a string to contain the name and version of a namespace, separated by `:`

Since some namespace may have `:` in the name, this will break. 

Just need update all namespace representation to have both name and version.

### Environment

- Clair version/image:  master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
To implement: 
1. Change Database Namespace Schema from "Name, Verisonfmt" to "Name, Version, Versionfmt"
2. Change Database Namespace Model
3. Change all related queries and stuff and ensure all tests are passed. 
4. Change gRPC Namespace to split into name and version fields.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
