### ISSUE TITLE
Implementing CentOS data source driver for Clair

### ISSUE THREAD

**Issue by irenexychen** [quay/clair#732]
### Feature Implementation
Scanning CentOS docker image doesn't report back security advisories without fixes when referring to the RHEL data source driver. Hence, in the process of implementing a CentOS-specific driver using CESA by CentOS Announce, combined with RH's security data api instead, developing on top of release v2.0.7

Link to fork: [https://github.com/irenexychen/clair/tree/centos-driver](https://github.com/irenexychen/clair/tree/centos-driver)

Data sources: 
[CESA db](https://cefs.b-cdn.net/errata.latest.xml)
[CVEs](https://access.redhat.com/labs/securitydataapi/cve.json)
[OVAL](https://access.redhat.com/labs/securitydataapi/oval.json)

### Description of Problem
After the CVE database and its NVD metadata for CentOS has been populated, running into issues inserting vulnerabilities into the datastore, with the following error from updater.go:

`{"Description":"insertVulnerability","Event":"Handled Database Error","Level":"error","Location":"pgsql.go:284","Time":"2019-03-11 10:12:58.451329","error":"pq: value too long for type character varying(128)"}`

This causes a re-fetch of the centos vulnsrc driver, repopulating in a loop. Insight is much appreciated.

### Environment
- Clair version/image: v2.0.7
- Clair client name/version: n/a
- Host OS: Linux
- Kernel: 4.15.0-45-generic

**Comment by KeyboardNerd** [comment]
```
`CREATE TABLE IF NOT EXISTS Vulnerability (
        id SERIAL PRIMARY KEY,
        namespace_id INT NOT NULL REFERENCES Namespace,
        name VARCHAR(128) NOT NULL,
        description TEXT NULL,
        link VARCHAR(128) NULL,
        severity severity NOT NULL,
        metadata TEXT NULL,
        created_at TIMESTAMP WITH TIME ZONE,
        deleted_at TIMESTAMP WITH TIME ZONE NULL);`,
```
look at the schema, name or link is too long.
Please print out the vulnerabilities given by your vuln source driver, and check the size.

**Comment by irenexychen** [comment]
EDIT: nvm 128 characters, not bytes.

Thanks, KeyboardNerd. I've verified that for all CVEs, fields vulnerability.Name, vulnerability.Link, vulnerability.FixedIn are all individually within 128 bytes using unsafe.Sizeof(), so these don't seem to be the issue... 

Still unfamiliar with how the datastore is formatted, what field is used as the KeyValue? 

(00002_initial_schema.go)
```
`CREATE TABLE IF NOT EXISTS KeyValue (
        id SERIAL PRIMARY KEY,
        key VARCHAR(128) NOT NULL UNIQUE,
        value TEXT);`,
```

**Comment by KeyboardNerd** [comment]
KeyValue is for storing flags e.g. vulnerability fetch timestamps or git revision

**Comment by irenexychen** [comment]
Update on this issue: validating and cross-comparing scan results on Docker images based on CentOS, with plans to push out a pull request for this feature within a week or so. Will close this issue once that happens.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
