### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#743]
### Description of Problem / Feature Request
I got some thoughts about caching in Clair.

We cache any immutable data based on LRU. 

The immutable data:
Detector, Namespace, Feature, Detected Content based on Detector in each layer, NamespacedFeature, Vulnerability Name/Namespace <-> Vulnerability ID in table, etc. 

We can cache the database ID to row value pair, so that a lot of insertions, soi queries can be simplified. ( Query from the cache before insertion, insert with database IDs only ).

I'll guess the structure can be like this: 
Clair Query -> Memcache -> Database.

If we can have some statistic happening, we can warm the cache before deploying a Clair cluster.

### Environment
- Clair version/image: master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
