### ISSUE TITLE
Add integration test on API endpoint

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#744]
### Description of Problem / Feature Request

Make it easier to test the gRPC and RESTful API. 

### Environment

- Clair version/image: master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
