### ISSUE TITLE
As a Clair user, I'd like to have Clair to return vulnerable ancestry changes instead of computing that on Client side

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#746]
### Description of Problem / Feature Request

Currently Clair returns two lists of old vulnerable ancestries and new vulnerable ancestries, each with pagination token and indexes.

As a user, it's hard to understand how to use the "index" field, which, in practice is the database primary key and used to save expensive diffs on the client side.

Since Clair implementation can simply compute this on its side, we can change the API interface to return the vulnerable ancestry diffs. 

e.g. 
A vulnerability is changed:
Currently we return a list of all vulnerable ancestries with the old vulnerability and the new vulnerability. 
OldVulnerableAncestry: A, B, C, F
NewVulnerableAncestry: A, B, C, D, E

In the future, we return a list of the difference:
NotVulnerableAnyMore: F
NewVulnerableAncestry: D, E

### Environment

- Clair version/image: 
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
