### ISSUE TITLE
Colon ':' breaks GET /ancestry/ REST API

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#747]
### Description of Problem / Feature Request

when we request ancestry API with something like
/ancestry/sha256:12345

It will return 404 directly.

### Environment

- Clair version/image: master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
This is a known issue in gRPC gateway. 
https://github.com/grpc-ecosystem/grpc-gateway/issues/224

**Comment by KeyboardNerd** [comment]
apparently because of backward compat issue, they are not going to resolve this problem. 
I guess either to redesign this gateway API or change the dependency to be the commit before reverting "allowing colon" PR.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
