### ISSUE TITLE
NPM vulnerability scanner

### ISSUE THREAD

**Issue by cnorthwood** [quay/clair#750]
### Feature Request

Clair should report on vulnerabilities in NodeJS packages installed using NPM (or Yarn or a similar tool).

### Expected Outcome

If I have built a Docker image which in the build phase runs `npm install`, but one of my dependencies has a known security issue, then it should be identified when it is scanned by Clair.

### Actual Outcome

Currently nothing (unless it's a system-level package)

### Environment

N/A

**Comment by cnorthwood** [comment]
I've started on this with https://github.com/coreos/clair/pull/740. I suggest that https://github.com/nodejs/security-wg/tree/master/vuln is a reasonable place to pull vulnerability information from, as it's MIT licensed and is used by `npm audit`

**Comment by KeyboardNerd** [comment]
Looks promising!

**Comment by spaparaju** [comment]
@cnorthwood does the 'security advisories' cover all the known CVEs for the NPM dependencies  ? I am looking at https://github.com/nodejs/security-wg/tree/master/vuln/npm. Its not frequently being updated and currently I see not more than 500 CVEs. Does these 'security advisories' cover only the 'third party NPM modules', not the 'third party NPM dependencies' ?

**Comment by cnorthwood** [comment]
I'm unsure, and I'm not sure I understand what you mean by modules vs dependencies. It's the official repo for the NodeJS security advisories though, and I'm not sure of any other upstream repo.

**Comment by spaparaju** [comment]
Yes, its an official repo for NodeJS security advisories. I am trying to understand does this source [https://github.com/nodejs/security-wg/tree/master/vuln/npm](https://github.com/nodejs/security-wg/tree/master/vuln/npm) cover the CVEs been identified across ALL the NPM dependencies.   I see that these security advisories cover around 500 CVEs for the entire NPM ecosystem of dependencies / modules and its not frequently get updated.  For example, a simple  'npm audit' on a repo. like  [https://github.com/shzlw/zeu](https://github.com/shzlw/zeu) would result in 500+ vulnerabilities.

You are right, there is no NPM upstream repo. with permissive license enable integrations. 'npm audit' is one good source. Its free for individual developers to try out and has not-so-friendly terms for integrations. (Please check out the Condition:4 at [https://www.npmjs.com/policies/open-source-terms](https://www.npmjs.com/policies/open-source-terms))

**Comment by cnorthwood** [comment]
It's the same database as npm audit uses (the database is licensed permissively and separately from the NPM codebase), I don't know what promises the Node Security Working Group make about coverage though.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
