### ISSUE TITLE
API Docs?

### ISSUE THREAD

**Issue by JoelPagliuca** [quay/clair#753]
### Description of Problem / Feature Request

README.md provides a link to the API docs:
https://app.swaggerhub.com/apis/coreos/clair/3.0

However, this link leads to a page displaying "Sorry, we can't find coreos / clair / 3.0" and no API docs.

It also provides a link to the documentation on the CoreOS website:
https://coreos.com/clair/docs/latest/

This page contains a banner saying "These docs are deprecated while they are being migrated to Red Hat. For the most up to date docs, please see the corresponding GitHub repository.", so the user is directed back to the GitHub repo.

### Expected Outcome

Docs to help us get started using this cool project 🥰

### Actual Outcome

We are confused about API documentation

### Environment

- Clair version/image: `quay.io/coreos/clair:latest` - `f4f22837644d`
- Clair client name/version: `curl`
- Host OS: Mac
- Kernel (e.g. `uname -a`): none
- Kubernetes version (use `kubectl version`): none
- Helm version (use `helm version`): none
- Network/Firewall setup: none

**Comment by JoelPagliuca** [comment]
@kmoe tried to raise this issue [here](https://github.com/coreos/clair/issues/689)

**Comment by KeyboardNerd** [comment]
??

> README.md provides a link to the API docs:
https://app.swaggerhub.com/apis/coreos/clair/3.0
> However, this link leads to a page displaying "Sorry, we can't find coreos / clair / 3.0" and no API docs.


https://github.com/KeyboardNerd/keyboardnerd.github.io/blob/master/Screen%20Shot%202019-03-28%20at%2012.03.21%20PM.png

**Comment by kmoe** [comment]
@JoelPagliuca I raised the issue again here: https://github.com/coreos/clair/issues/690

The SwaggerHub docs work for me as well now.

**Comment by jzelinskie** [comment]
This issue has been created a few times. I'm not sure what the problem is. I've never had an issues, even in an Incognito Window being able to browse the API docs at Swagger Hub.

I do think that we need to scrap the link to the CoreOS docs. Their replacement is behind the Red Hat customer portal, which requires an account.

**Comment by JoelPagliuca** [comment]
Thanks guys
