### ISSUE TITLE
Fine grained Fixed in version

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#758]
### Description of Problem / Feature Request

Sometimes, there's no specific fixed in version for a package. 

For example, a CVE may affect curl version >= 1.0 and <= 2.3, and gives no recommended upgrade version. Then, Clair should report that version range to the user without giving a specific fixed in version.

### Environment

- Clair version/image: master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
