### ISSUE TITLE
Find fixed in version for binary package from source package fixed in

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#759]
### Description of Problem / Feature Request
Vulnerability report typically is on the source packages instead of binary packages. For those reports, we're using the source package fixed in version for the binary package's fixed in version. 
This assumption is ok for most cases that binary package must share the source package's version number. But still, it's an assumption.

We should do something like:
When we find that a vulnerability source reports that a source package, e.g. "openssl 1.0", is affected, we can find all the binary packages related to this source package, e.g. https://packages.debian.org/source/sid/openssl, then we can get all the actual structure.

### Environment

- Clair version/image: master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
