### ISSUE TITLE
Clair updates fails on RHEL

### ISSUE THREAD

**Issue by cesartl** [quay/clair#762]
### Description of Problem / Feature Request

During the database update process I'm getting the following error:

```
{"Event":"running database migrations","Level":"info","Location":"pgsql.go:216","Time":"2019-04-08 07:02:42.741920"}
{"Event":"database migration ran successfully","Level":"info","Location":"pgsql.go:223","Time":"2019-04-08 07:02:42.880970"}
{"Event":"starting main API","Level":"info","Location":"api.go:52","Time":"2019-04-08 07:02:42.881163","port":6060}
{"Event":"starting health API","Level":"info","Location":"api.go:85","Time":"2019-04-08 07:02:42.881275","port":6061}
{"Event":"updater service started","Level":"info","Location":"updater.go:83","Time":"2019-04-08 07:02:42.881653","lock identifier":"e95e2a0f-3d34-46be-a70a-f63e1a49a2fa"}
{"Event":"notifier service is disabled","Level":"info","Location":"notifier.go:77","Time":"2019-04-08 07:02:42.881934"}
{"Event":"updating vulnerabilities","Level":"info","Location":"updater.go:192","Time":"2019-04-08 07:02:42.884835"}
{"Event":"fetching vulnerability updates","Level":"info","Location":"updater.go:239","Time":"2019-04-08 07:02:42.884876"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"debian.go:63","Time":"2019-04-08 07:02:42.884920","package":"Debian"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2019-04-08 07:02:42.885008","package":"RHEL"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"oracle.go:119","Time":"2019-04-08 07:02:42.885032","package":"Oracle Linux"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"alpine.go:52","Time":"2019-04-08 07:02:42.885323","package":"Alpine"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"ubuntu.go:85","Time":"2019-04-08 07:02:42.885267","package":"Ubuntu"}

{"Event":"Failed to update RHEL","Level":"error","Location":"rhel.go:112","StatusCode":403,"Time":"2019-04-08 07:02:43.008489"}
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2019-04-08 07:02:43.008612","error":"could not download requested resource","updater name":"rhel"}

{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2019-04-08 07:02:43.617969","updater name":"alpine"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2019-04-08 07:02:43.928346","updater name":"debian"}
```

### Expected Outcome

Clair updates successfully

### Actual Outcome

Clair exits with error.

### Environment

- Clair version/image: 2.0.8
- Clair client name/version: 2.0.8
- Host OS: Docker?
- Kernel (e.g. `uname -a`):

**Comment by reasonerjt** [comment]
+1

**Comment by cesartl** [comment]
I run a daily build and this morning it worked fine 🤷‍♂️

Not sure if it means the issue was fixed

**Comment by cesartl** [comment]
Actually, the same problem happened today. So there is an element of randomness.

**Comment by sumeng001** [comment]
+1

**Comment by CyrilPeponnet** [comment]
https://www.redhat.com/security/data/oval/com.redhat.rhsa-20180483.xml leads me to 403 for evey xml as well.

But works after a while... wondering if they are not locking it during update somehow?

**Comment by lixianyang** [comment]
Same problem when run clair without internet, and proxy some sites:

- security-tracker.debian.org
- linux.oracle.com
- www.redhat.com
- git.launchpad.net
- github.com
- nvd.nist.gov
- access.redhat.com
- bugzilla.redhat.com
- oval.mitre.org

```shell
{"log":"{\"Event\":\"Failed to update RHEL\",\"Level\":\"error\",\"Location\":\"rhel.go:140\",\"StatusCode\":403,\"Time\":\"2019-07-22 09:12:48.110004\"}\n","stream":"stdout","time":"2019-07-22T09:12:48.110580332Z"}
{"log":"{\"Event\":\"an error occured when fetching update\",\"Level\":\"error\",\"Location\":\"updater.go:246\",\"Time\":\"2019-07-22 09:12:48.110365\",\"error\":\"could not download requested resource\",\"updater name\":\"rhel\"}\n","stream":"stdout","time":"2019-07-22T09:12:48.110654115Z"}
```
clair image: goharbor/clair-photon:v2.0.8-v1.8.1

**Comment by reasonerjt** [comment]
Seeing 403 on my env recently.
Possibly the RHEL intentionally blocks Clair from updating?

@KeyboardNerd Can we have this issue re-opened?

**Comment by chris-ng-1987** [comment]
Any update?

**Comment by KeyboardNerd** [comment]
@jzelinskie we might need to implement some kind of service to keep track of our data sources and see if they block us.
Actually if we can redistribute the update content by setting up some updater servers. It might even helps more.

**Comment by reasonerjt** [comment]
@KeyboardNerd @jzelinskie 

Do we have any channel for communication to RHEL to see why it returns 403?  
It's really a quite intermittent error.  Although the status is 4xx, it seems the server side issue and we may need some help from red hat.

**Comment by Divyang-Soni** [comment]
RHEL has problem in their CDN vendor from last 5 days.
Please track from below url.
https://status.redhat.com/

**Comment by michaelb990** [comment]
Seems like this has been an issue in the past: https://github.com/coreos/clair/issues/596

Last time, @djhenry and @sochotnicky were able to help, maybe they can work some magic again? :)

**Comment by sochotnicky** [comment]
Well the original reporter hasn't confirmed problems recently. Clair 2.0.8 should be providing user-agent headers as per https://github.com/coreos/clair/commit/9df4f5bd705b554fb6b024a5ed0793d65abf186b 

It's definitely possible that some clients could be "blacklisted" if they are considered to be abusing the network, but since things seem to be intermittent - I'd agree it's more likely to do with CDN vendor issues. But those issues were not happening back in April. I'll file a ticket with IT and see if they can find out anything more.

**Comment by cesartl** [comment]
@sochotnicky I can confirm it's still happening but it's random. I run a daily build of Clair and below are a few of the last builds:
Oct 16 - Fail
Oct 15 - Pass
Oct 14 - Fail
Oct 13 - Fail
Oct 12 - Pass

**Comment by hseljenes** [comment]
Howdy folks. You're probably seeing intermittent issues because the update is running into our rate limiter on our CDN. We deployed a change today to try to help but there may be other improvements we can make from the code side.

Looking at the Update code, it fetches the dir listing from https://www.redhat.com/security/data/oval/, matches all the com.redhat.rhsa.\d+.xml in the source, then downloads all the 2,500+ matches.

Could it instead just request https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml or even better request https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml.bz2 to do its update?

If it requires individual files we also deploy a tar package of them at https://www.redhat.com/security/data/oval/rhsa.tar.bz2

**Comment by djhenry** [comment]
If I remember correctly, the content behind https://www.redhat.com/security/ is limited to about 12 hits/s per IP.  After that, the IP address gets put in the naughty box for a few minutes and will get 403 responses with a cryptic error string.

Keep in mind, organizations using Clair may have many instances behind a single NAT IP.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
