### ISSUE TITLE
docker run "imagename

### ISSUE THREAD

**Issue by sathish-ms** [quay/clair#763]
### Environment

- Clair version/image: 
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
coping the removed issue content here:
```
{"Event":"failed to load configuration","Level":"fatal","Location":"main.go:186","Time":"2019-04-09 02:38:34.676164","error":"open /etc/clair/config.yaml: no such file or directory"}
```

check if that file exists
