### ISSUE TITLE
RFE: Allow users to force re-scan ancestry which is already in database

### ISSUE THREAD

**Issue by Allda** [quay/clair#771]
### Description of Problem / Feature Request
Currently, when users scan image in Clair it stores metadata about image/layers to the database and considers the metadata as static which can never change. However, in some cases, metadata doesn't have to be static due to various reasons (dynamic feature namespaces, fixed bug in feature scanner, additional changes in security metadata). This can cause some false positives/negatives in ancestry results.

It would be great if we can specify a `force` boolean flag in ancestry scan request which would basically say... Forget what you already know about the ancestry and scan image again.

### Expected Outcome

Allow force ancestry scan and update ancestry metadata in the database.

### Environment

- Clair version/image: master branch
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
When feature detector made breaking changed, it means that any layer feature found by this feature detector is invalidated.

We have the thing called "detector version", which is used to indicate this. 
And all scanned ancestries are associated with a set of detectors with their versions.

If you changed a feature detector, you need to 
1. update the detector version
2. post all the ancestries in your repository again <- this will cause the ancestry to be rescanned.

Therefore, I think it's not necessary to do it in API level to force rescan. 
However, I agree that it's necessary when developing some feature detector.
