### ISSUE TITLE
Failed to scan fedora images

### ISSUE THREAD

**Issue by karthiknannapaneni** [quay/clair#777]
### Description of Problem / Feature Request
Does Clair support fedora image scanning. 

### Expected Outcome

CVE findings. 

### Actual Outcome

Failed to analyze using API v1: push image https://xxxxxxxx:latest to Clair failed: push error 422: {"Error":{"Message":"worker: OS and/or package manager are not supported"}}

Failed to analyze using API v3: push image https://xxxxxxxxx:latest to Clair failed: rpc error: code = Unavailable desc = transport is closing

### Environment

- Clair version/image: latest 2.0.8
- Clair client name/version: 
- Host OS: linux 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by KeyboardNerd** [comment]
what fedora version are u testing?

**Comment by karthiknannapaneni** [comment]
I tried the latest version from docker hub and few other older versions too. 
https://hub.docker.com/_/fedora

**Comment by GJKrupa** [comment]
I've seen the same with an image based on fedora:29

**Comment by jdoss** [comment]
This is an issue with Fedora 29 and 30. Support for these base images would be great.

**Comment by urbaniak** [comment]
Also looking forward for Fedora support

**Comment by vigodeltoro** [comment]
I have the same issue with fedora 28 

Clair Version v2.0.9

Does anybody has a hint ? That would be great..

Thanks

**Comment by jdoss** [comment]
Do we need to keep bumping this to keep it open? Having support for Fedora would be great!

**Comment by xguitian** [comment]
Any update on this one?

**Comment by ldelossa** [comment]
AFAIK fedora devs do not maintain a security database for packages within the Fedora repositories. I do not believe the RHEL oval databases would provide accurate information for Fedora. 

Ill do a bit of research to confirm and if this is not the case we will add this as feature to  ClairCore (https://github.com/quay/claircore) and ClairV4. ClairV2 is in maintenance and will not be getting new features.

**Comment by vippujain** [comment]
I am having issue with Fedora version 28 and CLAIR version is 2.1.6. Do any hvae workaround for same?

**Comment by hdonnay** [comment]
Clair v2 doesn't recognize fedora, so returning 422 is expected behavior.
