### ISSUE TITLE
Clair support for Oracle Linux

### ISSUE THREAD

**Issue by pipseed** [quay/clair#78]
Are there any plans to expand the OS support for Oracle Linux. Scanning an OL image flags as unrecognized OS, as this is derived from a RedHat OS with an rpm based package manager would this be an easy fix?

**Comment by Quentin-M** [comment]
Hi.

Sure. If the packages are the same, it's just about updating https://github.com/coreos/clair/tree/master/worker/detectors/namespace/redhatrelease to make Oracle Linux detected as CentOS (ie. `centos:6`). Shouldn't be more than 10 lines of code.

Actually, to be more accurate, we should also:
- rename `centos` to `rhel` there,
- rename `centos` to `rhel` in `updater/fetchers/rhel/rhel.go`,
- rename every existing Namespace `centos:*` to `rhel:*` in databases.

**Comment by philips** [comment]
@pipseed would you be interested in helping out with this?

**Comment by Djelibeybi** [comment]
@Quentin-M Oracle Linux has it's own OVAL database and prefixes, so I'm not sure if the existing `rhel` fetcher would work. 

I've been meaning to take a look at Clair for a while, so I might do that and take a look at this at the same time.

(FYI: I'm the Product Manager for Oracle Linux)
