### ISSUE TITLE
Run clair with Sqlite (instead of Postgres)

### ISSUE THREAD

**Issue by bittner** [quay/clair#785]
### Description of Problem / Feature Request

[According to the documentation](https://github.com/coreos/clair/blob/master/Documentation/running-clair.md) it seems to be possible to run Clair in combination with Postgres only. For temporary, ephemeral, one-shot deployments it may be desirable to run it with a more lightweight RDBMS, such as Sqlite.

### Expected Outcome

* It's possible to run Clair with Sqlite as a DB backend
* The configuration of Sqlite as a DB backend is documented (e.g. in [Running Clair](https://github.com/coreos/clair/blob/master/Documentation/running-clair.md))

### Actual Outcome

It's not clear [from the docs](https://github.com/coreos/clair/blob/master/Documentation/running-clair.md) whether Clair can run with other DB backends. The documentation suggests, "Postgres is required".

### Environment

N/A

- Clair version/image: current master
- Clair client name/version: current master
- Host OS: any
- Kernel (e.g. `uname -a`): n/a
- Kubernetes version (use `kubectl version`): n/a
- Helm version (use `helm version`): n/a
- Network/Firewall setup: n/a

**Comment by KeyboardNerd** [comment]
sqlite is not currently supported.

**Comment by ldelossa** [comment]
@bittner @KeyboardNerd I'm going to close this issue for now. The database implementation is behind an interface so if @bittner you'd like to take a stab at a sqlite implementation and open a PR I would be interested in reviewing. Currently postgresql is the supported database implementation.
