### ISSUE TITLE
Getting Clair up and running instructions are wrong

### ISSUE THREAD

**Issue by jwlogemann** [quay/clair#790]
### Description of Problem / Feature Request

running-clair.md has the following steps to get Clair up and running in Kubernetes:
git clone https://github.com/coreos/clair
cd clair/contrib/helm
cp clair/values.yaml ~/my_custom_values.yaml
vi ~/my_custom_values.yaml
helm dependency update clair
helm install clair -f ~/my_custom_values.yaml

The last step gives the following error:
Error: validation failed: error validating "": error validating data: unknown object type "nil" in PersistentVolumeClaim.metadata.annotations.helm.sh/resource-policy
Kubernetes version: 1.14.2
Helm version: 2.14

### Expected Outcome

Clair running in kubernetes

### Actual Outcome

Error: validation failed: error validating "": error validating data: unknown object type "nil" in PersistentVolumeClaim.metadata.annotations.helm.sh/resource-policy
### Environment

Kubernetes version: 1.14.2
Helm version: 2.14

**Comment by ldelossa** [comment]
@jwlogemann
This is a known issue. We are reworking local development. https://github.com/coreos/clair/pull/788

Will ping you when we merge this in.

**Comment by ldelossa** [comment]
@jwlogemann we just merged this: https://github.com/coreos/clair/pull/788

Would you mind giving it a test run?

**Comment by usvgmani** [comment]
This helm was not just local install it was installing to a remote cluster as well, #788 is about local dev setup, do we have instructions for deploying to a remote k8s cluster?

**Comment by ldelossa** [comment]
@usvgmani we have decided not to be opinionated about the way you run Clair in production. That being said you can get an general idea of deployment via the helm charts in local development. We will only be supporting local development from this repository moving forward.

**Comment by tsturzl** [comment]
Honestly I don't think it's a "opinionated" thing, it's just that there is literally no correct documentation on starting clair at all.

**Comment by ldelossa** [comment]
@tsturzl I see, was this documentation not sufficient: https://github.com/coreos/clair/blob/master/Documentation/running-clair.md 

While the `helm` and `docker compose` portions are now irrelevant, the docker source build are. I will update these docs to remove helm and docker compose as we've removed those from master.

**Comment by swatimaruvada** [comment]
Can someone please update the document for starting clair? The Docker snippet URL doesnt seem to work and since helm & docker compose are not valid now it is not very clear how to use clair
Thanks !

**Comment by ldelossa** [comment]
@swatimaruvada can you give me a bit more detail on whats wrong with the current Docker documentation?

**Comment by garthoid** [comment]
Also the local section to get Clair running with docker-compose has an invalid link to the docker compose file.

https://raw.githubusercontent.com/coreos/clair/master/contrib/compose/docker-compose.yml

Returns not found.

**Comment by jwlogemann** [comment]
The docker-compose.yml is located here: https://raw.githubusercontent.com/coreos/clair/v2.0.8/docker-compose.yml

**Comment by ldelossa** [comment]
@jwlogemann @garthoid @swatimaruvada 

Is the usage of docker compose to get Clair running for local development? Or are you attempting to use docker compose for a production deployment? As stated above we were phasing out "contrib" directory in Clair and focusing on local development via minikube/docker-for-desktop.

**Comment by majinghe** [comment]
@ldelossa 
Hi team
I also met the same issue when i try to install clair on my k8s cluster according to the instructions on the  `https://github.com/coreos/clair/blob/master/Documentation/running-clair.md`. 
```
git clone https://github.com/coreos/clair
cd clair/contrib/helm
cp clair/values.yaml ~/my_custom_values.yaml
vi ~/my_custom_values.yaml
helm dependency update clair
helm install clair -f ~/my_custom_values.yaml
```

Clone step is ok, and then 
```
$ cd clair/contrib/helm
cd: clair/contrib/helm: No such file or directory
```
I found there is no `contrib` directory actually, after i exec `find . -name "helm" `, i found the helm files exist in `local-dev/` dir, there are two charts, one is `clair-pg `, another is `clair`. If i enter into the `clair dir`, and exec `$ helm install clair -f values.yaml` ,it shows `Error: failed to download "clair"`. Another question for step `vi ~/my_custom_values.yaml`, does it change anything for file `~/my_custom_values.yaml`? So is there any available and right instructions to install clair on k8s?
Thanks very much.

**Comment by adamcohen** [comment]
I'm trying to follow the [local-development instructions](https://github.com/coreos/clair/blob/92172487e741d9228357b02c3e570727f8d198c2/Documentation/local-development.md) and have installed the following on `OS X Mojave (10.14.6)`:

- `docker-desktop v2.1.0.0 (36874)`
- `Docker Engine 19.03.1` (via docker-desktop)
-  `kubernetes v1.14.3` (via docker-desktop) 
- `helm v2.14.3 (0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085)`

When I run `make deploy-local`, I get the following error reported in my `docker-dashboard`:

![image](https://user-images.githubusercontent.com/279925/62732695-fbd86d80-b9f2-11e9-8476-38ffb92cfbfa.png)

```
Container image "clair-local:latest" is not present with pull policy of Never
Error: ErrImageNeverPull
```

Can anyone please tell me what I'm doing wrong here? Thanks!
