### ISSUE TITLE
add a `ListVulnerabilities` API

### ISSUE THREAD

**Issue by liangchenye** [quay/clair#80]
When I use Clair, sometimes I want to know whether my images are really secure or just because my CVE database is empty, so I try to read my CVE database. I found that Clair does not have such API yet. There is a similar API (list namespace), I think maybe we can add this.  I already work on it in my repo (liangchenye/clair:getvulns), now the status is 'in progress'. 

@Quentin-M  @jzelinskie what do you think about this API?

**Comment by Quentin-M** [comment]
Hi,

That makes sense to me!
I looked a bit at your branch, I think that this API call should be paginated (see the notification code).

**Comment by jzelinskie** [comment]
@liangchenye I can see the use for `ListVulnerabilities` but for the scenario you described, would a better solution be to have an "last updated" field on the namespaces to see the last time a fetcher ran for it?

**Comment by liangchenye** [comment]
@jzelinskie yes, and that is another API:  get the metainfo for a given namespace.

Something like this:
GET http://localhost:6060/v1/namespaces/debian%3A8

{ "last_updated": ...
  "vulns_count": 1000
}

**Comment by Quentin-M** [comment]
#82 Merged. I'm closing this issue :)
