### ISSUE TITLE
RFE: Add option to filter only vulnerable packages

### ISSUE THREAD

**Issue by Allda** [quay/clair#807]
### Description of Problem / Feature Request
In some cases users are interested only if their container has/hasn't any vulnerable packages. It would be great to add option to `/ancestry/<name>` API to filter only packages which have any vulnerability. It would also reduced response size and requests would be faster.

### Expected Outcome

Add `only_vulnerable=True` option to `GET /ancestry/<name>` to filter only vulnerable packages.

### Actual Outcome

API `GET /ancestry/<name>` always returns all ancestry features.

### Environment

N/A

- Clair version/image: master branch
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
