### ISSUE TITLE
grpc is failing when ancestry response is bigger than 4MB

### ISSUE THREAD

**Issue by Allda** [quay/clair#809]
### Description of Problem / Feature Request

grpc is failing when ancestry response is bigger than 4MB

### Expected Outcome

Ancestry GET request would return the whole ancestry with no errors.

### Actual Outcome

ancestry `GET` request fails with: 
`b'{"error":"grpc: trying to send message larger than max (4763343 vs. 4194304)","code":8}'`
This is probably caused by default constant which can be overridden.
https://github.com/grpc/grpc-go/blob/master/clientconn.go#L96
### Environment

- Clair version/image: v3 - master branch
- Clair client name/version: v3 - master branch
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 3.11
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by ldelossa** [comment]
@Allda 
Believe the correct thing to do here would be implement message chunking to the client. I will have to take a look at this. 

@jzelinskie do we see this as a release blocker ?

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
