### ISSUE TITLE
Docker-Compose Misleading Documentation

### ISSUE THREAD

**Issue by ThunderSon** [quay/clair#815]
### Description of Problem / Feature Request

The [documentation](https://github.com/coreos/clair/blob/master/Documentation/running-clair.md#docker-compose) specifies in the first line how to download the config file from master. Master doesn't contain that file and it only exists in releases.

### Expected Outcome

Latest configuration file.

### Actual Outcome

404 not found

### Environment

N/A

**Comment by ThunderSon** [comment]
Hello! I didn't notice the addition of the tags. Is anyone handling this issue? Has it been fixed in any other issues?

**Comment by jzelinskie** [comment]
I don't think this has been fixed yet. Looks like a good first issue for anyone interested.

**Comment by digglife** [comment]
I think it's already been fixed.

**Comment by ThunderSon** [comment]
@digglife it no longer exists, so to say? I wasn't keeping track, if they don't use `docker-compose` I believe this can be closed.

**Comment by jkhalilkayak** [comment]
Thanks for the feedback.
I believe we found the issue, it was NIST retiring their XML feed and
replacing it with a JSON API.
I posted the link to the fix (by someone else) and now I am working on
fixing it.

Thanks again for your help.

**Comment by digglife** [comment]
@ThunderSon Yes, the guide about `docker-compose` was deleted. So, kind of fixed, I guess.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
