### ISSUE TITLE
Bug: database query with more than 65535 parameters fails

### ISSUE THREAD

**Issue by Allda** [quay/clair#819]
### Description of Problem / Feature Request

When scanning images with lot of installed features and namespaces there is a chance that database query fails because it has too much parameters. This needs be fixed because Clair returns non 200 code and image is not scanned properly.

### Expected Outcome

Clair stores image features to database with no limitation. Database query should be optimized to allow process big images.

### Actual Outcome
Function `saveLayerChange()` returns following error message:
`pq: got 78672 parameters but PostgreSQL only supports 65535 parameters`

It seems that the bug is in `PersistFeatures()` because it tries to save all layer features and their keys.

### Environment

- Clair version/image:  latest master branch
- Clair client name/version: latest master branch
- Host OS: alpine:3.8
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 3.11
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by Allda** [comment]
This seems to be related: https://github.com/lib/pq/blob/master/conn.go#L1269

**Comment by Allda** [comment]
Today I noticed similar issue related to database query limits:
`"error":"pq: stack depth limit exceeded"`
This error happens when Clair tries to get namespaces here: https://github.com/coreos/clair/blob/master/database/pgsql/namespace/namespace.go#L88

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
