### ISSUE TITLE
HTTP Connection leak in Clair

### ISSUE THREAD

**Issue by leogps** [quay/clair#821]
### Description of Problem
When creating layers for about 1000 Docker images in Clair from a Docker Registry, seeing the following error:
```
{"Event":"could not download layer","Level":"warning","Location":"driver.go:130","Time":"2019-07-11 00:32:33.766015","error":"G
et https://k8s-registry.htiol:443/v2/ubuntu/blobs/sha256:6abc03819f3e00a67ed5adc1132cfec041d5f7ec3c29d5416ba0433877
547b6f: dial tcp 172.20.80.172:443: connect: cannot assign requested address"}

```

When further investigating, I am seeing that Clair is unable to make any more connections to the registry because it has already made about 28,000 HTTP Connections to the Docker Registry (to download the layers, blobs).
For some reason, all the connections are in ESTABLISHED state, they do not go into CLOSE_WAIT or TIME_WAIT state for several days.

This can be easily reproduced even with few images, create layer in Clair for a few images and run: 
Get the PID of the clair container
`docker inspect -f '{{.State.Pid}}' clair`
And lookup active HTTP Connections from clair using netstat for the pid likewise:
```
nsenter -t 12056 -n netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 local-158:58280          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:55149          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:50016          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:47478          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:38326          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:38378          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:36041          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:55703          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:35268          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:46583          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:58062          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:50803          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:42218          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:58589          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:47718          k8s-registry.htio:https ESTABLISHED
...
...
...
...
......
tcp        0      0 local-158:36644          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:57889          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:36682          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:52481          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:37947          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:54123          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:60705          k8s-registry.htio:https ESTABLISHED
tcp        0      0 local-158:48633          k8s-registry.htio:https ESTABLISHED
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node   Path
```

The total number of connections are ~28239. See attached file.
[clair_connection_leak_bug-netstat.txt](https://github.com/coreos/clair/files/3388297/clair_connection_leak_bug-netstat.txt)

### Expected Outcome

Clair should either close the HTTP Connections or reuse them correctly. The number of active connections should not grow to 20K.

### Actual Outcome

HTTP Connections are neither closed not reused.

### Environment

- Clair version/image: v2.0.7
- Clair client name/version: N/A (Direct API Access)
- Host OS: CentOS 7
- Kernel (e.g. `uname -a`): Linux <redacted> 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`): N/A
- Docker version: Docker version 1.13.1, build b2f74b2/1.13.1
- Helm version (use `helm version`): N/A
- Network/Firewall setup: N/A

**Comment by glb** [comment]
@ldelossa are you still looking at this? I might have some cycles to take a look, if you have any thoughts it would be great to hear them.

**Comment by yocum137** [comment]
Will this be resolved in Clairv4?

**Comment by ldelossa** [comment]
@yocum137 v4 is a rewrite, so all signs point to yes.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
