### ISSUE TITLE
Allow ext/vulnsrc sources to be imported + not automatically injected.

### ISSUE THREAD

**Issue by clrprod** [quay/clair#824]
### Description of Problem / Feature Request

If you're attempting to do something interesting with one the clair vulnerability srcs (i.e. augment a vulnerability with a last fetched timestamp, or run a single fetcher through a different vulnerability proxy), it's relatively difficult to wrap the underlying vulnerability source. This is because the type is provide, and the import automatically registers the updater with clair. If the updater types were made public, and there was some way to control automatic registration (whether via a global config, or a dedicated library), you could wrap the clair vulnerability source much more easily.
### Expected Outcome

I could inject a custom http client and extract information from it which is fed into clair.

### Actual Outcome

There is a limited amount of possible dependency injection (mostly http.DefaultClient), as well as no ability to import a clair updater, or avoid having it register itself for execution.

### Environment
N/A

**Comment by clrprod** [comment]
And for reference I'd be happy to do this if clair thinks this is worth doing.

**Comment by jzelinskie** [comment]
I see your point. The advice in the past has been that you could copy the main package from Clair (`./cmd/clair`) and adjust the imports to include your your chosen upstream extensions and any custom ones. I can see how the copy and pasting here would be losing the inability to rebase cleanly. I'm not opposed to discussing alternative designs that could avoid these pitfalls, but I'd rather the solution be more flexible than just solving your specific use-case.

**Comment by clrprod** [comment]
What solution are you thinking of?

One option is to make each source that gets registered public (which
shouldn't hurt anything), and then add a new function call to make the
init() register call do nothing (likely in the library that implements the
register call).

Another option is to make the items public, and move the register call to a
second file in the same folder - this allows you to just blacklist that
file to prevent registration.

Another option is to make the source public, and then have another folder /
file which does the registration (maybe swapping the names to prevent
breakages), so that you can import the file without automatic registration
if desired.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
