### ISSUE TITLE
pq: current transaction is aborted, commands ignored until end of transaction block

### ISSUE THREAD

**Issue by Allda** [quay/clair#826]
### Description of Problem / Feature Request
When getting ancestry info using `GET /ancestry/<name>` database layer sometime throws following error message:

`{"Description":"searchNamespacedFeaturesVulnerabilities","Event":"database: handled database error","Level":"error","Location":"error.go:56","Time":"2019-07-30 12:14:29.097862","error":"pq: current transaction is aborted, commands ignored until end of transaction block"}`

Based on what I have read about this error message is seems that some previous database query was not handled correctly so the next query is blocked.

### Expected Outcome

Clair should not get database to state when it blocks other queries.

### Actual Outcome

Clair blocks database so other queries can't be executed in same database session.

### Environment

- Clair version/image: latest master branch
- Clair client name/version: latest master branch
- Host OS: alpine:3.8
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 3.11
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by Allda** [comment]
It seems that it is failing because database queries takes a long time to execute and connection is interrupted because of timeout. We should consider updating database indexes because for example this query can take over 1 minute:

```
SELECT vanf.namespaced_feature_id, v.name, v.description, v.link, 
		v.severity, v.metadata, vaf.fixedin, n.name, n.version_format
	FROM vulnerability_affected_namespaced_feature AS vanf, 
		Vulnerability AS v,
		vulnerability_affected_feature AS vaf,
		namespace AS n
	WHERE vanf.namespaced_feature_id = ANY($1)
		AND vaf.id = vanf.added_by
		AND v.id = vanf.vulnerability_id
		AND n.id = v.namespace_id
		AND v.deleted_at IS NULL
```

**Comment by KeyboardNerd** [comment]
it might be that this:
```
WHERE vanf.namespaced_feature_id = ANY($1)
```
contains too many things

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
