### ISSUE TITLE
Clair is not Detecting  vulnerabilities as per their CVSS Scores

### ISSUE THREAD

**Issue by Avy4140** [quay/clair#830]
### Environment

- Clair version/image: quay.io/coreos/clair:v2.0.5
- Clair client name/version: https://github.com/arminc/clair-scanner
- Host OS:  Debian
- Kernel (e.g. `uname -a`): Linux banking-sheep-clair-74589f8bfb-4wt4q 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 Linux (where hostname `banking-sheep-clair-74589f8bfb-4wt4q` is the pod name)
- Kubernetes version (use `kubectl version`): 1.12.9
- Helm version (use `helm version`): 2.14.2 
- Network/Firewall setup:

**Comment by jzelinskie** [comment]
Hey there!

Can you describe the problem in a little more detail?

Clair should report both the severity from the vulnerability source (the official redhat/debian/ubuntu/etc tracker) with the CVSS score simply as additional metadata.
