### ISSUE TITLE
Error on docker-desktop OS X while following Local Development instructions

### ISSUE THREAD

**Issue by adamcohen** [quay/clair#832]
### Description of Problem / Feature Request

I'm encountering an error while following the [local-development instructions](https://github.com/coreos/clair/blob/92172487e741d9228357b02c3e570727f8d198c2/Documentation/local-development.md) instructions

### Expected Outcome

Functioning Clair container on the local Kubernetes instance

### Actual Outcome

Receiving the following error in `docker-desktop`

![image](https://user-images.githubusercontent.com/279925/62732695-fbd86d80-b9f2-11e9-8476-38ffb92cfbfa.png)

```
Container image "clair-local:latest" is not present with pull policy of Never
Error: ErrImageNeverPull
```

### Environment

- Clair version/image: 

      source SHA 35191d63dd8d088cd81aa1d7655d333f6b8202c1

- Clair client name/version: Unknown

- Host OS: 

      OS X Mojave (10.14.6)

- Kernel (e.g. `uname -a`): 
      
      18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

- Kubernetes version (use `kubectl version`): 

      Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", 
      GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean",
      BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", 
      Platform:"darwin/amd64"}

      Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", 
      GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", 
      BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", 
      Platform:"linux/amd64"}

- Helm version (use `helm version`): 

      Client: &version.Version{SemVer:"v2.14.3", 
      GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

      Server: &version.Version{SemVer:"v2.14.3", 
      GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

- Network/Firewall setup: Firewall disabled, docker-desktop OS X running kubernetes

**Comment by ralgozino** [comment]
Hello @adamcohen , I was having the same issue testing `make deploy-local` on Minikube on MacOS.

I found a workaround, if you use the Minikube docker deamon the image built is pushed correctly and then it can be pulled by Minikube.

In my case I was using a "named" profile with minikube instead of the default, it might be the culprit.

You can try by running the following command:
`eval $(minikube --profile <your profile name> docker-env)`

and then `make deploy-local`

I hope that helps.

**Comment by isaac-carbo** [comment]
I'm having the same issue. Any solutions if minikube is not installed?

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
