### ISSUE TITLE
Running Clair doc doesn't discuss how to scan

### ISSUE THREAD

**Issue by mulakkalfaizal** [quay/clair#835]
### Description of Problem / Feature Request

currently, in the readme, you have details about how to start the Clair container and postgress. But there is no information on how to scan docker images.

Please guide me to the correct section if I am wrong.

### Expected Outcome

Need information regarding how i can scan the docker images also.

### Actual Outcome

Only have information to start the clair , postgress container.

### Environment

- Clair version/image: 
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by jzelinskie** [comment]
The [Getting Started section](https://github.com/coreos/clair#getting-started) links to the [doc on running Clair](https://github.com/coreos/clair/blob/master/Documentation/running-clair.md).

This document definitely needs to highlight the fact that this repository doesn't support any scanners, but there are third party ones linked in our [integrations doc](https://github.com/coreos/clair/blob/master/Documentation/integrations.md).

**Comment by gopurx** [comment]
Do we have any update on this? any references on how to run the scanner?

**Comment by brphelps** [comment]
I think if you compare the documentation on clair's pages to an alternative (tern in this case) there's a single command someone can run to scan a local image:
![image](https://user-images.githubusercontent.com/10023676/69294214-e06b2a00-0bbf-11ea-8085-a0c19d38e921.png)

Ideally that would be present somewhere in clair doc as well, I'm not really seeing it on my first browse through.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
