### ISSUE TITLE
Does clair work with windows docker images?

### ISSUE THREAD

**Issue by vksandeep** [quay/clair#836]
While trying out Clair with windows 2016 docker images, getting an error while retrieving layers. The setup seems to work fine with Linux images. Does the product support windows?

--------- more details ----------
----> HTTP REQUEST:
POST /v1/layers HTTP/1.1
Host: coreo-Clair-xxxxxxxxxxxxxxxxxxxxxxx.us-west-1.elb.amazonaws.com:6060

<---- HTTP RESPONSE:
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Date: Fri, 23 Aug 2019 01:43:32 GMT
Server: clair

{"Error":{"Message":"could not find layer"}}

Failed to analyze using API v1: push image https://xxxxxxxxx.dkr.ecr.us-west-1.amazonaws.com/v2/xxxxxxxxxxxxxxx:latest to Clair failed: push error 400: {"Error":{"Message":"could not find layer"}}

Failed to analyze using API v3: push image https://xxxxxxxxx.dkr.ecr.us-west-1.amazonaws.com/v2/xxxxxxxxxxxxxxx:latest to Clair failed: rpc error: code = Unavailable desc = transport is closing

Failed to analyze, exiting

-------------------------------------------

**Comment by jzelinskie** [comment]
Technically Clair can work with Windows images, but we don't have any explicit data sources or code to parse software out of a Windows image, so effectively you will not get any results.

**Comment by AakarshitAgarwal** [comment]
clair timeout 1m0s
docker timeout: 1m0s
no whitelist file
Analysing 10 layers

Failed to analyze using API v1: push image to Clair failed: push error 400: {"Error":{"Message":"could not find layer"}}


Failed to analyse using API v3: push image to Clair failed: rpc error: code = Unavailable desc = transport is closing

docker --version
Docker version 25.0.3, build 4debf41

had the same issue
