### ISSUE TITLE
Does clair support Azure ACK?

### ISSUE THREAD

**Issue by daxin09pp** [quay/clair#848]
### Description of Problem / Feature Request
I have an Azure ACK, and I want to scan the image inside.
Does clair support this now? Is there any document for reference?

### Environment
N/A

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
