### ISSUE TITLE
False negatives

### ISSUE THREAD

**Issue by kaurbhupinder** [quay/clair#855]
### Description of Problem / Feature Request
Clair is not detecting any vulnerabilities in the Linux package. Is there any specific reason why Clair ignores that package?

### Environment

Clair version/image:
arminc/clair-local-scan :v2.0.8_0ed98e9ead65a51ba53f7cc53fa5e80c92169207
Clair client name/version:
Host OS: Ubuntu 18.04
Kernel (e.g. uname -a): 4.18.0-25-generic
Kubernetes version (use kubectl version): no
Helm version (use helm version): no
Network/Firewall setup: no

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
