### ISSUE TITLE
Set connection string for database?

### ISSUE THREAD

**Issue by crdil** [quay/clair#86]
I'm trying to get clair docker to connect to my postgres container with at connection string, but it won't work.

My connection string is setup like this
`source: postgresql://postgres:XXXXXX@172.17.0.4/clairdb`

I also tried to run without the database clairdb which I created manually (not sure if that is needed), but I get the same error when I'm trying to run the container.

```
2016-03-02 22:10:10.950887 I | pgsql: running database migrations
2016-03-02 22:10:10.955685 E | pgsql: pq: SSL is not enabled on the server
2016-03-02 22:10:10.955803 C | main: database: could not open database

```

I haven't found any documentation on how to set this up. What am I doing wrong

**Comment by Quentin-M** [comment]
Hi,

Yeah, that's because Clair tries to connect to your PostgreSQL database using SSL (which is the default behavior with PostgreSQL) but your server doesn't support it. I'd use that instead:

```
source: "host=172.17.0.4 sslmode=disable dbname=clairdb user=postgres password=XXXXX statement_timeout=60000"`
```

I explicitly disabled SSL and added a statement timeout, just in case.

**Comment by crdil** [comment]
Worked great, thanks
