### ISSUE TITLE
CVE list synchronization

### ISSUE THREAD

**Issue by holyhope** [quay/clair#862]
### Description of Problem / Feature Request

At [OVH](https://www.ovh.com) we would like to deliver full [Harbor stack](https://github.com/goharbor/harbor): <https://labs.ovh.com/private-registry>
So we run an instance of Clair for each clients in order to isolate clients scan results.
When Clair instances start CVE list update, many connections are open.

### Expected Outcome

Link multiple Clair instances to reduce external connections.

One of the following solution would be great:

1. Single CVE database for multiple instances (whereas results/notifications/... are isolated).
2. Clair is able to synchronize CVE list with other Clair instances (new Clair vulnerability source).
3. Specific endpoint to synchronize Clair instances.

### Actual Outcome

All Clair instances pull external repositories by their own opening multiple connections.

### Environment

[goharbor/clair-photon](https://hub.docker.com/r/goharbor/clair-photon/) in Kubernetes.

**Comment by holyhope** [comment]
To be honest, I did not check if a notification to another Clair instances does the trick (sinceI do not know yet how notification works).
Also it would be painful to configure with many instances.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
