### ISSUE TITLE
Amazon Linux namespace incorrectly mapped

### ISSUE THREAD

**Issue by andrewsharon** [quay/clair#866]
### Description of Problem / Feature Request

Clair nondeterministically parses Amazon Linux namespace name to be either "amzn" or "amazon".

Both osrelease and redhatrelease detectors return non-nil namespaces for Amazon Linux 2. In the redhatrelease detector, `/etc/system-release` is read containing the string `Amazon Linux release 2 (Karoo)` which is a match against redhatrelease detector's regex. This returns the namespace name of "amazon". 

### Expected Outcome

Amazon Linux images should map to the namespace name "amzn"

### Actual Outcome

Clair sometimes maps Amazon Linux images to the namespace name of "amazon".

### Environment

- Clair version/image: v2.0.9
- Clair client name/version: N/A
- Host OS: Amazon Linux
- Kernel (e.g. `uname -a`): Linux 4.9
- Kubernetes version (use `kubectl version`): N/A
- Helm version (use `helm version`): N/A
- Network/Firewall setup: N/A

**Comment by CinchBlue** [comment]
Nice!

**Comment by andrewsharon** [comment]
One way to fix this issue is to convert `"amazon"` to `"amzn"` in the `redhatrelease.go` detector. 

``` golang
diff --git a/ext/featurens/redhatrelease/redhatrelease.go b/ext/featurens/redhatrelease/redhatrelease.go
index 0dabc3f..344f751 100644
--- a/ext/featurens/redhatrelease/redhatrelease.go
+++ b/ext/featurens/redhatrelease/redhatrelease.go

@@ -72,6 +74,21 @@ func (d detector) Detect(files tarutil.FilesMap) (*database.Namespace, error) {
                // Atempt to match CentOS.
                r = centosReleaseRegexp.FindStringSubmatch(string(f))
                if len(r) == 4 {
+                    	if strings.ToLower(r[1]) == "amazon" {
+                       	r[1] = "amzn";
+                    	}
                        return &database.Namespace{
                                Name:          strings.ToLower(r[1]) + ":" + r[3],
                                VersionFormat: rpm.ParserName,
```

A more robust solution seems to be ordering the detectors such that the `osrelease` detector runs first, making the namespace discovery for the layer deterministic. Without this change sometimes the "amzn" namespace is chosen, and other times "amazon" is, depending upon whether `redhatrelease` or `osrelease` detector runs first.

I wanted to get some thoughts on this since I believe these detectors were designed so they could be run in any order.
