### ISSUE TITLE
OLD image is not getting scan however new image scan looks good

### ISSUE THREAD

**Issue by cmpmohan** [quay/clair#868]
### Description of Problem / Feature Request

OLD image is not getting scan however new image scan looks good

### Expected Outcome

ALl image need to be scan

### Actual Outcome

Only new image scan is working

### Environment

- Clair version/image:  3.0.3
- Clair client name/version:  
- Host OS: sles 12
- Kernel (e.g. `uname -a`): 
 4.4.180-94.97-default #1 SMP Tue Jun 11 08:19:03 UTC 2019 (c0632f4) x86_64 x86_64 x86_64 GNU/Linux

- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup: 
  quay and clair is running as container in same VM

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
