### ISSUE TITLE
Compare the results of Anchore and Clair. 

### ISSUE THREAD

**Issue by daxin09pp** [quay/clair#870]
#629 # Description of Problem / Feature Request

[clair-result-postgres-9.5.1.txt](https://github.com/coreos/clair/files/3792411/clair-result-postgres-9.5.1.txt)
[anchore-result-postgres-9.5.1.txt](https://github.com/coreos/clair/files/3792409/anchore-result-postgres-9.5.1.txt)

I am currently evaluating a suitable container scan tool. I am now comparing Anchore and Clair. I used two tools to scan postgres:9.5.1. There were some differences. 
**Clair**: 19 Low, 43 Negligible, 83 Unknown
**Anchore**: 2 Low, 159 Negligible, 467 Unknown

Using two tools to scan our own images, the results are somewhat different:
**Clair**: 36 Low 58 Negligible 153 Unknown
**Anchore**: 4 Low 132 Negligible   191 Unknown

It seems that Anchore's Low has fewer issues and Unknown has more issues.

Now the problem is that I can't judge which tool is more suitable for my requirements based on the number of problems.

How do I determine which tool is more accurate and which has more false positives?

In addition, do you need to fix the problem scanned out, especially the problem of Unknown? How does everybody handle it?

Attached is the result of my scan of postgres:9.5.1 using two tools.

Look forward to your answers. Thank you.

### Environment
- Clair version/image:  quay.io/coreos/clair:latest
- Clair client name/version: Klar
- Host OS: Ubuntu
- Kernel (e.g. `uname -a`): 4.15.0
- Kubernetes version (use `kubectl version`): N/A
- Helm version (use `helm version`): N/A
- Network/Firewall setup: N/A

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
