### ISSUE TITLE
NVD XML feed retired, impacts Clair v2

### ISSUE THREAD

**Issue by reasonerjt** [quay/clair#872]
Clair v2 uses NVD xml data feed but it's retired

https://nvd.nist.gov/General/News/XML-Vulnerability-Feed-Retirement

@ldelossa @jzelinskie
Is there plan to backport the change in master to v2 so that v2 can consume the json feeds?

### Environment

- Clair version/image: v2.0.9

**Comment by michmike** [comment]
seems like a dupe of https://github.com/coreos/clair/issues/863

**Comment by reasonerjt** [comment]
PR #876 seems fixes this issue in my env, @ldelossa @jzelinskie please kindly have a look

**Comment by reasonerjt** [comment]
Closing as the PR is merged.
