### ISSUE TITLE
Increased memory usage during update (v2.1.0)

### ISSUE THREAD

**Issue by thomas-schilling-adn** [quay/clair#878]
### Description of Problem / Feature Request

We have our Clair pods set to a memory limit of 1.5GiB and since updating from 2.0.9 to 2.1.0 we now had a few OOM kills during update. We never had this problem with versions <2.1.0 (AFAICT).

I assume this is related to the switch to JSON instead of XML?

Are there plans to reduce this memory usage? Do the new data sources contain more data? Or is is the JSON parser not streaming?

I can increase the memory limit but super spiky memory usage isn't very nice in a prod env.

### Expected Outcome

2.0.9 seemed to use about half the amount of peak memory.

![Screenshot 2019-11-11 at 11 35 35](https://user-images.githubusercontent.com/34234952/68581252-56f98080-0478-11ea-8632-38bd6122bcb4.png)

The orange and blue lines are after the update to 2.1.0

### Actual Outcome

A lot more memory used during updates.

### Environment

- Clair version/image: 2.1.0
- Clair client name/version: Klar
- Host OS: RHEL/Openshift
- Kernel: Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP

**Comment by tahriabd** [comment]
Same pb with docker Swarm i need to increase memory to 1.5G to parse nvd Json files. Any plans to reduce memory usage will be appreciated

**Comment by Bonko** [comment]
I can confirm the problem in AWS ECS.
The problem still exists in 2.1.2

**Comment by ragsonline** [comment]
Still facing same issue with v2.1.2
reaches 95% pod memory and gets restart eventually.

What you guys did atm?

**Comment by ggilley** [comment]
Clair is using way too much memory. Is anyone looking at this?

**Comment by ldelossa** [comment]
We are actively developing Clair V4 in the "development-4.0" branch. Our main focus at this. These memory issues are handled by buffering layers and security data to disk.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
