### ISSUE TITLE
API to trigger all updaters to run

### ISSUE THREAD

**Issue by mdraijer** [quay/clair#879]
> If you mean to call an API to trigger all updaters to run, there's no existing plan to do that.

_Originally posted by @KeyboardNerd in https://github.com/quay/clair/issues/649#issuecomment-435106384_

In the meantime did someone already conceive the plan to do this?
It gets really annoying to just _wait_ until Clair decides to do something. Not knowing whether or not it will ever, whether or not it works at all.
Especially when upgrading to the latest Clair version, after the version that was broken and could not get any updates... (for weeks...)

**Comment by ldelossa** [comment]
@mdraijer we are currently working on 
https://github.com/quay/claircore

The feature you speak of will be incorporated. 

We are planning a ClairV4 development branch and announcement within the next few weeks.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
