### ISSUE TITLE
undefined : prometheus.Handler

### ISSUE THREAD

**Issue by Zoulou8** [quay/clair#880]
Hi guys,

From the error I'm having and what I've found around, it seems like prometheus.Handler became promhttp.Handler. For now, I can't even do a "go get github.com/quay/clair/cmd/clair" without having the error you can see in the title.

So if someone can do something or have an idea so I could fix the issue I'm having, it would be appreciated

**Comment by ldelossa** [comment]
@Zoulou8 Which development branch are you referring to?

**Comment by Zoulou8** [comment]
I tried release-2.0 and master branches and I'm having the same error about Prometheus Handler

**Comment by vippujain** [comment]
I got the same error "src/github.com/quay/clair/api/v3/server.go:46:25: undefined: prometheus.Handler"

**Comment by savujevi** [comment]
Hello developers,

can you please tell me if there is any progress on this topic ?

Thank you for your help.

Best regards.
