### ISSUE TITLE
How to list out all layers details from quay registry for specific image via API or curl command?

### ISSUE THREAD

**Issue by cmpmohan** [quay/clair#882]
### Description of Problem / Feature Request

We are looking curl command/ API to list the layers respective image. we want to perform manual scan for each layers. 

### Environment

- Clair version/image: 
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by cmpmohan** [comment]
Can any one help me for my request?

**Comment by quickparser** [comment]
You can try this out:
https://www.nearform.com/blog/static-analysis-of-docker-image-vulnerabilities-with-clair/

I haven't had much luck with it, however. Partly because, my clair installation is not working as it should :)

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
