### ISSUE TITLE
do not support archlinux image

### ISSUE THREAD

**Issue by newthis** [quay/clair#885]
It seems that the latest clair does not support archlinux pacman package scanning.

**Comment by jeffrichie** [comment]
Seconding - would love to see this.

**Comment by kbrwn** [comment]
Arch security team needs publish CVE data in format like rss/atom/xml/rest for this to be possible. The old atom feed has been disabled: https://bugs.archlinux.org/task/65596

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
