### ISSUE TITLE
Support Red Hat UBI 8

### ISSUE THREAD

**Issue by rpnguyen** [quay/clair#889]
### Description of Problem / Feature Request

Support Red Hat Universal Base Image 8. Currently with clair:v2.1.2 this image returns no vulnerabilities

### Expected Outcome

Vulnerabilities are returned when scanning [registry.redhat.io/ubi8](https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8)

### Actual Outcome

No vulnerabilities are returned and namespace is detected as `enterprise:8` by `redhat-release` detector.

e.g. vim-minimal-8.0.1763-10.el8 has a [known vulnerability](https://access.redhat.com/errata/RHSA-2019:1619)
```shell
curl http://localhost:6060/v1/layers/ubi801-2?features&vulnerabilities
{
  "Layer": {
    "Name": "ubi801-2",
    "NamespaceName": "enterprise:8",
    "ParentName": "ubi801-1",
    "IndexedByVersion": 3,
    "Features": [{
      "Name": "vim-minimal",
      "NamespaceName": "enterprise:8",
      "VersionFormat": "rpm",
      "Version": "2:8.0.1763-10.el8",
      "AddedBy": "ubi801-1"
    },
    # snip...
    ]
  }
}
```

### Environment

- Clair version/image: quay.io/coreos/clair:v2.1.2
- Clair client name/version: curl
- Host OS: N/A
- Kernel (e.g. `uname -a`): N/A
- Kubernetes version (use `kubectl version`): N/A
- Helm version (use `helm version`): N/A
- Network/Firewall setup: N/A

**Comment by ldelossa** [comment]
@rpnguyen Thanks.
Are you aware if previous versions identified vulnerabilities for UBI 8 in versions previous to v2.1.2. Trying to understand if this a regression or you are filing novel bug.

**Comment by rpnguyen** [comment]
@ldelossa I don't know this information but my guess would be that it was not previously supported and this should be treated like a feature request.

I do know that ubi7 works today - the namespace is detected as `centos:7`

**Comment by ldelossa** [comment]
@rpnguyen 
cool, I'll start taking a look.

**Comment by ldelossa** [comment]
@rpnguyen 
I confirmed that we are pulling in RHEL8 vulnerability data. 
```
19	centos:8	rpm
```
This is the namespace in my database. 

Can you provide me with the json you `POST`'d to Clair - I'll use this with my own links to UBI8 image to test.

**Comment by rpnguyen** [comment]
I'm sorry, I'm traveling right now and won't be able to share this information until late next week. The layers I `POST`'d are the two layers in the registry.redhat.io/ubi8 image. The namespace was detected by the `redhat-release` detector as `enterprise:8` - have you been able to reproduce this result?

**Comment by ldelossa** [comment]
@rpnguyen from my stock instance of ClairV2 running, I do not see an enterprise:8 namespace. Let me check again.

**Comment by rpnguyen** [comment]
The image I'm using for testing is `registry.redhat.io/ubi8:8.0-122` (`@sha256:fc84b5febd328eccaa913807716887b3eb5ed08bc22cc6933a9ebf82766725e3`). I expect the output to be [these 35 vulnerabilities](https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.0-122
).

This image has two layers that I named `ubi801-1` and `ubi801-2`. I posted these two JSON docs to `/v1/layers`

```js
{ "Layer": {"Name": "ubi801-1", "Path": "LAYER_1_URL", "Format": "Docker"} }
{ "Layer": {"Name": "ubi801-2", "Path": "LAYER_2_URL", "Format": "Docker", "ParentName": "ubi801-1"} }
```

And then requested the vulnerabilities with a GET to `/v1/layers/ubi801-2?features&vulnerabilities`. The version of clair I'm running is the tag `quay.io/coreos/clair:v2.1.2`

Let me know if you need more information!
