### ISSUE TITLE
go get not working since v2.1.1

### ISSUE THREAD

**Issue by Bonko** [quay/clair#899]
### Description of Problem / Feature Request

We are importing github.com/quay/clair as a library in one of our projects in order to handle notifications.
When updating the dependency from versoin 2.0.9 to v2.1.2, go get fails.
It looks like a problem with versioning inside the project.

### Expected Outcome

Updating dependency works fine

### Actual Outcome

```
$ go get github.com/quay/clair@v2.1.2 
go: finding github.com v2.1.2 
go: finding github.com/quay v2.1.2 
go: finding github.com/quay/clair v2.1.2 
go: finding github.com/quay/clair v2.1.2 
go get github.com/quay/clair@v2.1.2: github.com/quay/clair@v2.1.2: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

### Environment

- Clair version/image: 2.1.1
- Clair client name/version:  -
- Host OS: -
- Kernel (e.g. `uname -a`): -
- Kubernetes version (use `kubectl version`): -
- Helm version (use `helm version`):  - 
- Network/Firewall setup: -
- Go version: go1.13.5 linux/amd64

**Comment by ldelossa** [comment]
@Bonko 
That release marks the change to go mod. If you are not familiar with go mod please see https://blog.golang.org/using-go-modules

You should remove Clair from your go path and try to build.

**Comment by Bonko** [comment]
I am new to go mod, but read the blog posts.
I even changed my project to use go mod because I was not able to update the clair library via dep caused by the recent changes.

The problem still exists when removing clair from the go path. Moving my project outside the go path does not help either.

When I remove the dependency to clair from my go.mod file and build the program with `go build ./...`, version 2.1.0 is added to the go.mod file instead of 2.1.2
```
github.com/quay/clair v2.1.0+incompatible
```

**Comment by hdonnay** [comment]
The actual name of the module is `github.com/quay/clair/v2`, so the correct command is

```
go get github.com/quay/clair/v2@v2.1.2
```

This is a weird rub because of modules disallowing anything other than v1 or v0 as the "implicit version." In this case, we'd already cut v2.x.x tags and so needed to make the module end in `v2`.

**Comment by Bonko** [comment]
Ah, my mistake. Sorry for this and thanks for your help. It works now.
