### ISSUE TITLE
when clair report get generated in HTML and we try to publish it into Jenkins using publish HTML viewer plugin , the visualization is shifted and not readable

### ISSUE THREAD

**Issue by urvashipareta15** [quay/clair#900]
Hi Team,

I am using your image  image: quay.io/coreos/clair:v2.0.6

 when it publish the report and when I see this report in jenkins HTML view using the plugin publishHTML . It gives me distorted view. all shifted  to the left and not at all readable.

When I download that HTML report and open it locally , I am able to see it in good format but this is not how it should respond, Is this becasue of the CSS getting use? 

have anyone found a solution to it how to use it ?

I have attached screenshot of how it looks.

![clair_report](https://user-images.githubusercontent.com/59609930/71898711-02286c80-3180-11ea-8b70-245511a9673b.jpg)

### Environment

- Clair version/image: 
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
