### ISSUE TITLE
Clair fails to pull from DockerHub

### ISSUE THREAD

**Issue by orlando-jamie** [quay/clair#915]
### Description of Problem / Feature Request

Hello. I am trying to use Klar to feed Clair to scan all images running inside my Kubernetes cluster. This works with all containers in my private repository. However, Clair seems to be running into issues when downloading from docker hub (Kubernetes itself finds and runs the container with no issue).

``` bash
klar docker.io/bitnami/postgresql:11.6.0-debian-10-r5
```

```
----> HTTP REQUEST:
GET /v2/bitnami/postgresql/manifests/11.6.0-debian-10-r5 HTTP/1.1
Host: docker.io
Accept: application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws


<---- HTTP RESPONSE:
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Age: 163
Connection: keep-alive
Content-Language: en
Content-Type: text/html; charset=UTF-8
Date: Mon, 10 Feb 2020 20:11:16 GMT
Etag: W/"1581362177"
Last-Modified: Mon, 10 Feb 2020 19:16:17 GMT
Link: <https://www.docker.com/not-found>; rel="canonical"
Link: <https://www.docker.com/not-found>; rel="revision"
Link: <https://www.docker.com/not-found>; rel="canonical"
Link: <https://www.docker.com/not-found>; rel="revision"
Server: nginx
Strict-Transport-Security: max-age=31536000
Via: 1.1 2f66aa06710fece8ed203ab0ea81eb56.cloudfront.net (CloudFront)
X-Amz-Cf-Id: HCHyJeLW7URWGVQEqpWzsdR3QigS5wGtGG5qoPXE4F6PGPOqoqx_Xw==
X-Amz-Cf-Pop: IAD89-C3
X-Cache: Error from cloudfront
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Ua-Compatible: IE=edge
X-Varnish: 1061769
```

### Expected Outcome

I would have expected clair to scan the container properly.

### Actual Outcome

It seems that Clair gets a 404 error from https://docker.io/v2/bitnami/postgresql/manifests/11.6.0-debian-10-r5 and ends up failing.

```
ImageV1 decode error
Can't pull image: invalid character '<' looking for beginning of value
```

### Environment

- Clair version/image: 
- Clair client name/version: quay.io/coreos/clair:v2.1.2
- Host OS: Kubernetes running on CentOS-7
- Kernel (e.g. `uname -a`): Linux 5.2.9-1.el7.elrepo.x86_64 #1 SMP Fri Aug 16 08:17:55 EDT 2019 x86_64 Linux
- Kubernetes version (use `kubectl version`): 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Helm version (use `helm version`): N/A
- Network/Firewall setup: N/A

**Comment by nycnewman** [comment]
Try using "klar bitnami/postgresql:11.6.0-debian-10-r5". You had an extra docker.io in image name that was wrong. Also make sure you set CLAIR_ADDR, DOCKER_USERNAME and DOCKER_PASSWORD correctly.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
