### ISSUE TITLE
The NIST Urls that Clair is pulling are invalid

### ISSUE THREAD

**Issue by jkhalilkayak** [quay/clair#916]
### Description of Problem / Feature Request

Clair fails to pull CVEs.
When I run the docker logs <clair id> I get the following result:

{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-02-11 13:19:19.059664","data feed name":"2019","error":"Get https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2019.meta: dial tcp 54.85.30.225:443: i/o timeout"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-02-11 13:19:49.060067","data feed name":"2020","error":"Get https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2020.meta: dial tcp 54.85.30.225:443: i/o timeout"}
{"Event":"update finished","Level":"info","Location":"updater.go:223","Time":"2020-02-11 13:19:49.060175"}
{"Event":"Not all updaters succeeded, sleep duration: 2h0m0s","Level":"warning","Location":"updater.go:136","Time":"2020-02-11 13:19:49.063915"}

when I curl'd the url:
https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2009.meta

it returned:

<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://nvd.nist.gov/General/News/XML-Vulnerability-Feed-Retirement-Phase-3">here</a></body>

no metadata.

### Expected Outcome
List of CVEs

### Actual Outcome
0 vulnerabilities found

### Environment
I am running Clair on a Linux

- Clair version/image: quay.io/coreos/clair:latest
- Clair client name/version: 
- Host OS: Linux
- Kernel (e.g. `uname -a`): Linux p4swarmnet001.som.kayak.com 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by jkhalilkayak** [comment]
https://nvd.nist.gov/General/News/New-NVD-CVE-CPE-API-and-SOAP-Retirement

So problem found, now waiting for a new clair release :(

**Comment by tckb** [comment]
any plans on this? because of this issue I can not use Clair :-/

**Comment by fireba11** [comment]
can't believe this is still open :-(

**Comment by fpytloun** [comment]
Any chance this gets fixed? How can anyone use Clair without NVD database?

**Comment by fireba11** [comment]
@fpytloun i stumbled over this evaluation harbor registry. those guys added trivy as a second scanner, maybe you want to have a look at that

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
