### ISSUE TITLE
Add Clair scanner in harbor

### ISSUE THREAD

**Issue by patsevanton** [quay/clair#917]
I installed harbor by rpm.
MrMEEE/harbor-rpm-ansible#4

build and run by instruction
https://github.com/quay/clair/blob/master/Documentation/running-clair.md
```
$ go get github.com/quay/clair/cmd/clair
$ $EDITOR config.yaml # Add the URI for your postgres database
$ ./$GOPATH/bin/clair -config=config.yaml
```

curl -XGET http://localhost:6060/status
``
{"status":{"detectors":[{"name":"dpkg","version":"1.0","dtype":"DETECTOR_D_TYPE_FEATURE"},{"name":"rpm","version":"1.1","dtype":"DETECTOR_D_TYPE_FEATURE"},{"name":"apk","version":"1.0","dtype":"DETECTOR_D_TYPE_FEATURE"},{"name":"alpine-release","version":"1.0","dtype":"DETECTOR_D_TYPE_NAMESPACE"},{"name":"apt-sources","version":"1.0","dtype":"DETECTOR_D_TYPE_NAMESPACE"},{"name":"lsb-release","version":"1.0","dtype":"DETECTOR_D_TYPE_NAMESPACE"},{"name":"os-release","version":"1.0","dtype":"DETECTOR_D_TYPE_NAMESPACE"},{"name":"redhat-release","version":"1.0","dtype":"DETECTOR_D_TYPE_NAMESPACE"}]}}[root@harbor-apatsev ~]# 
``

health:
```
curl -i http://localhost:6061/health
HTTP/1.1 200 OK
Server: clair
Date: Thu, 13 Feb 2020 06:29:05 GMT
Content-Length: 0
```

![image](https://user-images.githubusercontent.com/10828883/74408134-d161e400-4e5d-11ea-95c9-4c1ab96cc121.png)

**Comment by danielpacak** [comment]
Hey @patsevanton I'm not familiar with the harbor-rpm-ansible installer but I know a thing or two about vulnerability scanners in Harbor.

In the **Add Scanner** dialog you're supposed to configure the URL endpoint of [Harbor Scanner Adapter for Clair](https://github.com/goharbor/harbor-scanner-clair) not the endpoint of Clair.

When you click Scan is Harbor UI, Harbor calls harbor-scanner-clair, which in turn, calls Clair.
This indirection is to allow other scanner to be plugged in. See the list of other scanners here https://goharbor.io/docs/1.10/install-config/harbor-compatibility-list/

**Comment by ldelossa** [comment]
@patsevanton I'm kindly closing this ticket. Please bring this integration issue up in the Harbor git repository.
