### ISSUE TITLE
Optimize the Fetching of Debian Security Bug Tracker

### ISSUE THREAD

**Issue by Quentin-M** [quay/clair#92]
As it is now, each time that Debian vulnerabilities are updated, we upsert all of them - and it takes time. It would be great to diff the vulnerabilities and only upsert the ones that actually need to be upserted.

**Comment by MatthewHinton56** [comment]
Is this still an active issue, and if so can I claim it. Also, it would great to have a starting point, such as files to look at.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
