### ISSUE TITLE
error: failed to extract data from path when using openshift builder image

### ISSUE THREAD

**Issue by gorantornqvist** [quay/clair#923]
### Description of Problem

Get this error in clair pod when a new tag is pushed to quay: 
```
{"Event":"failed to extract data from path","Level":"error","Location":"worker.go:122","Time":"2020-02-27 12:11:39.242216","error":"tarutil: could not extract the archive","layer":"9fb9468e-1e23-4fee-900a-70c08c01824c.780c19ff-479a-429c-ac89-e475a2a4b263","path":"https://quay.apps.mydomain.com/v2/demo/tasks-app/blobs/sha256:adadc56a4732b5c976228c1dec268c2666342999aa8dc37c800f3e0e9dc3a244"}
```
Its a openshift S2I build with registry.redhat.io/jboss-eap-7/eap72-openshift as build image

If (on my workstation with docker) I pull the image , retag and push it again to a different repo in quay it passes so not sure if its related to the openshift builder image (running openshift v4.3.1)

### Expected Outcome

Scan goes through

### Actual Outcome

Scan fails with error "Unable to scan" in Quay and above message in clair pod log

### Environment

- Clair version/image: quay.io/redhat/clair-jwt:v3.2.0 (Quay version/image: quay.io/redhat/quay:v3.2.0)
- Clair client name/version: not sure
- Host OS: Openshift 4.3.1

**Comment by ldelossa** [comment]
@gorantornqvist 

It is typically okay to see an error like this, it means that layer may not be a tar blob and could be a config layer.
