### ISSUE TITLE
Clair opensuse image scanning 

### ISSUE THREAD

**Issue by samuelmazilu2** [quay/clair#959]
### Description of Problem / Feature Request
I'm trying to scan a docker image based on openSUSE Leap 15.1 and when running the scan I receive the following error: 
 Could not fetch vulnerabilities. No features have been detected in the image. This usually means that the image isn't supported by Clair
In the logs I am seeing the following message: layer content has already been processed in the past with older engine. skipping analysis" and cannot find something else. I am stuck, can someone help?

### Environment
- Clair version/image: latest 79f851f41934
- Clair client name/version: wdijkerman/clair-scanner
- Host OS: Windows 10

**Comment by ldelossa** [comment]
@samuelmazilu2 this will be supported in ClairV4, you can obtain our alpha builds here:
https://quay.io/repository/projectquay/clair?tag=latest&tab=tags

We need a Suse matcher to be implemented. If you are interested in implementing this right away open a ticket in https://github.com/quay/claircore/ which is the engine powering ClairV4.
