### ISSUE TITLE
Error 404 downloading RHEL3.xml on v2.1.2

### ISSUE THREAD

**Issue by hetpats** [quay/clair#964]
### Description of Problem / Feature Request

{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2020-04-02 16:45:25.204396","error":"received 404 code downloading https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL3.xml","updater name":"rhel"}

### Environment
Production

- Clair version/image: v2.1.2
- Clair client name/version: clair scanner v11
- Host OS: Amazon Linux running clair container
- Kernel (e.g. `uname -a`): kernel-4.14.173-137.228.amzn2.x86_64 (Host OS)
- Kubernetes version (use `kubectl version`): NA
- Helm version (use `helm version`): NA
- Network/Firewall setup: Proxy configured in docker env vraible

**Comment by namloc2001** [comment]
Same here, using v2.1.2. I'm running this on OpenShift.

I tried this: https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL3.xml in my browser on a separate machine and got a 404:
![image](https://user-images.githubusercontent.com/30868661/78671226-ea739800-78d6-11ea-9532-6d824b8f1916.png)

**Comment by namloc2001** [comment]
Also, if you look at what is available here: https://www.redhat.com/security/data/oval/

RHEL3.xml isn't present.

**Comment by sdirbach** [comment]
Looks like this commit introduced the try to download this file (release branch for version 2.0)
https://github.com/quay/clair/commit/2ad2abc59b6b106ad474795a10f0167b86f98991#diff-ac1cd18df50532b1d209c439f4607811
Master looks good (at least better) btw.

**Comment by ldelossa** [comment]
Fixed with merge #988
