### ISSUE TITLE
an error occured when fetching update      updater name :ubuntu

### ISSUE THREAD

**Issue by hetpats** [quay/clair#965]
### Description of Problem / Feature Request

{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2020-04-02 16:45:24.282837","error":"could not download requested resource","updater name":"ubuntu"}
This Error Occurs on every update run

### Actual Outcome

production

### Environment

- Clair version/image: v2.12
- Clair client name/version: clair scanner v11
- Host OS: Amazon Linux2 running Clair container
- Kernel (e.g. `uname -a`): kernel-4.14.173-137.228.amzn2.x86_64
- Kubernetes version (use `kubectl version`): NA
- Helm version (use `helm version`): NA
- Network/Firewall setup: Proxy configured in docker container

**Comment by vladdoster** [comment]
Same issue here as well :cry:

**Comment by hetpats** [comment]
ubuntu updater is still failing can some on please help?
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2020-06-05 10:25:42.688390","error":"could not download requested resource","updater name":"ubuntu"}

**Comment by vladdoster** [comment]
> ubuntu updater is still failing can some on please help?
> {"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2020-06-05 10:25:42.688390","error":"could not download requested resource","updater name":"ubuntu"}

From what I can tell this is normal. Just give it some time to update it's DB and things will work out fine.

**Comment by ldelossa** [comment]
Can you please try with the latest version:
https://quay.io/repository/projectquay/clair-jwt?tag=latest&tab=tags v2.1.4

**Comment by Surkovsv** [comment]
Hello, I am using the latest version - v2.1.4 but still have a problem with ubuntu cve tracker. It seems to me that Ubuntu changed address of the tracker from  http://people.ubuntu.com/~ubuntu-security/cve/* to **https**://people.canonical.com/~ubuntu-security/cve/*


{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-06-17 13:11:30.874459","updater name":"rhel"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-06-17 13:11:31.825143","updater name":"oracle"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-06-17 13:11:32.502394","updater name":"amzn2"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-06-17 13:11:32.678763","updater name":"amzn1"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-06-17 13:12:24.009934","updater name":"debian"}
{"Event":"could not pull ubuntu-cve-tracker repository","Level":"error","Location":"ubuntu.go:174","Time":"2020-06-17 13:12:37.436439","error":"exit status 128","output":"Cloning into '.'...\nerror: RPC failed; curl 56 OpenSSL SSL_read: No error information\n"}

**Comment by vladdoster** [comment]
I do not think that is the issue.

Looking at `ubuntu.go`  that url is used. https://github.com/quay/clair/blob/dc8de7d31ef7196de5a273772f19de13f4f3cd4a/ext/vulnsrc/ubuntu/ubuntu.go#L41 

I think it is trying to retrieve `artful` and it is not available. It seems to throw a SSL error which makes sense with the error you are seeing.

https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.artful.cve.oval.xml.bz2

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!

**Comment by mirekphd** [comment]
> 
> From what I can tell this is normal. Just give it some time to update it's DB and things will work out fine.

Yes, it's a misused (non-specific) error message, printed in the logs instead of a download progress info. Ubuntu vulnerabilities take longer to update than others, and thus it can look like an error. But given adequate time for download (and I mean hours), it resolves itself.

A particularly long example (probably Ubuntu feed being broken an no-one there to restart it over the weekend):

```
$ docker logs -f clair_clair | grep updater
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2021-09-18 10:08:49.471035","error":"could not download requested resource","updater name":"ubuntu"}
[..]
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2021-09-18 19:08:24.141657","error":"could not download requested resource","updater name":"ubuntu"}
[..]
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2021-09-19 03:48:02.747171","error":"could not download requested resource","updater name":"ubuntu"}
[..]
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2021-09-19 15:53:17.710967","updater name":"ubuntu"}


```
