### ISSUE TITLE
Can clair scan a layer which is present in the filesystem, that is when a post request to clair is sent ..can i put the 'Path' : as file system path instead of URL?

### ISSUE THREAD

**Issue by subhamsps** [quay/clair#969]
I am trying to scan a docker image on my on my local system. I write a script to process the container images and keep the layes on my local file system. I have the following informations available : 
Name = parent name (image name)
Command = layer command
Path = Filesystem
ShaID = blobsum.

What i would like to do is run a static analysis on this layer/layers present on my file system using my script.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
