### ISSUE TITLE
Implement a ROADMAP.md

### ISSUE THREAD

**Issue by jzelinskie** [quay/clair#97]
This is standard across CoreOS projects and we still don't have one.

**Comment by liangchenye** [comment]
+1
So should we collect features and put them into ROADMAP?

**Comment by coolljt0725** [comment]
+1 for this

**Comment by liangchenye** [comment]
Here are some works in my mind, not sure if they can be added to the roadmap.
[customization]
1 more OS support
     alpine/oracle/suse ..
2 more package manager
     python/npm
3 different data detect
     although Clair is designed to be `clear, bright, transparent`, but the interface is quite flexible.
     'dynamic scan'  could also be realized in 'dataDetector'. 
4 different database as the backend

**Comment by Quentin-M** [comment]
Hi,

Could you please elaborate on 1. ? The entire image history is always considered when determining potential vulnerabilities.

**Comment by liangchenye** [comment]
I removed it cause it sounds a little scary and misleading.
The previous discussion is here: https://github.com/coreos/clair/issues/68.

**Comment by Quentin-M** [comment]
Closed by 51e4086
