### ISSUE TITLE
Is it possible to use environmental variables for the connection string et al?

### ISSUE THREAD

**Issue by jfabdo** [quay/clair#974]
I'm trying to deploy clair to AWS, and I'm able to build the container and copy in the config.yaml. The issue I'm facing is that my container needs to be in a public place, so no connection string and such in the YAML. I'd like to set it as an environmental variable and pass it in that way. Is there a way to indicate to clair that I'm trying to do that?

### Environment
NA

- Clair version/image: 2.0.1
- Clair client name/version: NA 
- Host OS: AWS Linux
- Kernel (e.g. `uname -a`): NA
- Kubernetes version (use `kubectl version`): NA
- Helm version (use `helm version`): NA
- Network/Firewall setup: NA

**Comment by ldelossa** [comment]
@jfabdo ClairV2 does not support env variable configuration. This is by design and the config needs to have nested data structures. 
This will most likely be the fact in newer versions of Clair as well.
