### ISSUE TITLE
Clair v2.1.2 log warning Ubuntu eoan and Ubuntu snap not mapped to any version number

### ISSUE THREAD

**Issue by namloc2001** [quay/clair#978]
### Description of Problem / Feature Request

Logs are stating ubuntu eoan (19.10) and ubuntu snap (???) are "not mapped to any version number (eg. trusty-\u003e14.04). Please update me."

(Not yet sure what it is referring to with ubuntu snap...)

### Expected Outcome

I thought mapping for Eoan had been added here: https://github.com/quay/clair/pull/867 (@jzelinskie )? Apologies if wrong...

### Actual Outcome

Receiving these messages in logs:
```
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-04-20 11:40:35.926528","note":"Ubuntu eoan is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-04-20 11:40:35.928086","note":"Ubuntu snap is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
```

### Environment

- Clair version/image: quay.io/coreos/clair:v2.1.2
- Clair client name/version: N/A
- Host OS: Red Hat (OCP on IBM Cloud)
- Kernel (e.g. `uname -a`): OCP on IBM Cloud, cannot run command
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-02-03T19:39:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
- Helm version (use `helm version`): version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
- Network/Firewall setup: N/A

**Comment by ldelossa** [comment]
Thanks, fixed with 
https://github.com/quay/clair/pull/987
