### ISSUE TITLE
Add name of associated file into log message - for updater

### ISSUE THREAD

**Issue by namloc2001** [quay/clair#979]
### Description of Feature Request

It it please possible to include the name of the file (thinking here of ubuntu CVE files) in error logs so that when logs such as:

```
{"Event":"could not parse package version. skipping","Level":"warning","Location":"ubuntu.go:316","Time":"2020-04-20 08:59:38.365219","error":"invalid version","version":"0.27-1+deb7u1build0.12.04.1, 0.28-1+deb8u1"}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-04-20 11:40:35.926528","note":"Ubuntu eoan is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-04-20 11:40:35.928086","note":"Ubuntu snap is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
```

are received, we can understand where it happened if we wish to research it, and so that we can look to understand potential impact of it not having been added to database?

### Environment

N/A - feature request

**Comment by ldelossa** [comment]
@namloc2001 ClairV2 is currently in maintenance. If you would like this please submit a pull request and we will merge in.
