### ISSUE TITLE
Does Clair support multi-client mode?

### ISSUE THREAD

**Issue by CloveXJ** [quay/clair#989]
I want to scan images in 3 different k8s nodes. My plan is:
1. install clairctl or analyze-local-image in every node;
2. install clair and clairdb in center node;
3. connect every client to the clair in center node;

if i start imagescan job in 3 nodes at the same time, will the cvedb in center node be locked or conflict?

**Comment by ldelossa** [comment]
@CloveXJ which Clair version are you referring to?

**Comment by ldelossa** [comment]
@CloveXJ if you're still interested in this issue, re-open with a response to the above question.

**Comment by CloveXJ** [comment]
my version is V2.0.8
