### ISSUE TITLE
namespace API should return objects

### ISSUE THREAD

**Issue by jzelinskie** [quay/clair#99]
In order to future-proof the API for namespaces, we should return a list of objects for the GET route rather than just a list of strings.

**Comment by liangchenye** [comment]
@jzelinskie , is 'self-assigned mean' you will work on it?
I just worried that multiply people might work on a same feature once we have a roadmap.

**Comment by jzelinskie** [comment]
@liangchenye Yep, I plan to get this out before 1.0, so that if we expand the properties on the namespace object after 1.0, it doesn't break API.
