### ISSUE TITLE
Proxy error / Connection refused when connecting to Clair backend from Quay

### ISSUE THREAD

**Issue by quickparser** [quay/clair#991]
### Description of Problem / Feature Request

I'm trying to get the Clair image scanning to work with Quay but it seems that Quay is unable to reach the Clair backend. All my images are queued for scanning, but scanning never happens. 

### Expected Outcome

I expect the connection to get established and layer sent for scanning to clair backend. 

### Actual Outcome

Logs from Quay container (replaced the actual domainname with mydomain):

$ sudo docker logs a591547cba37

...
securityworker stdout | 2020-04-29 09:42:24,230 [186] [INFO] [util.secscan.api] Analyzing layer 818aa6fb5851e491e6b25e7b19cbb2a62a914395c311f7af1823d856d03a73f2.52b53786-f22e-4105-99c5-3015
3deec065
2020-04-29 09:42:24,233 [186] [ERROR] [util.secscan.api] Connection error when trying to post layer data response for 42
Traceback (most recent call last):
  File "util/secscan/api.py", line 359, in analyze_layer
    response = self._call("POST", _API_METHOD_INSERT, body=request)
  File "util/secscan/api.py", line 546, in _call
    return self._request(method, endpoint, path, body, params, timeout)
  File "util/secscan/api.py", line 525, in _request
    proxies={"https": "https://" + signer_proxy_url, "http": "http://" + signer_proxy_url},
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
ProxyError: HTTPSConnectionPool(host='clair.mydomain', port=6060): Max retries exceeded with url: /v1/layers (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f328efa8790>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2020-04-29 09:42:24,235 [186] [INFO] [apscheduler.executors.default] Job "_index_images (trigger: interval[0:00:30], next run at: 2020-04-29 09:42:53 UTC)" executed successfully
securityworker stdout | 2020-04-29 09:42:24,234 [186] [ERROR] [workers.securityworker] Security scanner service unavailable
Traceback (most recent call last):
  File "workers/securityworker/__init__.py", line 27, in index_images
    analyzer.analyze_recursively(candidate)
  File "util/secscan/analyzer.py", line 43, in analyze_recursively
    self._analyze_recursively_and_check(layer)
  File "util/secscan/analyzer.py", line 66, in _analyze_recursively_and_check
    raise APIRequestFailure
APIRequestFailure
...

I get the following response when trying to connect to it manually (the same happens if I disable HTTPS connection):

$ sudo docker exec -it a591547cba37 bash

[root@a591547cba37 quay-registry]# curl https://clair.mydomain:6060/v1/layers
jwtproxy: unable to verify request: Could not parse JWT
[root@a591547cba37 quay-registry]#

[root@a591547cba37 quay-registry]# curl -I -X GET http://clair.mydomain:6061/health
HTTP/1.1 200 OK
Server: clair
Date: Wed, 29 Apr 2020 10:25:35 GMT
Content-Length: 0
[root@a591547cba37 quay-registry]#

### Environment

- Clair version/image: quay.io/redhat/clair-jwt:v3.2.2 (3.2.1)
- Clair client name/version: quay.io/redhat/quay:v3.2.1
- Host OS: RHEL 7.7
- Kernel (e.g. `uname -a`): 3.10.0-1062.el7.x86_64
- Kubernetes version (use `kubectl version`): n/a
- Helm version (use `helm version`): n/a
- Network/Firewall setup: Running in an environment with the connection to Internet via an http proxy. These FW rules are applied/ports enabled on the host OS:

$ sudo firewall-cmd --list-ports
8443/tcp 80/tcp 443/tcp 3306/tcp 6379/tcp 5432/tcp 6060/tcp 6061/tcp

**Comment by kmanalo** [comment]
I'm also seeing the same issues
"jwtproxy: unable to verify request: Could not parse JWT"

**Comment by ldelossa** [comment]
@quickparser @kmanalo   please bringup support issues in the quay-sig:
https://groups.google.com/forum/#!forum/quay-sig
