### ISSUE TITLE
Unable to scan quay images

### ISSUE THREAD

**Issue by priyanka19-98** [quay/clair#994]
I am deploying clair on kubernetes

### Description of Problem / Feature Request
The images on quay are not being scanned by clair. It says manifest cannot be indexed.

I am currently using clair v4-alpha 4 with quay 3.2.1. But I am not able to scan the images .
### Expected Outcome
The Images pushed on quay must be scanned and display vulnerabilities.

### Actual Outcome
Images are not beimg scanned.

### Environment
N/A
 N/A

- Clair version/image: v4 alpha 4
- Clair client name/version: N/A
- Host OS: RHEL 7
- Kernel (e.g. `uname -a`): N/A
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- Helm version (use `helm version`): 
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
- Network/Firewall setup: N/A
![quay](https://user-images.githubusercontent.com/50020569/81041555-c56d4780-8ecb-11ea-8963-32e25b45c1c4.png)

**Comment by ldelossa** [comment]
@16bce091 
Have you configured Quay to utilize ClairV4? Right now you must explicitly tell Quay via configuration to use ClairV4. 

Here's an instructional video: https://youtu.be/r40tKrJt3lg

**Comment by ldelossa** [comment]
Sorry, I had actually missed the Quay version you are using. ClairV4 support is a recent Quay feature. Are you able to deploy Quay via the Master branch? Currently the master branch of Quay contains support for ClairV4

**Comment by priyanka19-98** [comment]
Thanks a lot. Working on it.

**Comment by priyanka19-98** [comment]
I have deployed Quay Master along with Clair V4. But still it seems that Quay is calling Clair V2 api endpoints in Clair V4 and returning 404 Not found.
![clair_v4_logs](https://user-images.githubusercontent.com/50020569/81143800-53126b00-8f90-11ea-9262-c1b3337662ac.png)
![quay_logs_clair_v2](https://user-images.githubusercontent.com/50020569/81143864-7e955580-8f90-11ea-896d-6834996361cf.png)
 Attaching the logs for your reference.

**Comment by ldelossa** [comment]
Have you added the necessary configuration options to quay's config?

**Comment by priyanka19-98** [comment]
Using quay master (built using Docker file as stated in docs) I am not able to push any image to the quay running locally.
I am getting unexpected HTTP status: 502 Bad Gateway while pushing images.

But was able to push images using docker image quay.io/projectquay/quay:lando .

What could be the issue?

**Comment by ldelossa** [comment]
@16bce091 

If youre having an issue pushing to Quay when running locally, this issue should be brought up in the Quay repo. 

Are you having issues pushing images to quay?

**Comment by priyanka19-98** [comment]
Yes images are not being pushed

**Comment by priyanka19-98** [comment]
I am running quay 3.2.1 with clair v2.1.3 . I am able to push the images for quay 3.2.1. It seems that quay is making calls to clair for vulnerability scanning but clair return error with response status 400.

Attaching the logs.
![clair_quay_logs](https://user-images.githubusercontent.com/50020569/81342096-4432d200-90d0-11ea-8acb-5b202ce86789.png)

**Comment by ldelossa** [comment]
I would suggest posting on the Quay mailing lists. https://groups.google.com/forum/#!forum/quay-sig

I see you have already made a post. Your issue will be better addressed there.
